// Code generated by sqlc-ydb. DO NOT EDIT.
import type { Query, SQL } from "@ydbjs/query";
import { Json, JsonType, Uint64, Uint64Type, Utf8, Utf8Type } from "@ydbjs/value/primitive";
import { List, ListType } from "@ydbjs/value/list";
import { Struct, StructType } from "@ydbjs/value/struct";
import type { Value } from "@ydbjs/value";
import { Optional, OptionalType } from "@ydbjs/value/optional";

export type ConfigureQuery = (query: Query) => void;

// The SDK infers Null for an empty List, so retain the declared item type.
function structList(items: Struct[], type: StructType): Value<ListType> {
  const list = new List<Struct>();
  for (const item of items) list.items.push(item);
  return { type: new ListType(type), encode: () => list.encode() };
}

export type CreateBooksBooksItem = {
  readonly bookId: bigint;
  readonly title: string | null;
  readonly tags: string;
};

export class Queries {
  readonly #sql: SQL;

  constructor(sql: SQL) {
    if (typeof sql !== "function") throw new TypeError("Queries requires a YDB SQL function");
    this.#sql = sql;
  }

  // -- name: CreateBooks :exec
  async createBooks(books: ReadonlyArray<CreateBooksBooksItem>, configure?: ConfigureQuery): Promise<void> {
    const stmt = this.#sql`INSERT INTO books (book_id, title, tags)
      SELECT book_id, title, tags FROM AS_TABLE($books);`
      .parameter("books", structList(books.map(item => new Struct({ ["book_id"]: new Uint64(item.bookId), ["title"]: new Optional(item.title === null ? null : new Utf8(item.title), new Utf8Type()), ["tags"]: new Json(item.tags) })), new StructType(["book_id", "title", "tags"], [new Uint64Type(), new OptionalType(new Utf8Type()), new JsonType()])));
    configure?.(stmt);
    await stmt;
  }
}
