# Code generated by sqlc-ydb. DO NOT EDIT.
from __future__ import annotations
from typing import Iterable, Optional, Union
from . import models as _models
import ydb as _ydb


def _typed(value, typ):
    return _ydb.TypedValue(value, typ)


class Querier:
    def __init__(self, executor: Union[_ydb.QuerySessionPool, _ydb.QueryTxContext]):
        self._executor = executor

    def _execute(self, query: str, parameters: dict):
        if isinstance(self._executor, _ydb.QuerySessionPool):
            return self._executor.execute_with_retries(query, parameters)
        return list(self._executor.execute(query, parameters))

    # -- name: GetAuthor :one
    def get_author(self, author_id: int) -> Optional[_models.Author]:
        parameters = {"$author_id": _typed(author_id, _ydb.PrimitiveType.Uint64)}
        result_sets = self._execute(
            ("DECLARE $author_id AS Uint64;\n"
             "SELECT `id`, `name`, `bio` FROM `authors` WHERE `id` = $author_id;"), parameters)
        rows = result_sets[0].rows
        if not rows:
            return None
        row = rows[0]
        return _models.Author(
            id=row["id"],
            name=row["name"],
            bio=row["bio"],
        )
