// Code generated by sqlc. DO NOT EDIT.
// source: queries.sql

package db

import (
	"context"
	"database/sql"

	_ "github.com/ydb-platform/ydb-go-sdk/v3"
	"github.com/ydb-platform/ydb-go-sdk/v3/pkg/xerrors"
	"github.com/ydb-platform/ydb-go-sdk/v3/retry"
)

const getAuthor = `-- name: GetAuthor :one
SELECT * FROM authors
WHERE id = $id LIMIT 1;`

func (q *Queries) GetAuthor(ctx context.Context,
	id uint64,
) (*Author, error) {
	i, err := retry.RetryWithResult(ctx, func(ctx context.Context) (*Author, error) {
		row := q.db.QueryRowContext(ctx, getAuthor,
			sql.Named("id", id),
		)
		var i Author
		err := row.Scan(&i.ID, &i.Name)
		if err != nil {
			return nil, xerrors.WithStackTrace(err)
		}

		return &i, nil
	}, retry.WithLabel("GetAuthor"))
	if err != nil {
		return nil, xerrors.WithStackTrace(err)
	}

	return i, nil
}

const listAuthors = `-- name: ListAuthors :many
SELECT * FROM authors
ORDER BY name;`

func (q *Queries) ListAuthors(ctx context.Context) ([]Author, error) {
	items, err := retry.RetryWithResult(ctx, func(ctx context.Context) ([]Author, error) {
		rows, err := q.db.QueryContext(ctx, listAuthors)
		if err != nil {
			return nil, err
		}
		defer rows.Close()
		var items []Author
		for rows.Next() {
			var i Author
			if err := rows.Scan(&i.ID, &i.Name); err != nil {
				return nil, xerrors.WithStackTrace(err)
			}
			items = append(items, i)
		}
		if err := rows.Err(); err != nil {
			return nil, xerrors.WithStackTrace(err)
		}

		return items, nil
	}, retry.WithLabel("ListAuthors"))
	if err != nil {
		return nil, xerrors.WithStackTrace(err)
	}

	return items, nil
}

const createAuthor = `-- name: CreateAuthor :one
INSERT INTO authors (name)
VALUES ($name)
RETURNING *;`

func (q *Queries) CreateAuthor(ctx context.Context,
	name string,
) (*Author, error) {
	i, err := retry.RetryWithResult(ctx, func(ctx context.Context) (*Author, error) {
		row := q.db.QueryRowContext(ctx, createAuthor,
			sql.Named("name", name),
		)
		var i Author
		err := row.Scan(&i.ID, &i.Name)
		if err != nil {
			return nil, xerrors.WithStackTrace(err)
		}

		return &i, nil
	}, retry.WithLabel("CreateAuthor"))
	if err != nil {
		return nil, xerrors.WithStackTrace(err)
	}

	return i, nil
}

const getAlbum = `-- name: GetAlbum :one
SELECT * FROM albums
WHERE id = $id LIMIT 1;`

func (q *Queries) GetAlbum(ctx context.Context,
	id uint64,
) (*Album, error) {
	i, err := retry.RetryWithResult(ctx, func(ctx context.Context) (*Album, error) {
		row := q.db.QueryRowContext(ctx, getAlbum,
			sql.Named("id", id),
		)
		var i Album
		err := row.Scan(&i.ID, &i.Title, &i.Author_id)
		if err != nil {
			return nil, xerrors.WithStackTrace(err)
		}

		return &i, nil
	}, retry.WithLabel("GetAlbum"))
	if err != nil {
		return nil, xerrors.WithStackTrace(err)
	}

	return i, nil
}

const listAlbumsByAuthor = `-- name: ListAlbumsByAuthor :many
SELECT * FROM albums
WHERE author_id = $author_id
ORDER BY title;`

func (q *Queries) ListAlbumsByAuthor(ctx context.Context,
	author_id uint64,
) ([]Album, error) {
	items, err := retry.RetryWithResult(ctx, func(ctx context.Context) ([]Album, error) {
		rows, err := q.db.QueryContext(ctx, listAlbumsByAuthor,
			sql.Named("author_id", author_id),
		)
		if err != nil {
			return nil, err
		}
		defer rows.Close()
		var items []Album
		for rows.Next() {
			var i Album
			if err := rows.Scan(&i.ID, &i.Title, &i.Author_id); err != nil {
				return nil, xerrors.WithStackTrace(err)
			}
			items = append(items, i)
		}
		if err := rows.Err(); err != nil {
			return nil, xerrors.WithStackTrace(err)
		}

		return items, nil
	}, retry.WithLabel("ListAlbumsByAuthor"))
	if err != nil {
		return nil, xerrors.WithStackTrace(err)
	}

	return items, nil
}

const createAlbum = `-- name: CreateAlbum :one
INSERT INTO albums (title, author_id)
VALUES ($title, $author_id)
RETURNING *;`

func (q *Queries) CreateAlbum(ctx context.Context,
	title string,
	author_id uint64,
) (*Album, error) {
	i, err := retry.RetryWithResult(ctx, func(ctx context.Context) (*Album, error) {
		row := q.db.QueryRowContext(ctx, createAlbum,
			sql.Named("title", title),
			sql.Named("author_id", author_id),
		)
		var i Album
		err := row.Scan(&i.ID, &i.Title, &i.Author_id)
		if err != nil {
			return nil, xerrors.WithStackTrace(err)
		}

		return &i, nil
	}, retry.WithLabel("CreateAlbum"))
	if err != nil {
		return nil, xerrors.WithStackTrace(err)
	}

	return i, nil
}

const deleteAlbum = `-- name: DeleteAlbum :exec
DELETE FROM albums
WHERE id = $id;`

func (q *Queries) DeleteAlbum(ctx context.Context,
	id uint64,
) error {
	err := retry.Retry(ctx, func(ctx context.Context) error {
		_, err := q.db.ExecContext(ctx, deleteAlbum,
			sql.Named("id", id),
		)
		if err != nil {
			return xerrors.WithStackTrace(err)
		}

		return nil
	}, retry.WithLabel("DeleteAlbum"))
	if err != nil {
		return xerrors.WithStackTrace(err)
	}

	return nil
}
