// Code generated by sqlc-ydb. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;
using LinqToDB;
using LinqToDB.Data;
using Ydb.Sdk.Value;

namespace Authors.Linq2DB;

public sealed class Queries
{
    private readonly DataConnection _connection;

    public Queries(DataConnection connection)
    {
        _connection = connection ?? throw new ArgumentNullException(nameof(connection));
    }

    // -- name: GetAuthor :one
    public async Task<GetAuthorRow> GetAuthorAsync(ulong authorId, CancellationToken cancellationToken = default)
    {
        await foreach (var row in _connection.QueryToAsyncEnumerable(GetAuthorRowFrom,
            "SELECT id, name, bio FROM authors WHERE id = $author_id;", new DataParameter("$author_id", authorId, DataType.UInt64)).WithCancellation(cancellationToken).ConfigureAwait(false))
        {
            return row;
        }
        throw new InvalidOperationException("query returned no rows");
    }

    private static GetAuthorRow GetAuthorRowFrom(DbDataReader reader) => new(
        reader.GetFieldValue<ulong>(0),
        reader.GetFieldValue<string>(1),
        reader.IsDBNull(2) ? null : reader.GetFieldValue<string>(2)
    );

    // -- name: ListAuthors :many
    public async Task<IReadOnlyList<ListAuthorsRow>> ListAuthorsAsync(CancellationToken cancellationToken = default)
    {
        return await _connection.QueryToListAsync(ListAuthorsRowFrom,
            "SELECT id, name, bio FROM authors ORDER BY name;", cancellationToken).ConfigureAwait(false);
    }

    private static ListAuthorsRow ListAuthorsRowFrom(DbDataReader reader) => new(
        reader.GetFieldValue<ulong>(0),
        reader.GetFieldValue<string>(1),
        reader.IsDBNull(2) ? null : reader.GetFieldValue<string>(2)
    );

    // -- name: GetAuthorName :one
    public async Task<GetAuthorNameRow> GetAuthorNameAsync(ulong authorId, CancellationToken cancellationToken = default)
    {
        await foreach (var row in _connection.QueryToAsyncEnumerable(GetAuthorNameRowFrom,
            "SELECT name FROM authors WHERE id = $author_id;", new DataParameter("$author_id", authorId, DataType.UInt64)).WithCancellation(cancellationToken).ConfigureAwait(false))
        {
            return row;
        }
        throw new InvalidOperationException("query returned no rows");
    }

    private static GetAuthorNameRow GetAuthorNameRowFrom(DbDataReader reader) => new(
        reader.GetFieldValue<string>(0)
    );

    // -- name: CreateAuthor :one
    public async Task<CreateAuthorRow> CreateAuthorAsync(CreateAuthorParams args, CancellationToken cancellationToken = default)
    {
        await foreach (var row in _connection.QueryToAsyncEnumerable(CreateAuthorRowFrom,
            "INSERT INTO `authors` (`id`, `name`, `bio`)\n" +
            "VALUES ($author_id, $author_name, $biography)\n" +
            "RETURNING `id`, `name`, `bio`;", new DataParameter("$author_id", args.AuthorID, DataType.UInt64), new DataParameter("$author_name", args.AuthorName, DataType.NVarChar), new DataParameter("$biography", YdbValue.MakeOptionalUtf8(args.Biography), DataType.NVarChar)).WithCancellation(cancellationToken).ConfigureAwait(false))
        {
            return row;
        }
        throw new InvalidOperationException("query returned no rows");
    }

    private static CreateAuthorRow CreateAuthorRowFrom(DbDataReader reader) => new(
        reader.GetFieldValue<ulong>(0),
        reader.GetFieldValue<string>(1),
        reader.IsDBNull(2) ? null : reader.GetFieldValue<string>(2)
    );

    // -- name: UpsertAuthor :exec
    public async Task UpsertAuthorAsync(UpsertAuthorParams args, CancellationToken cancellationToken = default)
    {
        await _connection.ExecuteAsync(
            "UPSERT INTO authors (id, name, bio)\n" +
            "VALUES ($author_id, $author_name, $biography);", cancellationToken, new DataParameter("$author_id", args.AuthorID, DataType.UInt64), new DataParameter("$author_name", args.AuthorName, DataType.NVarChar), new DataParameter("$biography", YdbValue.MakeOptionalUtf8(args.Biography), DataType.NVarChar)).ConfigureAwait(false);
    }

    // -- name: DeleteAuthor :exec
    public async Task DeleteAuthorAsync(ulong authorId, CancellationToken cancellationToken = default)
    {
        await _connection.ExecuteAsync(
            "DELETE FROM authors WHERE id = $author_id;", cancellationToken, new DataParameter("$author_id", authorId, DataType.UInt64)).ConfigureAwait(false);
    }
}
