// Code generated by sqlc-ydb. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;
using LinqToDB;
using LinqToDB.Data;
using Ydb.Sdk.Value;

namespace Authors.Linq2DB;

public sealed class Queries
{
    private readonly DataConnection _connection;

    public Queries(DataConnection connection)
    {
        _connection = connection ?? throw new ArgumentNullException(nameof(connection));
    }

    private const string SqlGetAuthor =
        "-- name: GetAuthor :one\n" +
        "DECLARE $author_id AS Uint64;\n" +
        "SELECT id, name, bio FROM authors WHERE id = $author_id;";

    public async Task<GetAuthorRow> GetAuthorAsync(ulong AuthorID, CancellationToken cancellationToken = default)
    {
        var rows = await _connection.QueryToListAsync(GetAuthorRowFrom, SqlGetAuthor, cancellationToken, new DataParameter("$author_id", AuthorID, DataType.UInt64)).ConfigureAwait(false);
        if (rows.Count == 0)
        {
            throw new InvalidOperationException("query returned no rows");
        }
        return rows[0];
    }

    private static GetAuthorRow GetAuthorRowFrom(DbDataReader reader) => new(
        reader.GetFieldValue<ulong>(0),
        reader.GetFieldValue<string>(1),
        reader.IsDBNull(2) ? null : reader.GetFieldValue<string>(2)
    );

    private const string SqlListAuthors =
        "-- name: ListAuthors :many\n" +
        "SELECT id, name, bio FROM authors ORDER BY name;";

    public async Task<IReadOnlyList<ListAuthorsRow>> ListAuthorsAsync(CancellationToken cancellationToken = default)
    {
        var rows = await _connection.QueryToListAsync(ListAuthorsRowFrom, SqlListAuthors, cancellationToken).ConfigureAwait(false);
        return rows;
    }

    private static ListAuthorsRow ListAuthorsRowFrom(DbDataReader reader) => new(
        reader.GetFieldValue<ulong>(0),
        reader.GetFieldValue<string>(1),
        reader.IsDBNull(2) ? null : reader.GetFieldValue<string>(2)
    );

    private const string SqlGetAuthorName =
        "-- name: GetAuthorName :one\n" +
        "DECLARE $author_id AS Uint64;\n" +
        "SELECT name FROM authors WHERE id = $author_id;";

    public async Task<GetAuthorNameRow> GetAuthorNameAsync(ulong AuthorID, CancellationToken cancellationToken = default)
    {
        var rows = await _connection.QueryToListAsync(GetAuthorNameRowFrom, SqlGetAuthorName, cancellationToken, new DataParameter("$author_id", AuthorID, DataType.UInt64)).ConfigureAwait(false);
        if (rows.Count == 0)
        {
            throw new InvalidOperationException("query returned no rows");
        }
        return rows[0];
    }

    private static GetAuthorNameRow GetAuthorNameRowFrom(DbDataReader reader) => new(
        reader.GetFieldValue<string>(0)
    );

    private const string SqlCreateAuthor =
        "-- name: CreateAuthor :one\n" +
        "DECLARE $author_id AS Uint64;\n" +
        "DECLARE $author_name AS Utf8;\n" +
        "DECLARE $biography AS Optional<Utf8>;\n" +
        "INSERT INTO authors (id, name, bio)\n" +
        "VALUES ($author_id, $author_name, $biography)\n" +
        "RETURNING id, name, bio;";

    public async Task<CreateAuthorRow> CreateAuthorAsync(CreateAuthorParams args, CancellationToken cancellationToken = default)
    {
        var rows = await _connection.QueryToListAsync(CreateAuthorRowFrom, SqlCreateAuthor, cancellationToken, new DataParameter("$author_id", args.AuthorID, DataType.UInt64), new DataParameter("$author_name", args.AuthorName, DataType.NVarChar), new DataParameter("$biography", YdbValue.MakeOptionalUtf8(args.Biography), DataType.NVarChar)).ConfigureAwait(false);
        if (rows.Count == 0)
        {
            throw new InvalidOperationException("query returned no rows");
        }
        return rows[0];
    }

    private static CreateAuthorRow CreateAuthorRowFrom(DbDataReader reader) => new(
        reader.GetFieldValue<ulong>(0),
        reader.GetFieldValue<string>(1),
        reader.IsDBNull(2) ? null : reader.GetFieldValue<string>(2)
    );

    private const string SqlUpsertAuthor =
        "-- name: UpsertAuthor :exec\n" +
        "DECLARE $author_id AS Uint64;\n" +
        "DECLARE $author_name AS Utf8;\n" +
        "DECLARE $biography AS Optional<Utf8>;\n" +
        "UPSERT INTO authors (id, name, bio)\n" +
        "VALUES ($author_id, $author_name, $biography);";

    public async Task UpsertAuthorAsync(UpsertAuthorParams args, CancellationToken cancellationToken = default)
    {
        await _connection.ExecuteAsync(SqlUpsertAuthor, cancellationToken, new DataParameter("$author_id", args.AuthorID, DataType.UInt64), new DataParameter("$author_name", args.AuthorName, DataType.NVarChar), new DataParameter("$biography", YdbValue.MakeOptionalUtf8(args.Biography), DataType.NVarChar)).ConfigureAwait(false);
    }

    private const string SqlDeleteAuthor =
        "-- name: DeleteAuthor :exec\n" +
        "DECLARE $author_id AS Uint64;\n" +
        "DELETE FROM authors WHERE id = $author_id;";

    public async Task DeleteAuthorAsync(ulong AuthorID, CancellationToken cancellationToken = default)
    {
        await _connection.ExecuteAsync(SqlDeleteAuthor, cancellationToken, new DataParameter("$author_id", AuthorID, DataType.UInt64)).ConfigureAwait(false);
    }
}
