// Code generated by sqlc-ydb. DO NOT EDIT.
#pragma once

#include <cstdint>
#include <optional>
#include <string>
#include <util/datetime/base.h>

namespace batch::native {

struct GetAuthorRow final {
    std::uint64_t author_id;
    std::string name;
    std::optional<std::string> biography;
};

struct BooksByYearRow final {
    std::uint64_t book_id;
    std::uint64_t author_id;
    std::string isbn;
    std::string book_type;
    std::string title;
    std::int32_t year;
    TInstant available;
    std::string tags;
};

struct CreateAuthorRow final {
    std::uint64_t author_id;
    std::string name;
    std::optional<std::string> biography;
};

struct CreateBookRow final {
    std::uint64_t book_id;
    std::uint64_t author_id;
    std::string isbn;
    std::string book_type;
    std::string title;
    std::int32_t year;
    TInstant available;
    std::string tags;
};

struct GetBiographyRow final {
    std::optional<std::string> biography;
};

}  // namespace batch::native
