// Code generated by sqlc-ydb. DO NOT EDIT.
#pragma once

#include "models.hpp"

#include <cstdint>
#include <optional>
#include <vector>
#include <string>

#include <ydb-cpp-sdk/client/query/client.h>

namespace batch::native {

class Queries final {
public:
    explicit Queries(NYdb::NQuery::TQueryClient& client,
        const NYdb::NRetry::TRetryOperationSettings& retry_settings = {},
        const NYdb::NQuery::TTxSettings& tx_settings = NYdb::NQuery::TTxSettings::SerializableRW(),
        const NYdb::NQuery::TExecuteQuerySettings& execute_settings = {})
        : client_(&client), transaction_(nullptr), retry_settings_(retry_settings),
          tx_settings_(tx_settings), execute_settings_(execute_settings) {}
    explicit Queries(NYdb::NQuery::TTransaction& transaction,
        const NYdb::NQuery::TExecuteQuerySettings& execute_settings = {})
        : client_(nullptr), transaction_(&transaction), execute_settings_(execute_settings) {}

    std::optional<GetAuthorRow> GetAuthor(std::uint64_t author_id) const;
    void DeleteBookExecResult(std::uint64_t book_id) const;
    void DeleteBook(std::uint64_t book_id) const;
    void DeleteBookNamedFunc(std::uint64_t book_id) const;
    void DeleteBookNamedSign(std::uint64_t book_id) const;
    std::vector<BooksByYearRow> BooksByYear(std::int32_t year) const;
    std::optional<CreateAuthorRow> CreateAuthor(std::uint64_t author_id, const std::string& name, const std::optional<std::string>& biography) const;
    std::optional<CreateBookRow> CreateBook(std::uint64_t book_id, std::uint64_t author_id, const std::string& isbn, const std::string& book_type, const std::string& title, std::int32_t year, const TInstant& available, const std::string& tags) const;
    void UpdateBook(const std::string& title, const std::string& tags, std::uint64_t book_id) const;
    std::optional<GetBiographyRow> GetBiography(std::uint64_t author_id) const;

private:
    NYdb::NQuery::TQueryClient* client_;
    NYdb::NQuery::TTransaction* transaction_;
    NYdb::NRetry::TRetryOperationSettings retry_settings_;
    NYdb::NQuery::TTxSettings tx_settings_{NYdb::NQuery::TTxSettings::SerializableRW()};
    NYdb::NQuery::TExecuteQuerySettings execute_settings_;
};

}  // namespace batch::native
