// Code generated by sqlc. DO NOT EDIT.
// source: queries.sql

package db

import (
	"context"
	"database/sql"

	_ "github.com/ydb-platform/ydb-go-sdk/v3"
	"github.com/ydb-platform/ydb-go-sdk/v3/pkg/xerrors"
	"github.com/ydb-platform/ydb-go-sdk/v3/retry"
)

const getAuthor = `-- name: GetAuthor :one
SELECT * FROM authors
WHERE author_id = $author_id LIMIT 1;`

type GetAuthorParams struct {
	Author_id uint64 `json:"author_id"`
}

func (q *Queries) GetAuthor(ctx context.Context, arg GetAuthorParams) (*GetAuthorRow, error) {
	i, err := retry.RetryWithResult(ctx, func(ctx context.Context) (*GetAuthorRow, error) {
		row := q.db.QueryRowContext(ctx, getAuthor,
			sql.Named("author_id", arg.Author_id),
		)
		var i GetAuthorRow
		err := row.Scan(&i.Author_id, &i.Name, &i.Biography)
		if err != nil {
			return nil, xerrors.WithStackTrace(err)
		}

		return &i, nil
	}, retry.WithLabel("GetAuthor"))
	if err != nil {
		return nil, xerrors.WithStackTrace(err)
	}

	return i, nil
}

const deleteBook = `-- name: DeleteBook :exec
DELETE FROM books
WHERE book_id = $book_id;`

type DeleteBookParams struct {
	Book_id uint64 `json:"book_id"`
}

func (q *Queries) DeleteBook(ctx context.Context, arg DeleteBookParams) error {
	err := retry.Retry(ctx, func(ctx context.Context) error {
		_, err := q.db.ExecContext(ctx, deleteBook,
			sql.Named("book_id", arg.Book_id),
		)
		if err != nil {
			return xerrors.WithStackTrace(err)
		}

		return nil
	}, retry.WithLabel("DeleteBook"))
	if err != nil {
		return xerrors.WithStackTrace(err)
	}

	return nil
}

const booksByYear = `-- name: BooksByYear :many
SELECT * FROM books
WHERE year = $year;`

type BooksByYearParams struct {
	Year uint64 `json:"year"`
}

func (q *Queries) BooksByYear(ctx context.Context, arg BooksByYearParams) ([]BooksByYearRow, error) {
	items, err := retry.RetryWithResult(ctx, func(ctx context.Context) ([]BooksByYearRow, error) {
		rows, err := q.db.QueryContext(ctx, booksByYear,
			sql.Named("year", arg.Year),
		)
		if err != nil {
			return nil, err
		}
		defer rows.Close()
		var items []BooksByYearRow
		for rows.Next() {
			var i BooksByYearRow
			if err := rows.Scan(&i.Book_id, &i.Author_id, &i.Isbn, &i.Book_type, &i.Title, &i.Year, &i.Available, &i.Tags); err != nil {
				return nil, xerrors.WithStackTrace(err)
			}
			items = append(items, i)
		}
		if err := rows.Err(); err != nil {
			return nil, xerrors.WithStackTrace(err)
		}

		return items, nil
	}, retry.WithLabel("BooksByYear"))
	if err != nil {
		return nil, xerrors.WithStackTrace(err)
	}

	return items, nil
}

const createAuthor = `-- name: CreateAuthor :one
INSERT INTO authors (name)
VALUES ($name)
RETURNING *;`

type CreateAuthorParams struct {
	Name string `json:"name"`
}

func (q *Queries) CreateAuthor(ctx context.Context, arg CreateAuthorParams) (*CreateAuthorRow, error) {
	i, err := retry.RetryWithResult(ctx, func(ctx context.Context) (*CreateAuthorRow, error) {
		row := q.db.QueryRowContext(ctx, createAuthor,
			sql.Named("name", arg.Name),
		)
		var i CreateAuthorRow
		err := row.Scan(&i.Author_id, &i.Name, &i.Biography)
		if err != nil {
			return nil, xerrors.WithStackTrace(err)
		}

		return &i, nil
	}, retry.WithLabel("CreateAuthor"))
	if err != nil {
		return nil, xerrors.WithStackTrace(err)
	}

	return i, nil
}

const createBook = `-- name: CreateBook :one
INSERT INTO books (
    author_id,
    isbn,
    book_type,
    title,
    year,
    available,
    tags
) VALUES (
    $author_id,
    $isbn,
    $book_type,
    $title,
    $year,
    $available,
    $tags
)
RETURNING *;`

type CreateBookParams struct {
	Author_id uint64 `json:"author_id"`
	Isbn string `json:"isbn"`
	Book_type string `json:"book_type"`
	Title string `json:"title"`
	Year uint64 `json:"year"`
	Available *string `json:"available"`
	Tags *string `json:"tags"`
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (*CreateBookRow, error) {
	i, err := retry.RetryWithResult(ctx, func(ctx context.Context) (*CreateBookRow, error) {
		row := q.db.QueryRowContext(ctx, createBook,
			sql.Named("author_id", arg.Author_id),
			sql.Named("isbn", arg.Isbn),
			sql.Named("book_type", arg.Book_type),
			sql.Named("title", arg.Title),
			sql.Named("year", arg.Year),
			sql.Named("available", arg.Available),
			sql.Named("tags", arg.Tags),
		)
		var i CreateBookRow
		err := row.Scan(&i.Book_id, &i.Author_id, &i.Isbn, &i.Book_type, &i.Title, &i.Year, &i.Available, &i.Tags)
		if err != nil {
			return nil, xerrors.WithStackTrace(err)
		}

		return &i, nil
	}, retry.WithLabel("CreateBook"))
	if err != nil {
		return nil, xerrors.WithStackTrace(err)
	}

	return i, nil
}

const updateBook = `-- name: UpdateBook :exec
UPDATE books
SET title = $title, tags = $tags
WHERE book_id = $book_id;`

type UpdateBookParams struct {
	Title string `json:"title"`
	Tags *string `json:"tags"`
	Book_id uint64 `json:"book_id"`
}

func (q *Queries) UpdateBook(ctx context.Context, arg UpdateBookParams) error {
	err := retry.Retry(ctx, func(ctx context.Context) error {
		_, err := q.db.ExecContext(ctx, updateBook,
			sql.Named("title", arg.Title),
			sql.Named("tags", arg.Tags),
			sql.Named("book_id", arg.Book_id),
		)
		if err != nil {
			return xerrors.WithStackTrace(err)
		}

		return nil
	}, retry.WithLabel("UpdateBook"))
	if err != nil {
		return xerrors.WithStackTrace(err)
	}

	return nil
}

const getBiography = `-- name: GetBiography :one
SELECT biography FROM authors
WHERE author_id = $author_id LIMIT 1;`

type GetBiographyParams struct {
	Author_id uint64 `json:"author_id"`
}

func (q *Queries) GetBiography(ctx context.Context, arg GetBiographyParams) (*interface{}, error) {
	i, err := retry.RetryWithResult(ctx, func(ctx context.Context) (*interface{}, error) {
		row := q.db.QueryRowContext(ctx, getBiography,
			sql.Named("author_id", arg.Author_id),
		)
		var i interface{}
		err := row.Scan()
		if err != nil {
			return nil, xerrors.WithStackTrace(err)
		}

		return &i, nil
	}, retry.WithLabel("GetBiography"))
	if err != nil {
		return nil, xerrors.WithStackTrace(err)
	}

	return i, nil
}
