// Code generated by sqlc-ydb. DO NOT EDIT.
#include "queries.hpp"

namespace authors::userver {

// -- name: GetAuthor :one
std::optional<GetAuthorRow> Queries::GetAuthor(std::uint64_t author_id) const {
    const auto sqlc_query = ::userver::ydb::Query{
        R"sql(
            SELECT id, name, bio FROM authors WHERE id = $author_id;
        )sql",
        ::userver::ydb::Query::Name{"GetAuthor"},
        ::userver::ydb::Query::LogMode::kNameOnly,
    };
    auto sqlc_response =
        this->transaction_ != nullptr
        ? this->transaction_->Execute(this->execute_settings_, sqlc_query, "$author_id", author_id)
        : this->client_->ExecuteQuery(this->operation_settings_, sqlc_query, "$author_id", author_id);
    auto sqlc_cursor = sqlc_response.GetSingleCursor();
    if (sqlc_cursor.empty()) {
        return std::nullopt;
    }
    auto sqlc_row = sqlc_cursor.GetFirstRow();
    return GetAuthorRow{
        sqlc_row.Get<std::uint64_t>("id"),
        sqlc_row.Get<::userver::ydb::Utf8>("name"),
        sqlc_row.Get<std::optional<::userver::ydb::Utf8>>("bio"),
    };
}

// -- name: ListAuthors :many
std::vector<ListAuthorsRow> Queries::ListAuthors() const {
    const auto sqlc_query = ::userver::ydb::Query{
        R"sql(
            SELECT id, name, bio FROM authors ORDER BY name;
        )sql",
        ::userver::ydb::Query::Name{"ListAuthors"},
        ::userver::ydb::Query::LogMode::kNameOnly,
    };
    auto sqlc_response =
        this->transaction_ != nullptr
        ? this->transaction_->Execute(this->execute_settings_, sqlc_query)
        : this->client_->ExecuteQuery(this->operation_settings_, sqlc_query);
    auto sqlc_cursor = sqlc_response.GetSingleCursor();
    std::vector<ListAuthorsRow> sqlc_rows;
    sqlc_rows.reserve(sqlc_cursor.size());
    for (auto sqlc_row : sqlc_cursor) {
        sqlc_rows.push_back(ListAuthorsRow{
            sqlc_row.Get<std::uint64_t>("id"),
            sqlc_row.Get<::userver::ydb::Utf8>("name"),
            sqlc_row.Get<std::optional<::userver::ydb::Utf8>>("bio"),
        });
    }
    return sqlc_rows;
}

// -- name: GetAuthorName :one
std::optional<GetAuthorNameRow> Queries::GetAuthorName(std::uint64_t author_id) const {
    const auto sqlc_query = ::userver::ydb::Query{
        R"sql(
            SELECT name FROM authors WHERE id = $author_id;
        )sql",
        ::userver::ydb::Query::Name{"GetAuthorName"},
        ::userver::ydb::Query::LogMode::kNameOnly,
    };
    auto sqlc_response =
        this->transaction_ != nullptr
        ? this->transaction_->Execute(this->execute_settings_, sqlc_query, "$author_id", author_id)
        : this->client_->ExecuteQuery(this->operation_settings_, sqlc_query, "$author_id", author_id);
    auto sqlc_cursor = sqlc_response.GetSingleCursor();
    if (sqlc_cursor.empty()) {
        return std::nullopt;
    }
    auto sqlc_row = sqlc_cursor.GetFirstRow();
    return GetAuthorNameRow{
        sqlc_row.Get<::userver::ydb::Utf8>("name"),
    };
}

// -- name: CreateAuthor :one
std::optional<CreateAuthorRow> Queries::CreateAuthor(std::uint64_t author_id, const ::userver::ydb::Utf8& author_name, const std::optional<::userver::ydb::Utf8>& biography) const {
    const auto sqlc_query = ::userver::ydb::Query{
        R"sql(
            INSERT INTO `authors` (`id`, `name`, `bio`)
            VALUES ($author_id, $author_name, $biography)
            RETURNING `id`, `name`, `bio`;
        )sql",
        ::userver::ydb::Query::Name{"CreateAuthor"},
        ::userver::ydb::Query::LogMode::kNameOnly,
    };
    auto sqlc_response =
        this->transaction_ != nullptr
        ? this->transaction_->Execute(this->execute_settings_, sqlc_query, "$author_id", author_id, "$author_name", author_name, "$biography", biography)
        : this->client_->ExecuteQuery(this->operation_settings_, sqlc_query, "$author_id", author_id, "$author_name", author_name, "$biography", biography);
    auto sqlc_cursor = sqlc_response.GetSingleCursor();
    if (sqlc_cursor.empty()) {
        return std::nullopt;
    }
    auto sqlc_row = sqlc_cursor.GetFirstRow();
    return CreateAuthorRow{
        sqlc_row.Get<std::uint64_t>("id"),
        sqlc_row.Get<::userver::ydb::Utf8>("name"),
        sqlc_row.Get<std::optional<::userver::ydb::Utf8>>("bio"),
    };
}

// -- name: UpsertAuthor :exec
void Queries::UpsertAuthor(std::uint64_t author_id, const ::userver::ydb::Utf8& author_name, const std::optional<::userver::ydb::Utf8>& biography) const {
    const auto sqlc_query = ::userver::ydb::Query{
        R"sql(
            UPSERT INTO authors (id, name, bio)
            VALUES ($author_id, $author_name, $biography);
        )sql",
        ::userver::ydb::Query::Name{"UpsertAuthor"},
        ::userver::ydb::Query::LogMode::kNameOnly,
    };
    static_cast<void>(
        this->transaction_ != nullptr
        ? this->transaction_->Execute(this->execute_settings_, sqlc_query, "$author_id", author_id, "$author_name", author_name, "$biography", biography)
        : this->client_->ExecuteQuery(this->operation_settings_, sqlc_query, "$author_id", author_id, "$author_name", author_name, "$biography", biography)
    );
}

// -- name: DeleteAuthor :exec
void Queries::DeleteAuthor(std::uint64_t author_id) const {
    const auto sqlc_query = ::userver::ydb::Query{
        R"sql(
            DELETE FROM authors WHERE id = $author_id;
        )sql",
        ::userver::ydb::Query::Name{"DeleteAuthor"},
        ::userver::ydb::Query::LogMode::kNameOnly,
    };
    static_cast<void>(
        this->transaction_ != nullptr
        ? this->transaction_->Execute(this->execute_settings_, sqlc_query, "$author_id", author_id)
        : this->client_->ExecuteQuery(this->operation_settings_, sqlc_query, "$author_id", author_id)
    );
}

}  // namespace authors::userver
