// Code generated by sqlc-ydb. DO NOT EDIT.
#include "queries.hpp"

namespace authors::userver {

// -- name: GetAuthor :one
std::optional<GetAuthorRow> Queries::GetAuthor(std::uint64_t author_id) const {
    const auto sqlc_query = ::userver::ydb::Query{
        "SELECT id, name, bio FROM authors WHERE id = $author_id;",
        ::userver::ydb::Query::Name{"GetAuthor"},
        ::userver::ydb::Query::LogMode::kNameOnly,
    };
    auto sqlc_response =
        this->transaction_ != nullptr
        ? this->transaction_->Execute(this->execute_settings_, sqlc_query, "$author_id", author_id)
        : this->client_->ExecuteQuery(this->operation_settings_, sqlc_query, "$author_id", author_id);
    auto sqlc_cursor = sqlc_response.GetSingleCursor();
    if (sqlc_cursor.empty()) {
        return std::nullopt;
    }
    auto sqlc_row = sqlc_cursor.GetFirstRow();
    return GetAuthorRow{
        sqlc_row.Get<std::uint64_t>("id"),
        sqlc_row.Get<::userver::ydb::Utf8>("name"),
        sqlc_row.Get<std::optional<::userver::ydb::Utf8>>("bio"),
    };
}

// -- name: ListAuthors :many
std::vector<ListAuthorsRow> Queries::ListAuthors() const {
    const auto sqlc_query = ::userver::ydb::Query{
        "SELECT id, name, bio FROM authors ORDER BY name;",
        ::userver::ydb::Query::Name{"ListAuthors"},
        ::userver::ydb::Query::LogMode::kNameOnly,
    };
    auto sqlc_response =
        this->transaction_ != nullptr
        ? this->transaction_->Execute(this->execute_settings_, sqlc_query)
        : this->client_->ExecuteQuery(this->operation_settings_, sqlc_query);
    auto sqlc_cursor = sqlc_response.GetSingleCursor();
    std::vector<ListAuthorsRow> sqlc_rows;
    sqlc_rows.reserve(sqlc_cursor.size());
    for (auto sqlc_row : sqlc_cursor) {
        sqlc_rows.push_back(ListAuthorsRow{
            sqlc_row.Get<std::uint64_t>("id"),
            sqlc_row.Get<::userver::ydb::Utf8>("name"),
            sqlc_row.Get<std::optional<::userver::ydb::Utf8>>("bio"),
        });
    }
    return sqlc_rows;
}

// -- name: ListAuthorsPage :many
std::vector<ListAuthorsPageRow> Queries::ListAuthorsPage(std::int32_t page_size, std::uint32_t offset) const {
    const auto sqlc_query = ::userver::ydb::Query{
        "DECLARE $page_size AS Int;\n"
        "DECLARE $offset AS Uint32;\n"
        "SELECT id, name, bio FROM authors ORDER BY id LIMIT $page_size OFFSET $offset;",
        ::userver::ydb::Query::Name{"ListAuthorsPage"},
        ::userver::ydb::Query::LogMode::kNameOnly,
    };
    auto sqlc_response =
        this->transaction_ != nullptr
        ? this->transaction_->Execute(this->execute_settings_, sqlc_query, "$page_size", page_size, "$offset", offset)
        : this->client_->ExecuteQuery(this->operation_settings_, sqlc_query, "$page_size", page_size, "$offset", offset);
    auto sqlc_cursor = sqlc_response.GetSingleCursor();
    std::vector<ListAuthorsPageRow> sqlc_rows;
    sqlc_rows.reserve(sqlc_cursor.size());
    for (auto sqlc_row : sqlc_cursor) {
        sqlc_rows.push_back(ListAuthorsPageRow{
            sqlc_row.Get<std::uint64_t>("id"),
            sqlc_row.Get<::userver::ydb::Utf8>("name"),
            sqlc_row.Get<std::optional<::userver::ydb::Utf8>>("bio"),
        });
    }
    return sqlc_rows;
}

// -- name: GetAuthorName :one
std::optional<GetAuthorNameRow> Queries::GetAuthorName(std::uint64_t author_id) const {
    const auto sqlc_query = ::userver::ydb::Query{
        "SELECT name FROM authors WHERE id = $author_id;",
        ::userver::ydb::Query::Name{"GetAuthorName"},
        ::userver::ydb::Query::LogMode::kNameOnly,
    };
    auto sqlc_response =
        this->transaction_ != nullptr
        ? this->transaction_->Execute(this->execute_settings_, sqlc_query, "$author_id", author_id)
        : this->client_->ExecuteQuery(this->operation_settings_, sqlc_query, "$author_id", author_id);
    auto sqlc_cursor = sqlc_response.GetSingleCursor();
    if (sqlc_cursor.empty()) {
        return std::nullopt;
    }
    auto sqlc_row = sqlc_cursor.GetFirstRow();
    return GetAuthorNameRow{
        sqlc_row.Get<::userver::ydb::Utf8>("name"),
    };
}

// -- name: CreateAuthor :one
std::optional<CreateAuthorRow> Queries::CreateAuthor(std::uint64_t author_id, const ::userver::ydb::Utf8& author_name, const std::optional<::userver::ydb::Utf8>& biography) const {
    const auto sqlc_query = ::userver::ydb::Query{
        "INSERT INTO `authors` (`id`, `name`, `bio`)\n"
        "VALUES ($author_id, $author_name, $biography)\n"
        "RETURNING `id`, `name`, `bio`;",
        ::userver::ydb::Query::Name{"CreateAuthor"},
        ::userver::ydb::Query::LogMode::kNameOnly,
    };
    auto sqlc_response =
        this->transaction_ != nullptr
        ? this->transaction_->Execute(this->execute_settings_, sqlc_query, "$author_id", author_id, "$author_name", author_name, "$biography", biography)
        : this->client_->ExecuteQuery(this->operation_settings_, sqlc_query, "$author_id", author_id, "$author_name", author_name, "$biography", biography);
    auto sqlc_cursor = sqlc_response.GetSingleCursor();
    if (sqlc_cursor.empty()) {
        return std::nullopt;
    }
    auto sqlc_row = sqlc_cursor.GetFirstRow();
    return CreateAuthorRow{
        sqlc_row.Get<std::uint64_t>("id"),
        sqlc_row.Get<::userver::ydb::Utf8>("name"),
        sqlc_row.Get<std::optional<::userver::ydb::Utf8>>("bio"),
    };
}

// -- name: UpsertAuthor :exec
void Queries::UpsertAuthor(std::uint64_t author_id, const ::userver::ydb::Utf8& author_name, const std::optional<::userver::ydb::Utf8>& biography) const {
    const auto sqlc_query = ::userver::ydb::Query{
        "UPSERT INTO authors (id, name, bio)\n"
        "VALUES ($author_id, $author_name, $biography);",
        ::userver::ydb::Query::Name{"UpsertAuthor"},
        ::userver::ydb::Query::LogMode::kNameOnly,
    };
    static_cast<void>(
        this->transaction_ != nullptr
        ? this->transaction_->Execute(this->execute_settings_, sqlc_query, "$author_id", author_id, "$author_name", author_name, "$biography", biography)
        : this->client_->ExecuteQuery(this->operation_settings_, sqlc_query, "$author_id", author_id, "$author_name", author_name, "$biography", biography)
    );
}

// -- name: DeleteAuthor :exec
void Queries::DeleteAuthor(std::uint64_t author_id) const {
    const auto sqlc_query = ::userver::ydb::Query{
        "DELETE FROM authors WHERE id = $author_id;",
        ::userver::ydb::Query::Name{"DeleteAuthor"},
        ::userver::ydb::Query::LogMode::kNameOnly,
    };
    static_cast<void>(
        this->transaction_ != nullptr
        ? this->transaction_->Execute(this->execute_settings_, sqlc_query, "$author_id", author_id)
        : this->client_->ExecuteQuery(this->operation_settings_, sqlc_query, "$author_id", author_id)
    );
}

// -- name: FindAuthorsByName :many
std::vector<FindAuthorsByNameRow> Queries::FindAuthorsByName(const ::userver::ydb::Utf8& name) const {
    const auto sqlc_query = ::userver::ydb::Query{
        "SELECT a.`id` AS `id`, `a`.`name` AS `name`, `a`.`bio` AS `bio` FROM authors VIEW by_name AS a\n"
        "WHERE a.name = $name ORDER BY a.id;",
        ::userver::ydb::Query::Name{"FindAuthorsByName"},
        ::userver::ydb::Query::LogMode::kNameOnly,
    };
    auto sqlc_response =
        this->transaction_ != nullptr
        ? this->transaction_->Execute(this->execute_settings_, sqlc_query, "$name", name)
        : this->client_->ExecuteQuery(this->operation_settings_, sqlc_query, "$name", name);
    auto sqlc_cursor = sqlc_response.GetSingleCursor();
    std::vector<FindAuthorsByNameRow> sqlc_rows;
    sqlc_rows.reserve(sqlc_cursor.size());
    for (auto sqlc_row : sqlc_cursor) {
        sqlc_rows.push_back(FindAuthorsByNameRow{
            sqlc_row.Get<std::uint64_t>("id"),
            sqlc_row.Get<::userver::ydb::Utf8>("name"),
            sqlc_row.Get<std::optional<::userver::ydb::Utf8>>("bio"),
        });
    }
    return sqlc_rows;
}

// -- name: FindAuthorsByNameCovering :many
std::vector<FindAuthorsByNameCoveringRow> Queries::FindAuthorsByNameCovering(const ::userver::ydb::Utf8& name) const {
    const auto sqlc_query = ::userver::ydb::Query{
        "DECLARE $name AS Utf8;\n"
        "SELECT `id`, `name`, `bio` FROM authors VIEW by_name_covering WHERE name = $name ORDER BY id;",
        ::userver::ydb::Query::Name{"FindAuthorsByNameCovering"},
        ::userver::ydb::Query::LogMode::kNameOnly,
    };
    auto sqlc_response =
        this->transaction_ != nullptr
        ? this->transaction_->Execute(this->execute_settings_, sqlc_query, "$name", name)
        : this->client_->ExecuteQuery(this->operation_settings_, sqlc_query, "$name", name);
    auto sqlc_cursor = sqlc_response.GetSingleCursor();
    std::vector<FindAuthorsByNameCoveringRow> sqlc_rows;
    sqlc_rows.reserve(sqlc_cursor.size());
    for (auto sqlc_row : sqlc_cursor) {
        sqlc_rows.push_back(FindAuthorsByNameCoveringRow{
            sqlc_row.Get<std::uint64_t>("id"),
            sqlc_row.Get<::userver::ydb::Utf8>("name"),
            sqlc_row.Get<std::optional<::userver::ydb::Utf8>>("bio"),
        });
    }
    return sqlc_rows;
}

// -- name: FindAuthorsByNamePrefix :many
std::vector<FindAuthorsByNamePrefixRow> Queries::FindAuthorsByNamePrefix(const ::userver::ydb::Utf8& prefix) const {
    const auto sqlc_query = ::userver::ydb::Query{
        "DECLARE $prefix AS Utf8;\n"
        "SELECT id, name, bio, bio IS NOT NULL AS has_bio\n"
        "FROM authors\n"
        "WHERE name LIKE $prefix || \"%\"u\n"
        "ORDER BY id;",
        ::userver::ydb::Query::Name{"FindAuthorsByNamePrefix"},
        ::userver::ydb::Query::LogMode::kNameOnly,
    };
    auto sqlc_response =
        this->transaction_ != nullptr
        ? this->transaction_->Execute(this->execute_settings_, sqlc_query, "$prefix", prefix)
        : this->client_->ExecuteQuery(this->operation_settings_, sqlc_query, "$prefix", prefix);
    auto sqlc_cursor = sqlc_response.GetSingleCursor();
    std::vector<FindAuthorsByNamePrefixRow> sqlc_rows;
    sqlc_rows.reserve(sqlc_cursor.size());
    for (auto sqlc_row : sqlc_cursor) {
        sqlc_rows.push_back(FindAuthorsByNamePrefixRow{
            sqlc_row.Get<std::uint64_t>("id"),
            sqlc_row.Get<::userver::ydb::Utf8>("name"),
            sqlc_row.Get<std::optional<::userver::ydb::Utf8>>("bio"),
            sqlc_row.Get<bool>("has_bio"),
        });
    }
    return sqlc_rows;
}

// -- name: GetAuthorStatistics :one
std::optional<GetAuthorStatisticsRow> Queries::GetAuthorStatistics() const {
    const auto sqlc_query = ::userver::ydb::Query{
        "SELECT\n"
        "    COUNT(*) AS total,\n"
        "    COUNT_IF(bio IS NOT NULL) AS with_bio,\n"
        "    COUNT_IF(bio != \"\"u) AS with_nonempty_bio,\n"
        "    CAST(COUNT(*) AS Bool)\n"
        "FROM authors;",
        ::userver::ydb::Query::Name{"GetAuthorStatistics"},
        ::userver::ydb::Query::LogMode::kNameOnly,
    };
    auto sqlc_response =
        this->transaction_ != nullptr
        ? this->transaction_->Execute(this->execute_settings_, sqlc_query)
        : this->client_->ExecuteQuery(this->operation_settings_, sqlc_query);
    auto sqlc_cursor = sqlc_response.GetSingleCursor();
    if (sqlc_cursor.empty()) {
        return std::nullopt;
    }
    auto sqlc_row = sqlc_cursor.GetFirstRow();
    return GetAuthorStatisticsRow{
        sqlc_row.Get<std::uint64_t>("total"),
        sqlc_row.Get<std::uint64_t>("with_bio"),
        sqlc_row.Get<std::uint64_t>("with_nonempty_bio"),
        sqlc_row.Get<bool>("column3"),
    };
}

// -- name: GetAuthorExportMetadata :one
std::optional<GetAuthorExportMetadataRow> Queries::GetAuthorExportMetadata(std::uint64_t author_id) const {
    const auto sqlc_query = ::userver::ydb::Query{
        "DECLARE $author_id AS Uint64;\n"
        "SELECT\n"
        "    id,\n"
        "    CAST(CurrentUtcDate() AS String) AS export_date,\n"
        "    CAST(CurrentUtcDatetime() AS String) AS export_datetime,\n"
        "    CurrentUtcTimestamp() AS export_timestamp,\n"
        "    CAST(CurrentUtcTimestamp() AS String) AS export_timestamp_text,\n"
        "    CAST(CurrentUtcTimestamp() AS Uint64) AS export_timestamp_micros,\n"
        "    COALESCE(CAST(id AS Uint32), 0),\n"
        "    CAST('{\"source\":\"authors\"}' AS Json) AS export_metadata\n"
        "FROM authors\n"
        "WHERE id = $author_id;",
        ::userver::ydb::Query::Name{"GetAuthorExportMetadata"},
        ::userver::ydb::Query::LogMode::kNameOnly,
    };
    auto sqlc_response =
        this->transaction_ != nullptr
        ? this->transaction_->Execute(this->execute_settings_, sqlc_query, "$author_id", author_id)
        : this->client_->ExecuteQuery(this->operation_settings_, sqlc_query, "$author_id", author_id);
    auto sqlc_cursor = sqlc_response.GetSingleCursor();
    if (sqlc_cursor.empty()) {
        return std::nullopt;
    }
    auto sqlc_row = sqlc_cursor.GetFirstRow();
    return GetAuthorExportMetadataRow{
        sqlc_row.Get<std::uint64_t>("id"),
        sqlc_row.Get<std::string>("export_date"),
        sqlc_row.Get<std::string>("export_datetime"),
        sqlc_row.Get<std::chrono::system_clock::time_point>("export_timestamp"),
        sqlc_row.Get<std::string>("export_timestamp_text"),
        sqlc_row.Get<std::uint64_t>("export_timestamp_micros"),
        sqlc_row.Get<std::uint32_t>("column6"),
        sqlc_row.Get<std::optional<::userver::formats::json::Value>>("export_metadata"),
    };
}

// -- name: EchoAuthorIDText :one
std::optional<EchoAuthorIDTextRow> Queries::EchoAuthorIDText(const ::userver::ydb::Utf8& author_id) const {
    const auto sqlc_query = ::userver::ydb::Query{
        "SELECT $author_id AS author_id_text;",
        ::userver::ydb::Query::Name{"EchoAuthorIDText"},
        ::userver::ydb::Query::LogMode::kNameOnly,
    };
    auto sqlc_response =
        this->transaction_ != nullptr
        ? this->transaction_->Execute(this->execute_settings_, sqlc_query, "$author_id", author_id)
        : this->client_->ExecuteQuery(this->operation_settings_, sqlc_query, "$author_id", author_id);
    auto sqlc_cursor = sqlc_response.GetSingleCursor();
    if (sqlc_cursor.empty()) {
        return std::nullopt;
    }
    auto sqlc_row = sqlc_cursor.GetFirstRow();
    return EchoAuthorIDTextRow{
        sqlc_row.Get<::userver::ydb::Utf8>("author_id_text"),
    };
}

}  // namespace authors::userver
