// Code generated by sqlc-ydb. DO NOT EDIT.
package db

import (
	"context"
	"database/sql"
)

type DBTX interface {
	ExecContext(context.Context, string, ...any) (sql.Result, error)
	QueryContext(context.Context, string, ...any) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...any) *sql.Row
}
type Queries struct{ db DBTX }

func New(db DBTX) *Queries                    { return &Queries{db: db} }
func (q *Queries) WithTx(tx *sql.Tx) *Queries { return &Queries{db: tx} }
