// Code generated by sqlc-ydb. DO NOT EDIT.
// source: queries.sql
package db

import (
	"context"
	"database/sql"
)

const queryColdCities = `-- name: ColdCities :many
DECLARE $maximum_temperature AS Int32;
SELECT city, COUNT(*) AS reading_count, MAX(temperature) AS hottest_temperature
FROM weather
GROUP BY city
HAVING MAX(temperature) < $maximum_temperature;`

func (q *Queries) ColdCities(ctx context.Context, arg int32) ([]ColdCitiesRow, error) {
	rows, err := q.db.QueryContext(ctx, queryColdCities, sql.Named("maximum_temperature", arg))
	if err != nil {
		return []ColdCitiesRow(nil), err
	}
	defer rows.Close()
	items := []ColdCitiesRow(nil)
	for rows.Next() {
		var row ColdCitiesRow
		if err := rows.Scan(&row.City, &row.ReadingCount, &row.HottestTemperature); err != nil {
			return nil, err
		}
		items = append(items, row)
	}
	return items, rows.Err()
}
