// Code generated by sqlc-ydb. DO NOT EDIT.
package booktest.jdbc;

import tech.ydb.table.values.PrimitiveValue;

// The caller owns the injected client and its lifecycle.
public final class Queries {
    private final java.sql.Connection client;

    public Queries(java.sql.Connection client) {
        this.client = java.util.Objects.requireNonNull(client);
    }

    // -- name: GetAuthor :one
    public java.util.Optional<GetAuthorRow> getAuthor(long authorId) throws java.sql.SQLException {
        try (var _prepared = client.prepareStatement("""
            SELECT author_id, name
            FROM authors
            WHERE author_id = ?;\
            """)) {
            _prepared.setObject(1, PrimitiveValue.newUint64(authorId));
            try (var _rows = _prepared.executeQuery()) {
                if (!_rows.next()) return java.util.Optional.empty();
                long _value0 = _rows.getLong(1);
                String _value1 = _rows.getString(2);
                return java.util.Optional.of(new GetAuthorRow(_value0, _value1));
            }
        }
    }

    // -- name: GetBook :one
    public java.util.Optional<GetBookRow> getBook(long bookId) throws java.sql.SQLException {
        try (var _prepared = client.prepareStatement("""
            SELECT book_id, author_id, isbn, book_type, title, publication_year, available, tags
            FROM books
            WHERE book_id = ?;\
            """)) {
            _prepared.setObject(1, PrimitiveValue.newUint64(bookId));
            try (var _rows = _prepared.executeQuery()) {
                if (!_rows.next()) return java.util.Optional.empty();
                long _value0 = _rows.getLong(1);
                long _value1 = _rows.getLong(2);
                String _value2 = _rows.getString(3);
                String _value3 = _rows.getString(4);
                String _value4 = _rows.getString(5);
                int _value5 = _rows.getInt(6);
                var _value6Raw = _rows.getTimestamp(7);
                java.time.Instant _value6 = _value6Raw == null ? null : _value6Raw.toInstant();
                String _value7 = _rows.getString(8);
                return java.util.Optional.of(new GetBookRow(_value0, _value1, _value2, _value3, _value4, _value5, _value6, _value7));
            }
        }
    }

    // -- name: DeleteBook :exec
    public void deleteBook(long bookId) throws java.sql.SQLException {
        try (var _prepared = client.prepareStatement("""
            DELETE FROM books
            WHERE book_id = ?;\
            """)) {
            _prepared.setObject(1, PrimitiveValue.newUint64(bookId));
            _prepared.execute();
        }
    }

    // -- name: BooksByTitleYear :many
    public java.util.List<BooksByTitleYearRow> booksByTitleYear(String title, int publicationYear) throws java.sql.SQLException {
        try (var _prepared = client.prepareStatement("""
            SELECT book_id, author_id, isbn, book_type, title, publication_year, available, tags
            FROM books
            WHERE title = ? AND publication_year = ?;\
            """)) {
            _prepared.setString(1, title);
            _prepared.setInt(2, publicationYear);
            try (var _rows = _prepared.executeQuery()) {
                var _items = new java.util.ArrayList<BooksByTitleYearRow>();
                while (_rows.next()) {
                    long _value0 = _rows.getLong(1);
                    long _value1 = _rows.getLong(2);
                    String _value2 = _rows.getString(3);
                    String _value3 = _rows.getString(4);
                    String _value4 = _rows.getString(5);
                    int _value5 = _rows.getInt(6);
                    var _value6Raw = _rows.getTimestamp(7);
                    java.time.Instant _value6 = _value6Raw == null ? null : _value6Raw.toInstant();
                    String _value7 = _rows.getString(8);
                    _items.add(new BooksByTitleYearRow(_value0, _value1, _value2, _value3, _value4, _value5, _value6, _value7));
                }
                return _items;
            }
        }
    }

    // -- name: BooksByTags :many
    public java.util.List<BooksByTagsRow> booksByTags(String tags) throws java.sql.SQLException {
        try (var _prepared = client.unwrap(tech.ydb.jdbc.YdbConnection.class).prepareStatement("""
            DECLARE $tags AS Json;
            SELECT
                b.book_id,
                b.title,
                a.name,
                b.isbn,
                b.tags
            FROM books AS b
            LEFT JOIN authors AS a ON b.author_id = a.author_id
            WHERE NOT SetIsDisjoint(
                ToSet(Yson::ConvertToStringList(b.tags)),
                Yson::ConvertToStringList($tags)
            );\
            """, tech.ydb.jdbc.YdbPrepareMode.DATA_QUERY)) {
            _prepared.setString("tags", tags);
            try (var _rows = _prepared.executeQuery()) {
                var _items = new java.util.ArrayList<BooksByTagsRow>();
                while (_rows.next()) {
                    long _value0 = _rows.getLong(1);
                    String _value1 = _rows.getString(2);
                    String _value2 = _rows.getString(3);
                    String _value3 = _rows.getString(4);
                    String _value4 = _rows.getString(5);
                    _items.add(new BooksByTagsRow(_value0, _value1, _value2, _value3, _value4));
                }
                return _items;
            }
        }
    }

    // -- name: CreateAuthor :one
    public java.util.Optional<CreateAuthorRow> createAuthor(long authorId, String name) throws java.sql.SQLException {
        try (var _prepared = client.prepareStatement("""
            INSERT INTO authors (author_id, name)
            VALUES (?, ?)
            RETURNING author_id, name;\
            """)) {
            _prepared.setObject(1, PrimitiveValue.newUint64(authorId));
            _prepared.setString(2, name);
            try (var _rows = _prepared.executeQuery()) {
                if (!_rows.next()) return java.util.Optional.empty();
                long _value0 = _rows.getLong(1);
                String _value1 = _rows.getString(2);
                return java.util.Optional.of(new CreateAuthorRow(_value0, _value1));
            }
        }
    }

    // -- name: CreateBook :one
    public java.util.Optional<CreateBookRow> createBook(long bookId, long authorId, String isbn, String bookType, String title, int publicationYear, java.time.Instant available, String tags) throws java.sql.SQLException {
        try (var _prepared = client.prepareStatement("""
            INSERT INTO books (
                book_id,
                author_id,
                isbn,
                book_type,
                title,
                publication_year,
                available,
                tags
            ) VALUES (
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?
            )
            RETURNING book_id, author_id, isbn, book_type, title, publication_year, available, tags;\
            """)) {
            _prepared.setObject(1, PrimitiveValue.newUint64(bookId));
            _prepared.setObject(2, PrimitiveValue.newUint64(authorId));
            _prepared.setString(3, isbn);
            _prepared.setString(4, bookType);
            _prepared.setString(5, title);
            _prepared.setInt(6, publicationYear);
            _prepared.setTimestamp(7, java.sql.Timestamp.from(available));
            _prepared.setObject(8, PrimitiveValue.newJson(tags));
            try (var _rows = _prepared.executeQuery()) {
                if (!_rows.next()) return java.util.Optional.empty();
                long _value0 = _rows.getLong(1);
                long _value1 = _rows.getLong(2);
                String _value2 = _rows.getString(3);
                String _value3 = _rows.getString(4);
                String _value4 = _rows.getString(5);
                int _value5 = _rows.getInt(6);
                var _value6Raw = _rows.getTimestamp(7);
                java.time.Instant _value6 = _value6Raw == null ? null : _value6Raw.toInstant();
                String _value7 = _rows.getString(8);
                return java.util.Optional.of(new CreateBookRow(_value0, _value1, _value2, _value3, _value4, _value5, _value6, _value7));
            }
        }
    }

    // -- name: UpdateBook :exec
    public void updateBook(String title, String tags, long bookId) throws java.sql.SQLException {
        try (var _prepared = client.prepareStatement("""
            UPDATE books
            SET title = ?, tags = ?
            WHERE book_id = ?;\
            """)) {
            _prepared.setString(1, title);
            _prepared.setObject(2, PrimitiveValue.newJson(tags));
            _prepared.setObject(3, PrimitiveValue.newUint64(bookId));
            _prepared.execute();
        }
    }

    // -- name: UpdateBookISBN :exec
    public void updateBookISBN(String title, String tags, String isbn, long bookId) throws java.sql.SQLException {
        try (var _prepared = client.prepareStatement("""
            UPDATE books
            SET title = ?, tags = ?, isbn = ?
            WHERE book_id = ?;\
            """)) {
            _prepared.setString(1, title);
            _prepared.setObject(2, PrimitiveValue.newJson(tags));
            _prepared.setString(3, isbn);
            _prepared.setObject(4, PrimitiveValue.newUint64(bookId));
            _prepared.execute();
        }
    }

    // -- name: DeleteAuthorBeforeYear :exec
    public void deleteAuthorBeforeYear(int publicationYear, long authorId) throws java.sql.SQLException {
        try (var _prepared = client.prepareStatement("""
            DELETE FROM books
            WHERE publication_year < ? AND author_id = ?;\
            """)) {
            _prepared.setInt(1, publicationYear);
            _prepared.setObject(2, PrimitiveValue.newUint64(authorId));
            _prepared.execute();
        }
    }

    // -- name: SayHello :one
    public java.util.Optional<SayHelloRow> sayHello(String name) throws java.sql.SQLException {
        try (var _prepared = client.prepareStatement("""
            SELECT \"hello \"u || ? AS greeting;\
            """)) {
            _prepared.setString(1, name);
            try (var _rows = _prepared.executeQuery()) {
                if (!_rows.next()) return java.util.Optional.empty();
                String _value0 = _rows.getString(1);
                return java.util.Optional.of(new SayHelloRow(_value0));
            }
        }
    }

    // -- name: ListAuthorsWithRecentBooks :many
    public java.util.List<ListAuthorsWithRecentBooksRow> listAuthorsWithRecentBooks(int sinceYear) throws java.sql.SQLException {
        try (var _prepared = client.prepareStatement("""
            SELECT a.author_id, a.name
            FROM authors AS a
            WHERE a.author_id IN (
                SELECT b.author_id FROM books AS b WHERE b.publication_year >= ?
            )
            ORDER BY a.author_id;\
            """)) {
            _prepared.setInt(1, sinceYear);
            try (var _rows = _prepared.executeQuery()) {
                var _items = new java.util.ArrayList<ListAuthorsWithRecentBooksRow>();
                while (_rows.next()) {
                    long _value0 = _rows.getLong(1);
                    String _value1 = _rows.getString(2);
                    _items.add(new ListAuthorsWithRecentBooksRow(_value0, _value1));
                }
                return _items;
            }
        }
    }

    // -- name: ListBooksWithRecentEditions :many
    public java.util.List<ListBooksWithRecentEditionsRow> listBooksWithRecentEditions(int sinceYear) throws java.sql.SQLException {
        try (var _prepared = client.unwrap(tech.ydb.jdbc.YdbConnection.class).prepareStatement("""
            DECLARE $since_year AS Int32;
            SELECT b.book_id, b.author_id, b.isbn, b.book_type, b.title, b.publication_year, b.available, b.tags
            FROM books AS b
            WHERE (b.author_id, b.book_type) IN (
                SELECT (recent.author_id, recent.book_type)
                FROM books AS recent
                WHERE recent.publication_year >= $since_year
            )
            ORDER BY b.book_id;\
            """, tech.ydb.jdbc.YdbPrepareMode.DATA_QUERY)) {
            _prepared.setInt("since_year", sinceYear);
            try (var _rows = _prepared.executeQuery()) {
                var _items = new java.util.ArrayList<ListBooksWithRecentEditionsRow>();
                while (_rows.next()) {
                    long _value0 = _rows.getLong(1);
                    long _value1 = _rows.getLong(2);
                    String _value2 = _rows.getString(3);
                    String _value3 = _rows.getString(4);
                    String _value4 = _rows.getString(5);
                    int _value5 = _rows.getInt(6);
                    var _value6Raw = _rows.getTimestamp(7);
                    java.time.Instant _value6 = _value6Raw == null ? null : _value6Raw.toInstant();
                    String _value7 = _rows.getString(8);
                    _items.add(new ListBooksWithRecentEditionsRow(_value0, _value1, _value2, _value3, _value4, _value5, _value6, _value7));
                }
                return _items;
            }
        }
    }

    // -- name: DeleteBooksByAuthorName :exec
    public void deleteBooksByAuthorName(String authorName) throws java.sql.SQLException {
        try (var _prepared = client.prepareStatement("""
            DELETE FROM books
            WHERE author_id IN (SELECT author_id FROM authors WHERE name = ?);\
            """)) {
            _prepared.setString(1, authorName);
            _prepared.execute();
        }
    }

    // -- name: DeleteAuthorWithBooks :exec
    public void deleteAuthorWithBooks(long authorId) throws java.sql.SQLException {
        try (var _prepared = client.unwrap(tech.ydb.jdbc.YdbConnection.class).prepareStatement("""
            DECLARE $author_id AS Uint64;
            DELETE FROM books WHERE author_id = $author_id;
            DELETE FROM authors WHERE author_id = $author_id;\
            """, tech.ydb.jdbc.YdbPrepareMode.DATA_QUERY)) {
            _prepared.setObject("author_id", PrimitiveValue.newUint64(authorId));
            _prepared.execute();
        }
    }

    // -- name: UpdateAuthorAndListBooks :many
    public java.util.List<UpdateAuthorAndListBooksRow> updateAuthorAndListBooks(long authorId, String name) throws java.sql.SQLException {
        try (var _prepared = client.unwrap(tech.ydb.jdbc.YdbConnection.class).prepareStatement("""
            DECLARE $author_id AS Uint64;
            DECLARE $name AS Utf8;
            UPDATE authors SET name = $name WHERE author_id = $author_id;
            SELECT book_id, title FROM books WHERE author_id = $author_id ORDER BY book_id;\
            """, tech.ydb.jdbc.YdbPrepareMode.DATA_QUERY)) {
            _prepared.setObject("author_id", PrimitiveValue.newUint64(authorId));
            _prepared.setString("name", name);
            _prepared.execute();
            while (_prepared.getResultSet() == null && _prepared.getUpdateCount() != -1) {
                _prepared.getMoreResults();
            }
            try (var _rows = _prepared.getResultSet()) {
                if (_rows == null) throw new java.sql.SQLException("Expected one result set");
                var _items = new java.util.ArrayList<UpdateAuthorAndListBooksRow>();
                while (_rows.next()) {
                    long _value0 = _rows.getLong(1);
                    String _value1 = _rows.getString(2);
                    _items.add(new UpdateAuthorAndListBooksRow(_value0, _value1));
                }
                while (_prepared.getMoreResults() || _prepared.getUpdateCount() != -1) {
                    if (_prepared.getResultSet() != null) throw new java.sql.SQLException("Expected one result set");
                }
                return _items;
            }
        }
    }

    // -- name: SelectAuthorAndDeleteBooks :one
    public java.util.Optional<SelectAuthorAndDeleteBooksRow> selectAuthorAndDeleteBooks(long authorId) throws java.sql.SQLException {
        try (var _prepared = client.unwrap(tech.ydb.jdbc.YdbConnection.class).prepareStatement("""
            DECLARE $author_id AS Uint64;
            SELECT author_id, name FROM authors WHERE author_id = $author_id;
            DELETE FROM books WHERE author_id = $author_id;\
            """, tech.ydb.jdbc.YdbPrepareMode.DATA_QUERY)) {
            _prepared.setObject("author_id", PrimitiveValue.newUint64(authorId));
            _prepared.execute();
            while (_prepared.getResultSet() == null && _prepared.getUpdateCount() != -1) {
                _prepared.getMoreResults();
            }
            try (var _rows = _prepared.getResultSet()) {
                if (_rows == null) throw new java.sql.SQLException("Expected one result set");
                if (!_rows.next()) {
                    while (_prepared.getMoreResults() || _prepared.getUpdateCount() != -1) {
                        if (_prepared.getResultSet() != null) throw new java.sql.SQLException("Expected one result set");
                    }
                    return java.util.Optional.empty();
                }
                long _value0 = _rows.getLong(1);
                String _value1 = _rows.getString(2);
                while (_rows.next()) {}
                while (_prepared.getMoreResults() || _prepared.getUpdateCount() != -1) {
                    if (_prepared.getResultSet() != null) throw new java.sql.SQLException("Expected one result set");
                }
                return java.util.Optional.of(new SelectAuthorAndDeleteBooksRow(_value0, _value1));
            }
        }
    }
}
