# Code generated by sqlc-ydb. DO NOT EDIT.
from __future__ import annotations
from typing import Iterable, Optional
from . import models as _models
import ydb as _ydb


def _typed(value, typ):
    return (value, typ)


class Querier:
    def __init__(self, connection):
        self._connection = connection

    def get_author(self, author_id: int) -> Optional[_models.Author]:
        parameters = {"$author_id": _typed(author_id, _ydb.PrimitiveType.Uint64)}
        cursor = self._connection.cursor()
        try:
            cursor.execute(
                ("-- name: GetAuthor :one\n"
                 "SELECT id, name, bio FROM authors WHERE id = $author_id;"), parameters)
            rows = cursor.fetchall()
            if not rows:
                return None
            row = rows[0]
            return _models.Author(
                id=row[0],
                name=row[1],
                bio=row[2],
            )
        finally:
            cursor.close()

    def list_authors(self) -> Iterable[_models.Author]:
        parameters = {}
        cursor = self._connection.cursor()
        try:
            cursor.execute(
                ("-- name: ListAuthors :many\n"
                 "SELECT id, name, bio FROM authors ORDER BY name;"), parameters)
            rows = cursor.fetchall()
            return (_models.Author(
                id=row[0],
                name=row[1],
                bio=row[2],
            ) for row in rows)
        finally:
            cursor.close()

    def get_author_name(self, author_id: int) -> Optional[_models.GetAuthorNameRow]:
        parameters = {"$author_id": _typed(author_id, _ydb.PrimitiveType.Uint64)}
        cursor = self._connection.cursor()
        try:
            cursor.execute(
                ("-- name: GetAuthorName :one\n"
                 "SELECT name FROM authors WHERE id = $author_id;"), parameters)
            rows = cursor.fetchall()
            if not rows:
                return None
            row = rows[0]
            return _models.GetAuthorNameRow(
                name=row[0],
            )
        finally:
            cursor.close()

    def create_author(self, author_id: int, author_name: str, biography: Optional[str]) -> Optional[_models.Author]:
        parameters = {"$author_id": _typed(author_id, _ydb.PrimitiveType.Uint64),"$author_name": _typed(author_name, _ydb.PrimitiveType.Utf8),"$biography": _typed(biography, _ydb.OptionalType(_ydb.PrimitiveType.Utf8))}
        cursor = self._connection.cursor()
        try:
            cursor.execute(
                ("-- name: CreateAuthor :one\n"
                 "INSERT INTO authors (id, name, bio)\n"
                 "VALUES ($author_id, $author_name, $biography)\n"
                 "RETURNING id, name, bio;"), parameters)
            rows = cursor.fetchall()
            if not rows:
                return None
            row = rows[0]
            return _models.Author(
                id=row[0],
                name=row[1],
                bio=row[2],
            )
        finally:
            cursor.close()

    def upsert_author(self, author_id: int, author_name: str, biography: Optional[str]) -> None:
        parameters = {"$author_id": _typed(author_id, _ydb.PrimitiveType.Uint64),"$author_name": _typed(author_name, _ydb.PrimitiveType.Utf8),"$biography": _typed(biography, _ydb.OptionalType(_ydb.PrimitiveType.Utf8))}
        cursor = self._connection.cursor()
        try:
            cursor.execute(
                ("-- name: UpsertAuthor :exec\n"
                 "UPSERT INTO authors (id, name, bio)\n"
                 "VALUES ($author_id, $author_name, $biography);"), parameters)
            return None
        finally:
            cursor.close()

    def delete_author(self, author_id: int) -> None:
        parameters = {"$author_id": _typed(author_id, _ydb.PrimitiveType.Uint64)}
        cursor = self._connection.cursor()
        try:
            cursor.execute(
                ("-- name: DeleteAuthor :exec\n"
                 "DELETE FROM authors WHERE id = $author_id;"), parameters)
            return None
        finally:
            cursor.close()
