# Code generated by sqlc-ydb. DO NOT EDIT.
from __future__ import annotations
from typing import Iterable, Optional
from . import models
import ydb

SQL_GET_AUTHOR = """-- name: GetAuthor :one
DECLARE $author_id AS Uint64;
SELECT id, name, bio FROM authors WHERE id = $author_id;"""

SQL_LIST_AUTHORS = """-- name: ListAuthors :many
SELECT id, name, bio FROM authors ORDER BY id;"""

SQL_GET_AUTHOR_NAME = """-- name: GetAuthorName :one
DECLARE $author_id AS Uint64;
SELECT name FROM authors WHERE id = $author_id;"""

SQL_UPSERT_AUTHOR = """-- name: UpsertAuthor :exec
DECLARE $author_id AS Uint64;
DECLARE $author_name AS Utf8;
DECLARE $biography AS Optional<Utf8>;
UPSERT INTO authors (id, name, bio)
VALUES ($author_id, $author_name, $biography);"""

SQL_DELETE_AUTHOR = """-- name: DeleteAuthor :exec
DECLARE $author_id AS Uint64;
DELETE FROM authors WHERE id = $author_id;"""


def _typed(value, typ):
    return (value, typ)

def _row_value(row, name, index):
    try:
        return row[name]
    except (KeyError, IndexError, TypeError):
        try:
            return row[index]
        except (KeyError, IndexError, TypeError):
            return getattr(row, name)


class Querier:
    def __init__(self, connection):
        self._connection = connection

    def get_author(self, author_id: int) -> Optional[models.Author]:
        parameters = {"$author_id": _typed(author_id, ydb.PrimitiveType.Uint64)}
        cursor = self._connection.cursor()
        try:
            cursor.execute(SQL_GET_AUTHOR, parameters)
            rows = cursor.fetchall()
            if not rows:
                return None
            row = rows[0]
            return models.Author(
                id=_row_value(row, "id", 0),
                name=_row_value(row, "name", 1),
                bio=_row_value(row, "bio", 2),
            )
        finally:
            cursor.close()

    def list_authors(self) -> Iterable[models.Author]:
        parameters = {}
        cursor = self._connection.cursor()
        try:
            cursor.execute(SQL_LIST_AUTHORS, parameters)
            rows = cursor.fetchall()
            return (models.Author(
                id=_row_value(row, "id", 0),
                name=_row_value(row, "name", 1),
                bio=_row_value(row, "bio", 2),
            ) for row in rows)
        finally:
            cursor.close()

    def get_author_name(self, author_id: int) -> Optional[models.GetAuthorNameRow]:
        parameters = {"$author_id": _typed(author_id, ydb.PrimitiveType.Uint64)}
        cursor = self._connection.cursor()
        try:
            cursor.execute(SQL_GET_AUTHOR_NAME, parameters)
            rows = cursor.fetchall()
            if not rows:
                return None
            row = rows[0]
            return models.GetAuthorNameRow(
                name=_row_value(row, "name", 0),
            )
        finally:
            cursor.close()

    def upsert_author(self, author_id: int, author_name: str, biography: Optional[str]) -> None:
        parameters = {"$author_id": _typed(author_id, ydb.PrimitiveType.Uint64),"$author_name": _typed(author_name, ydb.PrimitiveType.Utf8),"$biography": _typed(biography, ydb.OptionalType(ydb.PrimitiveType.Utf8))}
        cursor = self._connection.cursor()
        try:
            cursor.execute(SQL_UPSERT_AUTHOR, parameters)
            return None
        finally:
            cursor.close()

    def delete_author(self, author_id: int) -> None:
        parameters = {"$author_id": _typed(author_id, ydb.PrimitiveType.Uint64)}
        cursor = self._connection.cursor()
        try:
            cursor.execute(SQL_DELETE_AUTHOR, parameters)
            return None
        finally:
            cursor.close()
