<?php
// Code generated by sqlc-ydb. DO NOT EDIT.
declare(strict_types=1);

namespace Ondeck\Native;

final class UpdateCityNameParams
{
    public function __construct(
        public readonly string $name,
        public readonly string $slug
    ) {}
}
