<?php
// Code generated by sqlc-ydb. DO NOT EDIT.
declare(strict_types=1);

namespace Ondeck\Native;

final class Venue
{
    public function __construct(
        public readonly string $id,
        public readonly string $status,
        public readonly ?string $statuses,
        public readonly string $slug,
        public readonly string $name,
        public readonly string $city,
        public readonly string $spotifyPlaylist,
        public readonly ?string $songkickId,
        public readonly ?string $tags,
        public readonly ?int $createdAt
    ) {}
}
