// Code generated by sqlc-ydb. DO NOT EDIT.
import { Json, JsonType, Primitive, TimestampType, Uint64, Utf8 } from "@ydbjs/value/primitive";
import { Optional } from "@ydbjs/value/optional";

export const LIST_CITIES_SQL = `-- name: ListCities :many
SELECT slug, name
FROM city
ORDER BY name;`;

export const GET_CITY_SQL = `-- name: GetCity :one
DECLARE $slug AS Utf8;
SELECT slug, name
FROM city
WHERE slug = $slug;`;
const _GET_CITY_SQL_EXEC = `-- name: GetCity :one
\x20\x20\x20
SELECT slug, name
FROM city
WHERE slug = $slug;`;

export const CREATE_CITY_SQL = `-- name: CreateCity :one
DECLARE $name AS Utf8;
DECLARE $slug AS Utf8;
INSERT INTO city (
    name,
    slug
) VALUES (
    $name,
    $slug
) RETURNING slug, name;`;
const _CREATE_CITY_SQL_EXEC = `-- name: CreateCity :one
\x20\x20\x20
\x20\x20\x20
INSERT INTO city (
    name,
    slug
) VALUES (
    $name,
    $slug
) RETURNING slug, name;`;

export const UPDATE_CITY_NAME_SQL = `-- name: UpdateCityName :exec
DECLARE $name AS Utf8;
DECLARE $slug AS Utf8;
UPDATE city
SET name = $name
WHERE slug = $slug;`;
const _UPDATE_CITY_NAME_SQL_EXEC = `-- name: UpdateCityName :exec
\x20\x20\x20
\x20\x20\x20
UPDATE city
SET name = $name
WHERE slug = $slug;`;

export const LIST_VENUES_SQL = `-- name: ListVenues :many
DECLARE $city AS Utf8;
SELECT id, slug, name, city, status, statuses, spotify_playlist, songkick_id, tags, created_at
FROM venue
WHERE city = $city
ORDER BY name;`;
const _LIST_VENUES_SQL_EXEC = `-- name: ListVenues :many
\x20\x20\x20
SELECT id, slug, name, city, status, statuses, spotify_playlist, songkick_id, tags, created_at
FROM venue
WHERE city = $city
ORDER BY name;`;

export const DELETE_VENUE_SQL = `-- name: DeleteVenue :exec
DECLARE $slug AS Utf8;
DELETE FROM venue
WHERE slug = $slug AND slug = $slug;`;
const _DELETE_VENUE_SQL_EXEC = `-- name: DeleteVenue :exec
\x20\x20\x20
DELETE FROM venue
WHERE slug = $slug AND slug = $slug;`;

export const GET_VENUE_SQL = `-- name: GetVenue :one
DECLARE $slug AS Utf8;
DECLARE $city AS Utf8;
SELECT id, slug, name, city, status, statuses, spotify_playlist, songkick_id, tags, created_at
FROM venue
WHERE slug = $slug AND city = $city;`;
const _GET_VENUE_SQL_EXEC = `-- name: GetVenue :one
\x20\x20\x20
\x20\x20\x20
SELECT id, slug, name, city, status, statuses, spotify_playlist, songkick_id, tags, created_at
FROM venue
WHERE slug = $slug AND city = $city;`;

export const CREATE_VENUE_SQL = `-- name: CreateVenue :one
DECLARE $id AS Uint64;
DECLARE $slug AS Utf8;
DECLARE $name AS Utf8;
DECLARE $city AS Utf8;
DECLARE $created_at AS Optional<Timestamp>;
DECLARE $spotify_playlist AS Utf8;
DECLARE $status AS Utf8;
DECLARE $statuses AS Optional<Json>;
DECLARE $tags AS Optional<Json>;
INSERT INTO venue (
    id,
    slug,
    name,
    city,
    created_at,
    spotify_playlist,
    status,
    statuses,
    tags
) VALUES (
    $id,
    $slug,
    $name,
    $city,
    $created_at,
    $spotify_playlist,
    $status,
    $statuses,
    $tags
) RETURNING id;`;
const _CREATE_VENUE_SQL_EXEC = `-- name: CreateVenue :one
\x20\x20\x20
\x20\x20\x20
\x20\x20\x20
\x20\x20\x20
\x20\x20\x20
\x20\x20\x20
\x20\x20\x20
\x20\x20\x20
\x20\x20\x20
INSERT INTO venue (
    id,
    slug,
    name,
    city,
    created_at,
    spotify_playlist,
    status,
    statuses,
    tags
) VALUES (
    $id,
    $slug,
    $name,
    $city,
    $created_at,
    $spotify_playlist,
    $status,
    $statuses,
    $tags
) RETURNING id;`;

export const UPDATE_VENUE_NAME_SQL = `-- name: UpdateVenueName :one
DECLARE $name AS Utf8;
DECLARE $slug AS Utf8;
UPDATE venue
SET name = $name
WHERE slug = $slug
RETURNING id;`;
const _UPDATE_VENUE_NAME_SQL_EXEC = `-- name: UpdateVenueName :one
\x20\x20\x20
\x20\x20\x20
UPDATE venue
SET name = $name
WHERE slug = $slug
RETURNING id;`;

export const VENUE_COUNT_BY_CITY_SQL = `-- name: VenueCountByCity :many
SELECT
    city,
    COUNT(*) AS venue_count
FROM venue
GROUP BY city
ORDER BY city;`;

function _uint64(value, name) { if (typeof value !== "bigint" || value < 0n || value > 18446744073709551615n) throw new RangeError(`${name} is outside YQL Uint64 range`); return value; }
function _string(value, name) { if (typeof value !== "string") throw new TypeError(`${name} must be a string`); return value; }
function _timestamp(value, name) { if (typeof value !== "bigint" || value < 0n || value > 4291747199999999n) throw new RangeError(`${name} is outside YQL Timestamp microsecond range`); return value; }
function _json(value, name) { if (typeof value !== "string") throw new TypeError(`${name} must be JSON text`); try { JSON.parse(value); } catch (error) { throw new TypeError(`${name} must contain valid JSON`, { cause: error }); } return value; }
function _optional(value, name, itemType, makeValue) { if (value === undefined) throw new TypeError(`${name} must not be undefined; use null for an empty Optional`); return new Optional(value === null ? null : makeValue(value), itemType); }

function _rawValue(value, name, expectedCase) { if (value === null || typeof value !== "object" || value.value?.case !== expectedCase) throw new TypeError(`${name} has an unexpected YDB value shape`); return value.value.value; }
function _rawOptional(value, name, read) { if (value === null || typeof value !== "object") throw new TypeError(`${name} has an unexpected YDB Optional shape`); return value.value?.case === "nullFlagValue" ? null : read(value); }

function decodeListCitiesRow(row) {
  if (row === null || typeof row !== "object" || Array.isArray(row)) throw new TypeError("ListCities: expected an object row");
  if (!Object.hasOwn(row, "slug")) throw new TypeError("ListCities: result row is missing column slug");
  if (!Object.hasOwn(row, "name")) throw new TypeError("ListCities: result row is missing column name");
  return {
    slug: row["slug"],
    name: row["name"],
  };
}

function decodeGetCityRow(row) {
  if (row === null || typeof row !== "object" || Array.isArray(row)) throw new TypeError("GetCity: expected an object row");
  if (!Object.hasOwn(row, "slug")) throw new TypeError("GetCity: result row is missing column slug");
  if (!Object.hasOwn(row, "name")) throw new TypeError("GetCity: result row is missing column name");
  return {
    slug: row["slug"],
    name: row["name"],
  };
}

function decodeCreateCityRow(row) {
  if (row === null || typeof row !== "object" || Array.isArray(row)) throw new TypeError("CreateCity: expected an object row");
  if (!Object.hasOwn(row, "slug")) throw new TypeError("CreateCity: result row is missing column slug");
  if (!Object.hasOwn(row, "name")) throw new TypeError("CreateCity: result row is missing column name");
  return {
    slug: row["slug"],
    name: row["name"],
  };
}

function decodeListVenuesRow(row) {
  if (row === null || typeof row !== "object" || Array.isArray(row)) throw new TypeError("ListVenues: expected an object row");
  if (!Object.hasOwn(row, "id")) throw new TypeError("ListVenues: result row is missing column id");
  if (!Object.hasOwn(row, "slug")) throw new TypeError("ListVenues: result row is missing column slug");
  if (!Object.hasOwn(row, "name")) throw new TypeError("ListVenues: result row is missing column name");
  if (!Object.hasOwn(row, "city")) throw new TypeError("ListVenues: result row is missing column city");
  if (!Object.hasOwn(row, "status")) throw new TypeError("ListVenues: result row is missing column status");
  if (!Object.hasOwn(row, "statuses")) throw new TypeError("ListVenues: result row is missing column statuses");
  if (!Object.hasOwn(row, "spotify_playlist")) throw new TypeError("ListVenues: result row is missing column spotify_playlist");
  if (!Object.hasOwn(row, "songkick_id")) throw new TypeError("ListVenues: result row is missing column songkick_id");
  if (!Object.hasOwn(row, "tags")) throw new TypeError("ListVenues: result row is missing column tags");
  if (!Object.hasOwn(row, "created_at")) throw new TypeError("ListVenues: result row is missing column created_at");
  return {
    id: _rawValue(row["id"], "ListVenues.id", "uint64Value"),
    slug: _rawValue(row["slug"], "ListVenues.slug", "textValue"),
    name: _rawValue(row["name"], "ListVenues.name", "textValue"),
    city: _rawValue(row["city"], "ListVenues.city", "textValue"),
    status: _rawValue(row["status"], "ListVenues.status", "textValue"),
    statuses: _rawOptional(row["statuses"], "ListVenues.statuses", (value) => _rawValue(value, "ListVenues.statuses", "textValue")),
    spotifyPlaylist: _rawValue(row["spotify_playlist"], "ListVenues.spotify_playlist", "textValue"),
    songkickId: _rawOptional(row["songkick_id"], "ListVenues.songkick_id", (value) => _rawValue(value, "ListVenues.songkick_id", "textValue")),
    tags: _rawOptional(row["tags"], "ListVenues.tags", (value) => _rawValue(value, "ListVenues.tags", "textValue")),
    createdAt: _rawOptional(row["created_at"], "ListVenues.created_at", (value) => _rawValue(value, "ListVenues.created_at", "uint64Value")),
  };
}

function decodeGetVenueRow(row) {
  if (row === null || typeof row !== "object" || Array.isArray(row)) throw new TypeError("GetVenue: expected an object row");
  if (!Object.hasOwn(row, "id")) throw new TypeError("GetVenue: result row is missing column id");
  if (!Object.hasOwn(row, "slug")) throw new TypeError("GetVenue: result row is missing column slug");
  if (!Object.hasOwn(row, "name")) throw new TypeError("GetVenue: result row is missing column name");
  if (!Object.hasOwn(row, "city")) throw new TypeError("GetVenue: result row is missing column city");
  if (!Object.hasOwn(row, "status")) throw new TypeError("GetVenue: result row is missing column status");
  if (!Object.hasOwn(row, "statuses")) throw new TypeError("GetVenue: result row is missing column statuses");
  if (!Object.hasOwn(row, "spotify_playlist")) throw new TypeError("GetVenue: result row is missing column spotify_playlist");
  if (!Object.hasOwn(row, "songkick_id")) throw new TypeError("GetVenue: result row is missing column songkick_id");
  if (!Object.hasOwn(row, "tags")) throw new TypeError("GetVenue: result row is missing column tags");
  if (!Object.hasOwn(row, "created_at")) throw new TypeError("GetVenue: result row is missing column created_at");
  return {
    id: _rawValue(row["id"], "GetVenue.id", "uint64Value"),
    slug: _rawValue(row["slug"], "GetVenue.slug", "textValue"),
    name: _rawValue(row["name"], "GetVenue.name", "textValue"),
    city: _rawValue(row["city"], "GetVenue.city", "textValue"),
    status: _rawValue(row["status"], "GetVenue.status", "textValue"),
    statuses: _rawOptional(row["statuses"], "GetVenue.statuses", (value) => _rawValue(value, "GetVenue.statuses", "textValue")),
    spotifyPlaylist: _rawValue(row["spotify_playlist"], "GetVenue.spotify_playlist", "textValue"),
    songkickId: _rawOptional(row["songkick_id"], "GetVenue.songkick_id", (value) => _rawValue(value, "GetVenue.songkick_id", "textValue")),
    tags: _rawOptional(row["tags"], "GetVenue.tags", (value) => _rawValue(value, "GetVenue.tags", "textValue")),
    createdAt: _rawOptional(row["created_at"], "GetVenue.created_at", (value) => _rawValue(value, "GetVenue.created_at", "uint64Value")),
  };
}

function decodeCreateVenueRow(row) {
  if (row === null || typeof row !== "object" || Array.isArray(row)) throw new TypeError("CreateVenue: expected an object row");
  if (!Object.hasOwn(row, "id")) throw new TypeError("CreateVenue: result row is missing column id");
  return {
    id: row["id"],
  };
}

function decodeUpdateVenueNameRow(row) {
  if (row === null || typeof row !== "object" || Array.isArray(row)) throw new TypeError("UpdateVenueName: expected an object row");
  if (!Object.hasOwn(row, "id")) throw new TypeError("UpdateVenueName: result row is missing column id");
  return {
    id: row["id"],
  };
}

function decodeVenueCountByCityRow(row) {
  if (row === null || typeof row !== "object" || Array.isArray(row)) throw new TypeError("VenueCountByCity: expected an object row");
  if (!Object.hasOwn(row, "city")) throw new TypeError("VenueCountByCity: result row is missing column city");
  if (!Object.hasOwn(row, "venue_count")) throw new TypeError("VenueCountByCity: result row is missing column venue_count");
  return {
    city: row["city"],
    venueCount: row["venue_count"],
  };
}

export class Queries {
  #client;

  /** @param {import("@ydbjs/query").QueryClient} client */
  constructor(client) {
    if (typeof client !== "function") throw new TypeError("Queries requires a YDB QueryClient");
    this.#client = client;
  }

  async listCities() {
    const resultSets = await this.#client(LIST_CITIES_SQL);
    if (!Array.isArray(resultSets) || !Array.isArray(resultSets[0])) throw new TypeError("ListCities: expected the first YDB result set to be an array");
    const rows = resultSets[0];
    return rows.map(decodeListCitiesRow);
  }

  async getCity(slug) {
    const pending = this.#client(_GET_CITY_SQL_EXEC)
      .parameter("slug", new Utf8(_string(slug, "slug")))
    ;
    const resultSets = await pending;
    if (!Array.isArray(resultSets) || !Array.isArray(resultSets[0])) throw new TypeError("GetCity: expected the first YDB result set to be an array");
    const rows = resultSets[0];
    return rows.length === 0 ? null : decodeGetCityRow(rows[0]);
  }

  async createCity(args) {
    const pending = this.#client(_CREATE_CITY_SQL_EXEC)
      .parameter("name", new Utf8(_string(args.name, "name")))
      .parameter("slug", new Utf8(_string(args.slug, "slug")))
    ;
    const resultSets = await pending;
    if (!Array.isArray(resultSets) || !Array.isArray(resultSets[0])) throw new TypeError("CreateCity: expected the first YDB result set to be an array");
    const rows = resultSets[0];
    return rows.length === 0 ? null : decodeCreateCityRow(rows[0]);
  }

  async updateCityName(args) {
    const pending = this.#client(_UPDATE_CITY_NAME_SQL_EXEC)
      .parameter("name", new Utf8(_string(args.name, "name")))
      .parameter("slug", new Utf8(_string(args.slug, "slug")))
    ;
    const resultSets = await pending;
    return undefined;
  }

  async listVenues(city) {
    const pending = this.#client(_LIST_VENUES_SQL_EXEC)
      .parameter("city", new Utf8(_string(city, "city")))
    ;
    const resultSets = await pending.raw();
    if (!Array.isArray(resultSets) || !Array.isArray(resultSets[0])) throw new TypeError("ListVenues: expected the first YDB result set to be an array");
    const rows = resultSets[0];
    return rows.map(decodeListVenuesRow);
  }

  async deleteVenue(slug) {
    const pending = this.#client(_DELETE_VENUE_SQL_EXEC)
      .parameter("slug", new Utf8(_string(slug, "slug")))
    ;
    const resultSets = await pending;
    return undefined;
  }

  async getVenue(args) {
    const pending = this.#client(_GET_VENUE_SQL_EXEC)
      .parameter("slug", new Utf8(_string(args.slug, "slug")))
      .parameter("city", new Utf8(_string(args.city, "city")))
    ;
    const resultSets = await pending.raw();
    if (!Array.isArray(resultSets) || !Array.isArray(resultSets[0])) throw new TypeError("GetVenue: expected the first YDB result set to be an array");
    const rows = resultSets[0];
    return rows.length === 0 ? null : decodeGetVenueRow(rows[0]);
  }

  async createVenue(args) {
    const pending = this.#client(_CREATE_VENUE_SQL_EXEC)
      .parameter("id", new Uint64(_uint64(args.id, "id")))
      .parameter("slug", new Utf8(_string(args.slug, "slug")))
      .parameter("name", new Utf8(_string(args.name, "name")))
      .parameter("city", new Utf8(_string(args.city, "city")))
      .parameter("created_at", _optional(args.createdAt, "created_at", new TimestampType(), (item) => new Primitive({ value: { case: "uint64Value", value: _timestamp(item, "created_at") } }, new TimestampType())))
      .parameter("spotify_playlist", new Utf8(_string(args.spotifyPlaylist, "spotify_playlist")))
      .parameter("status", new Utf8(_string(args.status, "status")))
      .parameter("statuses", _optional(args.statuses, "statuses", new JsonType(), (item) => new Json(_json(item, "statuses"))))
      .parameter("tags", _optional(args.tags, "tags", new JsonType(), (item) => new Json(_json(item, "tags"))))
    ;
    const resultSets = await pending;
    if (!Array.isArray(resultSets) || !Array.isArray(resultSets[0])) throw new TypeError("CreateVenue: expected the first YDB result set to be an array");
    const rows = resultSets[0];
    return rows.length === 0 ? null : decodeCreateVenueRow(rows[0]);
  }

  async updateVenueName(args) {
    const pending = this.#client(_UPDATE_VENUE_NAME_SQL_EXEC)
      .parameter("name", new Utf8(_string(args.name, "name")))
      .parameter("slug", new Utf8(_string(args.slug, "slug")))
    ;
    const resultSets = await pending;
    if (!Array.isArray(resultSets) || !Array.isArray(resultSets[0])) throw new TypeError("UpdateVenueName: expected the first YDB result set to be an array");
    const rows = resultSets[0];
    return rows.length === 0 ? null : decodeUpdateVenueNameRow(rows[0]);
  }

  async venueCountByCity() {
    const resultSets = await this.#client(VENUE_COUNT_BY_CITY_SQL);
    if (!Array.isArray(resultSets) || !Array.isArray(resultSets[0])) throw new TypeError("VenueCountByCity: expected the first YDB result set to be an array");
    const rows = resultSets[0];
    return rows.map(decodeVenueCountByCityRow);
  }
}
