// Code generated by sqlc-ydb. DO NOT EDIT.
// source: city.sql
package ondeck

import (
	"context"
	ydb "github.com/ydb-platform/ydb-go-sdk/v3"
	"github.com/ydb-platform/ydb-go-sdk/v3/query"
)

const queryListCities = `-- name: ListCities :many
SELECT slug, name
FROM city
ORDER BY name;`

func (q *Queries) ListCities(ctx context.Context) ([]ListCitiesRow, error) {
	result, err := q.db.QueryResultSet(ctx, queryListCities)
	if err != nil {
		return []ListCitiesRow(nil), err
	}
	defer result.Close(ctx)
	items := []ListCitiesRow(nil)
	for r, err := range result.Rows(ctx) {
		if err != nil {
			return nil, err
		}
		var row ListCitiesRow
		if err := r.Scan(&row.Slug, &row.Name); err != nil {
			return nil, err
		}
		items = append(items, row)
	}
	return items, nil
}

const queryGetCity = `-- name: GetCity :one
DECLARE $slug AS Utf8;
SELECT slug, name
FROM city
WHERE slug = $slug;`

func (q *Queries) GetCity(ctx context.Context, arg string) (GetCityRow, error) {
	result, err := q.db.QueryRow(ctx, queryGetCity, query.WithParameters(ydb.ParamsBuilder().Param("$slug").Text(arg).Build()))
	if err != nil {
		return GetCityRow{}, err
	}
	var row GetCityRow
	if err := result.Scan(&row.Slug, &row.Name); err != nil {
		return GetCityRow{}, err
	}
	return row, nil
}

const queryCreateCity = `-- name: CreateCity :one
DECLARE $name AS Utf8;
DECLARE $slug AS Utf8;
INSERT INTO city (
    name,
    slug
) VALUES (
    $name,
    $slug
) RETURNING slug, name;`

func (q *Queries) CreateCity(ctx context.Context, arg CreateCityParams) (CreateCityRow, error) {
	result, err := q.db.QueryRow(ctx, queryCreateCity, query.WithParameters(ydb.ParamsBuilder().Param("$name").Text(arg.Name).Param("$slug").Text(arg.Slug).Build()))
	if err != nil {
		return CreateCityRow{}, err
	}
	var row CreateCityRow
	if err := result.Scan(&row.Slug, &row.Name); err != nil {
		return CreateCityRow{}, err
	}
	return row, nil
}

const queryUpdateCityName = `-- name: UpdateCityName :exec
DECLARE $name AS Utf8;
DECLARE $slug AS Utf8;
UPDATE city
SET name = $name
WHERE slug = $slug;`

func (q *Queries) UpdateCityName(ctx context.Context, arg UpdateCityNameParams) error {
	return q.db.Exec(ctx, queryUpdateCityName, query.WithParameters(ydb.ParamsBuilder().Param("$name").Text(arg.Name).Param("$slug").Text(arg.Slug).Build()))
}
