// Code generated by sqlc. DO NOT EDIT.
// source: queries.sql

package db

import (
	"context"
	"database/sql"

	_ "github.com/ydb-platform/ydb-go-sdk/v3"
	"github.com/ydb-platform/ydb-go-sdk/v3/pkg/xerrors"
	"github.com/ydb-platform/ydb-go-sdk/v3/retry"
)

const listCities = `-- name: ListCities :many
SELECT * FROM city
ORDER BY name;`

func (q *Queries) ListCities(ctx context.Context) ([]ListCitiesRow, error) {
	items, err := retry.RetryWithResult(ctx, func(ctx context.Context) ([]ListCitiesRow, error) {
		rows, err := q.db.QueryContext(ctx, listCities)
		if err != nil {
			return nil, err
		}
		defer rows.Close()
		var items []ListCitiesRow
		for rows.Next() {
			var i ListCitiesRow
			if err := rows.Scan(&i.Slug, &i.Name); err != nil {
				return nil, xerrors.WithStackTrace(err)
			}
			items = append(items, i)
		}
		if err := rows.Err(); err != nil {
			return nil, xerrors.WithStackTrace(err)
		}

		return items, nil
	}, retry.WithLabel("ListCities"))
	if err != nil {
		return nil, xerrors.WithStackTrace(err)
	}

	return items, nil
}

const getCity = `-- name: GetCity :one
SELECT * FROM city
WHERE slug = $slug LIMIT 1;`

type GetCityParams struct {
	Slug string `json:"slug"`
}

func (q *Queries) GetCity(ctx context.Context, arg GetCityParams) (*GetCityRow, error) {
	i, err := retry.RetryWithResult(ctx, func(ctx context.Context) (*GetCityRow, error) {
		row := q.db.QueryRowContext(ctx, getCity,
			sql.Named("slug", arg.Slug),
		)
		var i GetCityRow
		err := row.Scan(&i.Slug, &i.Name)
		if err != nil {
			return nil, xerrors.WithStackTrace(err)
		}

		return &i, nil
	}, retry.WithLabel("GetCity"))
	if err != nil {
		return nil, xerrors.WithStackTrace(err)
	}

	return i, nil
}

const createCity = `-- name: CreateCity :one
INSERT INTO city (name, slug)
VALUES ($name, $slug)
RETURNING *;`

type CreateCityParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) CreateCity(ctx context.Context, arg CreateCityParams) (*CreateCityRow, error) {
	i, err := retry.RetryWithResult(ctx, func(ctx context.Context) (*CreateCityRow, error) {
		row := q.db.QueryRowContext(ctx, createCity,
			sql.Named("name", arg.Name),
			sql.Named("slug", arg.Slug),
		)
		var i CreateCityRow
		err := row.Scan(&i.Slug, &i.Name)
		if err != nil {
			return nil, xerrors.WithStackTrace(err)
		}

		return &i, nil
	}, retry.WithLabel("CreateCity"))
	if err != nil {
		return nil, xerrors.WithStackTrace(err)
	}

	return i, nil
}

const updateCityName = `-- name: UpdateCityName :exec
UPDATE city
SET name = $name
WHERE slug = $slug;`

type UpdateCityNameParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) UpdateCityName(ctx context.Context, arg UpdateCityNameParams) error {
	err := retry.Retry(ctx, func(ctx context.Context) error {
		_, err := q.db.ExecContext(ctx, updateCityName,
			sql.Named("name", arg.Name),
			sql.Named("slug", arg.Slug),
		)
		if err != nil {
			return xerrors.WithStackTrace(err)
		}

		return nil
	}, retry.WithLabel("UpdateCityName"))
	if err != nil {
		return xerrors.WithStackTrace(err)
	}

	return nil
}

const listVenues = `-- name: ListVenues :many
SELECT * FROM venue
WHERE city = $city
ORDER BY name;`

type ListVenuesParams struct {
	City string `json:"city"`
}

func (q *Queries) ListVenues(ctx context.Context, arg ListVenuesParams) ([]ListVenuesRow, error) {
	items, err := retry.RetryWithResult(ctx, func(ctx context.Context) ([]ListVenuesRow, error) {
		rows, err := q.db.QueryContext(ctx, listVenues,
			sql.Named("city", arg.City),
		)
		if err != nil {
			return nil, err
		}
		defer rows.Close()
		var items []ListVenuesRow
		for rows.Next() {
			var i ListVenuesRow
			if err := rows.Scan(&i.ID, &i.Status, &i.Slug, &i.Name, &i.City, &i.Spotify_playlist, &i.Songkick_id, &i.Tags, &i.Created_at); err != nil {
				return nil, xerrors.WithStackTrace(err)
			}
			items = append(items, i)
		}
		if err := rows.Err(); err != nil {
			return nil, xerrors.WithStackTrace(err)
		}

		return items, nil
	}, retry.WithLabel("ListVenues"))
	if err != nil {
		return nil, xerrors.WithStackTrace(err)
	}

	return items, nil
}

const deleteVenue = `-- name: DeleteVenue :exec
DELETE FROM venue
WHERE slug = $slug;`

type DeleteVenueParams struct {
	Slug string `json:"slug"`
}

func (q *Queries) DeleteVenue(ctx context.Context, arg DeleteVenueParams) error {
	err := retry.Retry(ctx, func(ctx context.Context) error {
		_, err := q.db.ExecContext(ctx, deleteVenue,
			sql.Named("slug", arg.Slug),
		)
		if err != nil {
			return xerrors.WithStackTrace(err)
		}

		return nil
	}, retry.WithLabel("DeleteVenue"))
	if err != nil {
		return xerrors.WithStackTrace(err)
	}

	return nil
}

const getVenue = `-- name: GetVenue :one
SELECT * FROM venue
WHERE slug = $slug AND city = $city LIMIT 1;`

type GetVenueParams struct {
	Slug string `json:"slug"`
	City string `json:"city"`
}

func (q *Queries) GetVenue(ctx context.Context, arg GetVenueParams) (*GetVenueRow, error) {
	i, err := retry.RetryWithResult(ctx, func(ctx context.Context) (*GetVenueRow, error) {
		row := q.db.QueryRowContext(ctx, getVenue,
			sql.Named("slug", arg.Slug),
			sql.Named("city", arg.City),
		)
		var i GetVenueRow
		err := row.Scan(&i.ID, &i.Status, &i.Slug, &i.Name, &i.City, &i.Spotify_playlist, &i.Songkick_id, &i.Tags, &i.Created_at)
		if err != nil {
			return nil, xerrors.WithStackTrace(err)
		}

		return &i, nil
	}, retry.WithLabel("GetVenue"))
	if err != nil {
		return nil, xerrors.WithStackTrace(err)
	}

	return i, nil
}

const createVenue = `-- name: CreateVenue :one
INSERT INTO venue (
    id,
    slug,
    name,
    city,
    created_at,
    spotify_playlist,
    status,
    tags
) VALUES (
    $id,
    $slug,
    $name,
    $city,
    $created_at,
    $spotify_playlist,
    $status,
    $tags
)
RETURNING id;`

type CreateVenueParams struct {
	ID uint64 `json:"id"`
	Slug string `json:"slug"`
	Name string `json:"name"`
	City string `json:"city"`
	Created_at *string `json:"created_at"`
	Spotify_playlist string `json:"spotify_playlist"`
	Status string `json:"status"`
	Tags *string `json:"tags"`
}

func (q *Queries) CreateVenue(ctx context.Context, arg CreateVenueParams) (*interface{}, error) {
	i, err := retry.RetryWithResult(ctx, func(ctx context.Context) (*interface{}, error) {
		row := q.db.QueryRowContext(ctx, createVenue,
			sql.Named("id", arg.ID),
			sql.Named("slug", arg.Slug),
			sql.Named("name", arg.Name),
			sql.Named("city", arg.City),
			sql.Named("created_at", arg.Created_at),
			sql.Named("spotify_playlist", arg.Spotify_playlist),
			sql.Named("status", arg.Status),
			sql.Named("tags", arg.Tags),
		)
		var i interface{}
		err := row.Scan()
		if err != nil {
			return nil, xerrors.WithStackTrace(err)
		}

		return &i, nil
	}, retry.WithLabel("CreateVenue"))
	if err != nil {
		return nil, xerrors.WithStackTrace(err)
	}

	return i, nil
}

const updateVenueName = `-- name: UpdateVenueName :one
UPDATE venue
SET name = $name
WHERE slug = $slug
RETURNING id;`

type UpdateVenueNameParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) UpdateVenueName(ctx context.Context, arg UpdateVenueNameParams) (*interface{}, error) {
	i, err := retry.RetryWithResult(ctx, func(ctx context.Context) (*interface{}, error) {
		row := q.db.QueryRowContext(ctx, updateVenueName,
			sql.Named("name", arg.Name),
			sql.Named("slug", arg.Slug),
		)
		var i interface{}
		err := row.Scan()
		if err != nil {
			return nil, xerrors.WithStackTrace(err)
		}

		return &i, nil
	}, retry.WithLabel("UpdateVenueName"))
	if err != nil {
		return nil, xerrors.WithStackTrace(err)
	}

	return i, nil
}

const venueCountByCity = `-- name: VenueCountByCity :many
SELECT city, COUNT(*) AS count
FROM venue
GROUP BY city
ORDER BY city;`

func (q *Queries) VenueCountByCity(ctx context.Context) ([]interface{}, error) {
	items, err := retry.RetryWithResult(ctx, func(ctx context.Context) ([]interface{}, error) {
		rows, err := q.db.QueryContext(ctx, venueCountByCity)
		if err != nil {
			return nil, err
		}
		defer rows.Close()
		var items []interface{}
		for rows.Next() {
			var i interface{}
			if err := rows.Scan(); err != nil {
				return nil, xerrors.WithStackTrace(err)
			}
			items = append(items, i)
		}
		if err := rows.Err(); err != nil {
			return nil, xerrors.WithStackTrace(err)
		}

		return items, nil
	}, retry.WithLabel("VenueCountByCity"))
	if err != nil {
		return nil, xerrors.WithStackTrace(err)
	}

	return items, nil
}
