// Code generated by sqlc-ydb. DO NOT EDIT.
#nullable enable
using System;

namespace Authors.Dapper;
public sealed record Authors(
    ulong ID,
    string Name,
    string? Bio
);

public sealed record GetAuthorRow(
    ulong ID,
    string Name,
    string? Bio
);

public sealed record ListAuthorsRow(
    ulong ID,
    string Name,
    string? Bio
);

public sealed record ListAuthorsWithoutBioRow(
    ulong ID,
    string Name
);

public sealed record ListAuthorsPageParams(
    int PageSize,
    uint Offset
);

public sealed record ListAuthorsPageRow(
    ulong ID,
    string Name,
    string? Bio
);

public sealed record GetAuthorNameRow(
    string Name
);

public sealed record CreateAuthorParams(
    ulong AuthorID,
    string AuthorName,
    string? Biography
);

public sealed record CreateAuthorRow(
    ulong ID,
    string Name,
    string? Bio
);

public sealed record UpsertAuthorParams(
    ulong AuthorID,
    string AuthorName,
    string? Biography
);

public sealed record FindAuthorsByNameRow(
    ulong ID,
    string Name,
    string? Bio
);

public sealed record FindAuthorsByNameCoveringRow(
    ulong ID,
    string Name,
    string? Bio
);

public sealed record FindAuthorsByNamePrefixRow(
    ulong ID,
    string Name,
    string? Bio,
    bool HasBio
);

public sealed record GetAuthorStatisticsRow(
    ulong Total,
    ulong WithBio,
    ulong WithNonemptyBio,
    bool Column3
);

public sealed record GetAuthorExportMetadataRow(
    ulong ID,
    byte[] ExportDate,
    byte[] ExportDatetime,
    DateTime ExportTimestamp,
    byte[] ExportTimestampText,
    ulong ExportTimestampMicros,
    uint Column6,
    string? ExportMetadata
);

public sealed record EchoAuthorIDTextRow(
    string AuthorIDText
);
