// Code generated by sqlc-ydb. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;
using Dapper;
using Ydb.Sdk.Ado;
using Ydb.Sdk.Value;

namespace Authors.Dapper;

public sealed class Queries
{
    private readonly YdbConnection _connection;
    private readonly YdbTransaction? _transaction;

    public Queries(YdbConnection connection, YdbTransaction? transaction = null)
    {
        _connection = connection ?? throw new ArgumentNullException(nameof(connection));
        if (transaction is not null && !ReferenceEquals(transaction.Connection, connection))
        {
            throw new ArgumentException("Transaction must belong to the supplied connection.", nameof(transaction));
        }
        _transaction = transaction;
    }

    public Queries WithTransaction(YdbTransaction transaction) => new(_connection, transaction ?? throw new ArgumentNullException(nameof(transaction)));

    // -- name: GetAuthor :one
    public async Task<GetAuthorRow> GetAuthorAsync(ulong authorId, CancellationToken cancellationToken = default)
    {
        var command = new CommandDefinition(
            "SELECT id, name, bio FROM authors WHERE id = $author_id;", new YdbParameters(new YdbParameter("$author_id", DbType.UInt64, authorId)), _transaction, cancellationToken: cancellationToken);
        await using var reader = await _connection.ExecuteReaderAsync(command).ConfigureAwait(false);
        if (!await reader.ReadAsync(cancellationToken).ConfigureAwait(false))
        {
            throw new InvalidOperationException("query returned no rows");
        }
        return GetAuthorRowFrom(reader);
    }

    private static GetAuthorRow GetAuthorRowFrom(DbDataReader reader) => new(
        reader.GetFieldValue<ulong>(0),
        reader.GetFieldValue<string>(1),
        reader.IsDBNull(2) ? null : reader.GetFieldValue<string>(2)
    );

    // -- name: ListAuthors :many
    public async Task<IReadOnlyList<ListAuthorsRow>> ListAuthorsAsync(CancellationToken cancellationToken = default)
    {
        var command = new CommandDefinition(
            "SELECT id, name, bio FROM authors ORDER BY name;", null, _transaction, cancellationToken: cancellationToken);
        await using var reader = await _connection.ExecuteReaderAsync(command).ConfigureAwait(false);
        var rows = new List<ListAuthorsRow>();
        while (await reader.ReadAsync(cancellationToken).ConfigureAwait(false))
        {
            rows.Add(ListAuthorsRowFrom(reader));
        }
        return rows;
    }

    private static ListAuthorsRow ListAuthorsRowFrom(DbDataReader reader) => new(
        reader.GetFieldValue<ulong>(0),
        reader.GetFieldValue<string>(1),
        reader.IsDBNull(2) ? null : reader.GetFieldValue<string>(2)
    );

    // -- name: GetAuthorName :one
    public async Task<GetAuthorNameRow> GetAuthorNameAsync(ulong authorId, CancellationToken cancellationToken = default)
    {
        var command = new CommandDefinition(
            "SELECT name FROM authors WHERE id = $author_id;", new YdbParameters(new YdbParameter("$author_id", DbType.UInt64, authorId)), _transaction, cancellationToken: cancellationToken);
        await using var reader = await _connection.ExecuteReaderAsync(command).ConfigureAwait(false);
        if (!await reader.ReadAsync(cancellationToken).ConfigureAwait(false))
        {
            throw new InvalidOperationException("query returned no rows");
        }
        return GetAuthorNameRowFrom(reader);
    }

    private static GetAuthorNameRow GetAuthorNameRowFrom(DbDataReader reader) => new(
        reader.GetFieldValue<string>(0)
    );

    // -- name: CreateAuthor :one
    public async Task<CreateAuthorRow> CreateAuthorAsync(CreateAuthorParams args, CancellationToken cancellationToken = default)
    {
        var command = new CommandDefinition(
            "INSERT INTO `authors` (`id`, `name`, `bio`)\n" +
            "VALUES ($author_id, $author_name, $biography)\n" +
            "RETURNING `id`, `name`, `bio`;", new YdbParameters(new YdbParameter("$author_id", DbType.UInt64, args.AuthorID), new YdbParameter("$author_name", DbType.String, args.AuthorName), new YdbParameter("$biography", YdbValue.MakeOptionalUtf8(args.Biography))), _transaction, cancellationToken: cancellationToken);
        await using var reader = await _connection.ExecuteReaderAsync(command).ConfigureAwait(false);
        if (!await reader.ReadAsync(cancellationToken).ConfigureAwait(false))
        {
            throw new InvalidOperationException("query returned no rows");
        }
        return CreateAuthorRowFrom(reader);
    }

    private static CreateAuthorRow CreateAuthorRowFrom(DbDataReader reader) => new(
        reader.GetFieldValue<ulong>(0),
        reader.GetFieldValue<string>(1),
        reader.IsDBNull(2) ? null : reader.GetFieldValue<string>(2)
    );

    // -- name: UpsertAuthor :exec
    public async Task UpsertAuthorAsync(UpsertAuthorParams args, CancellationToken cancellationToken = default)
    {
        var command = new CommandDefinition(
            "UPSERT INTO authors (id, name, bio)\n" +
            "VALUES ($author_id, $author_name, $biography);", new YdbParameters(new YdbParameter("$author_id", DbType.UInt64, args.AuthorID), new YdbParameter("$author_name", DbType.String, args.AuthorName), new YdbParameter("$biography", YdbValue.MakeOptionalUtf8(args.Biography))), _transaction, cancellationToken: cancellationToken);
        await _connection.ExecuteAsync(command).ConfigureAwait(false);
    }

    // -- name: DeleteAuthor :exec
    public async Task DeleteAuthorAsync(ulong authorId, CancellationToken cancellationToken = default)
    {
        var command = new CommandDefinition(
            "DELETE FROM authors WHERE id = $author_id;", new YdbParameters(new YdbParameter("$author_id", DbType.UInt64, authorId)), _transaction, cancellationToken: cancellationToken);
        await _connection.ExecuteAsync(command).ConfigureAwait(false);
    }

    private sealed class YdbParameters : SqlMapper.IDynamicParameters
    {
        private readonly YdbParameter[] _parameters;

        public YdbParameters(params YdbParameter[] parameters) => _parameters = parameters;

        public void AddParameters(IDbCommand command, SqlMapper.Identity identity)
        {
            foreach (var parameter in _parameters)
            {
                command.Parameters.Add(parameter);
            }
        }
    }
}
