// Code generated by sqlc-ydb. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Reflection;
using System.Threading;
using System.Threading.Tasks;
using Dapper;
using Ydb.Sdk.Ado;
using Ydb.Sdk.Value;

namespace Authors.Dapper;

public sealed class Queries
{
    private readonly YdbConnection _connection;
    private readonly YdbTransaction? _transaction;

    public Queries(YdbConnection connection, YdbTransaction? transaction = null)
    {
        _connection = connection ?? throw new ArgumentNullException(nameof(connection));
        if (transaction is not null && !ReferenceEquals(transaction.Connection, connection))
        {
            throw new ArgumentException("Transaction must belong to the supplied connection.", nameof(transaction));
        }
        _transaction = transaction;
    }

    public Queries WithTransaction(YdbTransaction transaction) => new(_connection, transaction ?? throw new ArgumentNullException(nameof(transaction)));

    static Queries()
    {
        SqlMapper.SetTypeMap(typeof(FindAuthorsByNamePrefixRow), new ColumnTypeMap(typeof(FindAuthorsByNamePrefixRow), new Dictionary<string, string>
        {
            ["has_bio"] = nameof(FindAuthorsByNamePrefixRow.HasBio),
        }));
        SqlMapper.SetTypeMap(typeof(GetAuthorStatisticsRow), new ColumnTypeMap(typeof(GetAuthorStatisticsRow), new Dictionary<string, string>
        {
            ["with_bio"] = nameof(GetAuthorStatisticsRow.WithBio),
            ["with_nonempty_bio"] = nameof(GetAuthorStatisticsRow.WithNonemptyBio),
        }));
        SqlMapper.SetTypeMap(typeof(GetAuthorExportMetadataRow), new ColumnTypeMap(typeof(GetAuthorExportMetadataRow), new Dictionary<string, string>
        {
            ["export_date"] = nameof(GetAuthorExportMetadataRow.ExportDate),
            ["export_datetime"] = nameof(GetAuthorExportMetadataRow.ExportDatetime),
            ["export_timestamp"] = nameof(GetAuthorExportMetadataRow.ExportTimestamp),
            ["export_timestamp_text"] = nameof(GetAuthorExportMetadataRow.ExportTimestampText),
            ["export_timestamp_micros"] = nameof(GetAuthorExportMetadataRow.ExportTimestampMicros),
            ["export_metadata"] = nameof(GetAuthorExportMetadataRow.ExportMetadata),
        }));
    }

    private sealed class ColumnTypeMap : SqlMapper.ITypeMap
    {
        private readonly DefaultTypeMap _default;
        private readonly IReadOnlyDictionary<string, string> _columns;

        public ColumnTypeMap(Type type, IReadOnlyDictionary<string, string> columns)
        {
            _default = new DefaultTypeMap(type);
            _columns = columns;
        }

        private string MemberName(string column) => _columns.TryGetValue(column, out var member) ? member : column;
        public ConstructorInfo? FindConstructor(string[] names, Type[] types) => _default.FindConstructor(names.Select(MemberName).ToArray(), types);
        public ConstructorInfo? FindExplicitConstructor() => _default.FindExplicitConstructor();
        public SqlMapper.IMemberMap? GetConstructorParameter(ConstructorInfo constructor, string columnName) => _default.GetConstructorParameter(constructor, MemberName(columnName));
        public SqlMapper.IMemberMap? GetMember(string columnName) => _default.GetMember(MemberName(columnName));
    }

    // -- name: GetAuthor :one
    public async Task<GetAuthorRow> GetAuthorAsync(ulong authorId, CancellationToken cancellationToken = default, int? commandTimeout = null)
    {
        var parameters = new YdbParameters(
            new YdbParameter("$author_id", DbType.UInt64, authorId)
        );

        var command = new CommandDefinition(
            commandText: """
            SELECT id, name, bio FROM authors WHERE id = $author_id;
            """,
            parameters: parameters,
            transaction: _transaction,
            commandTimeout: commandTimeout,
            cancellationToken: cancellationToken);

        return await _connection.QueryFirstAsync<GetAuthorRow>(command).ConfigureAwait(false);
    }

    // -- name: ListAuthors :many
    public async Task<IReadOnlyList<ListAuthorsRow>> ListAuthorsAsync(CancellationToken cancellationToken = default, int? commandTimeout = null)
    {
        var command = new CommandDefinition(
            commandText: """
            SELECT id, name, bio FROM authors ORDER BY name;
            """,
            parameters: null,
            transaction: _transaction,
            commandTimeout: commandTimeout,
            cancellationToken: cancellationToken);

        return (await _connection.QueryAsync<ListAuthorsRow>(command).ConfigureAwait(false)).AsList();
    }

    // -- name: ListAuthorsPage :many
    public async Task<IReadOnlyList<ListAuthorsPageRow>> ListAuthorsPageAsync(ListAuthorsPageParams args, CancellationToken cancellationToken = default, int? commandTimeout = null)
    {
        var parameters = new YdbParameters(
            new YdbParameter("$page_size", DbType.Int32, args.PageSize),
            new YdbParameter("$offset", DbType.UInt32, args.Offset)
        );

        var command = new CommandDefinition(
            commandText: """
            DECLARE $page_size AS Int;
            DECLARE $offset AS Uint32;
            SELECT id, name, bio FROM authors ORDER BY id LIMIT $page_size OFFSET $offset;
            """,
            parameters: parameters,
            transaction: _transaction,
            commandTimeout: commandTimeout,
            cancellationToken: cancellationToken);

        return (await _connection.QueryAsync<ListAuthorsPageRow>(command).ConfigureAwait(false)).AsList();
    }

    // -- name: GetAuthorName :one
    public async Task<GetAuthorNameRow> GetAuthorNameAsync(ulong authorId, CancellationToken cancellationToken = default, int? commandTimeout = null)
    {
        var parameters = new YdbParameters(
            new YdbParameter("$author_id", DbType.UInt64, authorId)
        );

        var command = new CommandDefinition(
            commandText: """
            SELECT name FROM authors WHERE id = $author_id;
            """,
            parameters: parameters,
            transaction: _transaction,
            commandTimeout: commandTimeout,
            cancellationToken: cancellationToken);

        return await _connection.QueryFirstAsync<GetAuthorNameRow>(command).ConfigureAwait(false);
    }

    // -- name: CreateAuthor :one
    public async Task<CreateAuthorRow> CreateAuthorAsync(CreateAuthorParams args, CancellationToken cancellationToken = default, int? commandTimeout = null)
    {
        var parameters = new YdbParameters(
            new YdbParameter("$author_id", DbType.UInt64, args.AuthorID),
            new YdbParameter("$author_name", DbType.String, args.AuthorName),
            new YdbParameter("$biography", YdbValue.MakeOptionalUtf8(args.Biography))
        );

        var command = new CommandDefinition(
            commandText: """
            INSERT INTO `authors` (`id`, `name`, `bio`)
            VALUES ($author_id, $author_name, $biography)
            RETURNING `id`, `name`, `bio`;
            """,
            parameters: parameters,
            transaction: _transaction,
            commandTimeout: commandTimeout,
            cancellationToken: cancellationToken);

        return await _connection.QueryFirstAsync<CreateAuthorRow>(command).ConfigureAwait(false);
    }

    // -- name: UpsertAuthor :exec
    public async Task UpsertAuthorAsync(UpsertAuthorParams args, CancellationToken cancellationToken = default, int? commandTimeout = null)
    {
        var parameters = new YdbParameters(
            new YdbParameter("$author_id", DbType.UInt64, args.AuthorID),
            new YdbParameter("$author_name", DbType.String, args.AuthorName),
            new YdbParameter("$biography", YdbValue.MakeOptionalUtf8(args.Biography))
        );

        var command = new CommandDefinition(
            commandText: """
            UPSERT INTO authors (id, name, bio)
            VALUES ($author_id, $author_name, $biography);
            """,
            parameters: parameters,
            transaction: _transaction,
            commandTimeout: commandTimeout,
            cancellationToken: cancellationToken);

        await _connection.ExecuteAsync(command).ConfigureAwait(false);
    }

    // -- name: DeleteAuthor :exec
    public async Task DeleteAuthorAsync(ulong authorId, CancellationToken cancellationToken = default, int? commandTimeout = null)
    {
        var parameters = new YdbParameters(
            new YdbParameter("$author_id", DbType.UInt64, authorId)
        );

        var command = new CommandDefinition(
            commandText: """
            DELETE FROM authors WHERE id = $author_id;
            """,
            parameters: parameters,
            transaction: _transaction,
            commandTimeout: commandTimeout,
            cancellationToken: cancellationToken);

        await _connection.ExecuteAsync(command).ConfigureAwait(false);
    }

    // -- name: FindAuthorsByName :many
    public async Task<IReadOnlyList<FindAuthorsByNameRow>> FindAuthorsByNameAsync(string name, CancellationToken cancellationToken = default, int? commandTimeout = null)
    {
        var parameters = new YdbParameters(
            new YdbParameter("$name", DbType.String, name)
        );

        var command = new CommandDefinition(
            commandText: """
            SELECT a.`id` AS `id`, `a`.`name` AS `name`, `a`.`bio` AS `bio` FROM authors VIEW by_name AS a
            WHERE a.name = $name ORDER BY a.id;
            """,
            parameters: parameters,
            transaction: _transaction,
            commandTimeout: commandTimeout,
            cancellationToken: cancellationToken);

        return (await _connection.QueryAsync<FindAuthorsByNameRow>(command).ConfigureAwait(false)).AsList();
    }

    // -- name: FindAuthorsByNameCovering :many
    public async Task<IReadOnlyList<FindAuthorsByNameCoveringRow>> FindAuthorsByNameCoveringAsync(string name, CancellationToken cancellationToken = default, int? commandTimeout = null)
    {
        var parameters = new YdbParameters(
            new YdbParameter("$name", DbType.String, name)
        );

        var command = new CommandDefinition(
            commandText: """
            DECLARE $name AS Utf8;
            SELECT `id`, `name`, `bio` FROM authors VIEW by_name_covering WHERE name = $name ORDER BY id;
            """,
            parameters: parameters,
            transaction: _transaction,
            commandTimeout: commandTimeout,
            cancellationToken: cancellationToken);

        return (await _connection.QueryAsync<FindAuthorsByNameCoveringRow>(command).ConfigureAwait(false)).AsList();
    }

    // -- name: FindAuthorsByNamePrefix :many
    public async Task<IReadOnlyList<FindAuthorsByNamePrefixRow>> FindAuthorsByNamePrefixAsync(string prefix, CancellationToken cancellationToken = default, int? commandTimeout = null)
    {
        var parameters = new YdbParameters(
            new YdbParameter("$prefix", DbType.String, prefix)
        );

        var command = new CommandDefinition(
            commandText: """
            DECLARE $prefix AS Utf8;
            SELECT id, name, bio, bio IS NOT NULL AS has_bio
            FROM authors
            WHERE name LIKE $prefix || "%"u
            ORDER BY id;
            """,
            parameters: parameters,
            transaction: _transaction,
            commandTimeout: commandTimeout,
            cancellationToken: cancellationToken);

        return (await _connection.QueryAsync<FindAuthorsByNamePrefixRow>(command).ConfigureAwait(false)).AsList();
    }

    // -- name: GetAuthorStatistics :one
    public async Task<GetAuthorStatisticsRow> GetAuthorStatisticsAsync(CancellationToken cancellationToken = default, int? commandTimeout = null)
    {
        var command = new CommandDefinition(
            commandText: """
            SELECT
                COUNT(*) AS total,
                COUNT_IF(bio IS NOT NULL) AS with_bio,
                COUNT_IF(bio != ""u) AS with_nonempty_bio,
                CAST(COUNT(*) AS Bool)
            FROM authors;
            """,
            parameters: null,
            transaction: _transaction,
            commandTimeout: commandTimeout,
            cancellationToken: cancellationToken);

        return await _connection.QueryFirstAsync<GetAuthorStatisticsRow>(command).ConfigureAwait(false);
    }

    // -- name: GetAuthorExportMetadata :one
    public async Task<GetAuthorExportMetadataRow> GetAuthorExportMetadataAsync(ulong authorId, CancellationToken cancellationToken = default, int? commandTimeout = null)
    {
        var parameters = new YdbParameters(
            new YdbParameter("$author_id", DbType.UInt64, authorId)
        );

        var command = new CommandDefinition(
            commandText: """
            DECLARE $author_id AS Uint64;
            SELECT
                id,
                CAST(CurrentUtcDate() AS String) AS export_date,
                CAST(CurrentUtcDatetime() AS String) AS export_datetime,
                CurrentUtcTimestamp() AS export_timestamp,
                CAST(CurrentUtcTimestamp() AS String) AS export_timestamp_text,
                CAST(CurrentUtcTimestamp() AS Uint64) AS export_timestamp_micros,
                COALESCE(CAST(id AS Uint32), 0),
                CAST('{"source":"authors"}' AS Json) AS export_metadata
            FROM authors
            WHERE id = $author_id;
            """,
            parameters: parameters,
            transaction: _transaction,
            commandTimeout: commandTimeout,
            cancellationToken: cancellationToken);

        return await _connection.QueryFirstAsync<GetAuthorExportMetadataRow>(command).ConfigureAwait(false);
    }

    private sealed class YdbParameters : SqlMapper.IDynamicParameters
    {
        private readonly YdbParameter[] _parameters;

        public YdbParameters(params YdbParameter[] parameters) => _parameters = parameters;

        public void AddParameters(IDbCommand command, SqlMapper.Identity identity)
        {
            foreach (var parameter in _parameters)
            {
                command.Parameters.Add(parameter);
            }
        }
    }
}
