// Code generated by sqlc-ydb. DO NOT EDIT.

#[derive(Debug, Clone, PartialEq)]
pub struct GetAuthorRow {
    pub id: u64,
    pub name: String,
    pub bio: Option<String>,
}

#[derive(Debug, Clone, PartialEq)]
pub struct ListAuthorsRow {
    pub id: u64,
    pub name: String,
    pub bio: Option<String>,
}

#[derive(Debug, Clone, PartialEq)]
pub struct GetAuthorNameRow {
    pub name: String,
}

#[derive(Debug, Clone, PartialEq)]
pub struct CreateAuthorRow {
    pub id: u64,
    pub name: String,
    pub bio: Option<String>,
}
