// Code generated by sqlc-ydb. DO NOT EDIT.

use super::models::*;

pub struct Queries<'a> {
    client: &'a mut ydb::QueryClient,
}

impl<'a> Queries<'a> {
    pub fn new(client: &'a mut ydb::QueryClient) -> Self {
        Self { client }
    }

    pub async fn author(&mut self, author_id: u64) -> ydb::YdbResult<GetAuthorRow> {
        let mut row = self
            .client
            .query_row(concat!(
                concat!(r"-- name: GetAuthor :one", "\x0a"),
                r"SELECT id, name, bio FROM authors WHERE id = $author_id;",
            ))
            .param("$author_id", author_id)
            .await?;
        Ok(GetAuthorRow {
            id: row.remove_field(0)?.try_into()?,
            name: row.remove_field(1)?.try_into()?,
            bio: row.remove_field(2)?.try_into()?,
        })
    }

    pub async fn list_authors(&mut self) -> ydb::YdbResult<Vec<ListAuthorsRow>> {
        let result_set = self
            .client
            .query_result_set(concat!(
                concat!(r"-- name: ListAuthors :many", "\x0a"),
                r"SELECT id, name, bio FROM authors ORDER BY name;",
            ))
            .await?;
        let mut rows = Vec::new();
        for mut row in result_set.rows() {
            rows.push(ListAuthorsRow {
                id: row.remove_field(0)?.try_into()?,
                name: row.remove_field(1)?.try_into()?,
                bio: row.remove_field(2)?.try_into()?,
            });
        }
        Ok(rows)
    }

    pub async fn author_name(&mut self, author_id: u64) -> ydb::YdbResult<GetAuthorNameRow> {
        let mut row = self
            .client
            .query_row(concat!(
                concat!(r"-- name: GetAuthorName :one", "\x0a"),
                r"SELECT name FROM authors WHERE id = $author_id;",
            ))
            .param("$author_id", author_id)
            .await?;
        Ok(GetAuthorNameRow {
            name: row.remove_field(0)?.try_into()?,
        })
    }

    pub async fn create_author(
        &mut self,
        author_id: u64,
        author_name: String,
        biography: Option<String>,
    ) -> ydb::YdbResult<CreateAuthorRow> {
        let mut row = self
            .client
            .query_row(concat!(
                concat!(r"-- name: CreateAuthor :one", "\x0a"),
                concat!(r"INSERT INTO `authors` (`id`, `name`, `bio`)", "\x0a"),
                concat!(r"VALUES ($author_id, $author_name, $biography)", "\x0a"),
                r"RETURNING `id`, `name`, `bio`;",
            ))
            .param("$author_id", author_id)
            .param("$author_name", author_name)
            .param("$biography", biography)
            .await?;
        Ok(CreateAuthorRow {
            id: row.remove_field(0)?.try_into()?,
            name: row.remove_field(1)?.try_into()?,
            bio: row.remove_field(2)?.try_into()?,
        })
    }

    pub async fn upsert_author(
        &mut self,
        author_id: u64,
        author_name: String,
        biography: Option<String>,
    ) -> ydb::YdbResult<()> {
        self.client
            .exec(concat!(
                concat!(r"-- name: UpsertAuthor :exec", "\x0a"),
                concat!(r"UPSERT INTO authors (id, name, bio)", "\x0a"),
                r"VALUES ($author_id, $author_name, $biography);",
            ))
            .param("$author_id", author_id)
            .param("$author_name", author_name)
            .param("$biography", biography)
            .await
    }

    pub async fn delete_author(&mut self, author_id: u64) -> ydb::YdbResult<()> {
        self.client
            .exec(concat!(
                concat!(r"-- name: DeleteAuthor :exec", "\x0a"),
                r"DELETE FROM authors WHERE id = $author_id;",
            ))
            .param("$author_id", author_id)
            .await
    }
}
