// Code generated by sqlc-ydb. DO NOT EDIT.
package authors.hibernate.jpa;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import org.hibernate.annotations.JdbcTypeCode;

import tech.ydb.hibernate.dialect.code.YdbJdbcCode;

@Entity
@Table(name = "authors")
public class Authors {
    @Id
    @JdbcTypeCode(YdbJdbcCode.UINT64)
    private long id;

    private String name;
    private String bio;

    public Authors() { }

    public Authors(long id, String name, String bio) {
        this.id = id;
        this.name = name;
        this.bio = bio;
    }

    public long id() {
        return id;
    }

    public String name() {
        return name;
    }

    public String bio() {
        return bio;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setBio(String bio) {
        this.bio = bio;
    }
}

