# Code generated by sqlc-ydb. DO NOT EDIT.
from dataclasses import dataclass
from datetime import date, datetime, timedelta
from uuid import UUID
from typing import Optional

@dataclass
class Authors:
    author_id: int
    name: str

@dataclass
class Books:
    book_id: int
    author_id: int
    isbn: str
    book_type: str
    title: str
    publication_year: int
    available: datetime
    tags: str

@dataclass
class BooksByTagsRow:
    book_id: int
    title: str
    name: Optional[str]
    isbn: str
    tags: str

@dataclass
class SayHelloRow:
    greeting: str

@dataclass
class UpdateAuthorAndListBooksRow:
    book_id: int
    title: str

@dataclass
class ListAuthorBookTitlesRow:
    author_id: int
    name: str
    titles_json: Optional[str]

@dataclass
class InspectBookTextRow:
    base32: bytes
    alphabetic: bool
    host: Optional[bytes]
    square_root: float
    yson_string: bool
    pattern_found: bool
