// Code generated by sqlc-ydb. DO NOT EDIT.
package jets.jooq;

import java.util.List;
import java.util.Objects;
import java.util.Optional;

import org.jooq.impl.SQLDataType;
import tech.ydb.jooq.YdbDSLContext;
import tech.ydb.jooq.YdbTypes;

import static org.jooq.impl.DSL.*;
import static org.jooq.Records.mapping;
import static jets.jooq.Tables.*;

public final class Queries {
    private final YdbDSLContext dsl;

    public Queries(YdbDSLContext dsl) {
        this.dsl = Objects.requireNonNull(dsl);
    }

    // -- name: CountPilots :one
    public Optional<CountPilotsRow> countPilots() {
        return dsl.select(count().coerce(YdbTypes.UINT64).as("pilot_count"))
                .from(PILOTS)
                .fetchOptional(mapping(CountPilotsRow::new));
    }

    // -- name: ListPilots :many
    public List<ListPilotsRow> listPilots() {
        return dsl.select(PILOTS.ID, PILOTS.NAME)
                .from(PILOTS)
                .orderBy(PILOTS.ID)
                .limit(inline(5))
                .fetch(mapping(ListPilotsRow::new));
    }

    // -- name: DeletePilot :exec
    public void deletePilot(Integer pilotId) {
        dsl.deleteFrom(PILOTS)
                .where(PILOTS.ID.eq(val(pilotId, YdbTypes.INT32)))
                .execute();
    }
}
