// Code generated by sqlc-ydb. DO NOT EDIT.
package authors.jdbc;

import tech.ydb.table.values.PrimitiveValue;

// The caller owns the injected client and its lifecycle.
public final class Queries {
    private final java.sql.Connection client;

    public Queries(java.sql.Connection client) {
        this.client = java.util.Objects.requireNonNull(client);
    }

    // -- name: GetAuthor :one
    public java.util.Optional<GetAuthorRow> getAuthor(long authorId) throws java.sql.SQLException {
        try (var _prepared = client.prepareStatement("""
            SELECT id, name, bio FROM authors WHERE id = ?;\
            """)) {
            _prepared.setObject(1, PrimitiveValue.newUint64(authorId));
            try (var _rows = _prepared.executeQuery()) {
                if (!_rows.next()) return java.util.Optional.empty();
                long _value0 = _rows.getLong(1);
                String _value1 = _rows.getString(2);
                String _value2 = _rows.getString(3);
                return java.util.Optional.of(new GetAuthorRow(_value0, _value1, _value2));
            }
        }
    }

    // -- name: ListAuthors :many
    public java.util.List<ListAuthorsRow> listAuthors() throws java.sql.SQLException {
        try (var _prepared = client.prepareStatement("""
            SELECT id, name, bio FROM authors ORDER BY name;\
            """)) {
            try (var _rows = _prepared.executeQuery()) {
                var _items = new java.util.ArrayList<ListAuthorsRow>();
                while (_rows.next()) {
                    long _value0 = _rows.getLong(1);
                    String _value1 = _rows.getString(2);
                    String _value2 = _rows.getString(3);
                    _items.add(new ListAuthorsRow(_value0, _value1, _value2));
                }
                return _items;
            }
        }
    }

    // -- name: ListAuthorsPage :many
    public java.util.List<ListAuthorsPageRow> listAuthorsPage(int pageSize, long offset) throws java.sql.SQLException {
        if (offset < 0 || offset > 4294967295L) throw new IllegalArgumentException("parameter $offset is outside Uint32 range");
        try (var _prepared = client.unwrap(tech.ydb.jdbc.YdbConnection.class).prepareStatement("""
            DECLARE $page_size AS Int;
            DECLARE $offset AS Uint32;
            SELECT id, name, bio FROM authors ORDER BY id LIMIT $page_size OFFSET $offset;\
            """, tech.ydb.jdbc.YdbPrepareMode.DATA_QUERY)) {
            _prepared.setInt("page_size", pageSize);
            _prepared.setLong("offset", offset);
            try (var _rows = _prepared.executeQuery()) {
                var _items = new java.util.ArrayList<ListAuthorsPageRow>();
                while (_rows.next()) {
                    long _value0 = _rows.getLong(1);
                    String _value1 = _rows.getString(2);
                    String _value2 = _rows.getString(3);
                    _items.add(new ListAuthorsPageRow(_value0, _value1, _value2));
                }
                return _items;
            }
        }
    }

    // -- name: GetAuthorName :one
    public java.util.Optional<GetAuthorNameRow> getAuthorName(long authorId) throws java.sql.SQLException {
        try (var _prepared = client.prepareStatement("""
            SELECT name FROM authors WHERE id = ?;\
            """)) {
            _prepared.setObject(1, PrimitiveValue.newUint64(authorId));
            try (var _rows = _prepared.executeQuery()) {
                if (!_rows.next()) return java.util.Optional.empty();
                String _value0 = _rows.getString(1);
                return java.util.Optional.of(new GetAuthorNameRow(_value0));
            }
        }
    }

    // -- name: CreateAuthor :one
    public java.util.Optional<CreateAuthorRow> createAuthor(long authorId, String authorName, String biography) throws java.sql.SQLException {
        try (var _prepared = client.prepareStatement("""
            INSERT INTO `authors` (`id`, `name`, `bio`)
            VALUES (?, ?, ?)
            RETURNING `id`, `name`, `bio`;\
            """)) {
            _prepared.setObject(1, PrimitiveValue.newUint64(authorId));
            _prepared.setString(2, authorName);
            _prepared.setString(3, biography);
            try (var _rows = _prepared.executeQuery()) {
                if (!_rows.next()) return java.util.Optional.empty();
                long _value0 = _rows.getLong(1);
                String _value1 = _rows.getString(2);
                String _value2 = _rows.getString(3);
                return java.util.Optional.of(new CreateAuthorRow(_value0, _value1, _value2));
            }
        }
    }

    // -- name: UpsertAuthor :exec
    public void upsertAuthor(long authorId, String authorName, String biography) throws java.sql.SQLException {
        try (var _prepared = client.prepareStatement("""
            UPSERT INTO authors (id, name, bio)
            VALUES (?, ?, ?);\
            """)) {
            _prepared.setObject(1, PrimitiveValue.newUint64(authorId));
            _prepared.setString(2, authorName);
            _prepared.setString(3, biography);
            _prepared.execute();
        }
    }

    // -- name: DeleteAuthor :exec
    public void deleteAuthor(long authorId) throws java.sql.SQLException {
        try (var _prepared = client.prepareStatement("""
            DELETE FROM authors WHERE id = ?;\
            """)) {
            _prepared.setObject(1, PrimitiveValue.newUint64(authorId));
            _prepared.execute();
        }
    }

    // -- name: FindAuthorsByName :many
    public java.util.List<FindAuthorsByNameRow> findAuthorsByName(String name) throws java.sql.SQLException {
        try (var _prepared = client.prepareStatement("""
            SELECT a.`id` AS `id`, `a`.`name` AS `name`, `a`.`bio` AS `bio` FROM authors VIEW by_name AS a
            WHERE a.name = ? ORDER BY a.id;\
            """)) {
            _prepared.setString(1, name);
            try (var _rows = _prepared.executeQuery()) {
                var _items = new java.util.ArrayList<FindAuthorsByNameRow>();
                while (_rows.next()) {
                    long _value0 = _rows.getLong(1);
                    String _value1 = _rows.getString(2);
                    String _value2 = _rows.getString(3);
                    _items.add(new FindAuthorsByNameRow(_value0, _value1, _value2));
                }
                return _items;
            }
        }
    }

    // -- name: FindAuthorsByNameCovering :many
    public java.util.List<FindAuthorsByNameCoveringRow> findAuthorsByNameCovering(String name) throws java.sql.SQLException {
        try (var _prepared = client.unwrap(tech.ydb.jdbc.YdbConnection.class).prepareStatement("""
            DECLARE $name AS Utf8;
            SELECT `id`, `name`, `bio` FROM authors VIEW by_name_covering WHERE name = $name ORDER BY id;\
            """, tech.ydb.jdbc.YdbPrepareMode.DATA_QUERY)) {
            _prepared.setString("name", name);
            try (var _rows = _prepared.executeQuery()) {
                var _items = new java.util.ArrayList<FindAuthorsByNameCoveringRow>();
                while (_rows.next()) {
                    long _value0 = _rows.getLong(1);
                    String _value1 = _rows.getString(2);
                    String _value2 = _rows.getString(3);
                    _items.add(new FindAuthorsByNameCoveringRow(_value0, _value1, _value2));
                }
                return _items;
            }
        }
    }

    // -- name: FindAuthorsByNamePrefix :many
    public java.util.List<FindAuthorsByNamePrefixRow> findAuthorsByNamePrefix(String prefix) throws java.sql.SQLException {
        try (var _prepared = client.unwrap(tech.ydb.jdbc.YdbConnection.class).prepareStatement("""
            DECLARE $prefix AS Utf8;
            SELECT id, name, bio, bio IS NOT NULL AS has_bio
            FROM authors
            WHERE name LIKE $prefix || \"%\"u
            ORDER BY id;\
            """, tech.ydb.jdbc.YdbPrepareMode.DATA_QUERY)) {
            _prepared.setString("prefix", prefix);
            try (var _rows = _prepared.executeQuery()) {
                var _items = new java.util.ArrayList<FindAuthorsByNamePrefixRow>();
                while (_rows.next()) {
                    long _value0 = _rows.getLong(1);
                    String _value1 = _rows.getString(2);
                    String _value2 = _rows.getString(3);
                    boolean _value3 = _rows.getBoolean(4);
                    _items.add(new FindAuthorsByNamePrefixRow(_value0, _value1, _value2, _value3));
                }
                return _items;
            }
        }
    }

    // -- name: GetAuthorStatistics :one
    public java.util.Optional<GetAuthorStatisticsRow> getAuthorStatistics() throws java.sql.SQLException {
        try (var _prepared = client.prepareStatement("""
            SELECT
                COUNT(*) AS total,
                COUNT_IF(bio IS NOT NULL) AS with_bio,
                COUNT_IF(bio != \"\"u) AS with_nonempty_bio,
                CAST(COUNT(*) AS Bool)
            FROM authors;\
            """)) {
            try (var _rows = _prepared.executeQuery()) {
                if (!_rows.next()) return java.util.Optional.empty();
                long _value0 = _rows.getLong(1);
                long _value1 = _rows.getLong(2);
                long _value2 = _rows.getLong(3);
                boolean _value3 = _rows.getBoolean(4);
                return java.util.Optional.of(new GetAuthorStatisticsRow(_value0, _value1, _value2, _value3));
            }
        }
    }

    // -- name: GetAuthorExportMetadata :one
    public java.util.Optional<GetAuthorExportMetadataRow> getAuthorExportMetadata(long authorId) throws java.sql.SQLException {
        try (var _prepared = client.unwrap(tech.ydb.jdbc.YdbConnection.class).prepareStatement("""
            DECLARE $author_id AS Uint64;
            SELECT
                id,
                CAST(CurrentUtcDate() AS String) AS export_date,
                CAST(CurrentUtcDatetime() AS String) AS export_datetime,
                CurrentUtcTimestamp() AS export_timestamp,
                CAST(CurrentUtcTimestamp() AS String) AS export_timestamp_text,
                CAST(CurrentUtcTimestamp() AS Uint64) AS export_timestamp_micros,
                COALESCE(CAST(id AS Uint32), 0),
                CAST('{\"source\":\"authors\"}' AS Json) AS export_metadata
            FROM authors
            WHERE id = $author_id;\
            """, tech.ydb.jdbc.YdbPrepareMode.DATA_QUERY)) {
            _prepared.setObject("author_id", PrimitiveValue.newUint64(authorId));
            try (var _rows = _prepared.executeQuery()) {
                if (!_rows.next()) return java.util.Optional.empty();
                long _value0 = _rows.getLong(1);
                byte[] _value1 = _rows.getBytes(2);
                byte[] _value2 = _rows.getBytes(3);
                var _value3Raw = _rows.getTimestamp(4);
                java.time.Instant _value3 = _value3Raw == null ? null : _value3Raw.toInstant();
                byte[] _value4 = _rows.getBytes(5);
                long _value5 = _rows.getLong(6);
                long _value6 = _rows.getLong(7);
                String _value7 = _rows.getString(8);
                return java.util.Optional.of(new GetAuthorExportMetadataRow(_value0, _value1, _value2, _value3, _value4, _value5, _value6, _value7));
            }
        }
    }

    // -- name: EchoAuthorIDText :one
    public java.util.Optional<EchoAuthorIDTextRow> echoAuthorIDText(String authorId) throws java.sql.SQLException {
        try (var _prepared = client.prepareStatement("""
            SELECT ? AS author_id_text;\
            """)) {
            _prepared.setString(1, authorId);
            try (var _rows = _prepared.executeQuery()) {
                if (!_rows.next()) return java.util.Optional.empty();
                String _value0 = _rows.getString(1);
                return java.util.Optional.of(new EchoAuthorIDTextRow(_value0));
            }
        }
    }
}
