// Code generated by sqlc-ydb. DO NOT EDIT.
#pragma once

#include "models.hpp"

#include <cstdint>
#include <optional>
#include <string>
#include <vector>

#include <ydb-cpp-sdk/client/query/client.h>

namespace authors::native {

class Queries final {
public:
    explicit Queries(NYdb::NQuery::TQueryClient& client) noexcept : client_(&client), transaction_(nullptr) {}
    explicit Queries(NYdb::NQuery::TTransaction& transaction) noexcept : client_(nullptr), transaction_(&transaction) {}

    std::optional<GetAuthorRow> GetAuthor(std::uint64_t author_id) const;

private:
    NYdb::NQuery::TQueryClient* client_;
    NYdb::NQuery::TTransaction* transaction_;
};

}  // namespace authors::native
