// Code generated by sqlc-ydb. DO NOT EDIT.
package authors.nativeapi

data class GetAuthorStatisticsRow(
    val total: Long,
    val withBio: Long,
    val withNonemptyBio: Long,
    val column3: Boolean
)
