// Code generated by sqlc-ydb. DO NOT EDIT.
package booktest.jooq;

import java.time.Instant;
import org.jooq.JSON;
import org.jooq.types.ULong;

import java.util.List;
import java.util.Objects;
import java.util.Optional;

import org.jooq.impl.SQLDataType;
import tech.ydb.jooq.YdbDSLContext;
import tech.ydb.jooq.YdbTypes;

import static org.jooq.impl.DSL.*;
import static org.jooq.Records.mapping;
import static booktest.jooq.Tables.*;

public final class Queries {
    private final YdbDSLContext dsl;

    public Queries(YdbDSLContext dsl) {
        this.dsl = Objects.requireNonNull(dsl);
    }

    // -- name: GetAuthor :one
    public Optional<GetAuthorRow> getAuthor(ULong authorId) {
        return dsl.select(AUTHORS.AUTHOR_ID, AUTHORS.NAME)
                .from(AUTHORS)
                .where(AUTHORS.AUTHOR_ID.eq(val(authorId, YdbTypes.UINT64)))
                .fetchOptional(mapping(GetAuthorRow::new));
    }

    // -- name: GetBook :one
    public Optional<GetBookRow> getBook(ULong bookId) {
        return dsl.select(
            BOOKS.BOOK_ID,
            BOOKS.AUTHOR_ID,
            BOOKS.ISBN,
            BOOKS.BOOK_TYPE,
            BOOKS.TITLE,
            BOOKS.PUBLICATION_YEAR,
            BOOKS.AVAILABLE,
            BOOKS.TAGS
        )
                .from(BOOKS)
                .where(BOOKS.BOOK_ID.eq(val(bookId, YdbTypes.UINT64)))
                .fetchOptional(mapping(GetBookRow::new));
    }

    // -- name: DeleteBook :exec
    public void deleteBook(ULong bookId) {
        dsl.deleteFrom(BOOKS)
                .where(BOOKS.BOOK_ID.eq(val(bookId, YdbTypes.UINT64)))
                .execute();
    }

    // -- name: BooksByTitleYear :many
    public List<BooksByTitleYearRow> booksByTitleYear(String title, Integer publicationYear) {
        return dsl.select(
            BOOKS.BOOK_ID,
            BOOKS.AUTHOR_ID,
            BOOKS.ISBN,
            BOOKS.BOOK_TYPE,
            BOOKS.TITLE,
            BOOKS.PUBLICATION_YEAR,
            BOOKS.AVAILABLE,
            BOOKS.TAGS
        )
                .from(BOOKS)
                .where(
                    BOOKS.TITLE.eq(val(title, YdbTypes.UTF8)).and(BOOKS.PUBLICATION_YEAR.eq(val(publicationYear, YdbTypes.INT32)))
                )
                .fetch(mapping(BooksByTitleYearRow::new));
    }

    // -- name: BooksByTags :many
    public List<BooksByTagsRow> booksByTags(JSON tags) {
        var b = BOOKS.as("b");
        var a = AUTHORS.as("a");
        return dsl.select(b.BOOK_ID, b.TITLE, a.NAME, b.ISBN, b.TAGS)
                .from(b)
                .leftJoin(a)
                .on(b.AUTHOR_ID.eq(a.AUTHOR_ID))
                .where(
                    condition(
                        function(
                            systemName("SetIsDisjoint"),
                            YdbTypes.BOOL,
                            function(
                                systemName("ToSet"),
                                SQLDataType.OTHER,
                                function(systemName("Yson::ConvertToStringList"), SQLDataType.OTHER, b.TAGS)
                            ),
                            function(systemName("Yson::ConvertToStringList"), SQLDataType.OTHER, val(tags, YdbTypes.JSON))
                        )
                    ).not()
                )
                .fetch(mapping(BooksByTagsRow::new));
    }

    // -- name: CreateAuthor :one
    public Optional<CreateAuthorRow> createAuthor(ULong authorId, String name) {
        var stmt = dsl.insertInto(AUTHORS, AUTHORS.AUTHOR_ID, AUTHORS.NAME)
                .values(val(authorId, YdbTypes.UINT64), val(name, YdbTypes.UTF8))
                .returningResult(field(name("author_id"), YdbTypes.UINT64), field(name("name"), YdbTypes.UTF8));

        // YDB RETURNING produces a result set, not JDBC generated keys.
        return dsl.resultQuery("{0}", stmt)
                .coerce(AUTHORS.AUTHOR_ID, AUTHORS.NAME)
                .fetchOptional(mapping(CreateAuthorRow::new));
    }

    // -- name: CreateBook :one
    public Optional<CreateBookRow> createBook(
            ULong bookId,
            ULong authorId,
            String isbn,
            String bookType,
            String title,
            Integer publicationYear,
            Instant available,
            JSON tags
    ) {
        var stmt = dsl.insertInto(
            BOOKS,
            BOOKS.BOOK_ID,
            BOOKS.AUTHOR_ID,
            BOOKS.ISBN,
            BOOKS.BOOK_TYPE,
            BOOKS.TITLE,
            BOOKS.PUBLICATION_YEAR,
            BOOKS.AVAILABLE,
            BOOKS.TAGS
        )
                .values(
                    val(bookId, YdbTypes.UINT64),
                    val(authorId, YdbTypes.UINT64),
                    val(isbn, YdbTypes.UTF8),
                    val(bookType, YdbTypes.UTF8),
                    val(title, YdbTypes.UTF8),
                    val(publicationYear, YdbTypes.INT32),
                    val(available, YdbTypes.TIMESTAMP),
                    val(tags, YdbTypes.JSON)
                )
                .returningResult(
                    field(name("book_id"), YdbTypes.UINT64),
                    field(name("author_id"), YdbTypes.UINT64),
                    field(name("isbn"), YdbTypes.UTF8),
                    field(name("book_type"), YdbTypes.UTF8),
                    field(name("title"), YdbTypes.UTF8),
                    field(name("publication_year"), YdbTypes.INT32),
                    field(name("available"), YdbTypes.TIMESTAMP),
                    field(name("tags"), YdbTypes.JSON)
                );

        // YDB RETURNING produces a result set, not JDBC generated keys.
        return dsl.resultQuery("{0}", stmt)
                .coerce(BOOKS.BOOK_ID, BOOKS.AUTHOR_ID, BOOKS.ISBN, BOOKS.BOOK_TYPE, BOOKS.TITLE, BOOKS.PUBLICATION_YEAR, BOOKS.AVAILABLE, BOOKS.TAGS)
                .fetchOptional(mapping(CreateBookRow::new));
    }

    // -- name: UpdateBook :exec
    public void updateBook(String title, JSON tags, ULong bookId) {
        dsl.update(BOOKS)
                .set(BOOKS.TITLE, val(title, YdbTypes.UTF8))
                .set(BOOKS.TAGS, val(tags, YdbTypes.JSON))
                .where(BOOKS.BOOK_ID.eq(val(bookId, YdbTypes.UINT64)))
                .execute();
    }

    // -- name: UpdateBookISBN :exec
    public void updateBookISBN(
            String title,
            JSON tags,
            String isbn,
            ULong bookId
    ) {
        dsl.update(BOOKS)
                .set(BOOKS.TITLE, val(title, YdbTypes.UTF8))
                .set(BOOKS.TAGS, val(tags, YdbTypes.JSON))
                .set(BOOKS.ISBN, val(isbn, YdbTypes.UTF8))
                .where(BOOKS.BOOK_ID.eq(val(bookId, YdbTypes.UINT64)))
                .execute();
    }

    // -- name: DeleteAuthorBeforeYear :exec
    public void deleteAuthorBeforeYear(Integer publicationYear, ULong authorId) {
        dsl.deleteFrom(BOOKS)
                .where(BOOKS.PUBLICATION_YEAR.lt(val(publicationYear, YdbTypes.INT32)).and(BOOKS.AUTHOR_ID.eq(val(authorId, YdbTypes.UINT64))))
                .execute();
    }

    // -- name: SayHello :one
    public Optional<SayHelloRow> sayHello(String name) {
        return dsl.select(inline("hello ", YdbTypes.UTF8).concat(val(name, YdbTypes.UTF8)).as("greeting"))
                .fetchOptional(mapping(SayHelloRow::new));
    }
}
