// Code generated by sqlc-ydb. DO NOT EDIT.
// source: queries.sql
package jets

import (
	"context"

	ydb "github.com/ydb-platform/ydb-go-sdk/v3"
	"github.com/ydb-platform/ydb-go-sdk/v3/query"
)

const queryCountPilots = `-- name: CountPilots :one
SELECT COUNT(*) AS pilot_count FROM pilots;`

func (q *Queries) CountPilots(ctx context.Context, opts ...query.ExecuteOption) (CountPilotsRow, error) {
	result, err := q.db.QueryRow(ctx, queryCountPilots, opts...)
	if err != nil {
		return CountPilotsRow{}, err
	}
	var row CountPilotsRow
	if err := result.ScanNamed(
		query.Named("pilot_count", &row.PilotCount),
	); err != nil {
		return CountPilotsRow{}, err
	}
	return row, nil
}

const queryListPilots = `-- name: ListPilots :many
SELECT id, name FROM pilots ORDER BY id LIMIT 5;`

func (q *Queries) ListPilots(ctx context.Context, opts ...query.ExecuteOption) ([]ListPilotsRow, error) {
	result, err := q.db.QueryResultSet(ctx, queryListPilots, opts...)
	if err != nil {
		return []ListPilotsRow(nil), err
	}
	defer result.Close(ctx)
	items := []ListPilotsRow(nil)
	for r, err := range result.Rows(ctx) {
		if err != nil {
			return nil, err
		}
		var row ListPilotsRow
		if err := r.ScanNamed(
			query.Named("id", &row.ID),
			query.Named("name", &row.Name),
		); err != nil {
			return nil, err
		}
		items = append(items, row)
	}
	return items, nil
}

const queryDeletePilot = `-- name: DeletePilot :exec
DELETE FROM pilots WHERE id = $pilot_id;`

func (q *Queries) DeletePilot(ctx context.Context, arg int32, opts ...query.ExecuteOption) error {
	parameters := ydb.ParamsBuilder()
	parameters = parameters.Param("$pilot_id").Int32(arg)
	callOptions := append([]query.ExecuteOption(nil), opts...)
	callOptions = append(callOptions, query.WithParameters(parameters.Build()))
	return q.db.Exec(ctx, queryDeletePilot, callOptions...)
}
