# Code generated by sqlc-ydb. DO NOT EDIT.
from __future__ import annotations
from typing import Iterable, Optional, Union
from . import models as _models
import ydb as _ydb


def _typed(value, typ):
    return _ydb.TypedValue(value, typ)


class Querier:
    def __init__(self, executor: Union[_ydb.QuerySessionPool, _ydb.QueryTxContext]):
        self._executor = executor

    def _execute(self, query: str, parameters: dict):
        if isinstance(self._executor, _ydb.QuerySessionPool):
            return self._executor.execute_with_retries(query, parameters)
        return list(self._executor.execute(query, parameters))

    # -- name: ColdCities :many
    def cold_cities(self, maximum_temperature: int) -> Iterable[_models.ColdCitiesRow]:
        parameters = {"$maximum_temperature": _typed(maximum_temperature, _ydb.PrimitiveType.Int32)}
        result_sets = self._execute(
            ("DECLARE $maximum_temperature AS Int32;\n"
             "SELECT city, COUNT(*) AS reading_count, MAX(temperature) AS hottest_temperature\n"
             "FROM weather\n"
             "GROUP BY city\n"
             "HAVING MAX(temperature) < $maximum_temperature;"), parameters)
        rows = result_sets[0].rows
        return (_models.ColdCitiesRow(
            city=row["city"],
            reading_count=row["reading_count"],
            hottest_temperature=row["hottest_temperature"],
        ) for row in rows)
