// Code generated by sqlc-ydb. DO NOT EDIT.
package authors

type GetAuthorRow struct {
	ID   uint64
	Name string
	Bio  *string
}

type ListAuthorsRow struct {
	ID   uint64
	Name string
	Bio  *string
}

type GetAuthorNameRow struct {
	Name string
}

type UpsertAuthorParams struct {
	AuthorID   uint64
	AuthorName string
	Biography  *string
}
