// Code generated by sqlc-ydb. DO NOT EDIT.
package namespaces.nativeapi;

import tech.ydb.query.QueryTransaction;
import tech.ydb.query.tools.QueryReader;
import tech.ydb.table.query.Params;
import tech.ydb.table.values.PrimitiveValue;

// The caller owns the injected client and its lifecycle.
public final class Queries {
    private final QueryTransaction client;

    public Queries(QueryTransaction client) {
        this.client = java.util.Objects.requireNonNull(client);
    }

    // -- name: UpsertPrimaryUser :exec
    public void upsertPrimaryUser(long id, String name) {
        var _params = Params.create();
        _params.put("$id", PrimitiveValue.newUint64(id));
        _params.put("$name", PrimitiveValue.newText(name));
        client.createQuery("""
            PRAGMA TablePathPrefix(\"/local/sqlc_namespaces/a\");
            DECLARE $id AS Uint64;
            DECLARE $name AS Utf8;
            UPSERT INTO users (id, name) VALUES ($id, $name);\
            """, _params).execute().join().getStatus().expectSuccess();
    }

    // -- name: UpsertSecondaryUser :exec
    public void upsertSecondaryUser(long id, String name) {
        var _params = Params.create();
        _params.put("$id", PrimitiveValue.newUint64(id));
        _params.put("$name", PrimitiveValue.newText(name));
        client.createQuery("""
            PRAGMA TablePathPrefix(\"/local/sqlc_namespaces/b\");
            DECLARE $id AS Uint64;
            DECLARE $name AS Utf8;
            UPSERT INTO users (id, name) VALUES ($id, $name);\
            """, _params).execute().join().getStatus().expectSuccess();
    }

    // -- name: GetPrimaryUser :one
    public java.util.Optional<GetPrimaryUserRow> getPrimaryUser(long id) {
        var _params = Params.create();
        _params.put("$id", PrimitiveValue.newUint64(id));
        var _query = QueryReader.readFrom(
                client.createQuery("""
                    PRAGMA TablePathPrefix(\"/local/sqlc_namespaces/a\");
                    SELECT users.`id` AS `id`, `users`.`name` AS `name` FROM users WHERE id = $id;\
                    """, _params)).join().getValue();
        if (_query.getResultSetCount() != 1) throw new IllegalStateException("Expected one result set");
        var _rows = _query.getResultSet(0);
        if (!_rows.next()) return java.util.Optional.empty();
        long _value0 = _rows.getColumn(0).getUint64();
        String _value1 = _rows.getColumn(1).getText();
        return java.util.Optional.of(new GetPrimaryUserRow(_value0, _value1));
    }

    // -- name: GetSecondaryUser :one
    public java.util.Optional<GetSecondaryUserRow> getSecondaryUser(long id) {
        var _params = Params.create();
        _params.put("$id", PrimitiveValue.newUint64(id));
        var _query = QueryReader.readFrom(
                client.createQuery("""
                    PRAGMA TablePathPrefix(\"/local/sqlc_namespaces/b\");
                    DECLARE $id AS Uint64;
                    SELECT users.`id` AS `id`, `users`.`name` AS `name` FROM users WHERE id = $id;\
                    """, _params)).join().getValue();
        if (_query.getResultSetCount() != 1) throw new IllegalStateException("Expected one result set");
        var _rows = _query.getResultSet(0);
        if (!_rows.next()) return java.util.Optional.empty();
        long _value0 = _rows.getColumn(0).getUint64();
        String _value1 = _rows.getColumn(1).getText();
        return java.util.Optional.of(new GetSecondaryUserRow(_value0, _value1));
    }

    // -- name: FindPrimaryUsersByName :many
    public java.util.List<FindPrimaryUsersByNameRow> findPrimaryUsersByName(String name) {
        var _params = Params.create();
        _params.put("$name", PrimitiveValue.newText(name));
        var _query = QueryReader.readFrom(
                client.createQuery("""
                    PRAGMA TablePathPrefix(\"/local/sqlc_namespaces/a\");
                    SELECT u.`id` AS `id`, `u`.`name` AS `name` FROM users VIEW by_name AS u WHERE u.name = $name ORDER BY u.id;\
                    """, _params)).join().getValue();
        if (_query.getResultSetCount() != 1) throw new IllegalStateException("Expected one result set");
        var _rows = _query.getResultSet(0);
        var _items = new java.util.ArrayList<FindPrimaryUsersByNameRow>();
        while (_rows.next()) {
            long _value0 = _rows.getColumn(0).getUint64();
            String _value1 = _rows.getColumn(1).getText();
            _items.add(new FindPrimaryUsersByNameRow(_value0, _value1));
        }
        return _items;
    }

    // -- name: CompareUserNames :many
    public java.util.List<CompareUserNamesRow> compareUserNames() {
        var _params = Params.create();
        var _query = QueryReader.readFrom(
                client.createQuery("""
                    PRAGMA TablePathPrefix(\"/local/sqlc_namespaces/a\");
                    SELECT a.id AS id, a.name AS primary_name, b.name AS secondary_name
                    FROM users AS a
                    LEFT JOIN `/local/sqlc_namespaces/b/users` AS b ON a.id = b.id
                    ORDER BY a.id;\
                    """, _params)).join().getValue();
        if (_query.getResultSetCount() != 1) throw new IllegalStateException("Expected one result set");
        var _rows = _query.getResultSet(0);
        var _items = new java.util.ArrayList<CompareUserNamesRow>();
        while (_rows.next()) {
            long _value0 = _rows.getColumn(0).getUint64();
            String _value1 = _rows.getColumn(1).getText();
            String _value2 = _rows.getColumn(2).getText();
            _items.add(new CompareUserNamesRow(_value0, _value1, _value2));
        }
        return _items;
    }
}
