# Code generated by sqlc-ydb. DO NOT EDIT.
from __future__ import annotations
from typing import Optional, Union
from . import models as _models
import ydb as _ydb


class Querier:
    def __init__(self, executor: Union[_ydb.QuerySessionPool, _ydb.QueryTxContext], *, retry_settings: Optional[_ydb.RetrySettings] = None):
        if retry_settings is not None and not isinstance(executor, _ydb.QuerySessionPool):
            raise ValueError("retry_settings belongs to the pool; configure retries around the whole transaction")
        self._executor = executor
        self._retry_settings = retry_settings
        if isinstance(executor, _ydb.QuerySessionPool) and retry_settings is None:
            self._retry_settings = _ydb.RetrySettings(max_retries=0)

    def _execute(self, query: str, parameters: dict):
        if isinstance(self._executor, _ydb.QuerySessionPool):
            return self._executor.execute_with_retries(query, parameters, retry_settings=self._retry_settings)
        return list(self._executor.execute(query, parameters))

    # -- name: DistinctLabels :many
    def distinct_labels(self) -> list[_models.DistinctLabelsRow]:
        parameters = {
        }
        result_sets = self._execute(
            ("SELECT id, label FROM local_labels\n"
             "UNION\n"
             "SELECT id, label FROM imported_labels;"), parameters)
        if len(result_sets) != 1:
            raise ValueError("expected exactly one YDB result set")
        rows = result_sets[0].rows
        return [_models.DistinctLabelsRow(
            id=row["id"],
            label=row["label"],
        ) for row in rows]

    # -- name: QualifiedMissing :many
    def qualified_missing(self) -> list[_models.QualifiedMissingRow]:
        parameters = {
        }
        result_sets = self._execute(
            ("SELECT a.id FROM local_labels AS a JOIN imported_labels AS b ON a.id = b.id\n"
             "UNION ALL\n"
             "SELECT b.id FROM local_labels AS a JOIN imported_labels AS b ON a.id = b.id;"), parameters)
        if len(result_sets) != 1:
            raise ValueError("expected exactly one YDB result set")
        rows = result_sets[0].rows
        return [_models.QualifiedMissingRow(
            a_id=row["a.id"],
            b_id=row["b.id"],
        ) for row in rows]

    # -- name: QualifiedNames :many
    def qualified_names(self) -> list[_models.QualifiedNamesRow]:
        parameters = {
        }
        result_sets = self._execute(
            ("SELECT a.id, b.id FROM local_labels AS a JOIN imported_labels AS b ON a.id = b.id\n"
             "UNION ALL\n"
             "SELECT a.id, b.id FROM local_labels AS a JOIN imported_labels AS b ON a.id = b.id;"), parameters)
        if len(result_sets) != 1:
            raise ValueError("expected exactly one YDB result set")
        rows = result_sets[0].rows
        return [_models.QualifiedNamesRow(
            a_id=row["a.id"],
            b_id=row["b.id"],
        ) for row in rows]

    # -- name: AllLabels :many
    def all_labels(self) -> list[_models.AllLabelsRow]:
        parameters = {
        }
        result_sets = self._execute(
            ("SELECT id, label FROM local_labels\n"
             "UNION ALL\n"
             "SELECT id, label FROM imported_labels;"), parameters)
        if len(result_sets) != 1:
            raise ValueError("expected exactly one YDB result set")
        rows = result_sets[0].rows
        return [_models.AllLabelsRow(
            id=row["id"],
            label=row["label"],
        ) for row in rows]
