// Code generated by sqlc. DO NOT EDIT.
// source: queries.sql

package db

import (
	"context"

	_ "github.com/ydb-platform/ydb-go-sdk/v3"
	"github.com/ydb-platform/ydb-go-sdk/v3/pkg/xerrors"
	"github.com/ydb-platform/ydb-go-sdk/v3/retry"
)

const getAuthor = `-- name: GetAuthor :one
SELECT * FROM authors
WHERE id =  LIMIT 1;`

type GetAuthorParams struct {
	ID uint64 `json:"id"`
}

func (q *Queries) GetAuthor(ctx context.Context, arg GetAuthorParams) (*GetAuthorRow, error) {
	i, err := retry.RetryWithResult(ctx, func(ctx context.Context) (*GetAuthorRow, error) {
		row := q.db.QueryRowContext(ctx, getAuthor, arg.ID)
		var i GetAuthorRow
		err := row.Scan(&i.ID, &i.Name, &i.Bio)
		if err != nil {
			return nil, xerrors.WithStackTrace(err)
		}

		return &i, nil
	}, retry.WithLabel("GetAuthor"))
	if err != nil {
		return nil, xerrors.WithStackTrace(err)
	}

	return i, nil
}

const listAuthors = `-- name: ListAuthors :many
SELECT * FROM authors
ORDER BY name;`

func (q *Queries) ListAuthors(ctx context.Context) ([]ListAuthorsRow, error) {
	items, err := retry.RetryWithResult(ctx, func(ctx context.Context) ([]ListAuthorsRow, error) {
		rows, err := q.db.QueryContext(ctx, listAuthors)
		if err != nil {
			return nil, err
		}
		defer rows.Close()
		var items []ListAuthorsRow
		for rows.Next() {
			var i ListAuthorsRow
			if err := rows.Scan(&i.ID, &i.Name, &i.Bio); err != nil {
				return nil, xerrors.WithStackTrace(err)
			}
			items = append(items, i)
		}
		if err := rows.Err(); err != nil {
			return nil, xerrors.WithStackTrace(err)
		}

		return items, nil
	}, retry.WithLabel("ListAuthors"))
	if err != nil {
		return nil, xerrors.WithStackTrace(err)
	}

	return items, nil
}

const createAuthor = `-- name: CreateAuthor :one
INSERT INTO authors (name, bio)
VALUES (, )
RETURNING *;`

type CreateAuthorParams struct {
	Name string `json:"name"`
	Bio *string `json:"bio"`
}

func (q *Queries) CreateAuthor(ctx context.Context, arg CreateAuthorParams) (*CreateAuthorRow, error) {
	i, err := retry.RetryWithResult(ctx, func(ctx context.Context) (*CreateAuthorRow, error) {
		row := q.db.QueryRowContext(ctx, createAuthor, arg.Name, arg.Bio)
		var i CreateAuthorRow
		err := row.Scan(&i.ID, &i.Name, &i.Bio)
		if err != nil {
			return nil, xerrors.WithStackTrace(err)
		}

		return &i, nil
	}, retry.WithLabel("CreateAuthor"))
	if err != nil {
		return nil, xerrors.WithStackTrace(err)
	}

	return i, nil
}

const updateAuthor = `-- name: UpdateAuthor :exec
UPDATE authors
SET name = , bio = 
WHERE id = ;`

type UpdateAuthorParams struct {
	Name string `json:"name"`
	Bio *string `json:"bio"`
	ID uint64 `json:"id"`
}

func (q *Queries) UpdateAuthor(ctx context.Context, arg UpdateAuthorParams) error {
	err := retry.Retry(ctx, func(ctx context.Context) error {
		_, err := q.db.ExecContext(ctx, updateAuthor, arg.Name, arg.Bio, arg.ID)
		if err != nil {
			return xerrors.WithStackTrace(err)
		}

		return nil
	}, retry.WithLabel("UpdateAuthor"))
	if err != nil {
		return xerrors.WithStackTrace(err)
	}

	return nil
}

const deleteAuthor = `-- name: DeleteAuthor :exec
DELETE FROM authors
WHERE id = ;`

type DeleteAuthorParams struct {
	ID uint64 `json:"id"`
}

func (q *Queries) DeleteAuthor(ctx context.Context, arg DeleteAuthorParams) error {
	err := retry.Retry(ctx, func(ctx context.Context) error {
		_, err := q.db.ExecContext(ctx, deleteAuthor, arg.ID)
		if err != nil {
			return xerrors.WithStackTrace(err)
		}

		return nil
	}, retry.WithLabel("DeleteAuthor"))
	if err != nil {
		return xerrors.WithStackTrace(err)
	}

	return nil
}
