// Code generated by sqlc-ydb. DO NOT EDIT.
import type { Query, SQL } from "@ydbjs/query";
import type { JSValue } from "@ydbjs/value";
import { Int32, Json, Timestamp, Uint64, Utf8 } from "@ydbjs/value/primitive";

export type ConfigureQuery = (query: Query) => void;

export type GetAuthorRow = {
  readonly author_id: bigint;
  readonly name: string;
};

export type GetBookRow = {
  readonly book_id: bigint;
  readonly author_id: bigint;
  readonly isbn: string;
  readonly book_type: string;
  readonly title: string;
  readonly publication_year: number;
  readonly available: Date;
  readonly tags: JSValue;
};

export type BooksByTitleYearParams = {
  readonly title: string;
  readonly publicationYear: number;
};

export type BooksByTitleYearRow = {
  readonly book_id: bigint;
  readonly author_id: bigint;
  readonly isbn: string;
  readonly book_type: string;
  readonly title: string;
  readonly publication_year: number;
  readonly available: Date;
  readonly tags: JSValue;
};

export type BooksByTagsRow = {
  readonly "b.book_id": bigint;
  readonly "b.title": string;
  readonly "a.name": string | null;
  readonly "b.isbn": string;
  readonly "b.tags": JSValue;
};

export type CreateAuthorParams = {
  readonly authorId: bigint;
  readonly name: string;
};

export type CreateAuthorRow = {
  readonly author_id: bigint;
  readonly name: string;
};

export type CreateBookParams = {
  readonly bookId: bigint;
  readonly authorId: bigint;
  readonly isbn: string;
  readonly bookType: string;
  readonly title: string;
  readonly publicationYear: number;
  readonly available: Date;
  readonly tags: string;
};

export type CreateBookRow = {
  readonly book_id: bigint;
  readonly author_id: bigint;
  readonly isbn: string;
  readonly book_type: string;
  readonly title: string;
  readonly publication_year: number;
  readonly available: Date;
  readonly tags: JSValue;
};

export type UpdateBookParams = {
  readonly title: string;
  readonly tags: string;
  readonly bookId: bigint;
};

export type UpdateBookISBNParams = {
  readonly title: string;
  readonly tags: string;
  readonly isbn: string;
  readonly bookId: bigint;
};

export type DeleteAuthorBeforeYearParams = {
  readonly publicationYear: number;
  readonly authorId: bigint;
};

export type SayHelloRow = {
  readonly greeting: string;
};

export class Queries {
  readonly #sql: SQL;

  constructor(sql: SQL) {
    if (typeof sql !== "function") throw new TypeError("Queries requires a YDB SQL function");
    this.#sql = sql;
  }

  // -- name: GetAuthor :one
  async getAuthor(authorId: bigint, configure?: ConfigureQuery): Promise<GetAuthorRow | null> {
    const stmt = this.#sql<[GetAuthorRow]>`SELECT author_id, name
      FROM authors
      WHERE author_id = $author_id;`
      .parameter("author_id", new Uint64(authorId));
    configure?.(stmt);
    const [rows] = await stmt;

    return rows[0] ?? null;
  }

  // -- name: GetBook :one
  async getBook(bookId: bigint, configure?: ConfigureQuery): Promise<GetBookRow | null> {
    const stmt = this.#sql<[GetBookRow]>`SELECT book_id, author_id, isbn, book_type, title, publication_year, available, tags
      FROM books
      WHERE book_id = $book_id;`
      .parameter("book_id", new Uint64(bookId));
    configure?.(stmt);
    const [rows] = await stmt;

    return rows[0] ?? null;
  }

  // -- name: DeleteBook :exec
  async deleteBook(bookId: bigint, configure?: ConfigureQuery): Promise<void> {
    const stmt = this.#sql`DELETE FROM books
      WHERE book_id = $book_id;`
      .parameter("book_id", new Uint64(bookId));
    configure?.(stmt);
    await stmt;
  }

  // -- name: BooksByTitleYear :many
  async booksByTitleYear(args: BooksByTitleYearParams, configure?: ConfigureQuery): Promise<BooksByTitleYearRow[]> {
    const stmt = this.#sql<[BooksByTitleYearRow]>`SELECT book_id, author_id, isbn, book_type, title, publication_year, available, tags
      FROM books
      WHERE title = $title AND publication_year = $publication_year;`
      .parameter("title", new Utf8(args.title))
      .parameter("publication_year", new Int32(args.publicationYear));
    configure?.(stmt);
    const [rows] = await stmt;

    return rows;
  }

  // -- name: BooksByTags :many
  async booksByTags(tags: string, configure?: ConfigureQuery): Promise<BooksByTagsRow[]> {
    const stmt = this.#sql<[BooksByTagsRow]>`SELECT
          b.book_id,
          b.title,
          a.name,
          b.isbn,
          b.tags
      FROM books AS b
      LEFT JOIN authors AS a ON b.author_id = a.author_id
      WHERE NOT SetIsDisjoint(
          ToSet(Yson::ConvertToStringList(b.tags)),
          Yson::ConvertToStringList($tags)
      );`
      .parameter("tags", new Json(tags));
    configure?.(stmt);
    const [rows] = await stmt;

    return rows;
  }

  // -- name: CreateAuthor :one
  async createAuthor(args: CreateAuthorParams, configure?: ConfigureQuery): Promise<CreateAuthorRow | null> {
    const stmt = this.#sql<[CreateAuthorRow]>`INSERT INTO authors (author_id, name)
      VALUES ($author_id, $name)
      RETURNING author_id, name;`
      .parameter("author_id", new Uint64(args.authorId))
      .parameter("name", new Utf8(args.name));
    configure?.(stmt);
    const [rows] = await stmt;

    return rows[0] ?? null;
  }

  // -- name: CreateBook :one
  async createBook(args: CreateBookParams, configure?: ConfigureQuery): Promise<CreateBookRow | null> {
    const stmt = this.#sql<[CreateBookRow]>`INSERT INTO books (
          book_id,
          author_id,
          isbn,
          book_type,
          title,
          publication_year,
          available,
          tags
      ) VALUES (
          $book_id,
          $author_id,
          $isbn,
          $book_type,
          $title,
          $publication_year,
          $available,
          $tags
      )
      RETURNING book_id, author_id, isbn, book_type, title, publication_year, available, tags;`
      .parameter("book_id", new Uint64(args.bookId))
      .parameter("author_id", new Uint64(args.authorId))
      .parameter("isbn", new Utf8(args.isbn))
      .parameter("book_type", new Utf8(args.bookType))
      .parameter("title", new Utf8(args.title))
      .parameter("publication_year", new Int32(args.publicationYear))
      .parameter("available", new Timestamp(args.available))
      .parameter("tags", new Json(args.tags));
    configure?.(stmt);
    const [rows] = await stmt;

    return rows[0] ?? null;
  }

  // -- name: UpdateBook :exec
  async updateBook(args: UpdateBookParams, configure?: ConfigureQuery): Promise<void> {
    const stmt = this.#sql`UPDATE books
      SET title = $title, tags = $tags
      WHERE book_id = $book_id;`
      .parameter("title", new Utf8(args.title))
      .parameter("tags", new Json(args.tags))
      .parameter("book_id", new Uint64(args.bookId));
    configure?.(stmt);
    await stmt;
  }

  // -- name: UpdateBookISBN :exec
  async updateBookISBN(args: UpdateBookISBNParams, configure?: ConfigureQuery): Promise<void> {
    const stmt = this.#sql`UPDATE books
      SET title = $title, tags = $tags, isbn = $isbn
      WHERE book_id = $book_id;`
      .parameter("title", new Utf8(args.title))
      .parameter("tags", new Json(args.tags))
      .parameter("isbn", new Utf8(args.isbn))
      .parameter("book_id", new Uint64(args.bookId));
    configure?.(stmt);
    await stmt;
  }

  // -- name: DeleteAuthorBeforeYear :exec
  async deleteAuthorBeforeYear(args: DeleteAuthorBeforeYearParams, configure?: ConfigureQuery): Promise<void> {
    const stmt = this.#sql`DELETE FROM books
      WHERE publication_year < $publication_year AND author_id = $author_id;`
      .parameter("publication_year", new Int32(args.publicationYear))
      .parameter("author_id", new Uint64(args.authorId));
    configure?.(stmt);
    await stmt;
  }

  // -- name: SayHello :one
  async sayHello(name: string, configure?: ConfigureQuery): Promise<SayHelloRow | null> {
    const stmt = this.#sql<[SayHelloRow]>`SELECT "hello "u || $name AS greeting;`
      .parameter("name", new Utf8(name));
    configure?.(stmt);
    const [rows] = await stmt;

    return rows[0] ?? null;
  }
}
