<?php
// Code generated by sqlc-ydb. DO NOT EDIT.
declare(strict_types=1);

namespace Batch\Native;

require_once __DIR__ . '/YdbRuntime.php';

use Closure;
use UnexpectedValueException;
use Ydb\Table\ExecuteQueryResult;
use Ydb\Type\PrimitiveTypeId;
use YdbPlatform\Ydb\Retry\RetryParams;
use YdbPlatform\Ydb\Session;
use YdbPlatform\Ydb\Table;

final class Queries
{
    public function __construct(
        private readonly Table $table,
        private readonly bool $idempotent = false,
        private readonly ?Closure $configure = null,
        private readonly ?RetryParams $retryParams = null,
    )
    {
        if (PHP_INT_SIZE !== 8) {
            throw new \LogicException('sqlc-ydb generated PHP code requires a 64-bit PHP runtime');
        }
    }

    // -- name: GetAuthor :one
    public function getAuthor(string $authorId): ?GetAuthorRow
    {
        $parameters = [
            '$author_id' => YdbValueCodec::typedUint64($authorId, 'author_id'),
        ];

        $result = $this->table->retrySession(function (Session $session) use ($parameters): ExecuteQueryResult {
            $query = $session->newQuery(<<<'SQLC_YDB_YQL'
                SELECT author_id, name, biography FROM authors
                WHERE author_id = $author_id;
                SQLC_YDB_YQL)
                ->parameters($parameters)
                ->keepInCache(count($parameters) > 0)
                ->beginTx('serializable_read_write');
            if ($this->configure !== null) {
                ($this->configure)($query);
            }

            return (new YdbRawExecutor($this->table))->execute($session, $query);
        }, $this->idempotent, $this->retryParams);

        $rows = $this->decodeRows(
            $result,
            'GetAuthor',
            [
                ['author_id', PrimitiveTypeId::UINT64, false],
                ['name', PrimitiveTypeId::UTF8, false],
                ['biography', PrimitiveTypeId::JSON, true],
            ],
            static fn($items): GetAuthorRow => new GetAuthorRow(
                YdbValueCodec::uint64($items->offsetGet(0), 'GetAuthor.author_id'),
                YdbValueCodec::utf8($items->offsetGet(1), 'GetAuthor.name'),
                YdbValueCodec::optionalJson($items->offsetGet(2), 'GetAuthor.biography'),
            ),
        );

        return $rows[0] ?? null;
    }

    // -- name: DeleteBookExecResult :exec
    public function deleteBookExecResult(string $bookId): void
    {
        $parameters = [
            '$book_id' => YdbValueCodec::typedUint64($bookId, 'book_id'),
        ];

        $this->table->retrySession(function (Session $session) use ($parameters): ExecuteQueryResult {
            $query = $session->newQuery(<<<'SQLC_YDB_YQL'
                DELETE FROM books
                WHERE book_id = $book_id;
                SQLC_YDB_YQL)
                ->parameters($parameters)
                ->keepInCache(count($parameters) > 0)
                ->beginTx('serializable_read_write');
            if ($this->configure !== null) {
                ($this->configure)($query);
            }

            return (new YdbRawExecutor($this->table))->execute($session, $query);
        }, $this->idempotent, $this->retryParams);
    }

    // -- name: DeleteBook :exec
    public function deleteBook(string $bookId): void
    {
        $parameters = [
            '$book_id' => YdbValueCodec::typedUint64($bookId, 'book_id'),
        ];

        $this->table->retrySession(function (Session $session) use ($parameters): ExecuteQueryResult {
            $query = $session->newQuery(<<<'SQLC_YDB_YQL'
                DELETE FROM books
                WHERE book_id = $book_id;
                SQLC_YDB_YQL)
                ->parameters($parameters)
                ->keepInCache(count($parameters) > 0)
                ->beginTx('serializable_read_write');
            if ($this->configure !== null) {
                ($this->configure)($query);
            }

            return (new YdbRawExecutor($this->table))->execute($session, $query);
        }, $this->idempotent, $this->retryParams);
    }

    // -- name: DeleteBookNamedFunc :exec
    public function deleteBookNamedFunc(string $bookId): void
    {
        $parameters = [
            '$book_id' => YdbValueCodec::typedUint64($bookId, 'book_id'),
        ];

        $this->table->retrySession(function (Session $session) use ($parameters): ExecuteQueryResult {
            $query = $session->newQuery(<<<'SQLC_YDB_YQL'
                DELETE FROM books
                WHERE book_id = $book_id;
                SQLC_YDB_YQL)
                ->parameters($parameters)
                ->keepInCache(count($parameters) > 0)
                ->beginTx('serializable_read_write');
            if ($this->configure !== null) {
                ($this->configure)($query);
            }

            return (new YdbRawExecutor($this->table))->execute($session, $query);
        }, $this->idempotent, $this->retryParams);
    }

    // -- name: DeleteBookNamedSign :exec
    public function deleteBookNamedSign(string $bookId): void
    {
        $parameters = [
            '$book_id' => YdbValueCodec::typedUint64($bookId, 'book_id'),
        ];

        $this->table->retrySession(function (Session $session) use ($parameters): ExecuteQueryResult {
            $query = $session->newQuery(<<<'SQLC_YDB_YQL'
                DELETE FROM books
                WHERE book_id = $book_id;
                SQLC_YDB_YQL)
                ->parameters($parameters)
                ->keepInCache(count($parameters) > 0)
                ->beginTx('serializable_read_write');
            if ($this->configure !== null) {
                ($this->configure)($query);
            }

            return (new YdbRawExecutor($this->table))->execute($session, $query);
        }, $this->idempotent, $this->retryParams);
    }

    /** @return list<BooksByYearRow> */
    // -- name: BooksByYear :many
    public function booksByYear(int $year): array
    {
        $parameters = [
            '$year' => YdbValueCodec::typedInt32($year, 'year'),
        ];

        $result = $this->table->retrySession(function (Session $session) use ($parameters): ExecuteQueryResult {
            $query = $session->newQuery(<<<'SQLC_YDB_YQL'
                SELECT book_id, author_id, isbn, book_type, title, year, available, tags
                FROM books
                WHERE year = $year;
                SQLC_YDB_YQL)
                ->parameters($parameters)
                ->keepInCache(count($parameters) > 0)
                ->beginTx('serializable_read_write');
            if ($this->configure !== null) {
                ($this->configure)($query);
            }

            return (new YdbRawExecutor($this->table))->execute($session, $query);
        }, $this->idempotent, $this->retryParams);

        $rows = $this->decodeRows(
            $result,
            'BooksByYear',
            [
                ['book_id', PrimitiveTypeId::UINT64, false],
                ['author_id', PrimitiveTypeId::UINT64, false],
                ['isbn', PrimitiveTypeId::UTF8, false],
                ['book_type', PrimitiveTypeId::UTF8, false],
                ['title', PrimitiveTypeId::UTF8, false],
                ['year', PrimitiveTypeId::INT32, false],
                ['available', PrimitiveTypeId::TIMESTAMP, false],
                ['tags', PrimitiveTypeId::JSON, false],
            ],
            static fn($items): BooksByYearRow => new BooksByYearRow(
                YdbValueCodec::uint64($items->offsetGet(0), 'BooksByYear.book_id'),
                YdbValueCodec::uint64($items->offsetGet(1), 'BooksByYear.author_id'),
                YdbValueCodec::utf8($items->offsetGet(2), 'BooksByYear.isbn'),
                YdbValueCodec::utf8($items->offsetGet(3), 'BooksByYear.book_type'),
                YdbValueCodec::utf8($items->offsetGet(4), 'BooksByYear.title'),
                YdbValueCodec::int32($items->offsetGet(5), 'BooksByYear.year'),
                YdbValueCodec::timestamp($items->offsetGet(6), 'BooksByYear.available'),
                YdbValueCodec::json($items->offsetGet(7), 'BooksByYear.tags'),
            ),
        );

        return $rows;
    }

    // -- name: CreateAuthor :one
    public function createAuthor(CreateAuthorParams $params): ?CreateAuthorRow
    {
        $parameters = [
            '$author_id' => YdbValueCodec::typedUint64($params->authorId, 'author_id'),
            '$name' => YdbValueCodec::typedUtf8($params->name, 'name'),
            '$biography' => YdbValueCodec::typedOptionalJson($params->biography, 'biography'),
        ];

        $result = $this->table->retrySession(function (Session $session) use ($parameters): ExecuteQueryResult {
            $query = $session->newQuery(<<<'SQLC_YDB_YQL'
                INSERT INTO authors (author_id, name, biography)
                VALUES ($author_id, $name, $biography)
                RETURNING author_id, name, biography;
                SQLC_YDB_YQL)
                ->parameters($parameters)
                ->keepInCache(count($parameters) > 0)
                ->beginTx('serializable_read_write');
            if ($this->configure !== null) {
                ($this->configure)($query);
            }

            return (new YdbRawExecutor($this->table))->execute($session, $query);
        }, $this->idempotent, $this->retryParams);

        $rows = $this->decodeRows(
            $result,
            'CreateAuthor',
            [
                ['author_id', PrimitiveTypeId::UINT64, false],
                ['name', PrimitiveTypeId::UTF8, false],
                ['biography', PrimitiveTypeId::JSON, true],
            ],
            static fn($items): CreateAuthorRow => new CreateAuthorRow(
                YdbValueCodec::uint64($items->offsetGet(0), 'CreateAuthor.author_id'),
                YdbValueCodec::utf8($items->offsetGet(1), 'CreateAuthor.name'),
                YdbValueCodec::optionalJson($items->offsetGet(2), 'CreateAuthor.biography'),
            ),
        );

        return $rows[0] ?? null;
    }

    // -- name: CreateBook :one
    public function createBook(CreateBookParams $params): ?CreateBookRow
    {
        $parameters = [
            '$book_id' => YdbValueCodec::typedUint64($params->bookId, 'book_id'),
            '$author_id' => YdbValueCodec::typedUint64($params->authorId, 'author_id'),
            '$isbn' => YdbValueCodec::typedUtf8($params->isbn, 'isbn'),
            '$book_type' => YdbValueCodec::typedUtf8($params->bookType, 'book_type'),
            '$title' => YdbValueCodec::typedUtf8($params->title, 'title'),
            '$year' => YdbValueCodec::typedInt32($params->year, 'year'),
            '$available' => YdbValueCodec::typedTimestamp($params->available, 'available'),
            '$tags' => YdbValueCodec::typedJson($params->tags, 'tags'),
        ];

        $result = $this->table->retrySession(function (Session $session) use ($parameters): ExecuteQueryResult {
            $query = $session->newQuery(<<<'SQLC_YDB_YQL'
                INSERT INTO books (book_id, author_id, isbn, book_type, title, year, available, tags)
                VALUES ($book_id, $author_id, $isbn, $book_type, $title, $year, $available, $tags)
                RETURNING book_id, author_id, isbn, book_type, title, year, available, tags;
                SQLC_YDB_YQL)
                ->parameters($parameters)
                ->keepInCache(count($parameters) > 0)
                ->beginTx('serializable_read_write');
            if ($this->configure !== null) {
                ($this->configure)($query);
            }

            return (new YdbRawExecutor($this->table))->execute($session, $query);
        }, $this->idempotent, $this->retryParams);

        $rows = $this->decodeRows(
            $result,
            'CreateBook',
            [
                ['book_id', PrimitiveTypeId::UINT64, false],
                ['author_id', PrimitiveTypeId::UINT64, false],
                ['isbn', PrimitiveTypeId::UTF8, false],
                ['book_type', PrimitiveTypeId::UTF8, false],
                ['title', PrimitiveTypeId::UTF8, false],
                ['year', PrimitiveTypeId::INT32, false],
                ['available', PrimitiveTypeId::TIMESTAMP, false],
                ['tags', PrimitiveTypeId::JSON, false],
            ],
            static fn($items): CreateBookRow => new CreateBookRow(
                YdbValueCodec::uint64($items->offsetGet(0), 'CreateBook.book_id'),
                YdbValueCodec::uint64($items->offsetGet(1), 'CreateBook.author_id'),
                YdbValueCodec::utf8($items->offsetGet(2), 'CreateBook.isbn'),
                YdbValueCodec::utf8($items->offsetGet(3), 'CreateBook.book_type'),
                YdbValueCodec::utf8($items->offsetGet(4), 'CreateBook.title'),
                YdbValueCodec::int32($items->offsetGet(5), 'CreateBook.year'),
                YdbValueCodec::timestamp($items->offsetGet(6), 'CreateBook.available'),
                YdbValueCodec::json($items->offsetGet(7), 'CreateBook.tags'),
            ),
        );

        return $rows[0] ?? null;
    }

    // -- name: UpdateBook :exec
    public function updateBook(UpdateBookParams $params): void
    {
        $parameters = [
            '$title' => YdbValueCodec::typedUtf8($params->title, 'title'),
            '$tags' => YdbValueCodec::typedJson($params->tags, 'tags'),
            '$book_id' => YdbValueCodec::typedUint64($params->bookId, 'book_id'),
        ];

        $this->table->retrySession(function (Session $session) use ($parameters): ExecuteQueryResult {
            $query = $session->newQuery(<<<'SQLC_YDB_YQL'
                UPDATE books
                SET title = $title, tags = $tags
                WHERE book_id = $book_id;
                SQLC_YDB_YQL)
                ->parameters($parameters)
                ->keepInCache(count($parameters) > 0)
                ->beginTx('serializable_read_write');
            if ($this->configure !== null) {
                ($this->configure)($query);
            }

            return (new YdbRawExecutor($this->table))->execute($session, $query);
        }, $this->idempotent, $this->retryParams);
    }

    // -- name: GetBiography :one
    public function getBiography(string $authorId): ?GetBiographyRow
    {
        $parameters = [
            '$author_id' => YdbValueCodec::typedUint64($authorId, 'author_id'),
        ];

        $result = $this->table->retrySession(function (Session $session) use ($parameters): ExecuteQueryResult {
            $query = $session->newQuery(<<<'SQLC_YDB_YQL'
                SELECT biography FROM authors
                WHERE author_id = $author_id;
                SQLC_YDB_YQL)
                ->parameters($parameters)
                ->keepInCache(count($parameters) > 0)
                ->beginTx('serializable_read_write');
            if ($this->configure !== null) {
                ($this->configure)($query);
            }

            return (new YdbRawExecutor($this->table))->execute($session, $query);
        }, $this->idempotent, $this->retryParams);

        $rows = $this->decodeRows(
            $result,
            'GetBiography',
            [
                ['biography', PrimitiveTypeId::JSON, true],
            ],
            static fn($items): GetBiographyRow => new GetBiographyRow(
                YdbValueCodec::optionalJson($items->offsetGet(0), 'GetBiography.biography'),
            ),
        );

        return $rows[0] ?? null;
    }

    /**
     * @param array<int, array{0: string, 1: int, 2: bool}> $expectedColumns
     * @return list<object>
     */
    private function decodeRows(ExecuteQueryResult $result, string $query, array $expectedColumns, Closure $decode): array
    {
        $sets = $result->getResultSets();
        if (count($sets) !== 1) {
            throw new UnexpectedValueException(sprintf('%s: expected one YDB result set, got %d', $query, count($sets)));
        }
        $set = $sets->offsetGet(0);
        if ($set->getTruncated()) {
            throw new UnexpectedValueException($query . ': YDB result is truncated; use a bounded query or pagination');
        }

        $columns = $set->getColumns();
        if (count($columns) !== count($expectedColumns)) {
            throw new UnexpectedValueException(sprintf('%s: expected %d result columns, got %d', $query, count($expectedColumns), count($columns)));
        }
        foreach ($expectedColumns as $index => [$name, $typeId, $optional]) {
            $column = $columns->offsetGet($index);
            if ($column->getName() !== $name) {
                throw new UnexpectedValueException(sprintf('%s: result column %d is %s, expected %s', $query, $index, $column->getName(), $name));
            }
            YdbValueCodec::assertType($column->getType(), $typeId, $optional, $query . '.' . $name);
        }
        $rows = [];
        foreach ($set->getRows() as $rowIndex => $row) {
            $items = $row->getItems();
            if (count($items) !== count($expectedColumns)) {
                throw new UnexpectedValueException(sprintf('%s: row %d has %d values, expected %d', $query, $rowIndex, count($items), count($expectedColumns)));
            }
            $rows[] = $decode($items);
        }
        return $rows;
    }
}
