// Code generated by sqlc-ydb. DO NOT EDIT.
// source: queries.sql
package db

import (
	"context"
	"errors"
	"io"

	"github.com/ydb-platform/ydb-go-sdk/v3/pkg/xerrors"
	"github.com/ydb-platform/ydb-go-sdk/v3/query"
)

func (q *Queries) ListAuthorBooks(ctx context.Context, opts ...query.ExecuteOption) ([]ListAuthorBooksRow, error) {
	result, err := q.db.Query(ctx, `
		-- name: ListAuthorBooks :many
		SELECT a.id AS author_id, a.name AS author_name, b.title AS book_title
		FROM authors AS a JOIN books AS b ON a.id = b.author_id;
		`, opts...,
	)
	if err != nil {
		return []ListAuthorBooksRow(nil), err
	}
	defer result.Close(ctx)

	resultSet, err := result.NextResultSet(ctx)
	if errors.Is(err, io.EOF) {
		return []ListAuthorBooksRow(nil), xerrors.WithStackTrace(query.ErrNoResultSets)
	}
	if err != nil {
		return []ListAuthorBooksRow(nil), xerrors.WithStackTrace(err)
	}

	items := []ListAuthorBooksRow(nil)
	for r, err := range resultSet.Rows(ctx) {
		if err != nil {
			return []ListAuthorBooksRow(nil), xerrors.WithStackTrace(err)
		}
		var row ListAuthorBooksRow
		if err := r.ScanNamed(
			query.Named("author_id", &row.AuthorID),
			query.Named("author_name", &row.AuthorName),
			query.Named("book_title", &row.BookTitle),
		); err != nil {
			return []ListAuthorBooksRow(nil), xerrors.WithStackTrace(err)
		}
		items = append(items, row)
	}

	_, err = result.NextResultSet(ctx)
	if err == nil {
		return []ListAuthorBooksRow(nil), xerrors.WithStackTrace(query.ErrMoreThanOneResultSet)
	} else if !errors.Is(err, io.EOF) {
		return []ListAuthorBooksRow(nil), xerrors.WithStackTrace(err)
	}

	return items, nil
}
