// Code generated by sqlc-ydb. DO NOT EDIT.
// source: queries.sql
package booktest

import (
	"context"
	"errors"
	"io"

	ydb "github.com/ydb-platform/ydb-go-sdk/v3"
	"github.com/ydb-platform/ydb-go-sdk/v3/pkg/xerrors"
	"github.com/ydb-platform/ydb-go-sdk/v3/query"
)

func (q *Queries) GetAuthor(ctx context.Context, arg uint64, opts ...query.ExecuteOption) (GetAuthorRow, error) {
	parameters := ydb.ParamsBuilder()
	parameters = parameters.Param("$author_id").Uint64(arg)

	callOptions := append([]query.ExecuteOption(nil), opts...)
	callOptions = append(callOptions, query.WithParameters(parameters.Build()))

	result, err := q.db.QueryRow(ctx, "-- name: GetAuthor :one\n"+
		"SELECT author_id, name\n"+
		"FROM authors\n"+
		"WHERE author_id = $author_id;", callOptions...)
	if err != nil {
		return GetAuthorRow{}, err
	}

	var row GetAuthorRow
	if err := result.ScanNamed(
		query.Named("author_id", &row.AuthorID),
		query.Named("name", &row.Name),
	); err != nil {
		return GetAuthorRow{}, err
	}

	return row, nil
}

func (q *Queries) GetBook(ctx context.Context, arg uint64, opts ...query.ExecuteOption) (GetBookRow, error) {
	parameters := ydb.ParamsBuilder()
	parameters = parameters.Param("$book_id").Uint64(arg)

	callOptions := append([]query.ExecuteOption(nil), opts...)
	callOptions = append(callOptions, query.WithParameters(parameters.Build()))

	result, err := q.db.QueryRow(ctx, "-- name: GetBook :one\n"+
		"SELECT book_id, author_id, isbn, book_type, title, publication_year, available, tags\n"+
		"FROM books\n"+
		"WHERE book_id = $book_id;", callOptions...)
	if err != nil {
		return GetBookRow{}, err
	}

	var row GetBookRow
	if err := result.ScanNamed(
		query.Named("book_id", &row.BookID),
		query.Named("author_id", &row.AuthorID),
		query.Named("isbn", &row.Isbn),
		query.Named("book_type", &row.BookType),
		query.Named("title", &row.Title),
		query.Named("publication_year", &row.PublicationYear),
		query.Named("available", &row.Available),
		query.Named("tags", &row.Tags),
	); err != nil {
		return GetBookRow{}, err
	}

	return row, nil
}

func (q *Queries) DeleteBook(ctx context.Context, arg uint64, opts ...query.ExecuteOption) error {
	parameters := ydb.ParamsBuilder()
	parameters = parameters.Param("$book_id").Uint64(arg)

	callOptions := append([]query.ExecuteOption(nil), opts...)
	callOptions = append(callOptions, query.WithParameters(parameters.Build()))

	return q.db.Exec(ctx, "-- name: DeleteBook :exec\n"+
		"DELETE FROM books\n"+
		"WHERE book_id = $book_id;", callOptions...)
}

func (q *Queries) BooksByTitleYear(ctx context.Context, arg BooksByTitleYearParams, opts ...query.ExecuteOption) ([]BooksByTitleYearRow, error) {
	parameters := ydb.ParamsBuilder()
	parameters = parameters.Param("$title").Text(arg.Title)
	parameters = parameters.Param("$publication_year").Int32(arg.PublicationYear)

	callOptions := append([]query.ExecuteOption(nil), opts...)
	callOptions = append(callOptions, query.WithParameters(parameters.Build()))

	result, err := q.db.Query(ctx, "-- name: BooksByTitleYear :many\n"+
		"SELECT book_id, author_id, isbn, book_type, title, publication_year, available, tags\n"+
		"FROM books\n"+
		"WHERE title = $title AND publication_year = $publication_year;", callOptions...)
	if err != nil {
		return make([]BooksByTitleYearRow, 0), err
	}
	defer result.Close(ctx)

	resultSet, err := result.NextResultSet(ctx)
	if errors.Is(err, io.EOF) {
		return make([]BooksByTitleYearRow, 0), xerrors.WithStackTrace(query.ErrNoResultSets)
	}
	if err != nil {
		return make([]BooksByTitleYearRow, 0), xerrors.WithStackTrace(err)
	}

	items := make([]BooksByTitleYearRow, 0)
	for r, err := range resultSet.Rows(ctx) {
		if err != nil {
			return make([]BooksByTitleYearRow, 0), xerrors.WithStackTrace(err)
		}
		var row BooksByTitleYearRow
		if err := r.ScanNamed(
			query.Named("book_id", &row.BookID),
			query.Named("author_id", &row.AuthorID),
			query.Named("isbn", &row.Isbn),
			query.Named("book_type", &row.BookType),
			query.Named("title", &row.Title),
			query.Named("publication_year", &row.PublicationYear),
			query.Named("available", &row.Available),
			query.Named("tags", &row.Tags),
		); err != nil {
			return make([]BooksByTitleYearRow, 0), xerrors.WithStackTrace(err)
		}
		items = append(items, row)
	}

	_, err = result.NextResultSet(ctx)
	switch {
	case err == nil:
		return make([]BooksByTitleYearRow, 0), xerrors.WithStackTrace(query.ErrMoreThanOneResultSet)
	case errors.Is(err, io.EOF):
	case err != nil:
		return make([]BooksByTitleYearRow, 0), xerrors.WithStackTrace(err)
	}

	return items, nil
}

func (q *Queries) BooksByTags(ctx context.Context, arg string, opts ...query.ExecuteOption) ([]BooksByTagsRow, error) {
	parameters := ydb.ParamsBuilder()
	parameters = parameters.Param("$tags").JSON(arg)

	callOptions := append([]query.ExecuteOption(nil), opts...)
	callOptions = append(callOptions, query.WithParameters(parameters.Build()))

	result, err := q.db.Query(ctx, "-- name: BooksByTags :many\n"+
		"\n"+
		"SELECT\n"+
		"    b.book_id,\n"+
		"    b.title,\n"+
		"    a.name,\n"+
		"    b.isbn,\n"+
		"    b.tags\n"+
		"FROM books AS b\n"+
		"LEFT JOIN authors AS a ON b.author_id = a.author_id\n"+
		"WHERE NOT SetIsDisjoint(\n"+
		"    ToSet(Yson::ConvertToStringList(b.tags)),\n"+
		"    Yson::ConvertToStringList($tags)\n"+
		");", callOptions...)
	if err != nil {
		return make([]BooksByTagsRow, 0), err
	}
	defer result.Close(ctx)

	resultSet, err := result.NextResultSet(ctx)
	if errors.Is(err, io.EOF) {
		return make([]BooksByTagsRow, 0), xerrors.WithStackTrace(query.ErrNoResultSets)
	}
	if err != nil {
		return make([]BooksByTagsRow, 0), xerrors.WithStackTrace(err)
	}

	items := make([]BooksByTagsRow, 0)
	for r, err := range resultSet.Rows(ctx) {
		if err != nil {
			return make([]BooksByTagsRow, 0), xerrors.WithStackTrace(err)
		}
		var row BooksByTagsRow
		if err := r.ScanNamed(
			query.Named("b.book_id", &row.BookID),
			query.Named("b.title", &row.Title),
			query.Named("a.name", &row.Name),
			query.Named("b.isbn", &row.Isbn),
			query.Named("b.tags", &row.Tags),
		); err != nil {
			return make([]BooksByTagsRow, 0), xerrors.WithStackTrace(err)
		}
		items = append(items, row)
	}

	_, err = result.NextResultSet(ctx)
	switch {
	case err == nil:
		return make([]BooksByTagsRow, 0), xerrors.WithStackTrace(query.ErrMoreThanOneResultSet)
	case errors.Is(err, io.EOF):
	case err != nil:
		return make([]BooksByTagsRow, 0), xerrors.WithStackTrace(err)
	}

	return items, nil
}

func (q *Queries) CreateAuthor(ctx context.Context, arg CreateAuthorParams, opts ...query.ExecuteOption) (CreateAuthorRow, error) {
	parameters := ydb.ParamsBuilder()
	parameters = parameters.Param("$author_id").Uint64(arg.AuthorID)
	parameters = parameters.Param("$name").Text(arg.Name)

	callOptions := append([]query.ExecuteOption(nil), opts...)
	callOptions = append(callOptions, query.WithParameters(parameters.Build()))

	result, err := q.db.QueryRow(ctx, "-- name: CreateAuthor :one\n"+
		"INSERT INTO authors (author_id, name)\n"+
		"VALUES ($author_id, $name)\n"+
		"RETURNING author_id, name;", callOptions...)
	if err != nil {
		return CreateAuthorRow{}, err
	}

	var row CreateAuthorRow
	if err := result.ScanNamed(
		query.Named("author_id", &row.AuthorID),
		query.Named("name", &row.Name),
	); err != nil {
		return CreateAuthorRow{}, err
	}

	return row, nil
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams, opts ...query.ExecuteOption) (CreateBookRow, error) {
	parameters := ydb.ParamsBuilder()
	parameters = parameters.Param("$book_id").Uint64(arg.BookID)
	parameters = parameters.Param("$author_id").Uint64(arg.AuthorID)
	parameters = parameters.Param("$isbn").Text(arg.Isbn)
	parameters = parameters.Param("$book_type").Text(arg.BookType)
	parameters = parameters.Param("$title").Text(arg.Title)
	parameters = parameters.Param("$publication_year").Int32(arg.PublicationYear)
	parameters = parameters.Param("$available").Timestamp(arg.Available)
	parameters = parameters.Param("$tags").JSON(arg.Tags)

	callOptions := append([]query.ExecuteOption(nil), opts...)
	callOptions = append(callOptions, query.WithParameters(parameters.Build()))

	result, err := q.db.QueryRow(ctx, "-- name: CreateBook :one\n"+
		"INSERT INTO books (\n"+
		"    book_id,\n"+
		"    author_id,\n"+
		"    isbn,\n"+
		"    book_type,\n"+
		"    title,\n"+
		"    publication_year,\n"+
		"    available,\n"+
		"    tags\n"+
		") VALUES (\n"+
		"    $book_id,\n"+
		"    $author_id,\n"+
		"    $isbn,\n"+
		"    $book_type,\n"+
		"    $title,\n"+
		"    $publication_year,\n"+
		"    $available,\n"+
		"    $tags\n"+
		")\n"+
		"RETURNING book_id, author_id, isbn, book_type, title, publication_year, available, tags;", callOptions...)
	if err != nil {
		return CreateBookRow{}, err
	}

	var row CreateBookRow
	if err := result.ScanNamed(
		query.Named("book_id", &row.BookID),
		query.Named("author_id", &row.AuthorID),
		query.Named("isbn", &row.Isbn),
		query.Named("book_type", &row.BookType),
		query.Named("title", &row.Title),
		query.Named("publication_year", &row.PublicationYear),
		query.Named("available", &row.Available),
		query.Named("tags", &row.Tags),
	); err != nil {
		return CreateBookRow{}, err
	}

	return row, nil
}

func (q *Queries) UpdateBook(ctx context.Context, arg UpdateBookParams, opts ...query.ExecuteOption) error {
	parameters := ydb.ParamsBuilder()
	parameters = parameters.Param("$title").Text(arg.Title)
	parameters = parameters.Param("$tags").JSON(arg.Tags)
	parameters = parameters.Param("$book_id").Uint64(arg.BookID)

	callOptions := append([]query.ExecuteOption(nil), opts...)
	callOptions = append(callOptions, query.WithParameters(parameters.Build()))

	return q.db.Exec(ctx, "-- name: UpdateBook :exec\n"+
		"UPDATE books\n"+
		"SET title = $title, tags = $tags\n"+
		"WHERE book_id = $book_id;", callOptions...)
}

func (q *Queries) UpdateBookISBN(ctx context.Context, arg UpdateBookISBNParams, opts ...query.ExecuteOption) error {
	parameters := ydb.ParamsBuilder()
	parameters = parameters.Param("$title").Text(arg.Title)
	parameters = parameters.Param("$tags").JSON(arg.Tags)
	parameters = parameters.Param("$isbn").Text(arg.Isbn)
	parameters = parameters.Param("$book_id").Uint64(arg.BookID)

	callOptions := append([]query.ExecuteOption(nil), opts...)
	callOptions = append(callOptions, query.WithParameters(parameters.Build()))

	return q.db.Exec(ctx, "-- name: UpdateBookISBN :exec\n"+
		"UPDATE books\n"+
		"SET title = $title, tags = $tags, isbn = $isbn\n"+
		"WHERE book_id = $book_id;", callOptions...)
}

func (q *Queries) DeleteAuthorBeforeYear(ctx context.Context, arg DeleteAuthorBeforeYearParams, opts ...query.ExecuteOption) error {
	parameters := ydb.ParamsBuilder()
	parameters = parameters.Param("$publication_year").Int32(arg.PublicationYear)
	parameters = parameters.Param("$author_id").Uint64(arg.AuthorID)

	callOptions := append([]query.ExecuteOption(nil), opts...)
	callOptions = append(callOptions, query.WithParameters(parameters.Build()))

	return q.db.Exec(ctx, "-- name: DeleteAuthorBeforeYear :exec\n"+
		"DELETE FROM books\n"+
		"WHERE publication_year < $publication_year AND author_id = $author_id;", callOptions...)
}

func (q *Queries) SayHello(ctx context.Context, arg string, opts ...query.ExecuteOption) (SayHelloRow, error) {
	parameters := ydb.ParamsBuilder()
	parameters = parameters.Param("$name").Text(arg)

	callOptions := append([]query.ExecuteOption(nil), opts...)
	callOptions = append(callOptions, query.WithParameters(parameters.Build()))

	result, err := q.db.QueryRow(ctx, "-- name: SayHello :one\n"+
		"SELECT \"hello \"u || $name AS greeting;", callOptions...)
	if err != nil {
		return SayHelloRow{}, err
	}

	var row SayHelloRow
	if err := result.ScanNamed(
		query.Named("greeting", &row.Greeting),
	); err != nil {
		return SayHelloRow{}, err
	}

	return row, nil
}
