// Code generated by sqlc-ydb. DO NOT EDIT.
// source: queries.sql
package jets

import (
	"context"
	"database/sql"
)

func (q *Queries) CountPilots(ctx context.Context) (CountPilotsRow, error) {
	var row CountPilotsRow
	err := q.db.QueryRowContext(ctx, `-- name: CountPilots :one
		SELECT COUNT(*) AS pilot_count FROM pilots;
		`,
	).Scan(
		&row.PilotCount,
	)
	return row, err
}

func (q *Queries) ListPilots(ctx context.Context) ([]ListPilotsRow, error) {
	rows, err := q.db.QueryContext(ctx, `-- name: ListPilots :many
		SELECT id, name FROM pilots ORDER BY id LIMIT 5;
		`,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPilotsRow(nil)
	for rows.Next() {
		var row ListPilotsRow
		if err := rows.Scan(
			&row.ID,
			&row.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, row)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

func (q *Queries) DeletePilot(ctx context.Context, arg int32) error {
	_, err := q.db.ExecContext(ctx, `-- name: DeletePilot :exec
		DELETE FROM pilots WHERE id = $pilot_id;
		`, sql.Named("pilot_id", arg),
	)
	return err
}
