<?php
// Code generated by sqlc-ydb. DO NOT EDIT.
declare(strict_types=1);

namespace Booktest\Native;

require_once __DIR__ . '/YdbRuntime.php';

use Closure;
use UnexpectedValueException;
use Ydb\Table\ExecuteQueryResult;
use Ydb\Type\PrimitiveTypeId;
use YdbPlatform\Ydb\Session;
use YdbPlatform\Ydb\Table;

final class Queries
{
    public function __construct(private readonly Table $table)
    {
        if (PHP_INT_SIZE !== 8) {
            throw new \LogicException('sqlc-ydb generated PHP code requires a 64-bit PHP runtime');
        }
    }

    public function getAuthor(string $authorId): ?GetAuthorRow
    {
        $parameters = [
            '$author_id' => YdbValueCodec::typedUint64($authorId, 'author_id'),
        ];
        $result = $this->table->retrySession(function (Session $session) use ($parameters): ExecuteQueryResult {
            $query = $session->newQuery(<<<'SQLC_YDB_YQL'
                -- name: GetAuthor :one
                SELECT author_id, name
                FROM authors
                WHERE author_id = $author_id;
                SQLC_YDB_YQL)
                ->parameters($parameters)
                ->beginTx('serializable_read_write');
            return (new YdbRawExecutor($this->table))->execute($session, $query);
        }, false);
        $rows = $this->decodeRows(
            $result,
            'GetAuthor',
            [
                ['author_id', PrimitiveTypeId::UINT64, false],
                ['name', PrimitiveTypeId::UTF8, false],
            ],
            static fn($items): GetAuthorRow => new GetAuthorRow(
                YdbValueCodec::uint64($items->offsetGet(0), 'GetAuthor.author_id'),
                YdbValueCodec::utf8($items->offsetGet(1), 'GetAuthor.name'),
            ),
        );
        return $rows[0] ?? null;
    }

    public function getBook(string $bookId): ?GetBookRow
    {
        $parameters = [
            '$book_id' => YdbValueCodec::typedUint64($bookId, 'book_id'),
        ];
        $result = $this->table->retrySession(function (Session $session) use ($parameters): ExecuteQueryResult {
            $query = $session->newQuery(<<<'SQLC_YDB_YQL'
                -- name: GetBook :one
                SELECT book_id, author_id, isbn, book_type, title, publication_year, available, tags
                FROM books
                WHERE book_id = $book_id;
                SQLC_YDB_YQL)
                ->parameters($parameters)
                ->beginTx('serializable_read_write');
            return (new YdbRawExecutor($this->table))->execute($session, $query);
        }, false);
        $rows = $this->decodeRows(
            $result,
            'GetBook',
            [
                ['book_id', PrimitiveTypeId::UINT64, false],
                ['author_id', PrimitiveTypeId::UINT64, false],
                ['isbn', PrimitiveTypeId::UTF8, false],
                ['book_type', PrimitiveTypeId::UTF8, false],
                ['title', PrimitiveTypeId::UTF8, false],
                ['publication_year', PrimitiveTypeId::INT32, false],
                ['available', PrimitiveTypeId::TIMESTAMP, false],
                ['tags', PrimitiveTypeId::JSON, false],
            ],
            static fn($items): GetBookRow => new GetBookRow(
                YdbValueCodec::uint64($items->offsetGet(0), 'GetBook.book_id'),
                YdbValueCodec::uint64($items->offsetGet(1), 'GetBook.author_id'),
                YdbValueCodec::utf8($items->offsetGet(2), 'GetBook.isbn'),
                YdbValueCodec::utf8($items->offsetGet(3), 'GetBook.book_type'),
                YdbValueCodec::utf8($items->offsetGet(4), 'GetBook.title'),
                YdbValueCodec::int32($items->offsetGet(5), 'GetBook.publication_year'),
                YdbValueCodec::timestamp($items->offsetGet(6), 'GetBook.available'),
                YdbValueCodec::json($items->offsetGet(7), 'GetBook.tags'),
            ),
        );
        return $rows[0] ?? null;
    }

    public function deleteBook(string $bookId): void
    {
        $parameters = [
            '$book_id' => YdbValueCodec::typedUint64($bookId, 'book_id'),
        ];
        $result = $this->table->retrySession(function (Session $session) use ($parameters): ExecuteQueryResult {
            $query = $session->newQuery(<<<'SQLC_YDB_YQL'
                -- name: DeleteBook :exec
                DELETE FROM books
                WHERE book_id = $book_id;
                SQLC_YDB_YQL)
                ->parameters($parameters)
                ->beginTx('serializable_read_write');
            return (new YdbRawExecutor($this->table))->execute($session, $query);
        }, false);
    }

    /** @return list<BooksByTitleYearRow> */
    public function booksByTitleYear(BooksByTitleYearParams $params): array
    {
        $parameters = [
            '$title' => YdbValueCodec::typedUtf8($params->title, 'title'),
            '$publication_year' => YdbValueCodec::typedInt32($params->publicationYear, 'publication_year'),
        ];
        $result = $this->table->retrySession(function (Session $session) use ($parameters): ExecuteQueryResult {
            $query = $session->newQuery(<<<'SQLC_YDB_YQL'
                -- name: BooksByTitleYear :many
                SELECT book_id, author_id, isbn, book_type, title, publication_year, available, tags
                FROM books
                WHERE title = $title AND publication_year = $publication_year;
                SQLC_YDB_YQL)
                ->parameters($parameters)
                ->beginTx('serializable_read_write');
            return (new YdbRawExecutor($this->table))->execute($session, $query);
        }, false);
        $rows = $this->decodeRows(
            $result,
            'BooksByTitleYear',
            [
                ['book_id', PrimitiveTypeId::UINT64, false],
                ['author_id', PrimitiveTypeId::UINT64, false],
                ['isbn', PrimitiveTypeId::UTF8, false],
                ['book_type', PrimitiveTypeId::UTF8, false],
                ['title', PrimitiveTypeId::UTF8, false],
                ['publication_year', PrimitiveTypeId::INT32, false],
                ['available', PrimitiveTypeId::TIMESTAMP, false],
                ['tags', PrimitiveTypeId::JSON, false],
            ],
            static fn($items): BooksByTitleYearRow => new BooksByTitleYearRow(
                YdbValueCodec::uint64($items->offsetGet(0), 'BooksByTitleYear.book_id'),
                YdbValueCodec::uint64($items->offsetGet(1), 'BooksByTitleYear.author_id'),
                YdbValueCodec::utf8($items->offsetGet(2), 'BooksByTitleYear.isbn'),
                YdbValueCodec::utf8($items->offsetGet(3), 'BooksByTitleYear.book_type'),
                YdbValueCodec::utf8($items->offsetGet(4), 'BooksByTitleYear.title'),
                YdbValueCodec::int32($items->offsetGet(5), 'BooksByTitleYear.publication_year'),
                YdbValueCodec::timestamp($items->offsetGet(6), 'BooksByTitleYear.available'),
                YdbValueCodec::json($items->offsetGet(7), 'BooksByTitleYear.tags'),
            ),
        );
        return $rows;
    }

    /** @return list<BooksByTagsRow> */
    public function booksByTags(string $tags): array
    {
        $parameters = [
            '$tags' => YdbValueCodec::typedJson($tags, 'tags'),
        ];
        $result = $this->table->retrySession(function (Session $session) use ($parameters): ExecuteQueryResult {
            $query = $session->newQuery(<<<'SQLC_YDB_YQL'
                -- name: BooksByTags :many
                DECLARE $tags AS Json;
                SELECT
                    b.book_id,
                    b.title,
                    a.name,
                    b.isbn,
                    b.tags
                FROM books AS b
                LEFT JOIN authors AS a ON b.author_id = a.author_id
                WHERE NOT SetIsDisjoint(
                    ToSet(Yson::ConvertToStringList(b.tags)),
                    Yson::ConvertToStringList($tags)
                );
                SQLC_YDB_YQL)
                ->parameters($parameters)
                ->beginTx('serializable_read_write');
            return (new YdbRawExecutor($this->table))->execute($session, $query);
        }, false);
        $rows = $this->decodeRows(
            $result,
            'BooksByTags',
            [
                ['b.book_id', PrimitiveTypeId::UINT64, false],
                ['b.title', PrimitiveTypeId::UTF8, false],
                ['a.name', PrimitiveTypeId::UTF8, true],
                ['b.isbn', PrimitiveTypeId::UTF8, false],
                ['b.tags', PrimitiveTypeId::JSON, false],
            ],
            static fn($items): BooksByTagsRow => new BooksByTagsRow(
                YdbValueCodec::uint64($items->offsetGet(0), 'BooksByTags.book_id'),
                YdbValueCodec::utf8($items->offsetGet(1), 'BooksByTags.title'),
                YdbValueCodec::optionalUtf8($items->offsetGet(2), 'BooksByTags.name'),
                YdbValueCodec::utf8($items->offsetGet(3), 'BooksByTags.isbn'),
                YdbValueCodec::json($items->offsetGet(4), 'BooksByTags.tags'),
            ),
        );
        return $rows;
    }

    public function createAuthor(CreateAuthorParams $params): ?CreateAuthorRow
    {
        $parameters = [
            '$author_id' => YdbValueCodec::typedUint64($params->authorId, 'author_id'),
            '$name' => YdbValueCodec::typedUtf8($params->name, 'name'),
        ];
        $result = $this->table->retrySession(function (Session $session) use ($parameters): ExecuteQueryResult {
            $query = $session->newQuery(<<<'SQLC_YDB_YQL'
                -- name: CreateAuthor :one
                INSERT INTO authors (author_id, name)
                VALUES ($author_id, $name)
                RETURNING author_id, name;
                SQLC_YDB_YQL)
                ->parameters($parameters)
                ->beginTx('serializable_read_write');
            return (new YdbRawExecutor($this->table))->execute($session, $query);
        }, false);
        $rows = $this->decodeRows(
            $result,
            'CreateAuthor',
            [
                ['author_id', PrimitiveTypeId::UINT64, false],
                ['name', PrimitiveTypeId::UTF8, false],
            ],
            static fn($items): CreateAuthorRow => new CreateAuthorRow(
                YdbValueCodec::uint64($items->offsetGet(0), 'CreateAuthor.author_id'),
                YdbValueCodec::utf8($items->offsetGet(1), 'CreateAuthor.name'),
            ),
        );
        return $rows[0] ?? null;
    }

    public function createBook(CreateBookParams $params): ?CreateBookRow
    {
        $parameters = [
            '$book_id' => YdbValueCodec::typedUint64($params->bookId, 'book_id'),
            '$author_id' => YdbValueCodec::typedUint64($params->authorId, 'author_id'),
            '$isbn' => YdbValueCodec::typedUtf8($params->isbn, 'isbn'),
            '$book_type' => YdbValueCodec::typedUtf8($params->bookType, 'book_type'),
            '$title' => YdbValueCodec::typedUtf8($params->title, 'title'),
            '$publication_year' => YdbValueCodec::typedInt32($params->publicationYear, 'publication_year'),
            '$available' => YdbValueCodec::typedTimestamp($params->available, 'available'),
            '$tags' => YdbValueCodec::typedJson($params->tags, 'tags'),
        ];
        $result = $this->table->retrySession(function (Session $session) use ($parameters): ExecuteQueryResult {
            $query = $session->newQuery(<<<'SQLC_YDB_YQL'
                -- name: CreateBook :one
                INSERT INTO books (
                    book_id,
                    author_id,
                    isbn,
                    book_type,
                    title,
                    publication_year,
                    available,
                    tags
                ) VALUES (
                    $book_id,
                    $author_id,
                    $isbn,
                    $book_type,
                    $title,
                    $publication_year,
                    $available,
                    $tags
                )
                RETURNING book_id, author_id, isbn, book_type, title, publication_year, available, tags;
                SQLC_YDB_YQL)
                ->parameters($parameters)
                ->beginTx('serializable_read_write');
            return (new YdbRawExecutor($this->table))->execute($session, $query);
        }, false);
        $rows = $this->decodeRows(
            $result,
            'CreateBook',
            [
                ['book_id', PrimitiveTypeId::UINT64, false],
                ['author_id', PrimitiveTypeId::UINT64, false],
                ['isbn', PrimitiveTypeId::UTF8, false],
                ['book_type', PrimitiveTypeId::UTF8, false],
                ['title', PrimitiveTypeId::UTF8, false],
                ['publication_year', PrimitiveTypeId::INT32, false],
                ['available', PrimitiveTypeId::TIMESTAMP, false],
                ['tags', PrimitiveTypeId::JSON, false],
            ],
            static fn($items): CreateBookRow => new CreateBookRow(
                YdbValueCodec::uint64($items->offsetGet(0), 'CreateBook.book_id'),
                YdbValueCodec::uint64($items->offsetGet(1), 'CreateBook.author_id'),
                YdbValueCodec::utf8($items->offsetGet(2), 'CreateBook.isbn'),
                YdbValueCodec::utf8($items->offsetGet(3), 'CreateBook.book_type'),
                YdbValueCodec::utf8($items->offsetGet(4), 'CreateBook.title'),
                YdbValueCodec::int32($items->offsetGet(5), 'CreateBook.publication_year'),
                YdbValueCodec::timestamp($items->offsetGet(6), 'CreateBook.available'),
                YdbValueCodec::json($items->offsetGet(7), 'CreateBook.tags'),
            ),
        );
        return $rows[0] ?? null;
    }

    public function updateBook(UpdateBookParams $params): void
    {
        $parameters = [
            '$title' => YdbValueCodec::typedUtf8($params->title, 'title'),
            '$tags' => YdbValueCodec::typedJson($params->tags, 'tags'),
            '$book_id' => YdbValueCodec::typedUint64($params->bookId, 'book_id'),
        ];
        $result = $this->table->retrySession(function (Session $session) use ($parameters): ExecuteQueryResult {
            $query = $session->newQuery(<<<'SQLC_YDB_YQL'
                -- name: UpdateBook :exec
                UPDATE books
                SET title = $title, tags = $tags
                WHERE book_id = $book_id;
                SQLC_YDB_YQL)
                ->parameters($parameters)
                ->beginTx('serializable_read_write');
            return (new YdbRawExecutor($this->table))->execute($session, $query);
        }, false);
    }

    public function updateBookIsbn(UpdateBookIsbnParams $params): void
    {
        $parameters = [
            '$title' => YdbValueCodec::typedUtf8($params->title, 'title'),
            '$tags' => YdbValueCodec::typedJson($params->tags, 'tags'),
            '$isbn' => YdbValueCodec::typedUtf8($params->isbn, 'isbn'),
            '$book_id' => YdbValueCodec::typedUint64($params->bookId, 'book_id'),
        ];
        $result = $this->table->retrySession(function (Session $session) use ($parameters): ExecuteQueryResult {
            $query = $session->newQuery(<<<'SQLC_YDB_YQL'
                -- name: UpdateBookISBN :exec
                UPDATE books
                SET title = $title, tags = $tags, isbn = $isbn
                WHERE book_id = $book_id;
                SQLC_YDB_YQL)
                ->parameters($parameters)
                ->beginTx('serializable_read_write');
            return (new YdbRawExecutor($this->table))->execute($session, $query);
        }, false);
    }

    public function deleteAuthorBeforeYear(DeleteAuthorBeforeYearParams $params): void
    {
        $parameters = [
            '$publication_year' => YdbValueCodec::typedInt32($params->publicationYear, 'publication_year'),
            '$author_id' => YdbValueCodec::typedUint64($params->authorId, 'author_id'),
        ];
        $result = $this->table->retrySession(function (Session $session) use ($parameters): ExecuteQueryResult {
            $query = $session->newQuery(<<<'SQLC_YDB_YQL'
                -- name: DeleteAuthorBeforeYear :exec
                DELETE FROM books
                WHERE publication_year < $publication_year AND author_id = $author_id;
                SQLC_YDB_YQL)
                ->parameters($parameters)
                ->beginTx('serializable_read_write');
            return (new YdbRawExecutor($this->table))->execute($session, $query);
        }, false);
    }

    public function sayHello(string $name): ?SayHelloRow
    {
        $parameters = [
            '$name' => YdbValueCodec::typedUtf8($name, 'name'),
        ];
        $result = $this->table->retrySession(function (Session $session) use ($parameters): ExecuteQueryResult {
            $query = $session->newQuery(<<<'SQLC_YDB_YQL'
                -- name: SayHello :one
                SELECT "hello "u || $name AS greeting;
                SQLC_YDB_YQL)
                ->parameters($parameters)
                ->beginTx('serializable_read_write');
            return (new YdbRawExecutor($this->table))->execute($session, $query);
        }, false);
        $rows = $this->decodeRows(
            $result,
            'SayHello',
            [
                ['greeting', PrimitiveTypeId::UTF8, false],
            ],
            static fn($items): SayHelloRow => new SayHelloRow(
                YdbValueCodec::utf8($items->offsetGet(0), 'SayHello.greeting'),
            ),
        );
        return $rows[0] ?? null;
    }

    /**
     * @param array<int, array{0: string, 1: int, 2: bool}> $expectedColumns
     * @return list<object>
     */
    private function decodeRows(ExecuteQueryResult $result, string $query, array $expectedColumns, Closure $decode): array
    {
        $sets = $result->getResultSets();
        if (count($sets) !== 1) {
            throw new UnexpectedValueException(sprintf('%s: expected one YDB result set, got %d', $query, count($sets)));
        }
        $set = $sets->offsetGet(0);
        $columns = $set->getColumns();
        if (count($columns) !== count($expectedColumns)) {
            throw new UnexpectedValueException(sprintf('%s: expected %d result columns, got %d', $query, count($expectedColumns), count($columns)));
        }
        foreach ($expectedColumns as $index => [$name, $typeId, $optional]) {
            $column = $columns->offsetGet($index);
            if ($column->getName() !== $name) {
                throw new UnexpectedValueException(sprintf('%s: result column %d is %s, expected %s', $query, $index, $column->getName(), $name));
            }
            YdbValueCodec::assertType($column->getType(), $typeId, $optional, $query . '.' . $name);
        }
        $rows = [];
        foreach ($set->getRows() as $rowIndex => $row) {
            $items = $row->getItems();
            if (count($items) !== count($expectedColumns)) {
                throw new UnexpectedValueException(sprintf('%s: row %d has %d values, expected %d', $query, $rowIndex, count($items), count($expectedColumns)));
            }
            $rows[] = $decode($items);
        }
        return $rows;
    }
}
