<?php
// Code generated by sqlc-ydb. DO NOT EDIT.
declare(strict_types=1);

namespace Booktest\Native;

final class UpdateBookParams
{
    public function __construct(
        public readonly string $title,
        public readonly string $tags,
        public readonly string $bookId
    ) {}
}
