# Code generated by sqlc-ydb. DO NOT EDIT.
from dataclasses import dataclass
from datetime import date, datetime, timedelta
from uuid import UUID
from typing import Optional

@dataclass
class LocalLabels:
    id: int
    label: Optional[str]

@dataclass
class ImportedLabels:
    id: int
    label: str

@dataclass
class DistinctLabelsRow:
    id: int
    label: Optional[str]

@dataclass
class AllLabelsRow:
    id: int
    label: Optional[str]
