<?php
// Code generated by sqlc-ydb. DO NOT EDIT.
declare(strict_types=1);

namespace Authors\Native;

final class GetAuthorRow
{
    public function __construct(
        public readonly string $id,
        public readonly string $name,
        public readonly ?string $bio
    ) {}
}
