// Code generated by sqlc-ydb. DO NOT EDIT.

#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct CountPilotsRow {
    pub pilot_count: u64,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ListPilotsRow {
    pub id: i32,
    pub name: String,
}
