// Code generated by sqlc. DO NOT EDIT.
// source: queries.sql

package db

import (
	"context"

	ydb "github.com/ydb-platform/ydb-go-sdk/v3"
	"github.com/ydb-platform/ydb-go-sdk/v3/pkg/xerrors"
	"github.com/ydb-platform/ydb-go-sdk/v3/query"
)

const getAuthor = `-- name: GetAuthor :one
SELECT * FROM authors
WHERE id = $id LIMIT 1;`

type GetAuthorParams struct {
	ID uint64 `json:"id"`
}

func (q *Queries) GetAuthor(ctx context.Context, arg GetAuthorParams, opts ...query.ExecuteOption) (GetAuthorRow, error) {
	parameters := ydb.ParamsBuilder()
	parameters = parameters.Param("$id").Uint64(arg.ID)
	row, err := q.db.QueryRow(ctx, getAuthor,
		append(opts, query.WithParameters(parameters.Build()))...,
	)
	var i GetAuthorRow
	if err != nil {
		return i, xerrors.WithStackTrace(err)
	}
	err = row.Scan(&i.ID, &i.Name)
	if err != nil {
		return i, xerrors.WithStackTrace(err)
	}
	return i, nil
}


const listAuthors = `-- name: ListAuthors :many
SELECT * FROM authors
ORDER BY name;`

func (q *Queries) ListAuthors(ctx context.Context, opts ...query.ExecuteOption) ([]ListAuthorsRow, error) {
	result, err := q.db.QueryResultSet(ctx, listAuthors, opts...)
	if err != nil {
		return nil, xerrors.WithStackTrace(err)
	}
	var items []ListAuthorsRow
	for row, err := range result.Rows(ctx) {
		if err != nil {
			return nil, xerrors.WithStackTrace(err)
		}
		var i ListAuthorsRow
		if err := row.Scan(&i.ID, &i.Name); err != nil {
			return nil, xerrors.WithStackTrace(err)
		}
		items = append(items, i)
	}
	if err := result.Close(ctx); err != nil {
		return nil, xerrors.WithStackTrace(err)
	}
	return items, nil
}


const createAuthor = `-- name: CreateAuthor :one
INSERT INTO authors (name)
VALUES ($name)
RETURNING *;`

type CreateAuthorParams struct {
	Name string `json:"name"`
}

func (q *Queries) CreateAuthor(ctx context.Context, arg CreateAuthorParams, opts ...query.ExecuteOption) (CreateAuthorRow, error) {
	parameters := ydb.ParamsBuilder()
	parameters = parameters.Param("$name").Text(arg.Name)
	row, err := q.db.QueryRow(ctx, createAuthor,
		append(opts, query.WithParameters(parameters.Build()))...,
	)
	var i CreateAuthorRow
	if err != nil {
		return i, xerrors.WithStackTrace(err)
	}
	err = row.Scan(&i.ID, &i.Name)
	if err != nil {
		return i, xerrors.WithStackTrace(err)
	}
	return i, nil
}


const getAlbum = `-- name: GetAlbum :one
SELECT * FROM albums
WHERE id = $id LIMIT 1;`

type GetAlbumParams struct {
	ID uint64 `json:"id"`
}

func (q *Queries) GetAlbum(ctx context.Context, arg GetAlbumParams, opts ...query.ExecuteOption) (GetAlbumRow, error) {
	parameters := ydb.ParamsBuilder()
	parameters = parameters.Param("$id").Uint64(arg.ID)
	row, err := q.db.QueryRow(ctx, getAlbum,
		append(opts, query.WithParameters(parameters.Build()))...,
	)
	var i GetAlbumRow
	if err != nil {
		return i, xerrors.WithStackTrace(err)
	}
	err = row.Scan(&i.ID, &i.Title, &i.Author_id)
	if err != nil {
		return i, xerrors.WithStackTrace(err)
	}
	return i, nil
}


const listAlbumsByAuthor = `-- name: ListAlbumsByAuthor :many
SELECT * FROM albums
WHERE author_id = $author_id
ORDER BY title;`

type ListAlbumsByAuthorParams struct {
	Author_id uint64 `json:"author_id"`
}

func (q *Queries) ListAlbumsByAuthor(ctx context.Context, opts ...query.ExecuteOption) ([]ListAlbumsByAuthorRow, error) {
	result, err := q.db.QueryResultSet(ctx, listAlbumsByAuthor, opts...)
	if err != nil {
		return nil, xerrors.WithStackTrace(err)
	}
	var items []ListAlbumsByAuthorRow
	for row, err := range result.Rows(ctx) {
		if err != nil {
			return nil, xerrors.WithStackTrace(err)
		}
		var i ListAlbumsByAuthorRow
		if err := row.Scan(&i.ID, &i.Title, &i.Author_id); err != nil {
			return nil, xerrors.WithStackTrace(err)
		}
		items = append(items, i)
	}
	if err := result.Close(ctx); err != nil {
		return nil, xerrors.WithStackTrace(err)
	}
	return items, nil
}


const createAlbum = `-- name: CreateAlbum :one
INSERT INTO albums (title, author_id)
VALUES ($title, $author_id)
RETURNING *;`

type CreateAlbumParams struct {
	Title string `json:"title"`
	Author_id uint64 `json:"author_id"`
}

func (q *Queries) CreateAlbum(ctx context.Context, arg CreateAlbumParams, opts ...query.ExecuteOption) (CreateAlbumRow, error) {
	parameters := ydb.ParamsBuilder()
	parameters = parameters.Param("$title").Text(arg.Title)
	parameters = parameters.Param("$author_id").Uint64(arg.Author_id)
	row, err := q.db.QueryRow(ctx, createAlbum,
		append(opts, query.WithParameters(parameters.Build()))...,
	)
	var i CreateAlbumRow
	if err != nil {
		return i, xerrors.WithStackTrace(err)
	}
	err = row.Scan(&i.ID, &i.Title, &i.Author_id)
	if err != nil {
		return i, xerrors.WithStackTrace(err)
	}
	return i, nil
}


const deleteAlbum = `-- name: DeleteAlbum :exec
DELETE FROM albums
WHERE id = $id;`

type DeleteAlbumParams struct {
	ID uint64 `json:"id"`
}

func (q *Queries) DeleteAlbum(ctx context.Context, arg DeleteAlbumParams, opts ...query.ExecuteOption) error {
	parameters := ydb.ParamsBuilder()
	parameters = parameters.Param("$id").Uint64(arg.ID)
	err := q.db.Exec(ctx, deleteAlbum,
		append(opts, query.WithParameters(parameters.Build()))...,
	)
	if err != nil {
		return xerrors.WithStackTrace(err)
	}
	return nil
}


