// Code generated by sqlc-ydb. DO NOT EDIT.
// source: flatten.sql
package authors

import (
	"context"
	"errors"
	"io"

	"github.com/ydb-platform/ydb-go-sdk/v3/pkg/xerrors"
	"github.com/ydb-platform/ydb-go-sdk/v3/query"
)

// -- name: ListAuthorNameWords :many
func (q *Queries) ListAuthorNameWords(ctx context.Context, opts ...query.ExecuteOption) ([]ListAuthorNameWordsRow, error) {
	result, err := q.db.Query(ctx, ""+
		"SELECT id, word\n"+
		"FROM (SELECT id, Unicode::SplitToList(name, \" \"u) AS words FROM authors)\n"+
		"FLATTEN LIST BY words AS word\n"+
		"ORDER BY id, word;",
		opts...,
	)
	if err != nil {
		return nil, xerrors.WithStackTrace(err)
	}
	defer result.Close(ctx)

	resultSet, err := result.NextResultSet(ctx)
	if errors.Is(err, io.EOF) {
		return nil, xerrors.WithStackTrace(query.ErrNoResultSets)
	}
	if err != nil {
		return nil, xerrors.WithStackTrace(err)
	}

	items := make([]ListAuthorNameWordsRow, 0)
	for r, err := range resultSet.Rows(ctx) {
		if err != nil {
			return nil, xerrors.WithStackTrace(err)
		}
		var row ListAuthorNameWordsRow
		if err := r.ScanNamed(
			query.Named("id", &row.ID),
			query.Named("word", &row.Word),
		); err != nil {
			return nil, xerrors.WithStackTrace(err)
		}
		items = append(items, row)
	}

	_, err = result.NextResultSet(ctx)
	if err == nil {
		return nil, xerrors.WithStackTrace(query.ErrMoreThanOneResultSet)
	} else if !errors.Is(err, io.EOF) {
		return nil, xerrors.WithStackTrace(err)
	}

	return items, nil
}
