// Code generated by sqlc-ydb. DO NOT EDIT.
#include "queries.hpp"

#include <ydb-cpp-sdk/client/params/params.h>
#include <ydb-cpp-sdk/client/result/result.h>
#include <ydb-cpp-sdk/client/types/status/status.h>

#include <stdexcept>
#include <utility>

namespace authors::native {

// -- name: GetAuthor :one
std::optional<GetAuthorRow> Queries::GetAuthor(std::uint64_t author_id) const {
    std::optional<NYdb::TResultSet> sqlc_result_set;
    const auto sqlc_execute = [&](NYdb::NQuery::TSession sqlc_session, const NYdb::NQuery::TTxControl& sqlc_tx) -> NYdb::TStatus {
        auto sqlc_params = NYdb::TParamsBuilder()
            .AddParam("$author_id").Uint64(author_id).Build()
            .Build();
        auto sqlc_result = sqlc_session.ExecuteQuery(
            R"sql(
                SELECT id, name, bio FROM authors WHERE id = $author_id;
            )sql",
            sqlc_tx,
            sqlc_params,
            this->execute_settings_
        ).GetValueSync();
        if (sqlc_result.IsSuccess()) {
            if (sqlc_result.GetResultSets().size() != 1) {
                throw std::runtime_error("expected exactly one result set");
            }
            sqlc_result_set = sqlc_result.GetResultSet(0);
        }
        return sqlc_result;
    };
    const auto sqlc_status = this->transaction_ != nullptr
        ? sqlc_execute(this->transaction_->GetSession(), NYdb::NQuery::TTxControl::Tx(*this->transaction_))
        : this->client_->RetryQuerySync([&](NYdb::NQuery::TSession sqlc_session) -> NYdb::TStatus {
            return sqlc_execute(
                std::move(sqlc_session),
                NYdb::NQuery::TTxControl::BeginTx(this->tx_settings_).CommitTx()
            );
        }, this->retry_settings_);
    NYdb::NStatusHelpers::ThrowOnError(sqlc_status);
    if (!sqlc_result_set) {
        throw std::runtime_error("GetAuthor: successful query returned no result set");
    }
    NYdb::TResultSetParser sqlc_parser(*sqlc_result_set);
    if (!sqlc_parser.TryNextRow()) {
        return std::nullopt;
    }
    GetAuthorRow sqlc_row{
        sqlc_parser.ColumnParser("id").GetUint64(),
        sqlc_parser.ColumnParser("name").GetUtf8(),
        sqlc_parser.ColumnParser("bio").GetOptionalUtf8(),
    };
    return sqlc_row;
}

// -- name: ListAuthors :many
std::vector<ListAuthorsRow> Queries::ListAuthors() const {
    std::optional<NYdb::TResultSet> sqlc_result_set;
    const auto sqlc_execute = [&](NYdb::NQuery::TSession sqlc_session, const NYdb::NQuery::TTxControl& sqlc_tx) -> NYdb::TStatus {
        auto sqlc_result = sqlc_session.ExecuteQuery(
            R"sql(
                SELECT id, name, bio FROM authors ORDER BY name;
            )sql",
            sqlc_tx,
            this->execute_settings_
        ).GetValueSync();
        if (sqlc_result.IsSuccess()) {
            if (sqlc_result.GetResultSets().size() != 1) {
                throw std::runtime_error("expected exactly one result set");
            }
            sqlc_result_set = sqlc_result.GetResultSet(0);
        }
        return sqlc_result;
    };
    const auto sqlc_status = this->transaction_ != nullptr
        ? sqlc_execute(this->transaction_->GetSession(), NYdb::NQuery::TTxControl::Tx(*this->transaction_))
        : this->client_->RetryQuerySync([&](NYdb::NQuery::TSession sqlc_session) -> NYdb::TStatus {
            return sqlc_execute(
                std::move(sqlc_session),
                NYdb::NQuery::TTxControl::BeginTx(this->tx_settings_).CommitTx()
            );
        }, this->retry_settings_);
    NYdb::NStatusHelpers::ThrowOnError(sqlc_status);
    if (!sqlc_result_set) {
        throw std::runtime_error("ListAuthors: successful query returned no result set");
    }
    NYdb::TResultSetParser sqlc_parser(*sqlc_result_set);
    std::vector<ListAuthorsRow> sqlc_rows;
    sqlc_rows.reserve(sqlc_result_set->RowsCount());
    while (sqlc_parser.TryNextRow()) {
        sqlc_rows.push_back(ListAuthorsRow{
            sqlc_parser.ColumnParser("id").GetUint64(),
            sqlc_parser.ColumnParser("name").GetUtf8(),
            sqlc_parser.ColumnParser("bio").GetOptionalUtf8(),
        });
    }
    return sqlc_rows;
}

// -- name: GetAuthorName :one
std::optional<GetAuthorNameRow> Queries::GetAuthorName(std::uint64_t author_id) const {
    std::optional<NYdb::TResultSet> sqlc_result_set;
    const auto sqlc_execute = [&](NYdb::NQuery::TSession sqlc_session, const NYdb::NQuery::TTxControl& sqlc_tx) -> NYdb::TStatus {
        auto sqlc_params = NYdb::TParamsBuilder()
            .AddParam("$author_id").Uint64(author_id).Build()
            .Build();
        auto sqlc_result = sqlc_session.ExecuteQuery(
            R"sql(
                SELECT name FROM authors WHERE id = $author_id;
            )sql",
            sqlc_tx,
            sqlc_params,
            this->execute_settings_
        ).GetValueSync();
        if (sqlc_result.IsSuccess()) {
            if (sqlc_result.GetResultSets().size() != 1) {
                throw std::runtime_error("expected exactly one result set");
            }
            sqlc_result_set = sqlc_result.GetResultSet(0);
        }
        return sqlc_result;
    };
    const auto sqlc_status = this->transaction_ != nullptr
        ? sqlc_execute(this->transaction_->GetSession(), NYdb::NQuery::TTxControl::Tx(*this->transaction_))
        : this->client_->RetryQuerySync([&](NYdb::NQuery::TSession sqlc_session) -> NYdb::TStatus {
            return sqlc_execute(
                std::move(sqlc_session),
                NYdb::NQuery::TTxControl::BeginTx(this->tx_settings_).CommitTx()
            );
        }, this->retry_settings_);
    NYdb::NStatusHelpers::ThrowOnError(sqlc_status);
    if (!sqlc_result_set) {
        throw std::runtime_error("GetAuthorName: successful query returned no result set");
    }
    NYdb::TResultSetParser sqlc_parser(*sqlc_result_set);
    if (!sqlc_parser.TryNextRow()) {
        return std::nullopt;
    }
    GetAuthorNameRow sqlc_row{
        sqlc_parser.ColumnParser("name").GetUtf8(),
    };
    return sqlc_row;
}

// -- name: CreateAuthor :one
std::optional<CreateAuthorRow> Queries::CreateAuthor(std::uint64_t author_id, const std::string& author_name, const std::optional<std::string>& biography) const {
    std::optional<NYdb::TResultSet> sqlc_result_set;
    const auto sqlc_execute = [&](NYdb::NQuery::TSession sqlc_session, const NYdb::NQuery::TTxControl& sqlc_tx) -> NYdb::TStatus {
        auto sqlc_params = NYdb::TParamsBuilder()
            .AddParam("$author_id").Uint64(author_id).Build()
            .AddParam("$author_name").Utf8(author_name).Build()
            .AddParam("$biography").OptionalUtf8(biography).Build()
            .Build();
        auto sqlc_result = sqlc_session.ExecuteQuery(
            R"sql(
                INSERT INTO `authors` (`id`, `name`, `bio`)
                VALUES ($author_id, $author_name, $biography)
                RETURNING `id`, `name`, `bio`;
            )sql",
            sqlc_tx,
            sqlc_params,
            this->execute_settings_
        ).GetValueSync();
        if (sqlc_result.IsSuccess()) {
            if (sqlc_result.GetResultSets().size() != 1) {
                throw std::runtime_error("expected exactly one result set");
            }
            sqlc_result_set = sqlc_result.GetResultSet(0);
        }
        return sqlc_result;
    };
    const auto sqlc_status = this->transaction_ != nullptr
        ? sqlc_execute(this->transaction_->GetSession(), NYdb::NQuery::TTxControl::Tx(*this->transaction_))
        : this->client_->RetryQuerySync([&](NYdb::NQuery::TSession sqlc_session) -> NYdb::TStatus {
            return sqlc_execute(
                std::move(sqlc_session),
                NYdb::NQuery::TTxControl::BeginTx(this->tx_settings_).CommitTx()
            );
        }, this->retry_settings_);
    NYdb::NStatusHelpers::ThrowOnError(sqlc_status);
    if (!sqlc_result_set) {
        throw std::runtime_error("CreateAuthor: successful query returned no result set");
    }
    NYdb::TResultSetParser sqlc_parser(*sqlc_result_set);
    if (!sqlc_parser.TryNextRow()) {
        return std::nullopt;
    }
    CreateAuthorRow sqlc_row{
        sqlc_parser.ColumnParser("id").GetUint64(),
        sqlc_parser.ColumnParser("name").GetUtf8(),
        sqlc_parser.ColumnParser("bio").GetOptionalUtf8(),
    };
    return sqlc_row;
}

// -- name: UpsertAuthor :exec
void Queries::UpsertAuthor(std::uint64_t author_id, const std::string& author_name, const std::optional<std::string>& biography) const {
    const auto sqlc_execute = [&](NYdb::NQuery::TSession sqlc_session, const NYdb::NQuery::TTxControl& sqlc_tx) -> NYdb::TStatus {
        auto sqlc_params = NYdb::TParamsBuilder()
            .AddParam("$author_id").Uint64(author_id).Build()
            .AddParam("$author_name").Utf8(author_name).Build()
            .AddParam("$biography").OptionalUtf8(biography).Build()
            .Build();
        auto sqlc_result = sqlc_session.ExecuteQuery(
            R"sql(
                UPSERT INTO authors (id, name, bio)
                VALUES ($author_id, $author_name, $biography);
            )sql",
            sqlc_tx,
            sqlc_params,
            this->execute_settings_
        ).GetValueSync();
        return sqlc_result;
    };
    const auto sqlc_status = this->transaction_ != nullptr
        ? sqlc_execute(this->transaction_->GetSession(), NYdb::NQuery::TTxControl::Tx(*this->transaction_))
        : this->client_->RetryQuerySync([&](NYdb::NQuery::TSession sqlc_session) -> NYdb::TStatus {
            return sqlc_execute(
                std::move(sqlc_session),
                NYdb::NQuery::TTxControl::BeginTx(this->tx_settings_).CommitTx()
            );
        }, this->retry_settings_);
    NYdb::NStatusHelpers::ThrowOnError(sqlc_status);
}

// -- name: DeleteAuthor :exec
void Queries::DeleteAuthor(std::uint64_t author_id) const {
    const auto sqlc_execute = [&](NYdb::NQuery::TSession sqlc_session, const NYdb::NQuery::TTxControl& sqlc_tx) -> NYdb::TStatus {
        auto sqlc_params = NYdb::TParamsBuilder()
            .AddParam("$author_id").Uint64(author_id).Build()
            .Build();
        auto sqlc_result = sqlc_session.ExecuteQuery(
            R"sql(
                DELETE FROM authors WHERE id = $author_id;
            )sql",
            sqlc_tx,
            sqlc_params,
            this->execute_settings_
        ).GetValueSync();
        return sqlc_result;
    };
    const auto sqlc_status = this->transaction_ != nullptr
        ? sqlc_execute(this->transaction_->GetSession(), NYdb::NQuery::TTxControl::Tx(*this->transaction_))
        : this->client_->RetryQuerySync([&](NYdb::NQuery::TSession sqlc_session) -> NYdb::TStatus {
            return sqlc_execute(
                std::move(sqlc_session),
                NYdb::NQuery::TTxControl::BeginTx(this->tx_settings_).CommitTx()
            );
        }, this->retry_settings_);
    NYdb::NStatusHelpers::ThrowOnError(sqlc_status);
}

}  // namespace authors::native
