// Code generated by sqlc-ydb. DO NOT EDIT.

#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct Books {
    pub book_id: u64,
    pub author_id: u64,
    pub isbn: String,
    pub book_type: String,
    pub title: String,
    pub publication_year: i32,
    pub available: std::time::SystemTime,
    pub tags: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct Authors {
    pub author_id: u64,
    pub name: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct GetAuthorRow {
    pub author_id: u64,
    pub name: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct GetBookRow {
    pub book_id: u64,
    pub author_id: u64,
    pub isbn: String,
    pub book_type: String,
    pub title: String,
    pub publication_year: i32,
    pub available: std::time::SystemTime,
    pub tags: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct GetBookAndAuthorRow {
    pub books: Books,
    pub authors: Authors,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct BooksByTitleYearRow {
    pub book_id: u64,
    pub author_id: u64,
    pub isbn: String,
    pub book_type: String,
    pub title: String,
    pub publication_year: i32,
    pub available: std::time::SystemTime,
    pub tags: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct BooksByTagsRow {
    pub book_id: u64,
    pub title: String,
    pub name: Option<String>,
    pub isbn: String,
    pub tags: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct CreateAuthorRow {
    pub author_id: u64,
    pub name: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct CreateBookRow {
    pub book_id: u64,
    pub author_id: u64,
    pub isbn: String,
    pub book_type: String,
    pub title: String,
    pub publication_year: i32,
    pub available: std::time::SystemTime,
    pub tags: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct SayHelloRow {
    pub greeting: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ListAuthorsWithRecentBooksRow {
    pub author_id: u64,
    pub name: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ListBooksWithRecentEditionsRow {
    pub book_id: u64,
    pub author_id: u64,
    pub isbn: String,
    pub book_type: String,
    pub title: String,
    pub publication_year: i32,
    pub available: std::time::SystemTime,
    pub tags: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct UpdateAuthorAndListBooksRow {
    pub book_id: u64,
    pub title: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct SelectAuthorAndDeleteBooksRow {
    pub author_id: u64,
    pub name: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ListAuthorBookTitlesRow {
    pub author_id: u64,
    pub name: String,
    pub titles_json: Option<String>,
}

#[derive(Debug, Clone, PartialEq)]
pub struct InspectBookTextRow {
    pub base32: ydb::Bytes,
    pub alphabetic: bool,
    pub host: Option<ydb::Bytes>,
    pub square_root: f64,
    pub yson_string: bool,
    pub pattern_found: bool,
}
