// Code generated by sqlc-ydb. DO NOT EDIT.
import type { Query, SQL } from "@ydbjs/query";
import type { JSValue } from "@ydbjs/value";
import { Int32, Uint32, Uint64, Utf8, Utf8Type } from "@ydbjs/value/primitive";
import { Optional } from "@ydbjs/value/optional";

export type ConfigureQuery = (query: Query) => void;

export type GetAuthorRow = {
  readonly id: bigint;
  readonly name: string;
  readonly bio: string | null;
};

export type ListAuthorsRow = {
  readonly id: bigint;
  readonly name: string;
  readonly bio: string | null;
};

export type ListAuthorsPageParams = {
  readonly pageSize: number;
  readonly offset: number;
};

export type ListAuthorsPageRow = {
  readonly id: bigint;
  readonly name: string;
  readonly bio: string | null;
};

export type GetAuthorNameRow = {
  readonly name: string;
};

export type CreateAuthorParams = {
  readonly authorId: bigint;
  readonly authorName: string;
  readonly biography: string | null;
};

export type CreateAuthorRow = {
  readonly id: bigint;
  readonly name: string;
  readonly bio: string | null;
};

export type UpsertAuthorParams = {
  readonly authorId: bigint;
  readonly authorName: string;
  readonly biography: string | null;
};

export type FindAuthorsByNameRow = {
  readonly id: bigint;
  readonly name: string;
  readonly bio: string | null;
};

export type FindAuthorsByNameCoveringRow = {
  readonly id: bigint;
  readonly name: string;
  readonly bio: string | null;
};

export type FindAuthorsByNamePrefixRow = {
  readonly id: bigint;
  readonly name: string;
  readonly bio: string | null;
  readonly has_bio: boolean;
};

export type GetAuthorStatisticsRow = {
  readonly total: bigint;
  readonly with_bio: bigint;
  readonly with_nonempty_bio: bigint;
  readonly column3: boolean;
};

export type GetAuthorExportMetadataRow = {
  readonly id: bigint;
  readonly export_date: Uint8Array;
  readonly export_datetime: Uint8Array;
  readonly export_timestamp: Date;
  readonly export_timestamp_text: Uint8Array;
  readonly export_timestamp_micros: bigint;
  readonly column6: number;
  readonly export_metadata: JSValue;
};

export class Queries {
  readonly #sql: SQL;

  constructor(sql: SQL) {
    if (typeof sql !== "function") throw new TypeError("Queries requires a YDB SQL function");
    this.#sql = sql;
  }

  // -- name: GetAuthor :one
  async getAuthor(authorId: bigint, configure?: ConfigureQuery): Promise<GetAuthorRow | null> {
    const stmt = this.#sql<[GetAuthorRow]>(
      "SELECT id, name, bio FROM authors WHERE id = $author_id;"
    )
      .parameter("author_id", new Uint64(authorId));
    configure?.(stmt);
    const [rows] = await stmt;

    return rows[0] ?? null;
  }

  // -- name: ListAuthors :many
  async listAuthors(configure?: ConfigureQuery): Promise<ListAuthorsRow[]> {
    const stmt = this.#sql<[ListAuthorsRow]>(
      "SELECT id, name, bio FROM authors ORDER BY name;"
    );
    configure?.(stmt);
    const [rows] = await stmt;

    return rows;
  }

  // -- name: ListAuthorsPage :many
  async listAuthorsPage(args: ListAuthorsPageParams, configure?: ConfigureQuery): Promise<ListAuthorsPageRow[]> {
    const stmt = this.#sql<[ListAuthorsPageRow]>(
      "DECLARE $page_size AS Int;\n" +
      "DECLARE $offset AS Uint32;\n" +
      "SELECT id, name, bio FROM authors ORDER BY id LIMIT $page_size OFFSET $offset;"
    );
    // Keep explicit DECLARE statements; the SDK otherwise prepends duplicates.
    Object.defineProperty(stmt, "text", { value: stmt.text, writable: false });
    stmt
      .parameter("page_size", new Int32(args.pageSize))
      .parameter("offset", new Uint32(args.offset));
    configure?.(stmt);
    const [rows] = await stmt;

    return rows;
  }

  // -- name: GetAuthorName :one
  async getAuthorName(authorId: bigint, configure?: ConfigureQuery): Promise<GetAuthorNameRow | null> {
    const stmt = this.#sql<[GetAuthorNameRow]>(
      "SELECT name FROM authors WHERE id = $author_id;"
    )
      .parameter("author_id", new Uint64(authorId));
    configure?.(stmt);
    const [rows] = await stmt;

    return rows[0] ?? null;
  }

  // -- name: CreateAuthor :one
  async createAuthor(args: CreateAuthorParams, configure?: ConfigureQuery): Promise<CreateAuthorRow | null> {
    const stmt = this.#sql<[CreateAuthorRow]>(
      "INSERT INTO `authors` (`id`, `name`, `bio`)\n" +
      "VALUES ($author_id, $author_name, $biography)\n" +
      "RETURNING `id`, `name`, `bio`;"
    )
      .parameter("author_id", new Uint64(args.authorId))
      .parameter("author_name", new Utf8(args.authorName))
      .parameter("biography", new Optional(args.biography === null ? null : new Utf8(args.biography), new Utf8Type()));
    configure?.(stmt);
    const [rows] = await stmt;

    return rows[0] ?? null;
  }

  // -- name: UpsertAuthor :exec
  async upsertAuthor(args: UpsertAuthorParams, configure?: ConfigureQuery): Promise<void> {
    const stmt = this.#sql(
      "UPSERT INTO authors (id, name, bio)\n" +
      "VALUES ($author_id, $author_name, $biography);"
    )
      .parameter("author_id", new Uint64(args.authorId))
      .parameter("author_name", new Utf8(args.authorName))
      .parameter("biography", new Optional(args.biography === null ? null : new Utf8(args.biography), new Utf8Type()));
    configure?.(stmt);
    await stmt;
  }

  // -- name: DeleteAuthor :exec
  async deleteAuthor(authorId: bigint, configure?: ConfigureQuery): Promise<void> {
    const stmt = this.#sql(
      "DELETE FROM authors WHERE id = $author_id;"
    )
      .parameter("author_id", new Uint64(authorId));
    configure?.(stmt);
    await stmt;
  }

  // -- name: FindAuthorsByName :many
  async findAuthorsByName(name: string, configure?: ConfigureQuery): Promise<FindAuthorsByNameRow[]> {
    const stmt = this.#sql<[FindAuthorsByNameRow]>(
      "SELECT a.`id` AS `id`, `a`.`name` AS `name`, `a`.`bio` AS `bio` FROM authors VIEW by_name AS a\n" +
      "WHERE a.name = $name ORDER BY a.id;"
    )
      .parameter("name", new Utf8(name));
    configure?.(stmt);
    const [rows] = await stmt;

    return rows;
  }

  // -- name: FindAuthorsByNameCovering :many
  async findAuthorsByNameCovering(name: string, configure?: ConfigureQuery): Promise<FindAuthorsByNameCoveringRow[]> {
    const stmt = this.#sql<[FindAuthorsByNameCoveringRow]>(
      "DECLARE $name AS Utf8;\n" +
      "SELECT `id`, `name`, `bio` FROM authors VIEW by_name_covering WHERE name = $name ORDER BY id;"
    );
    // Keep explicit DECLARE statements; the SDK otherwise prepends duplicates.
    Object.defineProperty(stmt, "text", { value: stmt.text, writable: false });
    stmt
      .parameter("name", new Utf8(name));
    configure?.(stmt);
    const [rows] = await stmt;

    return rows;
  }

  // -- name: FindAuthorsByNamePrefix :many
  async findAuthorsByNamePrefix(prefix: string, configure?: ConfigureQuery): Promise<FindAuthorsByNamePrefixRow[]> {
    const stmt = this.#sql<[FindAuthorsByNamePrefixRow]>(
      "DECLARE $prefix AS Utf8;\n" +
      "SELECT id, name, bio, bio IS NOT NULL AS has_bio\n" +
      "FROM authors\n" +
      "WHERE name LIKE $prefix || \"%\"u\n" +
      "ORDER BY id;"
    );
    // Keep explicit DECLARE statements; the SDK otherwise prepends duplicates.
    Object.defineProperty(stmt, "text", { value: stmt.text, writable: false });
    stmt
      .parameter("prefix", new Utf8(prefix));
    configure?.(stmt);
    const [rows] = await stmt;

    return rows;
  }

  // -- name: GetAuthorStatistics :one
  async getAuthorStatistics(configure?: ConfigureQuery): Promise<GetAuthorStatisticsRow | null> {
    const stmt = this.#sql<[GetAuthorStatisticsRow]>(
      "SELECT\n" +
      "    COUNT(*) AS total,\n" +
      "    COUNT_IF(bio IS NOT NULL) AS with_bio,\n" +
      "    COUNT_IF(bio != \"\"u) AS with_nonempty_bio,\n" +
      "    CAST(COUNT(*) AS Bool)\n" +
      "FROM authors;"
    );
    configure?.(stmt);
    const [rows] = await stmt;

    return rows[0] ?? null;
  }

  // -- name: GetAuthorExportMetadata :one
  async getAuthorExportMetadata(authorId: bigint, configure?: ConfigureQuery): Promise<GetAuthorExportMetadataRow | null> {
    const stmt = this.#sql<[GetAuthorExportMetadataRow]>(
      "DECLARE $author_id AS Uint64;\n" +
      "SELECT\n" +
      "    id,\n" +
      "    CAST(CurrentUtcDate() AS String) AS export_date,\n" +
      "    CAST(CurrentUtcDatetime() AS String) AS export_datetime,\n" +
      "    CurrentUtcTimestamp() AS export_timestamp,\n" +
      "    CAST(CurrentUtcTimestamp() AS String) AS export_timestamp_text,\n" +
      "    CAST(CurrentUtcTimestamp() AS Uint64) AS export_timestamp_micros,\n" +
      "    COALESCE(CAST(id AS Uint32), 0),\n" +
      "    CAST('{\"source\":\"authors\"}' AS Json) AS export_metadata\n" +
      "FROM authors\n" +
      "WHERE id = $author_id;"
    );
    // Keep explicit DECLARE statements; the SDK otherwise prepends duplicates.
    Object.defineProperty(stmt, "text", { value: stmt.text, writable: false });
    stmt
      .parameter("author_id", new Uint64(authorId));
    configure?.(stmt);
    const [rows] = await stmt;

    return rows[0] ?? null;
  }
}
