// Code generated by sqlc-ydb. DO NOT EDIT.
package authors.jdbc;

import tech.ydb.table.values.PrimitiveValue;

// The caller owns the injected client and its lifecycle.
public final class Queries {
    private final java.sql.Connection client;

    public Queries(java.sql.Connection client) {
        this.client = java.util.Objects.requireNonNull(client);
    }

    // -- name: GetAuthor :one
    public java.util.Optional<GetAuthorRow> getAuthor(long authorId) throws java.sql.SQLException {
        try (var _prepared = client.prepareStatement("""
              \s
            SELECT `id`, `name`, `bio` FROM `authors` WHERE `id` = ?;\
            """)) {
            _prepared.setObject(1, PrimitiveValue.newUint64(authorId));
            try (var _rows = _prepared.executeQuery()) {
                if (!_rows.next()) return java.util.Optional.empty();
                long _value0 = _rows.getLong(1);
                String _value1 = _rows.getString(2);
                String _value2 = _rows.getString(3);
                return java.util.Optional.of(new GetAuthorRow(_value0, _value1, _value2));
            }
        }
    }
}
