# Code generated by sqlc-ydb. DO NOT EDIT.
from __future__ import annotations
from typing import Iterable, Optional
from . import models
import ydb

SQL_GET_AUTHOR = "-- name: GetAuthor :one\nDECLARE $author_id AS Uint64;\nSELECT id, name, bio FROM authors WHERE id = $author_id;"

SQL_LIST_AUTHORS = "-- name: ListAuthors :many\nSELECT id, name, bio FROM authors ORDER BY id;"

SQL_GET_AUTHOR_NAME = "-- name: GetAuthorName :one\nDECLARE $author_id AS Uint64;\nSELECT name FROM authors WHERE id = $author_id;"

SQL_UPSERT_AUTHOR = "-- name: UpsertAuthor :exec\nDECLARE $author_id AS Uint64;\nDECLARE $author_name AS Utf8;\nDECLARE $biography AS Optional<Utf8>;\nUPSERT INTO authors (id, name, bio)\nVALUES ($author_id, $author_name, $biography);"

SQL_DELETE_AUTHOR = "-- name: DeleteAuthor :exec\nDECLARE $author_id AS Uint64;\nDELETE FROM authors WHERE id = $author_id;"


def _row_value(row, name, index):
    try:
        return row[name]
    except (KeyError, IndexError, TypeError):
        try:
            return row[index]
        except (KeyError, IndexError, TypeError):
            return getattr(row, name)

def _typed(value, typ):
    return ydb.TypedValue(value, typ)


class Querier:
    def __init__(self, pool: ydb.QuerySessionPool):
        self._pool = pool

    def get_author(self, author_id: int) -> Optional[models.Author]:
        parameters = {"$author_id": _typed(author_id, ydb.PrimitiveType.Uint64)}
        result_sets = self._pool.execute_with_retries(SQL_GET_AUTHOR, parameters)
        rows = result_sets[0].rows if result_sets else []
        if not rows:
            return None
        row = rows[0]
        return models.Author(
            id=_row_value(row, "id", 0),
            name=_row_value(row, "name", 1),
            bio=_row_value(row, "bio", 2),
        )

    def list_authors(self) -> Iterable[models.Author]:
        parameters = {}
        result_sets = self._pool.execute_with_retries(SQL_LIST_AUTHORS, parameters)
        rows = result_sets[0].rows if result_sets else []
        return (models.Author(
            id=_row_value(row, "id", 0),
            name=_row_value(row, "name", 1),
            bio=_row_value(row, "bio", 2),
        ) for row in rows)

    def get_author_name(self, author_id: int) -> Optional[models.GetAuthorNameRow]:
        parameters = {"$author_id": _typed(author_id, ydb.PrimitiveType.Uint64)}
        result_sets = self._pool.execute_with_retries(SQL_GET_AUTHOR_NAME, parameters)
        rows = result_sets[0].rows if result_sets else []
        if not rows:
            return None
        row = rows[0]
        return models.GetAuthorNameRow(
            name=_row_value(row, "name", 0),
        )

    def upsert_author(self, author_id: int, author_name: str, biography: Optional[str]) -> None:
        parameters = {"$author_id": _typed(author_id, ydb.PrimitiveType.Uint64),"$author_name": _typed(author_name, ydb.PrimitiveType.Utf8),"$biography": _typed(biography, ydb.OptionalType(ydb.PrimitiveType.Utf8))}
        result_sets = self._pool.execute_with_retries(SQL_UPSERT_AUTHOR, parameters)
        return None

    def delete_author(self, author_id: int) -> None:
        parameters = {"$author_id": _typed(author_id, ydb.PrimitiveType.Uint64)}
        result_sets = self._pool.execute_with_retries(SQL_DELETE_AUTHOR, parameters)
        return None
