# Code generated by sqlc-ydb. DO NOT EDIT.
from dataclasses import dataclass
from datetime import date, datetime, timedelta
from uuid import UUID
from typing import Optional

@dataclass
class Weather:
    city: str
    temperature: int

@dataclass
class ColdCitiesRow:
    city: str
    reading_count: int
    hottest_temperature: int
