// Code generated by sqlc-ydb. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;
using Dapper;
using Ydb.Sdk.Ado;
using Ydb.Sdk.Value;

namespace Authors.Dapper;

public sealed class Queries
{
    private readonly YdbConnection _connection;
    private readonly YdbTransaction? _transaction;

    public Queries(YdbConnection connection, YdbTransaction? transaction = null)
    {
        _connection = connection ?? throw new ArgumentNullException(nameof(connection));
        _transaction = transaction;
    }

    public Queries WithTransaction(YdbTransaction transaction) => new(_connection, transaction ?? throw new ArgumentNullException(nameof(transaction)));

    // -- name: GetAuthor :one
    public async Task<GetAuthorRow> GetAuthorAsync(ulong AuthorID, CancellationToken cancellationToken = default)
    {
        var command = new CommandDefinition(
            "DECLARE $author_id AS Uint64;\n" +
            "SELECT `id`, `name`, `bio` FROM `authors` WHERE `id` = $author_id;", new YdbParameters(new YdbParameter("$author_id", DbType.UInt64, AuthorID)), _transaction, cancellationToken: cancellationToken);
        await using var reader = await _connection.ExecuteReaderAsync(command).ConfigureAwait(false);
        if (!await reader.ReadAsync(cancellationToken).ConfigureAwait(false))
        {
            throw new InvalidOperationException("query returned no rows");
        }
        return GetAuthorRowFrom(reader);
    }

    private static GetAuthorRow GetAuthorRowFrom(DbDataReader reader) => new(
        reader.GetFieldValue<ulong>(0),
        reader.GetFieldValue<string>(1),
        reader.IsDBNull(2) ? null : reader.GetFieldValue<string>(2)
    );

    private sealed class YdbParameters : SqlMapper.IDynamicParameters
    {
        private readonly YdbParameter[] _parameters;

        public YdbParameters(params YdbParameter[] parameters) => _parameters = parameters;

        public void AddParameters(IDbCommand command, SqlMapper.Identity identity)
        {
            foreach (var parameter in _parameters)
            {
                command.Parameters.Add(parameter);
            }
        }
    }
}
