// Code generated by sqlc. DO NOT EDIT.
// source: queries.sql

package db

import (
	"context"

	ydb "github.com/ydb-platform/ydb-go-sdk/v3"
	"github.com/ydb-platform/ydb-go-sdk/v3/pkg/xerrors"
	"github.com/ydb-platform/ydb-go-sdk/v3/query"
)

const getAuthor = `-- name: GetAuthor :one
SELECT * FROM authors
WHERE id = $id LIMIT 1;`

func (q *Queries) GetAuthor(ctx context.Context,
	id uint64,
	opts ...query.ExecuteOption,
) (*Author, error) {
	row, err := q.db.QueryRow(ctx, getAuthor,
		append(opts,
			query.WithParameters(
				ydb.ParamsBuilder().
				Param("$id").Uint64(id).
				Build(),
			),
			query.WithLabel("GetAuthor"),
		)...,
	)
	if err != nil {
		return nil, xerrors.WithStackTrace(err)
	}

	var i Author
	err = row.Scan(&i.ID, &i.Name, &i.Bio)
	if err != nil {
		return nil, xerrors.WithStackTrace(err)
	}

	return &i, nil
}


const listAuthors = `-- name: ListAuthors :many
SELECT * FROM authors
ORDER BY name;`

func (q *Queries) ListAuthors(ctx context.Context, opts ...query.ExecuteOption) ([]Author, error) {
	result, err := q.db.QueryResultSet(ctx, listAuthors,
		append(opts, query.WithLabel("ListAuthors"))...,
	)
	if err != nil {
		return nil, xerrors.WithStackTrace(err)
	}

	var items []Author
	for row, err := range result.Rows(ctx) {
		if err != nil {
			return nil, xerrors.WithStackTrace(err)
		}

		var i Author
		if err := row.Scan(&i.ID, &i.Name, &i.Bio); err != nil {
			return nil, xerrors.WithStackTrace(err)
		}
		items = append(items, i)
	}
	if err := result.Close(ctx); err != nil {
		return nil, xerrors.WithStackTrace(err)
	}

	return items, nil
}


const createAuthor = `-- name: CreateAuthor :one
INSERT INTO authors (id, name, bio)
VALUES ($id, $name, $bio)
RETURNING *;`

func (q *Queries) CreateAuthor(ctx context.Context,
	id uint64,
	name string,
	bio *string,
	opts ...query.ExecuteOption,
) (*Author, error) {
	row, err := q.db.QueryRow(ctx, createAuthor,
		append(opts,
			query.WithParameters(
				ydb.ParamsBuilder().
				Param("$id").Uint64(id).
				Param("$name").Text(name).
				Param("$bio").BeginOptional().Text(bio).EndOptional().
				Build(),
			),
			query.WithLabel("CreateAuthor"),
		)...,
	)
	if err != nil {
		return nil, xerrors.WithStackTrace(err)
	}

	var i Author
	err = row.Scan(&i.ID, &i.Name, &i.Bio)
	if err != nil {
		return nil, xerrors.WithStackTrace(err)
	}

	return &i, nil
}


const updateAuthor = `-- name: UpdateAuthor :exec
UPDATE authors
SET name = $name, bio = $bio
WHERE id = $id;`

func (q *Queries) UpdateAuthor(ctx context.Context,
	name string,
	bio *string,
	id uint64,
	opts ...query.ExecuteOption,
) error {
	err := q.db.Exec(ctx, updateAuthor,
		append(opts,
			query.WithParameters(
				ydb.ParamsBuilder().
				Param("$name").Text(name).
				Param("$bio").BeginOptional().Text(bio).EndOptional().
				Param("$id").Uint64(id).
				Build(),
			),
			query.WithLabel("UpdateAuthor"),
		)...,
	)
	if err != nil {
		return xerrors.WithStackTrace(err)
	}

	return nil
}


const deleteAuthor = `-- name: DeleteAuthor :exec
DELETE FROM authors
WHERE id = $id;`

func (q *Queries) DeleteAuthor(ctx context.Context,
	id uint64,
	opts ...query.ExecuteOption,
) error {
	err := q.db.Exec(ctx, deleteAuthor,
		append(opts,
			query.WithParameters(
				ydb.ParamsBuilder().
				Param("$id").Uint64(id).
				Build(),
			),
			query.WithLabel("DeleteAuthor"),
		)...,
	)
	if err != nil {
		return xerrors.WithStackTrace(err)
	}

	return nil
}


