// Code generated by sqlc-ydb. DO NOT EDIT.
#nullable enable
using System;

namespace Booktest.Dapper;
public sealed record Authors(
    ulong AuthorID,
    string Name
);

public sealed record Books(
    ulong BookID,
    ulong AuthorID,
    string Isbn,
    string BookType,
    string Title,
    int PublicationYear,
    DateTime Available,
    string Tags
);

public sealed record GetAuthorRow(
    ulong AuthorID,
    string Name
);

public sealed record GetBookRow(
    ulong BookID,
    ulong AuthorID,
    string Isbn,
    string BookType,
    string Title,
    int PublicationYear,
    DateTime Available,
    string Tags
);

public sealed record BooksByTitleYearParams(
    string Title,
    int PublicationYear
);

public sealed record BooksByTitleYearRow(
    ulong BookID,
    ulong AuthorID,
    string Isbn,
    string BookType,
    string Title,
    int PublicationYear,
    DateTime Available,
    string Tags
);

public sealed record BooksByTagsRow(
    ulong BookID,
    string Title,
    string? Name,
    string Isbn,
    string Tags
);

public sealed record CreateAuthorParams(
    ulong AuthorID,
    string Name
);

public sealed record CreateAuthorRow(
    ulong AuthorID,
    string Name
);

public sealed record CreateBookParams(
    ulong BookID,
    ulong AuthorID,
    string Isbn,
    string BookType,
    string Title,
    int PublicationYear,
    DateTime Available,
    string Tags
);

public sealed record CreateBookRow(
    ulong BookID,
    ulong AuthorID,
    string Isbn,
    string BookType,
    string Title,
    int PublicationYear,
    DateTime Available,
    string Tags
);

public sealed record UpdateBookParams(
    ulong BookID,
    string Title,
    string Tags
);

public sealed record UpdateBookISBNParams(
    ulong BookID,
    string Title,
    string Tags,
    string Isbn
);

public sealed record DeleteAuthorBeforeYearParams(
    ulong AuthorID,
    int PublicationYear
);

public sealed record SayHelloRow(
    string Greeting
);
