// Code generated by sqlc-ydb. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Reflection;
using System.Threading;
using System.Threading.Tasks;
using Dapper;
using Ydb.Sdk.Ado;
using Ydb.Sdk.Value;

namespace Booktest.Dapper;

public sealed class Queries
{
    private readonly YdbConnection _connection;
    private readonly YdbTransaction? _transaction;

    public Queries(YdbConnection connection, YdbTransaction? transaction = null)
    {
        _connection = connection ?? throw new ArgumentNullException(nameof(connection));
        if (transaction is not null && !ReferenceEquals(transaction.Connection, connection))
        {
            throw new ArgumentException("Transaction must belong to the supplied connection.", nameof(transaction));
        }
        _transaction = transaction;
    }

    public Queries WithTransaction(YdbTransaction transaction) => new(_connection, transaction ?? throw new ArgumentNullException(nameof(transaction)));

    private sealed record GetBookAndAuthorWireRow(
        ulong Column0,
        ulong Column1,
        string Column2,
        string Column3,
        string Column4,
        int Column5,
        DateTime Column6,
        string Column7,
        ulong Column8,
        string Column9
    );

    static Queries()
    {
        SqlMapper.SetTypeMap(typeof(GetAuthorRow), new ColumnTypeMap(typeof(GetAuthorRow), new Dictionary<string, string>
        {
            ["author_id"] = nameof(GetAuthorRow.AuthorID),
        }));
        SqlMapper.SetTypeMap(typeof(FindAuthorsRow), new ColumnTypeMap(typeof(FindAuthorsRow), new Dictionary<string, string>
        {
            ["author_id"] = nameof(FindAuthorsRow.AuthorID),
        }));
        SqlMapper.SetTypeMap(typeof(GetBookRow), new ColumnTypeMap(typeof(GetBookRow), new Dictionary<string, string>
        {
            ["book_id"] = nameof(GetBookRow.BookID),
            ["author_id"] = nameof(GetBookRow.AuthorID),
            ["book_type"] = nameof(GetBookRow.BookType),
            ["publication_year"] = nameof(GetBookRow.PublicationYear),
        }));
        SqlMapper.SetTypeMap(typeof(GetBookAndAuthorWireRow), new ColumnTypeMap(typeof(GetBookAndAuthorWireRow), new Dictionary<string, string>
        {
            ["__sqlc_embed_0_0"] = nameof(GetBookAndAuthorWireRow.Column0),
            ["__sqlc_embed_0_1"] = nameof(GetBookAndAuthorWireRow.Column1),
            ["__sqlc_embed_0_2"] = nameof(GetBookAndAuthorWireRow.Column2),
            ["__sqlc_embed_0_3"] = nameof(GetBookAndAuthorWireRow.Column3),
            ["__sqlc_embed_0_4"] = nameof(GetBookAndAuthorWireRow.Column4),
            ["__sqlc_embed_0_5"] = nameof(GetBookAndAuthorWireRow.Column5),
            ["__sqlc_embed_0_6"] = nameof(GetBookAndAuthorWireRow.Column6),
            ["__sqlc_embed_0_7"] = nameof(GetBookAndAuthorWireRow.Column7),
            ["__sqlc_embed_1_0"] = nameof(GetBookAndAuthorWireRow.Column8),
            ["__sqlc_embed_1_1"] = nameof(GetBookAndAuthorWireRow.Column9),
        }));
        SqlMapper.SetTypeMap(typeof(BooksByTitleYearRow), new ColumnTypeMap(typeof(BooksByTitleYearRow), new Dictionary<string, string>
        {
            ["book_id"] = nameof(BooksByTitleYearRow.BookID),
            ["author_id"] = nameof(BooksByTitleYearRow.AuthorID),
            ["book_type"] = nameof(BooksByTitleYearRow.BookType),
            ["publication_year"] = nameof(BooksByTitleYearRow.PublicationYear),
        }));
        SqlMapper.SetTypeMap(typeof(BooksByTagsRow), new ColumnTypeMap(typeof(BooksByTagsRow), new Dictionary<string, string>
        {
            ["b.book_id"] = nameof(BooksByTagsRow.BookID),
            ["b.title"] = nameof(BooksByTagsRow.Title),
            ["a.name"] = nameof(BooksByTagsRow.Name),
            ["b.isbn"] = nameof(BooksByTagsRow.Isbn),
            ["b.tags"] = nameof(BooksByTagsRow.Tags),
        }));
        SqlMapper.SetTypeMap(typeof(CreateAuthorRow), new ColumnTypeMap(typeof(CreateAuthorRow), new Dictionary<string, string>
        {
            ["author_id"] = nameof(CreateAuthorRow.AuthorID),
        }));
        SqlMapper.SetTypeMap(typeof(CreateBookRow), new ColumnTypeMap(typeof(CreateBookRow), new Dictionary<string, string>
        {
            ["book_id"] = nameof(CreateBookRow.BookID),
            ["author_id"] = nameof(CreateBookRow.AuthorID),
            ["book_type"] = nameof(CreateBookRow.BookType),
            ["publication_year"] = nameof(CreateBookRow.PublicationYear),
        }));
        SqlMapper.SetTypeMap(typeof(ListAuthorsWithRecentBooksRow), new ColumnTypeMap(typeof(ListAuthorsWithRecentBooksRow), new Dictionary<string, string>
        {
            ["author_id"] = nameof(ListAuthorsWithRecentBooksRow.AuthorID),
        }));
        SqlMapper.SetTypeMap(typeof(ListBooksWithRecentEditionsRow), new ColumnTypeMap(typeof(ListBooksWithRecentEditionsRow), new Dictionary<string, string>
        {
            ["book_id"] = nameof(ListBooksWithRecentEditionsRow.BookID),
            ["author_id"] = nameof(ListBooksWithRecentEditionsRow.AuthorID),
            ["book_type"] = nameof(ListBooksWithRecentEditionsRow.BookType),
            ["publication_year"] = nameof(ListBooksWithRecentEditionsRow.PublicationYear),
        }));
        SqlMapper.SetTypeMap(typeof(UpdateAuthorAndListBooksRow), new ColumnTypeMap(typeof(UpdateAuthorAndListBooksRow), new Dictionary<string, string>
        {
            ["book_id"] = nameof(UpdateAuthorAndListBooksRow.BookID),
        }));
        SqlMapper.SetTypeMap(typeof(SelectAuthorAndDeleteBooksRow), new ColumnTypeMap(typeof(SelectAuthorAndDeleteBooksRow), new Dictionary<string, string>
        {
            ["author_id"] = nameof(SelectAuthorAndDeleteBooksRow.AuthorID),
        }));
        SqlMapper.SetTypeMap(typeof(ListAuthorBookTitlesRow), new ColumnTypeMap(typeof(ListAuthorBookTitlesRow), new Dictionary<string, string>
        {
            ["a.author_id"] = nameof(ListAuthorBookTitlesRow.AuthorID),
            ["a.name"] = nameof(ListAuthorBookTitlesRow.Name),
            ["titles_json"] = nameof(ListAuthorBookTitlesRow.TitlesJson),
        }));
        SqlMapper.SetTypeMap(typeof(InspectBookTextRow), new ColumnTypeMap(typeof(InspectBookTextRow), new Dictionary<string, string>
        {
            ["square_root"] = nameof(InspectBookTextRow.SquareRoot),
            ["yson_string"] = nameof(InspectBookTextRow.YsonString),
            ["pattern_found"] = nameof(InspectBookTextRow.PatternFound),
        }));
    }

    private sealed class ColumnTypeMap : SqlMapper.ITypeMap
    {
        private readonly DefaultTypeMap _default;
        private readonly IReadOnlyDictionary<string, string> _columns;

        public ColumnTypeMap(Type type, IReadOnlyDictionary<string, string> columns)
        {
            _default = new DefaultTypeMap(type);
            _columns = columns;
        }

        private string MemberName(string column) => _columns.TryGetValue(column, out var member) ? member : column;
        public ConstructorInfo? FindConstructor(string[] names, Type[] types) => _default.FindConstructor(names.Select(MemberName).ToArray(), types);
        public ConstructorInfo? FindExplicitConstructor() => _default.FindExplicitConstructor();
        public SqlMapper.IMemberMap? GetConstructorParameter(ConstructorInfo constructor, string columnName) => _default.GetConstructorParameter(constructor, MemberName(columnName));
        public SqlMapper.IMemberMap? GetMember(string columnName) => _default.GetMember(MemberName(columnName));
    }

    private static DateTime NormalizeTimestamp(DateTime value) =>
        value.Kind == DateTimeKind.Local ? value.ToUniversalTime() : DateTime.SpecifyKind(value, DateTimeKind.Utc);

    private static DateTime? NormalizeTimestamp(DateTime? value) =>
        value.HasValue ? NormalizeTimestamp(value.Value) : null;

    // -- name: GetAuthor :one
    public async Task<GetAuthorRow> GetAuthorAsync(ulong authorId, CancellationToken cancellationToken = default, int? commandTimeout = null)
    {
        var parameters = new YdbParameters(
            new YdbParameter("$author_id", DbType.UInt64, authorId)
        );

        var command = new CommandDefinition(
            commandText: """
            SELECT author_id, name
            FROM authors
            WHERE author_id = $author_id;
            """,
            parameters: parameters,
            transaction: _transaction,
            commandTimeout: commandTimeout,
            cancellationToken: cancellationToken);

        return await _connection.QueryFirstAsync<GetAuthorRow>(command).ConfigureAwait(false);
    }

    // -- name: FindAuthors :many
    public async Task<IReadOnlyList<FindAuthorsRow>> FindAuthorsAsync(FindAuthorsParams args, CancellationToken cancellationToken = default, int? commandTimeout = null)
    {
        var parameters = new YdbParameters(
            new YdbParameter("$min_author_id", DbType.UInt64, args.MinAuthorID),
            new YdbParameter("$filter_name", YdbValue.MakeOptionalUtf8(args.FilterName))
        );

        var command = new CommandDefinition(
            commandText: """
            SELECT author_id, name
            FROM authors
            WHERE author_id >= $min_author_id
              AND ($`filter_name` IS NULL OR name = $`filter_name`)
            ORDER BY author_id;
            """,
            parameters: parameters,
            transaction: _transaction,
            commandTimeout: commandTimeout,
            cancellationToken: cancellationToken);

        return (await _connection.QueryAsync<FindAuthorsRow>(command).ConfigureAwait(false)).AsList();
    }

    // -- name: GetBook :one
    public async Task<GetBookRow> GetBookAsync(ulong bookId, CancellationToken cancellationToken = default, int? commandTimeout = null)
    {
        var parameters = new YdbParameters(
            new YdbParameter("$book_id", DbType.UInt64, bookId)
        );

        var command = new CommandDefinition(
            commandText: """
            SELECT book_id, author_id, isbn, book_type, title, publication_year, available, tags
            FROM books
            WHERE book_id = $book_id;
            """,
            parameters: parameters,
            transaction: _transaction,
            commandTimeout: commandTimeout,
            cancellationToken: cancellationToken);

        return await _connection.QueryFirstAsync<GetBookRow>(command).ConfigureAwait(false);
    }

    // -- name: GetBookAndAuthor :one
    public async Task<GetBookAndAuthorRow> GetBookAndAuthorAsync(ulong bookId, CancellationToken cancellationToken = default, int? commandTimeout = null)
    {
        var parameters = new YdbParameters(
            new YdbParameter("$book_id", DbType.UInt64, bookId)
        );

        var command = new CommandDefinition(
            commandText: """
            PRAGMA OrderedColumns;
            SELECT `b`.`book_id` AS `__sqlc_embed_0_0`, `b`.`author_id` AS `__sqlc_embed_0_1`, `b`.`isbn` AS `__sqlc_embed_0_2`, `b`.`book_type` AS `__sqlc_embed_0_3`, `b`.`title` AS `__sqlc_embed_0_4`, `b`.`publication_year` AS `__sqlc_embed_0_5`, `b`.`available` AS `__sqlc_embed_0_6`, `b`.`tags` AS `__sqlc_embed_0_7`, `a`.`author_id` AS `__sqlc_embed_1_0`, `a`.`name` AS `__sqlc_embed_1_1`
            FROM books AS b
            JOIN authors AS a ON b.author_id = a.author_id
            WHERE b.book_id = $book_id;
            """,
            parameters: parameters,
            transaction: _transaction,
            commandTimeout: commandTimeout,
            cancellationToken: cancellationToken);

        var row = await _connection.QueryFirstAsync<GetBookAndAuthorWireRow>(command).ConfigureAwait(false);
        return GetBookAndAuthorRowFromWire(row);
    }

    private static GetBookAndAuthorRow GetBookAndAuthorRowFromWire(GetBookAndAuthorWireRow row) => new(
        new Books(
            row.Column0,
            row.Column1,
            row.Column2,
            row.Column3,
            row.Column4,
            row.Column5,
            row.Column6,
            row.Column7
        ),
        new Authors(
            row.Column8,
            row.Column9
        )
    );

    // -- name: DeleteBook :exec
    public async Task DeleteBookAsync(ulong bookId, CancellationToken cancellationToken = default, int? commandTimeout = null)
    {
        var parameters = new YdbParameters(
            new YdbParameter("$book_id", DbType.UInt64, bookId)
        );

        var command = new CommandDefinition(
            commandText: """
            DELETE FROM books
            WHERE book_id = $book_id;
            """,
            parameters: parameters,
            transaction: _transaction,
            commandTimeout: commandTimeout,
            cancellationToken: cancellationToken);

        await _connection.ExecuteAsync(command).ConfigureAwait(false);
    }

    // -- name: BooksByTitleYear :many
    public async Task<IReadOnlyList<BooksByTitleYearRow>> BooksByTitleYearAsync(BooksByTitleYearParams args, CancellationToken cancellationToken = default, int? commandTimeout = null)
    {
        var parameters = new YdbParameters(
            new YdbParameter("$title", DbType.String, args.Title),
            new YdbParameter("$publication_year", DbType.Int32, args.PublicationYear)
        );

        var command = new CommandDefinition(
            commandText: """
            SELECT book_id, author_id, isbn, book_type, title, publication_year, available, tags
            FROM books
            WHERE title = $title AND publication_year = $publication_year;
            """,
            parameters: parameters,
            transaction: _transaction,
            commandTimeout: commandTimeout,
            cancellationToken: cancellationToken);

        return (await _connection.QueryAsync<BooksByTitleYearRow>(command).ConfigureAwait(false)).AsList();
    }

    // -- name: BooksByTags :many
    public async Task<IReadOnlyList<BooksByTagsRow>> BooksByTagsAsync(string tags, CancellationToken cancellationToken = default, int? commandTimeout = null)
    {
        var parameters = new YdbParameters(
            new YdbParameter("$tags", YdbValue.MakeJson(tags))
        );

        var command = new CommandDefinition(
            commandText: """
            DECLARE $tags AS Json;
            SELECT
                b.book_id,
                b.title,
                a.name,
                b.isbn,
                b.tags
            FROM books AS b
            LEFT JOIN authors AS a ON b.author_id = a.author_id
            WHERE NOT SetIsDisjoint(
                ToSet(Yson::ConvertToStringList(b.tags)),
                Yson::ConvertToStringList($tags)
            );
            """,
            parameters: parameters,
            transaction: _transaction,
            commandTimeout: commandTimeout,
            cancellationToken: cancellationToken);

        return (await _connection.QueryAsync<BooksByTagsRow>(command).ConfigureAwait(false)).AsList();
    }

    // -- name: CreateAuthor :one
    public async Task<CreateAuthorRow> CreateAuthorAsync(CreateAuthorParams args, CancellationToken cancellationToken = default, int? commandTimeout = null)
    {
        var parameters = new YdbParameters(
            new YdbParameter("$author_id", DbType.UInt64, args.AuthorID),
            new YdbParameter("$name", DbType.String, args.Name)
        );

        var command = new CommandDefinition(
            commandText: """
            INSERT INTO authors (author_id, name)
            VALUES ($author_id, $name)
            RETURNING author_id, name;
            """,
            parameters: parameters,
            transaction: _transaction,
            commandTimeout: commandTimeout,
            cancellationToken: cancellationToken);

        return await _connection.QueryFirstAsync<CreateAuthorRow>(command).ConfigureAwait(false);
    }

    // -- name: CreateBook :one
    public async Task<CreateBookRow> CreateBookAsync(CreateBookParams args, CancellationToken cancellationToken = default, int? commandTimeout = null)
    {
        var parameters = new YdbParameters(
            new YdbParameter("$book_id", DbType.UInt64, args.BookID),
            new YdbParameter("$author_id", DbType.UInt64, args.AuthorID),
            new YdbParameter("$isbn", DbType.String, args.Isbn),
            new YdbParameter("$book_type", DbType.String, args.BookType),
            new YdbParameter("$title", DbType.String, args.Title),
            new YdbParameter("$publication_year", DbType.Int32, args.PublicationYear),
            new YdbParameter("$available", YdbValue.MakeTimestamp(NormalizeTimestamp(args.Available))),
            new YdbParameter("$tags", YdbValue.MakeJson(args.Tags))
        );

        var command = new CommandDefinition(
            commandText: """
            INSERT INTO books (
                book_id,
                author_id,
                isbn,
                book_type,
                title,
                publication_year,
                available,
                tags
            ) VALUES (
                $book_id,
                $author_id,
                $isbn,
                $book_type,
                $title,
                $publication_year,
                $available,
                $tags
            )
            RETURNING book_id, author_id, isbn, book_type, title, publication_year, available, tags;
            """,
            parameters: parameters,
            transaction: _transaction,
            commandTimeout: commandTimeout,
            cancellationToken: cancellationToken);

        return await _connection.QueryFirstAsync<CreateBookRow>(command).ConfigureAwait(false);
    }

    // -- name: UpdateBook :exec
    public async Task UpdateBookAsync(UpdateBookParams args, CancellationToken cancellationToken = default, int? commandTimeout = null)
    {
        var parameters = new YdbParameters(
            new YdbParameter("$title", DbType.String, args.Title),
            new YdbParameter("$tags", YdbValue.MakeJson(args.Tags)),
            new YdbParameter("$book_id", DbType.UInt64, args.BookID)
        );

        var command = new CommandDefinition(
            commandText: """
            UPDATE books
            SET title = $title, tags = $tags
            WHERE book_id = $book_id;
            """,
            parameters: parameters,
            transaction: _transaction,
            commandTimeout: commandTimeout,
            cancellationToken: cancellationToken);

        await _connection.ExecuteAsync(command).ConfigureAwait(false);
    }

    // -- name: RemoveBookTag :exec
    public async Task RemoveBookTagAsync(RemoveBookTagParams args, CancellationToken cancellationToken = default, int? commandTimeout = null)
    {
        var parameters = new YdbParameters(
            new YdbParameter("$book_id", DbType.UInt64, args.BookID),
            new YdbParameter("$tag", DbType.Binary, args.Tag)
        );

        var command = new CommandDefinition(
            commandText: """
            DECLARE $book_id AS Uint64;
            DECLARE $tag AS String;
            UPDATE books
            SET tags = UNWRAP(Yson::SerializeJson(Json::From(ListFilter(
                Yson::ConvertToStringList(tags),
                ($item) -> ($item NOT IN AsList($tag))
            ))))
            WHERE book_id = $book_id;
            """,
            parameters: parameters,
            transaction: _transaction,
            commandTimeout: commandTimeout,
            cancellationToken: cancellationToken);

        await _connection.ExecuteAsync(command).ConfigureAwait(false);
    }

    // -- name: UpdateBookISBN :exec
    public async Task UpdateBookISBNAsync(UpdateBookISBNParams args, CancellationToken cancellationToken = default, int? commandTimeout = null)
    {
        var parameters = new YdbParameters(
            new YdbParameter("$title", DbType.String, args.Title),
            new YdbParameter("$tags", YdbValue.MakeJson(args.Tags)),
            new YdbParameter("$isbn", DbType.String, args.Isbn),
            new YdbParameter("$book_id", DbType.UInt64, args.BookID)
        );

        var command = new CommandDefinition(
            commandText: """
            UPDATE books
            SET title = $title, tags = $tags, isbn = $isbn
            WHERE book_id = $book_id;
            """,
            parameters: parameters,
            transaction: _transaction,
            commandTimeout: commandTimeout,
            cancellationToken: cancellationToken);

        await _connection.ExecuteAsync(command).ConfigureAwait(false);
    }

    // -- name: DeleteAuthorBeforeYear :exec
    public async Task DeleteAuthorBeforeYearAsync(DeleteAuthorBeforeYearParams args, CancellationToken cancellationToken = default, int? commandTimeout = null)
    {
        var parameters = new YdbParameters(
            new YdbParameter("$publication_year", DbType.Int32, args.PublicationYear),
            new YdbParameter("$author_id", DbType.UInt64, args.AuthorID)
        );

        var command = new CommandDefinition(
            commandText: """
            DELETE FROM books
            WHERE publication_year < $publication_year AND author_id = $author_id;
            """,
            parameters: parameters,
            transaction: _transaction,
            commandTimeout: commandTimeout,
            cancellationToken: cancellationToken);

        await _connection.ExecuteAsync(command).ConfigureAwait(false);
    }

    // -- name: SayHello :one
    public async Task<SayHelloRow> SayHelloAsync(string name, CancellationToken cancellationToken = default, int? commandTimeout = null)
    {
        var parameters = new YdbParameters(
            new YdbParameter("$name", DbType.String, name)
        );

        var command = new CommandDefinition(
            commandText: """
            SELECT "hello "u || $name AS greeting;
            """,
            parameters: parameters,
            transaction: _transaction,
            commandTimeout: commandTimeout,
            cancellationToken: cancellationToken);

        return await _connection.QueryFirstAsync<SayHelloRow>(command).ConfigureAwait(false);
    }

    // -- name: ListAuthorsWithRecentBooks :many
    public async Task<IReadOnlyList<ListAuthorsWithRecentBooksRow>> ListAuthorsWithRecentBooksAsync(int sinceYear, CancellationToken cancellationToken = default, int? commandTimeout = null)
    {
        var parameters = new YdbParameters(
            new YdbParameter("$since_year", DbType.Int32, sinceYear)
        );

        var command = new CommandDefinition(
            commandText: """
            SELECT a.author_id, a.name
            FROM authors AS a
            WHERE a.author_id IN (
                SELECT b.author_id FROM books AS b WHERE b.publication_year >= $since_year
            )
            ORDER BY a.author_id;
            """,
            parameters: parameters,
            transaction: _transaction,
            commandTimeout: commandTimeout,
            cancellationToken: cancellationToken);

        return (await _connection.QueryAsync<ListAuthorsWithRecentBooksRow>(command).ConfigureAwait(false)).AsList();
    }

    // -- name: ListBooksWithRecentEditions :many
    public async Task<IReadOnlyList<ListBooksWithRecentEditionsRow>> ListBooksWithRecentEditionsAsync(int sinceYear, CancellationToken cancellationToken = default, int? commandTimeout = null)
    {
        var parameters = new YdbParameters(
            new YdbParameter("$since_year", DbType.Int32, sinceYear)
        );

        var command = new CommandDefinition(
            commandText: """
            DECLARE $since_year AS Int32;
            SELECT b.book_id, b.author_id, b.isbn, b.book_type, b.title, b.publication_year, b.available, b.tags
            FROM books AS b
            WHERE (b.author_id, b.book_type) IN (
                SELECT (recent.author_id, recent.book_type)
                FROM books AS recent
                WHERE recent.publication_year >= $since_year
            )
            ORDER BY b.book_id;
            """,
            parameters: parameters,
            transaction: _transaction,
            commandTimeout: commandTimeout,
            cancellationToken: cancellationToken);

        return (await _connection.QueryAsync<ListBooksWithRecentEditionsRow>(command).ConfigureAwait(false)).AsList();
    }

    // -- name: DeleteBooksByAuthorName :exec
    public async Task DeleteBooksByAuthorNameAsync(string authorName, CancellationToken cancellationToken = default, int? commandTimeout = null)
    {
        var parameters = new YdbParameters(
            new YdbParameter("$author_name", DbType.String, authorName)
        );

        var command = new CommandDefinition(
            commandText: """
            DELETE FROM books
            WHERE author_id IN (SELECT author_id FROM authors WHERE name = $author_name);
            """,
            parameters: parameters,
            transaction: _transaction,
            commandTimeout: commandTimeout,
            cancellationToken: cancellationToken);

        await _connection.ExecuteAsync(command).ConfigureAwait(false);
    }

    // -- name: DeleteAuthorWithBooks :exec
    public async Task DeleteAuthorWithBooksAsync(ulong authorId, CancellationToken cancellationToken = default, int? commandTimeout = null)
    {
        var parameters = new YdbParameters(
            new YdbParameter("$author_id", DbType.UInt64, authorId)
        );

        var command = new CommandDefinition(
            commandText: """
            DECLARE $author_id AS Uint64;
            DELETE FROM books WHERE author_id = $author_id;
            DELETE FROM authors WHERE author_id = $author_id;
            """,
            parameters: parameters,
            transaction: _transaction,
            commandTimeout: commandTimeout,
            cancellationToken: cancellationToken);

        await _connection.ExecuteAsync(command).ConfigureAwait(false);
    }

    // -- name: UpdateAuthorAndListBooks :many
    public async Task<IReadOnlyList<UpdateAuthorAndListBooksRow>> UpdateAuthorAndListBooksAsync(UpdateAuthorAndListBooksParams args, CancellationToken cancellationToken = default, int? commandTimeout = null)
    {
        var parameters = new YdbParameters(
            new YdbParameter("$author_id", DbType.UInt64, args.AuthorID),
            new YdbParameter("$name", DbType.String, args.Name)
        );

        var command = new CommandDefinition(
            commandText: """
            DECLARE $author_id AS Uint64;
            DECLARE $name AS Utf8;
            UPDATE authors SET name = $name WHERE author_id = $author_id;
            SELECT book_id, title FROM books WHERE author_id = $author_id ORDER BY book_id;
            """,
            parameters: parameters,
            transaction: _transaction,
            commandTimeout: commandTimeout,
            cancellationToken: cancellationToken);

        return (await _connection.QueryAsync<UpdateAuthorAndListBooksRow>(command).ConfigureAwait(false)).AsList();
    }

    // -- name: SelectAuthorAndDeleteBooks :one
    public async Task<SelectAuthorAndDeleteBooksRow> SelectAuthorAndDeleteBooksAsync(ulong authorId, CancellationToken cancellationToken = default, int? commandTimeout = null)
    {
        var parameters = new YdbParameters(
            new YdbParameter("$author_id", DbType.UInt64, authorId)
        );

        var command = new CommandDefinition(
            commandText: """
            DECLARE $author_id AS Uint64;
            SELECT author_id, name FROM authors WHERE author_id = $author_id;
            DELETE FROM books WHERE author_id = $author_id;
            """,
            parameters: parameters,
            transaction: _transaction,
            commandTimeout: commandTimeout,
            cancellationToken: cancellationToken);

        return await _connection.QueryFirstAsync<SelectAuthorAndDeleteBooksRow>(command).ConfigureAwait(false);
    }

    // -- name: ListAuthorBookTitles :many
    public async Task<IReadOnlyList<ListAuthorBookTitlesRow>> ListAuthorBookTitlesAsync(int sinceYear, CancellationToken cancellationToken = default, int? commandTimeout = null)
    {
        var parameters = new YdbParameters(
            new YdbParameter("$since_year", DbType.Int32, sinceYear)
        );

        var command = new CommandDefinition(
            commandText: """
            DECLARE $since_year AS Int32;
            $recent = (SELECT author_id, title FROM books WHERE publication_year >= $since_year);
            $grouped = (
                SELECT author_id, AGGREGATE_LIST(title, 100u) AS titles
                FROM $recent
                GROUP BY author_id
            );
            SELECT a.author_id, a.name, Yson::SerializeJson(Json::From(g.titles)) AS titles_json
            FROM (SELECT author_id, name FROM authors) AS a
            JOIN $grouped AS g ON a.author_id = g.author_id
            ORDER BY a.author_id;
            """,
            parameters: parameters,
            transaction: _transaction,
            commandTimeout: commandTimeout,
            cancellationToken: cancellationToken);

        return (await _connection.QueryAsync<ListAuthorBookTitlesRow>(command).ConfigureAwait(false)).AsList();
    }

    // -- name: InspectBookText :one
    public async Task<InspectBookTextRow> InspectBookTextAsync(byte[] text, CancellationToken cancellationToken = default, int? commandTimeout = null)
    {
        var parameters = new YdbParameters(
            new YdbParameter("$text", DbType.Binary, text)
        );

        var command = new CommandDefinition(
            commandText: """
            DECLARE $text AS String;
            SELECT
                String::Base32Encode($text) AS base32,
                Unicode::IsAlpha("Book"u) AS alphabetic,
                Url::GetHost("https://example.org/books") AS host,
                Math::Sqrt(9.0) AS square_root,
                Yson::IsString(Yson::From($text)) AS yson_string,
                Pire::Grep("book")($text) AS pattern_found;
            """,
            parameters: parameters,
            transaction: _transaction,
            commandTimeout: commandTimeout,
            cancellationToken: cancellationToken);

        return await _connection.QueryFirstAsync<InspectBookTextRow>(command).ConfigureAwait(false);
    }

    private sealed class YdbParameters : SqlMapper.IDynamicParameters
    {
        private readonly YdbParameter[] _parameters;

        public YdbParameters(params YdbParameter[] parameters) => _parameters = parameters;

        public void AddParameters(IDbCommand command, SqlMapper.Identity identity)
        {
            foreach (var parameter in _parameters)
            {
                command.Parameters.Add(parameter);
            }
        }
    }
}
