// Package kotlin generates SQL-first Kotlin APIs for the YDB SDK and JDBC.
package kotlin

import (
	"fmt"
	"strings"
	"unicode/utf8"

	"github.com/ydb-platform/sqlc-ydb/internal/model"
)

type Options struct{ Package, Runtime string }
type scalar struct{ typ, sdk, jdbc string }

var scalars = map[string]scalar{
	"Bool": {"Boolean", "Bool", "Boolean"}, "Int8": {"Byte", "Int8", "Byte"},
	"Uint8": {"Int", "Uint8", "Int"}, "Int16": {"Short", "Int16", "Short"},
	"Uint16": {"Int", "Uint16", "Int"}, "Int32": {"Int", "Int32", "Int"},
	"Uint32": {"Long", "Uint32", "Long"}, "Int64": {"Long", "Int64", "Long"},
	"Uint64": {"Long", "Uint64", "Long"}, "Float": {"Float", "Float", "Float"},
	"Double": {"Double", "Double", "Double"}, "Utf8": {"String", "Text", "String"},
	"String": {"ByteArray", "Bytes", "Bytes"},
}

func typeInfo(t model.Type) (scalar, string, error) {
	base := t.UnwrapOptional()
	s, ok := scalars[base.Kind]
	if !ok || (t.IsOptional() && (t.Key != nil || len(t.Items) != 0 || t.Precision != 0 || t.Scale != 0)) || base.Elem != nil || base.Key != nil || len(base.Items) != 0 || base.Precision != 0 || base.Scale != 0 {
		return s, "", fmt.Errorf("unsupported Kotlin type %s", t.String())
	}
	typ := s.typ
	if t.IsOptional() {
		typ += "?"
	}
	return s, typ, nil
}

var reserved = func() map[string]bool {
	m := map[string]bool{}
	for _, s := range strings.Fields("as break class continue do else false for fun if in interface is null object package return super this throw true try typealias typeof val var when while by catch constructor delegate dynamic field file finally get import init param property receiver set setparam where actual abstract annotation companion const crossinline data enum expect external final infix inline inner internal lateinit noinline open operator out override private protected public reified sealed suspend tailrec vararg value field it equals hashCode toString clone finalize getClass notify notifyAll wait") {
		m[s] = true
	}
	return m
}()

func identifier(s string) bool {
	if s == "" || reserved[s] || strings.Trim(s, "_") == "" {
		return false
	}
	for i, r := range s {
		if !((r >= 'A' && r <= 'Z') || (r >= 'a' && r <= 'z') || r == '_' || (i > 0 && r >= '0' && r <= '9')) {
			return false
		}
	}
	return true
}
func name(s string, upper bool) (string, error) {
	var b strings.Builder
	for _, r := range s {
		if r == '_' || r == '-' || r == ' ' || r == '.' {
			upper = true
			continue
		}
		if upper && r >= 'a' && r <= 'z' {
			r -= 'a' - 'A'
		} else if b.Len() == 0 && !upper && r >= 'A' && r <= 'Z' {
			r += 'a' - 'A'
		}
		b.WriteRune(r)
		upper = false
	}
	n := b.String()
	if reserved[n] {
		n += "_"
	}
	if !identifier(n) {
		return "", fmt.Errorf("cannot represent %q as a Kotlin identifier", s)
	}
	return n, nil
}
func quoted(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '\\', '"', '$':
			b.WriteByte('\\')
			b.WriteRune(r)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		case '\t':
			b.WriteString(`\t`)
		default:
			if r < 32 || r == 127 {
				fmt.Fprintf(&b, "\\u%04x", r)
			} else {
				b.WriteRune(r)
			}
		}
	}
	b.WriteByte('"')
	return b.String()
}

// Raw strings preserve source indentation and newlines without trimIndent.
// Interpolated character escapes prevent dollars, quotes and controls from
// becoming Kotlin syntax or being normalized by the source-file reader.
func sqlLiteral(s string) string {
	var b strings.Builder
	b.WriteString(`"""`)
	for _, r := range s {
		switch {
		case r == '$':
			b.WriteString(`${'$'}`)
		case r == '"':
			b.WriteString(`${'"'}`)
		case r != '\n' && (r < 32 || r == 127):
			fmt.Fprintf(&b, "${'\\u%04x'}", r)
		default:
			b.WriteRune(r)
		}
	}
	b.WriteString(`"""`)
	return b.String()
}

func Generate(a *model.AnalysisResult, o Options) ([]model.File, error) {
	if a == nil {
		return nil, fmt.Errorf("nil analysis result")
	}
	if len(a.Diagnostics) != 0 {
		return nil, fmt.Errorf("cannot generate Kotlin with analysis diagnostics")
	}
	if o.Package == "" {
		o.Package = "db"
	}
	if o.Package == "java" || strings.HasPrefix(o.Package, "java.") || o.Package == "kotlin" || strings.HasPrefix(o.Package, "kotlin.") {
		return nil, fmt.Errorf("invalid Kotlin package %q: java and kotlin namespaces are reserved", o.Package)
	}
	for _, p := range strings.Split(o.Package, ".") {
		if !identifier(p) {
			return nil, fmt.Errorf("invalid Kotlin package %q", o.Package)
		}
	}
	if o.Runtime == "" || o.Runtime == "native" {
		o.Runtime = "ydb"
	}
	if o.Runtime != "ydb" && o.Runtime != "jdbc" && o.Runtime != "exposed" {
		return nil, fmt.Errorf("unsupported Kotlin runtime %q", o.Runtime)
	}
	header := "// Code generated by sqlc-ydb. DO NOT EDIT.\npackage " + o.Package + "\n\n"
	files := []model.File{}
	types := map[string]bool{}
	for _, n := range strings.Fields("Queries Boolean Byte Short Int Long Float Double String ByteArray List ArrayList Unit SessionRetryContext QueryReader TxMode Params PrimitiveValue PrimitiveType OptionalType IllegalStateException IllegalArgumentException") {
		types[n] = true
	}
	addRecord := func(n string, cols []model.Column) error {
		if types[n] {
			return fmt.Errorf("Kotlin type name collision: %s", n)
		}
		types[n] = true
		if len(cols) == 0 {
			return fmt.Errorf("Kotlin data class %s requires at least one field", n)
		}
		fields := []string{}
		seen := map[string]bool{}
		for _, c := range cols {
			field, err := name(c.Name, false)
			if err != nil {
				return err
			}
			if seen[field] {
				return fmt.Errorf("Kotlin field name collision in %s: %s", n, field)
			}
			seen[field] = true
			_, typ, err := typeInfo(c.Type)
			if err != nil {
				return fmt.Errorf("%s.%s: %w", n, c.Name, err)
			}
			fields = append(fields, "    val "+field+": "+typ)
		}
		files = append(files, model.File{Name: n + ".kt", Content: []byte(header + "data class " + n + "(\n" + strings.Join(fields, ",\n") + "\n)\n")})
		return nil
	}
	for _, table := range a.Catalog.Tables {
		n, err := name(table.Name, true)
		if err != nil {
			return nil, err
		}
		if err := addRecord(n, table.Columns); err != nil {
			return nil, err
		}
	}
	var b strings.Builder
	b.WriteString(header)
	if o.Runtime == "ydb" {
		b.WriteString("import tech.ydb.query.tools.SessionRetryContext\nimport tech.ydb.query.tools.QueryReader\nimport tech.ydb.common.transaction.TxMode\nimport tech.ydb.table.query.Params\n")
	}
	needsValues := false
	for _, q := range a.Queries {
		needsValues = needsValues || len(q.Parameters) > 0
	}
	if needsValues {
		b.WriteString("import tech.ydb.table.values.PrimitiveValue\nimport tech.ydb.table.values.PrimitiveType\nimport tech.ydb.table.values.OptionalType\n")
	}
	owner := map[string]string{"ydb": "SessionRetryContext", "jdbc": "java.sql.Connection", "exposed": "org.jetbrains.exposed.v1.jdbc.JdbcTransaction"}[o.Runtime]
	fmt.Fprintf(&b, "\n// The caller owns the injected client and its lifecycle.\nclass Queries(private val client: %s) {\n", owner)
	methods := map[string]bool{}
	for _, q := range a.Queries {
		if !utf8.ValidString(q.SQL) {
			return nil, fmt.Errorf("%s: Kotlin SQL must be valid UTF-8", q.Name)
		}
		method, err := name(q.Name, false)
		if err != nil {
			return nil, err
		}
		if methods[method] {
			return nil, fmt.Errorf("Kotlin method name collision: %s", method)
		}
		methods[method] = true
		row, _ := name(q.Name, true)
		row += "Row"
		constant := method + "Sql"
		preparedConstant := constant
		if o.Runtime != "ydb" && len(q.Parameters) > 0 && q.SQLWithoutDeclarations != "" {
			preparedConstant = method + "PreparedSql"
		}
		ret := "Unit"
		switch q.Command {
		case model.One, model.Many:
			if len(q.ResultSets) != 1 || len(q.ResultSets[0].Columns) == 0 {
				return nil, fmt.Errorf("%s: %s requires one nonempty result set", q.Name, q.Command)
			}
			if err := addRecord(row, q.ResultSets[0].Columns); err != nil {
				return nil, err
			}
			if q.Command == model.One {
				ret = row + "?"
			} else {
				ret = "List<" + row + ">"
			}
		case model.Exec:
			if len(q.ResultSets) != 0 {
				return nil, fmt.Errorf("%s: Kotlin :exec does not support result sets", q.Name)
			}
		default:
			return nil, fmt.Errorf("%s: Kotlin does not support %s", q.Name, q.Command)
		}
		params, names := []string{}, []string{}
		seen := map[string]bool{"client": true, constant: true, preparedConstant: true, "kotlin": true, "tech": true}
		for _, p := range q.Parameters {
			n, err := name(p.Name, false)
			if err != nil {
				return nil, err
			}
			if seen[n] || types[n] {
				return nil, fmt.Errorf("%s: Kotlin parameter name collision: %s", q.Name, n)
			}
			seen[n] = true
			_, typ, err := typeInfo(p.Type)
			if err != nil {
				return nil, fmt.Errorf("%s parameter %s: %w", q.Name, p.Name, err)
			}
			params = append(params, n+": "+typ)
			names = append(names, n)
		}
		fmt.Fprintf(&b, "\n    private val %s: String = %s\n", constant, sqlLiteral(q.SQL))
		if preparedConstant != constant {
			fmt.Fprintf(&b, "    private val %s: String = %s\n", preparedConstant, sqlLiteral(jdbcSQL(q)))
		}
		fmt.Fprintf(&b, "\n    fun %s(%s): %s {\n", method, strings.Join(params, ", "), ret)
		for i, p := range q.Parameters {
			max := map[string]string{"Uint8": "255", "Uint16": "65535", "Uint32": "4294967295L"}[p.Type.UnwrapOptional().Kind]
			if max == "" {
				continue
			}
			n := names[i]
			condition := n + " >= 0 && " + n + " <= " + max
			if p.Type.IsOptional() {
				condition = n + " == null || (" + condition + ")"
			}
			fmt.Fprintf(&b, "        kotlin.require(%s) { %s }\n", condition, quoted("parameter $"+p.Name+" is outside "+p.Type.UnwrapOptional().Kind+" range"))
		}
		if o.Runtime == "ydb" {
			emitNative(&b, q, names, constant, row)
		} else {
			emitJDBC(&b, q, names, preparedConstant, row, o.Runtime)
		}
		b.WriteString("    }\n")
	}
	b.WriteString("}\n")
	files = append(files, model.File{Name: "Queries.kt", Content: []byte(b.String())})
	return files, nil
}

func jdbcSQL(q model.AnalyzedQuery) string {
	var b strings.Builder
	for _, p := range q.Parameters {
		fmt.Fprintf(&b, "DECLARE $%s AS %s;\n", p.Name, p.Type.String())
	}
	b.WriteString(q.SQLWithoutDeclarations)
	return b.String()
}

func parameterValue(p model.Parameter, n string) string {
	s, _, _ := typeInfo(p.Type)
	value := "PrimitiveValue.new" + s.sdk + "(" + n + ")"
	if p.Type.IsOptional() {
		o := "OptionalType.of(PrimitiveType." + s.sdk + ")"
		value = "if (" + n + " == null) " + o + ".emptyValue() else " + o + ".newValue(" + value + ")"
	}
	return value
}
func emitNative(b *strings.Builder, q model.AnalyzedQuery, names []string, constant, row string) {
	b.WriteString("        val _params = Params.create()\n")
	for i, p := range q.Parameters {
		fmt.Fprintf(b, "        _params.put(%s, %s)\n", quoted("$"+p.Name), parameterValue(p, names[i]))
	}
	b.WriteString("        val _query = client.supplyResult { _session ->\n")
	fmt.Fprintf(b, "            QueryReader.readFrom(_session.createQuery(%s, TxMode.SERIALIZABLE_RW, _params))\n        }.join().getValue()\n", constant)
	if q.Command == model.Exec {
		return
	}
	b.WriteString("        kotlin.check(_query.getResultSetCount() == 1) { \"Expected one result set\" }\n        val _rows = _query.getResultSet(0)\n")
	emitRows(b, q, row, "        ", true)
}
func emitJDBC(b *strings.Builder, q model.AnalyzedQuery, names []string, constant, row, runtime string) {
	connection := "client"
	if runtime == "exposed" {
		b.WriteString("        val _connection = client.connection.connection as java.sql.Connection\n")
		connection = "_connection"
	}
	fmt.Fprintf(b, "        %s.prepareStatement(%s).use { _prepared ->\n", connection, constant)
	if len(q.Parameters) > 0 {
		b.WriteString("            val _statement = _prepared.unwrap(tech.ydb.jdbc.YdbPreparedStatement::class.java)\n")
	}
	for i, p := range q.Parameters {
		fmt.Fprintf(b, "            _statement.setObject(%s, %s)\n", quoted(p.Name), parameterValue(p, names[i]))
	}
	if q.Command == model.Exec {
		b.WriteString("            _prepared.execute()\n")
	} else {
		b.WriteString("            _prepared.executeQuery().use { _rows ->\n")
		emitRows(b, q, row, "                ", false)
		b.WriteString("            }\n")
	}
	b.WriteString("        }\n")
}
func emitRows(b *strings.Builder, q model.AnalyzedQuery, row, indent string, native bool) {
	if q.Command == model.One {
		b.WriteString(indent + "if (!_rows.next()) return null\n")
	} else {
		fmt.Fprintf(b, "%sval _items = ArrayList<%s>()\n%swhile (_rows.next()) {\n", indent, row, indent)
		indent += "    "
	}
	values := []string{}
	for i, c := range q.ResultSets[0].Columns {
		s, typ, _ := typeInfo(c.Type)
		n := fmt.Sprintf("_value%d", i)
		if native {
			reader := fmt.Sprintf("_rows.getColumn(%d)", i)
			value := reader + ".get" + s.sdk + "()"
			if c.Type.IsOptional() {
				value = "if (" + reader + ".isOptionalItemPresent()) " + reader + ".getOptionalItem().get" + s.sdk + "() else null"
			}
			fmt.Fprintf(b, "%sval %s: %s = %s\n", indent, n, typ, value)
		} else {
			value := fmt.Sprintf("_rows.get%s(%d)", s.jdbc, i+1)
			if c.Type.IsOptional() {
				fmt.Fprintf(b, "%sval %sRaw = %s\n%sval %s: %s = if (_rows.wasNull()) null else %sRaw\n", indent, n, value, indent, n, typ, n)
			} else {
				fmt.Fprintf(b, "%sval %s: %s = %s\n", indent, n, typ, value)
			}
		}
		values = append(values, n)
	}
	newRow := row + "(" + strings.Join(values, ", ") + ")"
	if q.Command == model.One {
		fmt.Fprintf(b, "%sreturn %s\n", indent, newRow)
	} else {
		fmt.Fprintf(b, "%s_items.add(%s)\n", indent, newRow)
		indent = strings.TrimSuffix(indent, "    ")
		b.WriteString(indent + "}\n" + indent + "return _items\n")
	}
}
