# Code generated by sqlc. DO NOT EDIT.
import dataclasses
from typing import Optional

@dataclasses.dataclass
class Author:
    author_id: int
    name: str

@dataclasses.dataclass
class Book:
    book_id: int
    author_id: int
    isbn: str
    book_type: str
    title: str
    year: int
    available: Optional[str]
    tags: Optional[str]

