// Code generated by sqlc-ydb. DO NOT EDIT.
// source: queries.sql
package booktest

import (
	"context"
	"database/sql"

	"github.com/ydb-platform/ydb-go-sdk/v3/types"
)

// -- name: GetAuthor :one
func (q *Queries) GetAuthor(ctx context.Context, arg uint64) (GetAuthorRow, error) {
	var row GetAuthorRow
	err := q.db.QueryRowContext(ctx, ""+
		"SELECT author_id, name\n"+
		"FROM authors\n"+
		"WHERE author_id = $author_id;",
		sql.Named("author_id", arg),
	).Scan(
		&row.AuthorID,
		&row.Name,
	)

	return row, err
}

// -- name: GetBook :one
func (q *Queries) GetBook(ctx context.Context, arg uint64) (GetBookRow, error) {
	var row GetBookRow
	err := q.db.QueryRowContext(ctx, ""+
		"SELECT book_id, author_id, isbn, book_type, title, publication_year, available, tags\n"+
		"FROM books\n"+
		"WHERE book_id = $book_id;",
		sql.Named("book_id", arg),
	).Scan(
		&row.BookID,
		&row.AuthorID,
		&row.Isbn,
		&row.BookType,
		&row.Title,
		&row.PublicationYear,
		&row.Available,
		&row.Tags,
	)

	return row, err
}

// -- name: GetBookAndAuthor :one
func (q *Queries) GetBookAndAuthor(ctx context.Context, arg uint64) (GetBookAndAuthorRow, error) {
	var row GetBookAndAuthorRow
	err := q.db.QueryRowContext(ctx, ""+
		"SELECT `b`.`book_id` AS `__sqlc_embed_0_0`, `b`.`author_id` AS `__sqlc_embed_0_1`, `b`.`isbn` AS `__sqlc_embed_0_2`, `b`.`book_type` AS `__sqlc_embed_0_3`, `b`.`title` AS `__sqlc_embed_0_4`, `b`.`publication_year` AS `__sqlc_embed_0_5`, `b`.`available` AS `__sqlc_embed_0_6`, `b`.`tags` AS `__sqlc_embed_0_7`, `a`.`author_id` AS `__sqlc_embed_1_0`, `a`.`name` AS `__sqlc_embed_1_1`\n"+
		"FROM books AS b\n"+
		"JOIN authors AS a ON b.author_id = a.author_id\n"+
		"WHERE b.book_id = $book_id;",
		sql.Named("book_id", arg),
	).Scan(
		&row.Books.BookID,
		&row.Books.AuthorID,
		&row.Books.Isbn,
		&row.Books.BookType,
		&row.Books.Title,
		&row.Books.PublicationYear,
		&row.Books.Available,
		&row.Books.Tags,
		&row.Authors.AuthorID,
		&row.Authors.Name,
	)

	return row, err
}

// -- name: DeleteBook :exec
func (q *Queries) DeleteBook(ctx context.Context, arg uint64) error {
	_, err := q.db.ExecContext(ctx, ""+
		"DELETE FROM books\n"+
		"WHERE book_id = $book_id;",
		sql.Named("book_id", arg),
	)

	return err
}

// -- name: BooksByTitleYear :many
func (q *Queries) BooksByTitleYear(ctx context.Context, arg BooksByTitleYearParams) ([]BooksByTitleYearRow, error) {
	rows, err := q.db.QueryContext(ctx, ""+
		"SELECT book_id, author_id, isbn, book_type, title, publication_year, available, tags\n"+
		"FROM books\n"+
		"WHERE title = $title AND publication_year = $publication_year;",
		sql.Named("title", arg.Title),
		sql.Named("publication_year", arg.PublicationYear),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	items := []BooksByTitleYearRow(nil)
	for rows.Next() {
		var row BooksByTitleYearRow
		if err := rows.Scan(
			&row.BookID,
			&row.AuthorID,
			&row.Isbn,
			&row.BookType,
			&row.Title,
			&row.PublicationYear,
			&row.Available,
			&row.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, row)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// -- name: BooksByTags :many
func (q *Queries) BooksByTags(ctx context.Context, arg string) ([]BooksByTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, ""+
		"DECLARE $tags AS Json;\n"+
		"SELECT\n"+
		"    b.book_id,\n"+
		"    b.title,\n"+
		"    a.name,\n"+
		"    b.isbn,\n"+
		"    b.tags\n"+
		"FROM books AS b\n"+
		"LEFT JOIN authors AS a ON b.author_id = a.author_id\n"+
		"WHERE NOT SetIsDisjoint(\n"+
		"    ToSet(Yson::ConvertToStringList(b.tags)),\n"+
		"    Yson::ConvertToStringList($tags)\n"+
		");",
		sql.Named("tags", types.JSONValue(arg)),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	items := []BooksByTagsRow(nil)
	for rows.Next() {
		var row BooksByTagsRow
		if err := rows.Scan(
			&row.BookID,
			&row.Title,
			&row.Name,
			&row.Isbn,
			&row.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, row)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// -- name: CreateAuthor :one
func (q *Queries) CreateAuthor(ctx context.Context, arg CreateAuthorParams) (CreateAuthorRow, error) {
	var row CreateAuthorRow
	err := q.db.QueryRowContext(ctx, ""+
		"INSERT INTO authors (author_id, name)\n"+
		"VALUES ($author_id, $name)\n"+
		"RETURNING author_id, name;",
		sql.Named("author_id", arg.AuthorID),
		sql.Named("name", arg.Name),
	).Scan(
		&row.AuthorID,
		&row.Name,
	)

	return row, err
}

// -- name: CreateBook :one
func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (CreateBookRow, error) {
	var row CreateBookRow
	err := q.db.QueryRowContext(ctx, ""+
		"INSERT INTO books (\n"+
		"    book_id,\n"+
		"    author_id,\n"+
		"    isbn,\n"+
		"    book_type,\n"+
		"    title,\n"+
		"    publication_year,\n"+
		"    available,\n"+
		"    tags\n"+
		") VALUES (\n"+
		"    $book_id,\n"+
		"    $author_id,\n"+
		"    $isbn,\n"+
		"    $book_type,\n"+
		"    $title,\n"+
		"    $publication_year,\n"+
		"    $available,\n"+
		"    $tags\n"+
		")\n"+
		"RETURNING book_id, author_id, isbn, book_type, title, publication_year, available, tags;",
		sql.Named("book_id", arg.BookID),
		sql.Named("author_id", arg.AuthorID),
		sql.Named("isbn", arg.Isbn),
		sql.Named("book_type", arg.BookType),
		sql.Named("title", arg.Title),
		sql.Named("publication_year", arg.PublicationYear),
		sql.Named("available", arg.Available),
		sql.Named("tags", types.JSONValue(arg.Tags)),
	).Scan(
		&row.BookID,
		&row.AuthorID,
		&row.Isbn,
		&row.BookType,
		&row.Title,
		&row.PublicationYear,
		&row.Available,
		&row.Tags,
	)

	return row, err
}

// -- name: UpdateBook :exec
func (q *Queries) UpdateBook(ctx context.Context, arg UpdateBookParams) error {
	_, err := q.db.ExecContext(ctx, ""+
		"UPDATE books\n"+
		"SET title = $title, tags = $tags\n"+
		"WHERE book_id = $book_id;",
		sql.Named("title", arg.Title),
		sql.Named("tags", types.JSONValue(arg.Tags)),
		sql.Named("book_id", arg.BookID),
	)

	return err
}

// -- name: RemoveBookTag :exec
func (q *Queries) RemoveBookTag(ctx context.Context, arg RemoveBookTagParams) error {
	_, err := q.db.ExecContext(ctx, ""+
		"DECLARE $book_id AS Uint64;\n"+
		"DECLARE $tag AS String;\n"+
		"UPDATE books\n"+
		"SET tags = UNWRAP(Yson::SerializeJson(Json::From(ListFilter(\n"+
		"    Yson::ConvertToStringList(tags),\n"+
		"    ($item) -> ($item NOT IN AsList($tag))\n"+
		"))))\n"+
		"WHERE book_id = $book_id;",
		sql.Named("book_id", arg.BookID),
		sql.Named("tag", arg.Tag),
	)

	return err
}

// -- name: UpdateBookISBN :exec
func (q *Queries) UpdateBookISBN(ctx context.Context, arg UpdateBookISBNParams) error {
	_, err := q.db.ExecContext(ctx, ""+
		"UPDATE books\n"+
		"SET title = $title, tags = $tags, isbn = $isbn\n"+
		"WHERE book_id = $book_id;",
		sql.Named("title", arg.Title),
		sql.Named("tags", types.JSONValue(arg.Tags)),
		sql.Named("isbn", arg.Isbn),
		sql.Named("book_id", arg.BookID),
	)

	return err
}

// -- name: DeleteAuthorBeforeYear :exec
func (q *Queries) DeleteAuthorBeforeYear(ctx context.Context, arg DeleteAuthorBeforeYearParams) error {
	_, err := q.db.ExecContext(ctx, ""+
		"DELETE FROM books\n"+
		"WHERE publication_year < $publication_year AND author_id = $author_id;",
		sql.Named("publication_year", arg.PublicationYear),
		sql.Named("author_id", arg.AuthorID),
	)

	return err
}

// -- name: SayHello :one
func (q *Queries) SayHello(ctx context.Context, arg string) (SayHelloRow, error) {
	var row SayHelloRow
	err := q.db.QueryRowContext(ctx, ""+
		"SELECT \"hello \"u || $name AS greeting;",
		sql.Named("name", arg),
	).Scan(
		&row.Greeting,
	)

	return row, err
}

// -- name: ListAuthorsWithRecentBooks :many
func (q *Queries) ListAuthorsWithRecentBooks(ctx context.Context, arg int32) ([]ListAuthorsWithRecentBooksRow, error) {
	rows, err := q.db.QueryContext(ctx, ""+
		"SELECT a.author_id, a.name\n"+
		"FROM authors AS a\n"+
		"WHERE a.author_id IN (\n"+
		"    SELECT b.author_id FROM books AS b WHERE b.publication_year >= $since_year\n"+
		")\n"+
		"ORDER BY a.author_id;",
		sql.Named("since_year", arg),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	items := []ListAuthorsWithRecentBooksRow(nil)
	for rows.Next() {
		var row ListAuthorsWithRecentBooksRow
		if err := rows.Scan(
			&row.AuthorID,
			&row.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, row)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// -- name: ListBooksWithRecentEditions :many
func (q *Queries) ListBooksWithRecentEditions(ctx context.Context, arg int32) ([]ListBooksWithRecentEditionsRow, error) {
	rows, err := q.db.QueryContext(ctx, ""+
		"DECLARE $since_year AS Int32;\n"+
		"SELECT b.book_id, b.author_id, b.isbn, b.book_type, b.title, b.publication_year, b.available, b.tags\n"+
		"FROM books AS b\n"+
		"WHERE (b.author_id, b.book_type) IN (\n"+
		"    SELECT (recent.author_id, recent.book_type)\n"+
		"    FROM books AS recent\n"+
		"    WHERE recent.publication_year >= $since_year\n"+
		")\n"+
		"ORDER BY b.book_id;",
		sql.Named("since_year", arg),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	items := []ListBooksWithRecentEditionsRow(nil)
	for rows.Next() {
		var row ListBooksWithRecentEditionsRow
		if err := rows.Scan(
			&row.BookID,
			&row.AuthorID,
			&row.Isbn,
			&row.BookType,
			&row.Title,
			&row.PublicationYear,
			&row.Available,
			&row.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, row)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// -- name: DeleteBooksByAuthorName :exec
func (q *Queries) DeleteBooksByAuthorName(ctx context.Context, arg string) error {
	_, err := q.db.ExecContext(ctx, ""+
		"DELETE FROM books\n"+
		"WHERE author_id IN (SELECT author_id FROM authors WHERE name = $author_name);",
		sql.Named("author_name", arg),
	)

	return err
}

// -- name: DeleteAuthorWithBooks :exec
func (q *Queries) DeleteAuthorWithBooks(ctx context.Context, arg uint64) error {
	_, err := q.db.ExecContext(ctx, ""+
		"DECLARE $author_id AS Uint64;\n"+
		"DELETE FROM books WHERE author_id = $author_id;\n"+
		"DELETE FROM authors WHERE author_id = $author_id;",
		sql.Named("author_id", arg),
	)

	return err
}

// -- name: UpdateAuthorAndListBooks :many
func (q *Queries) UpdateAuthorAndListBooks(ctx context.Context, arg UpdateAuthorAndListBooksParams) ([]UpdateAuthorAndListBooksRow, error) {
	rows, err := q.db.QueryContext(ctx, ""+
		"DECLARE $author_id AS Uint64;\n"+
		"DECLARE $name AS Utf8;\n"+
		"UPDATE authors SET name = $name WHERE author_id = $author_id;\n"+
		"SELECT book_id, title FROM books WHERE author_id = $author_id ORDER BY book_id;",
		sql.Named("author_id", arg.AuthorID),
		sql.Named("name", arg.Name),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	items := []UpdateAuthorAndListBooksRow(nil)
	for rows.Next() {
		var row UpdateAuthorAndListBooksRow
		if err := rows.Scan(
			&row.BookID,
			&row.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, row)
	}

	if err := rows.Close(); err != nil {
		return nil, err
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// -- name: SelectAuthorAndDeleteBooks :one
func (q *Queries) SelectAuthorAndDeleteBooks(ctx context.Context, arg uint64) (SelectAuthorAndDeleteBooksRow, error) {
	var row SelectAuthorAndDeleteBooksRow
	err := q.db.QueryRowContext(ctx, ""+
		"DECLARE $author_id AS Uint64;\n"+
		"SELECT author_id, name FROM authors WHERE author_id = $author_id;\n"+
		"DELETE FROM books WHERE author_id = $author_id;",
		sql.Named("author_id", arg),
	).Scan(
		&row.AuthorID,
		&row.Name,
	)

	return row, err
}

// -- name: ListAuthorBookTitles :many
func (q *Queries) ListAuthorBookTitles(ctx context.Context, arg int32) ([]ListAuthorBookTitlesRow, error) {
	rows, err := q.db.QueryContext(ctx, ""+
		"DECLARE $since_year AS Int32;\n"+
		"$recent = (SELECT author_id, title FROM books WHERE publication_year >= $since_year);\n"+
		"$grouped = (\n"+
		"    SELECT author_id, AGGREGATE_LIST(title, 100u) AS titles\n"+
		"    FROM $recent\n"+
		"    GROUP BY author_id\n"+
		");\n"+
		"SELECT a.author_id, a.name, Yson::SerializeJson(Json::From(g.titles)) AS titles_json\n"+
		"FROM (SELECT author_id, name FROM authors) AS a\n"+
		"JOIN $grouped AS g ON a.author_id = g.author_id\n"+
		"ORDER BY a.author_id;",
		sql.Named("since_year", arg),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	items := []ListAuthorBookTitlesRow(nil)
	for rows.Next() {
		var row ListAuthorBookTitlesRow
		if err := rows.Scan(
			&row.AuthorID,
			&row.Name,
			&row.TitlesJson,
		); err != nil {
			return nil, err
		}
		items = append(items, row)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// -- name: InspectBookText :one
func (q *Queries) InspectBookText(ctx context.Context, arg []byte) (InspectBookTextRow, error) {
	var row InspectBookTextRow
	err := q.db.QueryRowContext(ctx, ""+
		"DECLARE $text AS String;\n"+
		"SELECT\n"+
		"    String::Base32Encode($text) AS base32,\n"+
		"    Unicode::IsAlpha(\"Book\"u) AS alphabetic,\n"+
		"    Url::GetHost(\"https://example.org/books\") AS host,\n"+
		"    Math::Sqrt(9.0) AS square_root,\n"+
		"    Yson::IsString(Yson::From($text)) AS yson_string,\n"+
		"    Pire::Grep(\"book\")($text) AS pattern_found;",
		sql.Named("text", arg),
	).Scan(
		&row.Base32,
		&row.Alphabetic,
		&row.Host,
		&row.SquareRoot,
		&row.YsonString,
		&row.PatternFound,
	)

	return row, err
}
