// Code generated by sqlc. DO NOT EDIT.
package db

type Author struct {
	Author_id uint64 `json:"author_id"`
	Name string `json:"name"`
}

type Book struct {
	Book_id uint64 `json:"book_id"`
	Author_id uint64 `json:"author_id"`
	Isbn string `json:"isbn"`
	Book_type string `json:"book_type"`
	Title string `json:"title"`
	Year uint64 `json:"year"`
	Available *string `json:"available"`
	Tags *string `json:"tags"`
}

