// Code generated by sqlc. DO NOT EDIT.
// source: queries.sql

package db

import (
	"context"

	ydb "github.com/ydb-platform/ydb-go-sdk/v3"
	"github.com/ydb-platform/ydb-go-sdk/v3/pkg/xerrors"
	"github.com/ydb-platform/ydb-go-sdk/v3/query"
)

const getAuthor = `-- name: GetAuthor :one
SELECT * FROM authors
WHERE author_id = $author_id LIMIT 1;`

type GetAuthorParams struct {
	Author_id uint64 `json:"author_id"`
}

func (q *Queries) GetAuthor(ctx context.Context, arg GetAuthorParams, opts ...query.ExecuteOption) (GetAuthorRow, error) {
	parameters := ydb.ParamsBuilder()
	parameters = parameters.Param("$author_id").Uint64(arg.Author_id)
	row, err := q.db.QueryRow(ctx, getAuthor,
		append(opts, query.WithParameters(parameters.Build()))...,
	)
	var i GetAuthorRow
	if err != nil {
		return i, xerrors.WithStackTrace(err)
	}
	err = row.Scan(&i.Author_id, &i.Name)
	if err != nil {
		return i, xerrors.WithStackTrace(err)
	}
	return i, nil
}


const getBook = `-- name: GetBook :one
SELECT * FROM books
WHERE book_id = $book_id LIMIT 1;`

type GetBookParams struct {
	Book_id uint64 `json:"book_id"`
}

func (q *Queries) GetBook(ctx context.Context, arg GetBookParams, opts ...query.ExecuteOption) (GetBookRow, error) {
	parameters := ydb.ParamsBuilder()
	parameters = parameters.Param("$book_id").Uint64(arg.Book_id)
	row, err := q.db.QueryRow(ctx, getBook,
		append(opts, query.WithParameters(parameters.Build()))...,
	)
	var i GetBookRow
	if err != nil {
		return i, xerrors.WithStackTrace(err)
	}
	err = row.Scan(&i.Book_id, &i.Author_id, &i.Isbn, &i.Book_type, &i.Title, &i.Year, &i.Available, &i.Tags)
	if err != nil {
		return i, xerrors.WithStackTrace(err)
	}
	return i, nil
}


const deleteBook = `-- name: DeleteBook :exec
DELETE FROM books
WHERE book_id = $book_id;`

type DeleteBookParams struct {
	Book_id uint64 `json:"book_id"`
}

func (q *Queries) DeleteBook(ctx context.Context, arg DeleteBookParams, opts ...query.ExecuteOption) error {
	parameters := ydb.ParamsBuilder()
	parameters = parameters.Param("$book_id").Uint64(arg.Book_id)
	err := q.db.Exec(ctx, deleteBook,
		append(opts, query.WithParameters(parameters.Build()))...,
	)
	if err != nil {
		return xerrors.WithStackTrace(err)
	}
	return nil
}


const booksByTitleYear = `-- name: BooksByTitleYear :many
SELECT * FROM books
WHERE title = $title AND year = $year;`

type BooksByTitleYearParams struct {
	Title string `json:"title"`
	Year uint64 `json:"year"`
}

func (q *Queries) BooksByTitleYear(ctx context.Context, opts ...query.ExecuteOption) ([]BooksByTitleYearRow, error) {
	result, err := q.db.QueryResultSet(ctx, booksByTitleYear, opts...)
	if err != nil {
		return nil, xerrors.WithStackTrace(err)
	}
	var items []BooksByTitleYearRow
	for row, err := range result.Rows(ctx) {
		if err != nil {
			return nil, xerrors.WithStackTrace(err)
		}
		var i BooksByTitleYearRow
		if err := row.Scan(&i.Book_id, &i.Author_id, &i.Isbn, &i.Book_type, &i.Title, &i.Year, &i.Available, &i.Tags); err != nil {
			return nil, xerrors.WithStackTrace(err)
		}
		items = append(items, i)
	}
	if err := result.Close(ctx); err != nil {
		return nil, xerrors.WithStackTrace(err)
	}
	return items, nil
}


const createAuthor = `-- name: CreateAuthor :one
INSERT INTO authors (name)
VALUES ($name)
RETURNING *;`

type CreateAuthorParams struct {
	Name string `json:"name"`
}

func (q *Queries) CreateAuthor(ctx context.Context, arg CreateAuthorParams, opts ...query.ExecuteOption) (CreateAuthorRow, error) {
	parameters := ydb.ParamsBuilder()
	parameters = parameters.Param("$name").Text(arg.Name)
	row, err := q.db.QueryRow(ctx, createAuthor,
		append(opts, query.WithParameters(parameters.Build()))...,
	)
	var i CreateAuthorRow
	if err != nil {
		return i, xerrors.WithStackTrace(err)
	}
	err = row.Scan(&i.Author_id, &i.Name)
	if err != nil {
		return i, xerrors.WithStackTrace(err)
	}
	return i, nil
}


const createBook = `-- name: CreateBook :one
INSERT INTO books (
    author_id,
    isbn,
    book_type,
    title,
    year,
    available,
    tags
) VALUES (
    $author_id,
    $isbn,
    $book_type,
    $title,
    $year,
    $available,
    $tags
)
RETURNING *;`

type CreateBookParams struct {
	Author_id uint64 `json:"author_id"`
	Isbn string `json:"isbn"`
	Book_type string `json:"book_type"`
	Title string `json:"title"`
	Year uint64 `json:"year"`
	Available *string `json:"available"`
	Tags *string `json:"tags"`
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams, opts ...query.ExecuteOption) (CreateBookRow, error) {
	parameters := ydb.ParamsBuilder()
	parameters = parameters.Param("$author_id").Uint64(arg.Author_id)
	parameters = parameters.Param("$isbn").Text(arg.Isbn)
	parameters = parameters.Param("$book_type").Text(arg.Book_type)
	parameters = parameters.Param("$title").Text(arg.Title)
	parameters = parameters.Param("$year").Uint64(arg.Year)
	parameters = parameters.Param("$available").BeginOptional().Text(arg.Available).EndOptional()
	parameters = parameters.Param("$tags").BeginOptional().Text(arg.Tags).EndOptional()
	row, err := q.db.QueryRow(ctx, createBook,
		append(opts, query.WithParameters(parameters.Build()))...,
	)
	var i CreateBookRow
	if err != nil {
		return i, xerrors.WithStackTrace(err)
	}
	err = row.Scan(&i.Book_id, &i.Author_id, &i.Isbn, &i.Book_type, &i.Title, &i.Year, &i.Available, &i.Tags)
	if err != nil {
		return i, xerrors.WithStackTrace(err)
	}
	return i, nil
}


const updateBook = `-- name: UpdateBook :exec
UPDATE books
SET title = $title, tags = $tags
WHERE book_id = $book_id;`

type UpdateBookParams struct {
	Title string `json:"title"`
	Tags *string `json:"tags"`
	Book_id uint64 `json:"book_id"`
}

func (q *Queries) UpdateBook(ctx context.Context, arg UpdateBookParams, opts ...query.ExecuteOption) error {
	parameters := ydb.ParamsBuilder()
	parameters = parameters.Param("$title").Text(arg.Title)
	parameters = parameters.Param("$tags").BeginOptional().Text(arg.Tags).EndOptional()
	parameters = parameters.Param("$book_id").Uint64(arg.Book_id)
	err := q.db.Exec(ctx, updateBook,
		append(opts, query.WithParameters(parameters.Build()))...,
	)
	if err != nil {
		return xerrors.WithStackTrace(err)
	}
	return nil
}


const updateBookISBN = `-- name: UpdateBookISBN :exec
UPDATE books
SET title = $title, tags = $tags, isbn = $isbn
WHERE book_id = $book_id;`

type UpdateBookISBNParams struct {
	Title string `json:"title"`
	Tags *string `json:"tags"`
	Isbn string `json:"isbn"`
	Book_id uint64 `json:"book_id"`
}

func (q *Queries) UpdateBookISBN(ctx context.Context, arg UpdateBookISBNParams, opts ...query.ExecuteOption) error {
	parameters := ydb.ParamsBuilder()
	parameters = parameters.Param("$title").Text(arg.Title)
	parameters = parameters.Param("$tags").BeginOptional().Text(arg.Tags).EndOptional()
	parameters = parameters.Param("$isbn").Text(arg.Isbn)
	parameters = parameters.Param("$book_id").Uint64(arg.Book_id)
	err := q.db.Exec(ctx, updateBookISBN,
		append(opts, query.WithParameters(parameters.Build()))...,
	)
	if err != nil {
		return xerrors.WithStackTrace(err)
	}
	return nil
}


