// Code generated by sqlc-ydb. DO NOT EDIT.
package sql

import sqlcOverride0 "example.com/sqlc-ydb-examples/type_overrides/domain"

type PutCustomerParams struct {
	ID   sqlcOverride0.CustomerID
	Name sqlcOverride0.CustomerName
	Note *sqlcOverride0.Note
}

type GetCustomerRow struct {
	ID   sqlcOverride0.CustomerID
	Name sqlcOverride0.CustomerName
	Note *sqlcOverride0.Note
}
