// Code generated by sqlc-ydb. DO NOT EDIT.
// source: queries.sql
package sql

import (
	"context"
	"database/sql"

	sqlcOverride0 "example.com/sqlc-ydb-examples/type_overrides/domain"
)

// -- name: PutCustomer :exec
func (q *Queries) PutCustomer(ctx context.Context, arg PutCustomerParams) error {
	_, err := q.db.ExecContext(ctx, ""+
		"UPSERT INTO customers (id, name, note) VALUES ($id, $name, $note);",
		sql.Named("id", uint64(arg.ID)),
		sql.Named("name", string(arg.Name)),
		sql.Named("note", func() *string {
			if arg.Note == nil {
				return nil
			}
			v := string(*arg.Note)
			return &v
		}()),
	)

	return err
}

// -- name: GetCustomer :one
func (q *Queries) GetCustomer(ctx context.Context, arg sqlcOverride0.CustomerID) (GetCustomerRow, error) {
	var row GetCustomerRow
	err := q.db.QueryRowContext(ctx, ""+
		"SELECT id, name, note FROM customers WHERE id = $id;",
		sql.Named("id", uint64(arg)),
	).Scan(
		&row.ID,
		&row.Name,
		&row.Note,
	)

	return row, err
}
