// Code generated by sqlc-ydb. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;
using Dapper;
using Ydb.Sdk.Ado;
using Ydb.Sdk.Value;

namespace Ondeck.Dapper;

public sealed class Queries
{
    private readonly YdbConnection _connection;
    private readonly YdbTransaction? _transaction;

    public Queries(YdbConnection connection, YdbTransaction? transaction = null)
    {
        _connection = connection ?? throw new ArgumentNullException(nameof(connection));
        _transaction = transaction;
    }

    public Queries WithTransaction(YdbTransaction transaction) => new(_connection, transaction ?? throw new ArgumentNullException(nameof(transaction)));

    private const string SqlListCities =
        "-- name: ListCities :many\n" +
        "SELECT slug, name\n" +
        "FROM city\n" +
        "ORDER BY name;";

    public async Task<IReadOnlyList<ListCitiesRow>> ListCitiesAsync(CancellationToken cancellationToken = default)
    {
        var command = new CommandDefinition(SqlListCities, null, _transaction, cancellationToken: cancellationToken);
        await using var reader = await _connection.ExecuteReaderAsync(command).ConfigureAwait(false);
        var rows = new List<ListCitiesRow>();
        while (await reader.ReadAsync(cancellationToken).ConfigureAwait(false))
        {
            rows.Add(ListCitiesRowFrom(reader));
        }
        return rows;
    }

    private static ListCitiesRow ListCitiesRowFrom(DbDataReader reader) => new(
        reader.GetFieldValue<string>(0),
        reader.GetFieldValue<string>(1)
    );

    private const string SqlGetCity =
        "-- name: GetCity :one\n" +
        "DECLARE $slug AS Utf8;\n" +
        "SELECT slug, name\n" +
        "FROM city\n" +
        "WHERE slug = $slug;";

    public async Task<GetCityRow> GetCityAsync(string Slug, CancellationToken cancellationToken = default)
    {
        var command = new CommandDefinition(SqlGetCity, new YdbParameters(new YdbParameter("$slug", DbType.String, Slug)), _transaction, cancellationToken: cancellationToken);
        await using var reader = await _connection.ExecuteReaderAsync(command).ConfigureAwait(false);
        if (!await reader.ReadAsync(cancellationToken).ConfigureAwait(false))
        {
            throw new InvalidOperationException("query returned no rows");
        }
        return GetCityRowFrom(reader);
    }

    private static GetCityRow GetCityRowFrom(DbDataReader reader) => new(
        reader.GetFieldValue<string>(0),
        reader.GetFieldValue<string>(1)
    );

    private const string SqlCreateCity =
        "-- name: CreateCity :one\n" +
        "DECLARE $name AS Utf8;\n" +
        "DECLARE $slug AS Utf8;\n" +
        "INSERT INTO city (\n" +
        "    name,\n" +
        "    slug\n" +
        ") VALUES (\n" +
        "    $name,\n" +
        "    $slug\n" +
        ") RETURNING slug, name;";

    public async Task<CreateCityRow> CreateCityAsync(CreateCityParams args, CancellationToken cancellationToken = default)
    {
        var command = new CommandDefinition(SqlCreateCity, new YdbParameters(new YdbParameter("$name", DbType.String, args.Name), new YdbParameter("$slug", DbType.String, args.Slug)), _transaction, cancellationToken: cancellationToken);
        await using var reader = await _connection.ExecuteReaderAsync(command).ConfigureAwait(false);
        if (!await reader.ReadAsync(cancellationToken).ConfigureAwait(false))
        {
            throw new InvalidOperationException("query returned no rows");
        }
        return CreateCityRowFrom(reader);
    }

    private static CreateCityRow CreateCityRowFrom(DbDataReader reader) => new(
        reader.GetFieldValue<string>(0),
        reader.GetFieldValue<string>(1)
    );

    private const string SqlUpdateCityName =
        "-- name: UpdateCityName :exec\n" +
        "DECLARE $name AS Utf8;\n" +
        "DECLARE $slug AS Utf8;\n" +
        "UPDATE city\n" +
        "SET name = $name\n" +
        "WHERE slug = $slug;";

    public async Task UpdateCityNameAsync(UpdateCityNameParams args, CancellationToken cancellationToken = default)
    {
        var command = new CommandDefinition(SqlUpdateCityName, new YdbParameters(new YdbParameter("$name", DbType.String, args.Name), new YdbParameter("$slug", DbType.String, args.Slug)), _transaction, cancellationToken: cancellationToken);
        await _connection.ExecuteAsync(command).ConfigureAwait(false);
    }

    private const string SqlListVenues =
        "-- name: ListVenues :many\n" +
        "DECLARE $city AS Utf8;\n" +
        "SELECT id, slug, name, city, status, statuses, spotify_playlist, songkick_id, tags, created_at\n" +
        "FROM venue\n" +
        "WHERE city = $city\n" +
        "ORDER BY name;";

    public async Task<IReadOnlyList<ListVenuesRow>> ListVenuesAsync(string City, CancellationToken cancellationToken = default)
    {
        var command = new CommandDefinition(SqlListVenues, new YdbParameters(new YdbParameter("$city", DbType.String, City)), _transaction, cancellationToken: cancellationToken);
        await using var reader = await _connection.ExecuteReaderAsync(command).ConfigureAwait(false);
        var rows = new List<ListVenuesRow>();
        while (await reader.ReadAsync(cancellationToken).ConfigureAwait(false))
        {
            rows.Add(ListVenuesRowFrom(reader));
        }
        return rows;
    }

    private static ListVenuesRow ListVenuesRowFrom(DbDataReader reader) => new(
        reader.GetFieldValue<ulong>(0),
        reader.GetFieldValue<string>(1),
        reader.GetFieldValue<string>(2),
        reader.GetFieldValue<string>(3),
        reader.GetFieldValue<string>(4),
        reader.IsDBNull(5) ? null : reader.GetFieldValue<string>(5),
        reader.GetFieldValue<string>(6),
        reader.IsDBNull(7) ? null : reader.GetFieldValue<string>(7),
        reader.IsDBNull(8) ? null : reader.GetFieldValue<string>(8),
        reader.IsDBNull(9) ? null : reader.GetFieldValue<DateTime>(9)
    );

    private const string SqlDeleteVenue =
        "-- name: DeleteVenue :exec\n" +
        "DECLARE $slug AS Utf8;\n" +
        "DELETE FROM venue\n" +
        "WHERE slug = $slug AND slug = $slug;";

    public async Task DeleteVenueAsync(string Slug, CancellationToken cancellationToken = default)
    {
        var command = new CommandDefinition(SqlDeleteVenue, new YdbParameters(new YdbParameter("$slug", DbType.String, Slug)), _transaction, cancellationToken: cancellationToken);
        await _connection.ExecuteAsync(command).ConfigureAwait(false);
    }

    private const string SqlGetVenue =
        "-- name: GetVenue :one\n" +
        "DECLARE $slug AS Utf8;\n" +
        "DECLARE $city AS Utf8;\n" +
        "SELECT id, slug, name, city, status, statuses, spotify_playlist, songkick_id, tags, created_at\n" +
        "FROM venue\n" +
        "WHERE slug = $slug AND city = $city;";

    public async Task<GetVenueRow> GetVenueAsync(GetVenueParams args, CancellationToken cancellationToken = default)
    {
        var command = new CommandDefinition(SqlGetVenue, new YdbParameters(new YdbParameter("$slug", DbType.String, args.Slug), new YdbParameter("$city", DbType.String, args.City)), _transaction, cancellationToken: cancellationToken);
        await using var reader = await _connection.ExecuteReaderAsync(command).ConfigureAwait(false);
        if (!await reader.ReadAsync(cancellationToken).ConfigureAwait(false))
        {
            throw new InvalidOperationException("query returned no rows");
        }
        return GetVenueRowFrom(reader);
    }

    private static GetVenueRow GetVenueRowFrom(DbDataReader reader) => new(
        reader.GetFieldValue<ulong>(0),
        reader.GetFieldValue<string>(1),
        reader.GetFieldValue<string>(2),
        reader.GetFieldValue<string>(3),
        reader.GetFieldValue<string>(4),
        reader.IsDBNull(5) ? null : reader.GetFieldValue<string>(5),
        reader.GetFieldValue<string>(6),
        reader.IsDBNull(7) ? null : reader.GetFieldValue<string>(7),
        reader.IsDBNull(8) ? null : reader.GetFieldValue<string>(8),
        reader.IsDBNull(9) ? null : reader.GetFieldValue<DateTime>(9)
    );

    private const string SqlCreateVenue =
        "-- name: CreateVenue :one\n" +
        "DECLARE $id AS Uint64;\n" +
        "DECLARE $slug AS Utf8;\n" +
        "DECLARE $name AS Utf8;\n" +
        "DECLARE $city AS Utf8;\n" +
        "DECLARE $created_at AS Optional<Timestamp>;\n" +
        "DECLARE $spotify_playlist AS Utf8;\n" +
        "DECLARE $status AS Utf8;\n" +
        "DECLARE $statuses AS Optional<Json>;\n" +
        "DECLARE $tags AS Optional<Json>;\n" +
        "INSERT INTO venue (\n" +
        "    id,\n" +
        "    slug,\n" +
        "    name,\n" +
        "    city,\n" +
        "    created_at,\n" +
        "    spotify_playlist,\n" +
        "    status,\n" +
        "    statuses,\n" +
        "    tags\n" +
        ") VALUES (\n" +
        "    $id,\n" +
        "    $slug,\n" +
        "    $name,\n" +
        "    $city,\n" +
        "    $created_at,\n" +
        "    $spotify_playlist,\n" +
        "    $status,\n" +
        "    $statuses,\n" +
        "    $tags\n" +
        ") RETURNING id;";

    public async Task<CreateVenueRow> CreateVenueAsync(CreateVenueParams args, CancellationToken cancellationToken = default)
    {
        var command = new CommandDefinition(SqlCreateVenue, new YdbParameters(new YdbParameter("$id", DbType.UInt64, args.ID), new YdbParameter("$slug", DbType.String, args.Slug), new YdbParameter("$name", DbType.String, args.Name), new YdbParameter("$city", DbType.String, args.City), new YdbParameter("$created_at", YdbValue.MakeOptionalTimestamp(args.CreatedAt)), new YdbParameter("$spotify_playlist", DbType.String, args.SpotifyPlaylist), new YdbParameter("$status", DbType.String, args.Status), new YdbParameter("$statuses", YdbValue.MakeOptionalJson(args.Statuses)), new YdbParameter("$tags", YdbValue.MakeOptionalJson(args.Tags))), _transaction, cancellationToken: cancellationToken);
        await using var reader = await _connection.ExecuteReaderAsync(command).ConfigureAwait(false);
        if (!await reader.ReadAsync(cancellationToken).ConfigureAwait(false))
        {
            throw new InvalidOperationException("query returned no rows");
        }
        return CreateVenueRowFrom(reader);
    }

    private static CreateVenueRow CreateVenueRowFrom(DbDataReader reader) => new(
        reader.GetFieldValue<ulong>(0)
    );

    private const string SqlUpdateVenueName =
        "-- name: UpdateVenueName :one\n" +
        "DECLARE $name AS Utf8;\n" +
        "DECLARE $slug AS Utf8;\n" +
        "UPDATE venue\n" +
        "SET name = $name\n" +
        "WHERE slug = $slug\n" +
        "RETURNING id;";

    public async Task<UpdateVenueNameRow> UpdateVenueNameAsync(UpdateVenueNameParams args, CancellationToken cancellationToken = default)
    {
        var command = new CommandDefinition(SqlUpdateVenueName, new YdbParameters(new YdbParameter("$name", DbType.String, args.Name), new YdbParameter("$slug", DbType.String, args.Slug)), _transaction, cancellationToken: cancellationToken);
        await using var reader = await _connection.ExecuteReaderAsync(command).ConfigureAwait(false);
        if (!await reader.ReadAsync(cancellationToken).ConfigureAwait(false))
        {
            throw new InvalidOperationException("query returned no rows");
        }
        return UpdateVenueNameRowFrom(reader);
    }

    private static UpdateVenueNameRow UpdateVenueNameRowFrom(DbDataReader reader) => new(
        reader.GetFieldValue<ulong>(0)
    );

    private const string SqlVenueCountByCity =
        "-- name: VenueCountByCity :many\n" +
        "SELECT\n" +
        "    city,\n" +
        "    COUNT(*) AS venue_count\n" +
        "FROM venue\n" +
        "GROUP BY city\n" +
        "ORDER BY city;";

    public async Task<IReadOnlyList<VenueCountByCityRow>> VenueCountByCityAsync(CancellationToken cancellationToken = default)
    {
        var command = new CommandDefinition(SqlVenueCountByCity, null, _transaction, cancellationToken: cancellationToken);
        await using var reader = await _connection.ExecuteReaderAsync(command).ConfigureAwait(false);
        var rows = new List<VenueCountByCityRow>();
        while (await reader.ReadAsync(cancellationToken).ConfigureAwait(false))
        {
            rows.Add(VenueCountByCityRowFrom(reader));
        }
        return rows;
    }

    private static VenueCountByCityRow VenueCountByCityRowFrom(DbDataReader reader) => new(
        reader.GetFieldValue<string>(0),
        reader.GetFieldValue<ulong>(1)
    );

    private sealed class YdbParameters : SqlMapper.IDynamicParameters
    {
        private readonly YdbParameter[] _parameters;

        public YdbParameters(params YdbParameter[] parameters) => _parameters = parameters;

        public void AddParameters(IDbCommand command, SqlMapper.Identity identity)
        {
            foreach (var parameter in _parameters)
            {
                command.Parameters.Add(parameter);
            }
        }
    }
}
