# Code generated by sqlc. DO NOT EDIT.
# source: queries.sql
from typing import Iterator, Optional

import ydb

from db import models

GET_AUTHOR = """
-- name: GetAuthor :one
SELECT * FROM authors
WHERE id = $id LIMIT 1;"""

# params: $id


LIST_AUTHORS = """
-- name: ListAuthors :many
SELECT * FROM authors
ORDER BY name;"""


CREATE_AUTHOR = """
-- name: CreateAuthor :one
INSERT INTO authors (name)
VALUES ($name)
RETURNING *;"""

# params: $name


GET_ALBUM = """
-- name: GetAlbum :one
SELECT * FROM albums
WHERE id = $id LIMIT 1;"""

# params: $id


LIST_ALBUMS_BY_AUTHOR = """
-- name: ListAlbumsByAuthor :many
SELECT * FROM albums
WHERE author_id = $author_id
ORDER BY title;"""

# params: $author_id


CREATE_ALBUM = """
-- name: CreateAlbum :one
INSERT INTO albums (title, author_id)
VALUES ($title, $author_id)
RETURNING *;"""

# params: $title, $author_id


DELETE_ALBUM = """
-- name: DeleteAlbum :exec
DELETE FROM albums
WHERE id = $id;"""

# params: $id



class Querier:
    def __init__(self, pool: ydb.QuerySessionPool):
        self._pool = pool

    def get_author(self, *, id: int) -> Optional[models.GetAuthorRow]:
        result_sets = self._pool.execute_with_retries(GET_AUTHOR, parameters={"$id": id})
        if not result_sets or not result_sets[0].rows:
            return None
        row = result_sets[0].rows[0]
        return models.GetAuthorRow(
            id=row.id,
            name=row.name
        )

    def list_authors(self) -> Iterator[models.ListAuthorsRow]:
        result_sets = self._pool.execute_with_retries(LIST_AUTHORS, parameters={})
        for row in result_sets[0].rows:
            yield models.ListAuthorsRow(
                id=row.id,
                name=row.name
            )

    def create_author(self, *, name: str) -> Optional[models.CreateAuthorRow]:
        result_sets = self._pool.execute_with_retries(CREATE_AUTHOR, parameters={"$name": name})
        if not result_sets or not result_sets[0].rows:
            return None
        row = result_sets[0].rows[0]
        return models.CreateAuthorRow(
            id=row.id,
            name=row.name
        )

    def get_album(self, *, id: int) -> Optional[models.GetAlbumRow]:
        result_sets = self._pool.execute_with_retries(GET_ALBUM, parameters={"$id": id})
        if not result_sets or not result_sets[0].rows:
            return None
        row = result_sets[0].rows[0]
        return models.GetAlbumRow(
            id=row.id,
            title=row.title,
            author_id=row.author_id
        )

    def list_albums_by_author(self, *, author_id: int) -> Iterator[models.ListAlbumsByAuthorRow]:
        result_sets = self._pool.execute_with_retries(LIST_ALBUMS_BY_AUTHOR, parameters={"$author_id": author_id})
        for row in result_sets[0].rows:
            yield models.ListAlbumsByAuthorRow(
                id=row.id,
                title=row.title,
                author_id=row.author_id
            )

    def create_album(self, *, title: str, *, author_id: int) -> Optional[models.CreateAlbumRow]:
        result_sets = self._pool.execute_with_retries(CREATE_ALBUM, parameters={"$title": title, "$author_id": author_id})
        if not result_sets or not result_sets[0].rows:
            return None
        row = result_sets[0].rows[0]
        return models.CreateAlbumRow(
            id=row.id,
            title=row.title,
            author_id=row.author_id
        )

    def delete_album(self, *, id: int) -> None:
        self._pool.execute_with_retries(DELETE_ALBUM, parameters={"$id": id})

