// Code generated by sqlc-ydb. DO NOT EDIT.
package namespaces.jooq;

import org.jooq.types.ULong;

import org.jooq.Record;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;
import tech.ydb.jooq.YdbTypes;

import static org.jooq.impl.DSL.name;

public final class Tables {
    private Tables() {}

    public static final LocalSqlcNamespacesAUsersTable LOCAL_SQLC_NAMESPACES_A_USERS = new LocalSqlcNamespacesAUsersTable("/local/sqlc_namespaces/a/users", null);

    public static final class LocalSqlcNamespacesAUsersTable extends TableImpl<Record> {
        public final TableField<Record, ULong> ID = createField(name("id"), YdbTypes.UINT64.nullable(false), this);
        public final TableField<Record, String> NAME = createField(name("name"), YdbTypes.UTF8.nullable(false), this);

        private LocalSqlcNamespacesAUsersTable(String name, Table<Record> aliased) {
            super(name(name), null, aliased);
        }

        @Override
        public LocalSqlcNamespacesAUsersTable as(String alias) {
            return new LocalSqlcNamespacesAUsersTable(alias, this);
        }
    }

    public static final LocalSqlcNamespacesBUsersTable LOCAL_SQLC_NAMESPACES_B_USERS = new LocalSqlcNamespacesBUsersTable("/local/sqlc_namespaces/b/users", null);

    public static final class LocalSqlcNamespacesBUsersTable extends TableImpl<Record> {
        public final TableField<Record, ULong> ID = createField(name("id"), YdbTypes.UINT64.nullable(false), this);
        public final TableField<Record, String> NAME = createField(name("name"), YdbTypes.UTF8.nullable(false), this);

        private LocalSqlcNamespacesBUsersTable(String name, Table<Record> aliased) {
            super(name(name), null, aliased);
        }

        @Override
        public LocalSqlcNamespacesBUsersTable as(String alias) {
            return new LocalSqlcNamespacesBUsersTable(alias, this);
        }
    }
}
