// Code generated by sqlc-ydb. DO NOT EDIT.

use super::models::*;

#[derive(Default)]
struct JsonParam(String);

impl From<JsonParam> for ydb::Value {
    fn from(value: JsonParam) -> Self {
        ydb::Value::Json(value.0)
    }
}

pub struct Queries<'a> {
    client: &'a mut ydb::QueryClient,
}

impl<'a> Queries<'a> {
    pub fn new(client: &'a mut ydb::QueryClient) -> Self {
        Self { client }
    }

    pub async fn author(&mut self, author_id: u64) -> ydb::YdbResult<GetAuthorRow> {
        let mut row = self
            .client
            .query_row(concat!(
                concat!(r"-- name: GetAuthor :one", "\x0a"),
                concat!(r"SELECT author_id, name, biography FROM authors", "\x0a"),
                r"WHERE author_id = $author_id;",
            ))
            .param("$author_id", author_id)
            .await?;
        Ok(GetAuthorRow {
            author_id: row.remove_field(0)?.try_into()?,
            name: row.remove_field(1)?.try_into()?,
            biography: row.remove_field(2)?.try_into()?,
        })
    }

    pub async fn delete_book_exec_result(&mut self, book_id: u64) -> ydb::YdbResult<()> {
        self.client
            .exec(concat!(
                concat!(r"-- name: DeleteBookExecResult :exec", "\x0a"),
                concat!(r"DELETE FROM books", "\x0a"),
                r"WHERE book_id = $book_id;",
            ))
            .param("$book_id", book_id)
            .await
    }

    pub async fn delete_book(&mut self, book_id: u64) -> ydb::YdbResult<()> {
        self.client
            .exec(concat!(
                concat!(r"-- name: DeleteBook :exec", "\x0a"),
                concat!(r"DELETE FROM books", "\x0a"),
                r"WHERE book_id = $book_id;",
            ))
            .param("$book_id", book_id)
            .await
    }

    pub async fn delete_book_named_func(&mut self, book_id: u64) -> ydb::YdbResult<()> {
        self.client
            .exec(concat!(
                concat!(r"-- name: DeleteBookNamedFunc :exec", "\x0a"),
                concat!(r"DELETE FROM books", "\x0a"),
                r"WHERE book_id = $book_id;",
            ))
            .param("$book_id", book_id)
            .await
    }

    pub async fn delete_book_named_sign(&mut self, book_id: u64) -> ydb::YdbResult<()> {
        self.client
            .exec(concat!(
                concat!(r"-- name: DeleteBookNamedSign :exec", "\x0a"),
                concat!(r"DELETE FROM books", "\x0a"),
                r"WHERE book_id = $book_id;",
            ))
            .param("$book_id", book_id)
            .await
    }

    pub async fn books_by_year(&mut self, year: i32) -> ydb::YdbResult<Vec<BooksByYearRow>> {
        let result_set = self
            .client
            .query_result_set(concat!(
                concat!(r"-- name: BooksByYear :many", "\x0a"),
                concat!(
                    r"SELECT book_id, author_id, isbn, book_type, title, year, available, tags",
                    "\x0a"
                ),
                concat!(r"FROM books", "\x0a"),
                r"WHERE year = $year;",
            ))
            .param("$year", year)
            .await?;
        let mut rows = Vec::new();
        for mut row in result_set.rows() {
            rows.push(BooksByYearRow {
                book_id: row.remove_field(0)?.try_into()?,
                author_id: row.remove_field(1)?.try_into()?,
                isbn: row.remove_field(2)?.try_into()?,
                book_type: row.remove_field(3)?.try_into()?,
                title: row.remove_field(4)?.try_into()?,
                year: row.remove_field(5)?.try_into()?,
                available: row.remove_field(6)?.try_into()?,
                tags: row.remove_field(7)?.try_into()?,
            });
        }
        Ok(rows)
    }

    pub async fn create_author(
        &mut self,
        author_id: u64,
        name: String,
        biography: Option<String>,
    ) -> ydb::YdbResult<CreateAuthorRow> {
        let mut row = self
            .client
            .query_row(concat!(
                concat!(r"-- name: CreateAuthor :one", "\x0a"),
                concat!(r"INSERT INTO authors (author_id, name, biography)", "\x0a"),
                concat!(r"VALUES ($author_id, $name, $biography)", "\x0a"),
                r"RETURNING author_id, name, biography;",
            ))
            .param("$author_id", author_id)
            .param("$name", name)
            .param("$biography", biography.map(JsonParam))
            .await?;
        Ok(CreateAuthorRow {
            author_id: row.remove_field(0)?.try_into()?,
            name: row.remove_field(1)?.try_into()?,
            biography: row.remove_field(2)?.try_into()?,
        })
    }

    pub async fn create_book(
        &mut self,
        book_id: u64,
        author_id: u64,
        isbn: String,
        book_type: String,
        title: String,
        year: i32,
        available: std::time::SystemTime,
        tags: String,
    ) -> ydb::YdbResult<CreateBookRow> {
        let mut row = self
            .client
            .query_row(concat!(
                concat!(r"-- name: CreateBook :one", "\x0a"),
                concat!(r"INSERT INTO books (book_id, author_id, isbn, book_type, title, year, available, tags)", "\x0a"),
                concat!(r"VALUES ($book_id, $author_id, $isbn, $book_type, $title, $year, $available, $tags)", "\x0a"),
                r"RETURNING book_id, author_id, isbn, book_type, title, year, available, tags;",
            ))
            .param("$book_id", book_id)
            .param("$author_id", author_id)
            .param("$isbn", isbn)
            .param("$book_type", book_type)
            .param("$title", title)
            .param("$year", year)
            .param("$available", ydb::Value::Timestamp(available))
            .param("$tags", JsonParam(tags)).await?;
        Ok(CreateBookRow {
            book_id: row.remove_field(0)?.try_into()?,
            author_id: row.remove_field(1)?.try_into()?,
            isbn: row.remove_field(2)?.try_into()?,
            book_type: row.remove_field(3)?.try_into()?,
            title: row.remove_field(4)?.try_into()?,
            year: row.remove_field(5)?.try_into()?,
            available: row.remove_field(6)?.try_into()?,
            tags: row.remove_field(7)?.try_into()?,
        })
    }

    pub async fn update_book(
        &mut self,
        title: String,
        tags: String,
        book_id: u64,
    ) -> ydb::YdbResult<()> {
        self.client
            .exec(concat!(
                concat!(r"-- name: UpdateBook :exec", "\x0a"),
                concat!(r"UPDATE books", "\x0a"),
                concat!(r"SET title = $title, tags = $tags", "\x0a"),
                r"WHERE book_id = $book_id;",
            ))
            .param("$title", title)
            .param("$tags", JsonParam(tags))
            .param("$book_id", book_id)
            .await
    }

    pub async fn biography(&mut self, author_id: u64) -> ydb::YdbResult<GetBiographyRow> {
        let mut row = self
            .client
            .query_row(concat!(
                concat!(r"-- name: GetBiography :one", "\x0a"),
                concat!(r"SELECT biography FROM authors", "\x0a"),
                r"WHERE author_id = $author_id;",
            ))
            .param("$author_id", author_id)
            .await?;
        Ok(GetBiographyRow {
            biography: row.remove_field(0)?.try_into()?,
        })
    }
}
