// Code generated by sqlc-ydb. DO NOT EDIT.
// source: city.sql
package ondeck

import (
	"context"
	"database/sql"
)

const queryListCities = `-- name: ListCities :many
SELECT slug, name
FROM city
ORDER BY name;`

func (q *Queries) ListCities(ctx context.Context) ([]ListCitiesRow, error) {
	rows, err := q.db.QueryContext(ctx, queryListCities)
	if err != nil {
		return []ListCitiesRow(nil), err
	}
	defer rows.Close()
	items := []ListCitiesRow(nil)
	for rows.Next() {
		var row ListCitiesRow
		if err := rows.Scan(&row.Slug, &row.Name); err != nil {
			return nil, err
		}
		items = append(items, row)
	}
	return items, rows.Err()
}

const queryGetCity = `-- name: GetCity :one
DECLARE $slug AS Utf8;
SELECT slug, name
FROM city
WHERE slug = $slug;`

func (q *Queries) GetCity(ctx context.Context, arg string) (GetCityRow, error) {
	var row GetCityRow
	err := q.db.QueryRowContext(ctx, queryGetCity, sql.Named("slug", arg)).Scan(&row.Slug, &row.Name)
	return row, err
}

const queryCreateCity = `-- name: CreateCity :one
DECLARE $name AS Utf8;
DECLARE $slug AS Utf8;
INSERT INTO city (
    name,
    slug
) VALUES (
    $name,
    $slug
) RETURNING slug, name;`

func (q *Queries) CreateCity(ctx context.Context, arg CreateCityParams) (CreateCityRow, error) {
	var row CreateCityRow
	err := q.db.QueryRowContext(ctx, queryCreateCity, sql.Named("name", arg.Name), sql.Named("slug", arg.Slug)).Scan(&row.Slug, &row.Name)
	return row, err
}

const queryUpdateCityName = `-- name: UpdateCityName :exec
DECLARE $name AS Utf8;
DECLARE $slug AS Utf8;
UPDATE city
SET name = $name
WHERE slug = $slug;`

func (q *Queries) UpdateCityName(ctx context.Context, arg UpdateCityNameParams) error {
	_, err := q.db.ExecContext(ctx, queryUpdateCityName, sql.Named("name", arg.Name), sql.Named("slug", arg.Slug))
	return err
}
