// Code generated by sqlc-ydb. DO NOT EDIT.
import { Int32, Json, Primitive, TimestampType, Uint64, Utf8 } from "@ydbjs/value/primitive";

export const GET_AUTHOR_SQL = `-- name: GetAuthor :one
DECLARE $author_id AS Uint64;
SELECT author_id, name
FROM authors
WHERE author_id = $author_id;`;
const _GET_AUTHOR_SQL_EXEC = `-- name: GetAuthor :one
\x20\x20\x20
SELECT author_id, name
FROM authors
WHERE author_id = $author_id;`;

export const GET_BOOK_SQL = `-- name: GetBook :one
DECLARE $book_id AS Uint64;
SELECT book_id, author_id, isbn, book_type, title, publication_year, available, tags
FROM books
WHERE book_id = $book_id;`;
const _GET_BOOK_SQL_EXEC = `-- name: GetBook :one
\x20\x20\x20
SELECT book_id, author_id, isbn, book_type, title, publication_year, available, tags
FROM books
WHERE book_id = $book_id;`;

export const DELETE_BOOK_SQL = `-- name: DeleteBook :exec
DECLARE $book_id AS Uint64;
DELETE FROM books
WHERE book_id = $book_id;`;
const _DELETE_BOOK_SQL_EXEC = `-- name: DeleteBook :exec
\x20\x20\x20
DELETE FROM books
WHERE book_id = $book_id;`;

export const BOOKS_BY_TITLE_YEAR_SQL = `-- name: BooksByTitleYear :many
DECLARE $title AS Utf8;
DECLARE $publication_year AS Int32;
SELECT book_id, author_id, isbn, book_type, title, publication_year, available, tags
FROM books
WHERE title = $title AND publication_year = $publication_year;`;
const _BOOKS_BY_TITLE_YEAR_SQL_EXEC = `-- name: BooksByTitleYear :many
\x20\x20\x20
\x20\x20\x20
SELECT book_id, author_id, isbn, book_type, title, publication_year, available, tags
FROM books
WHERE title = $title AND publication_year = $publication_year;`;

export const BOOKS_BY_TAGS_SQL = `-- name: BooksByTags :many
DECLARE $tags AS Json;
SELECT
    b.book_id,
    b.title,
    a.name,
    b.isbn,
    b.tags
FROM books AS b
LEFT JOIN authors AS a ON b.author_id = a.author_id
WHERE NOT SetIsDisjoint(
    ToSet(Yson::ConvertToStringList(b.tags)),
    Yson::ConvertToStringList($tags)
);`;
const _BOOKS_BY_TAGS_SQL_EXEC = `-- name: BooksByTags :many
\x20\x20\x20
SELECT
    b.book_id,
    b.title,
    a.name,
    b.isbn,
    b.tags
FROM books AS b
LEFT JOIN authors AS a ON b.author_id = a.author_id
WHERE NOT SetIsDisjoint(
    ToSet(Yson::ConvertToStringList(b.tags)),
    Yson::ConvertToStringList($tags)
);`;

export const CREATE_AUTHOR_SQL = `-- name: CreateAuthor :one
DECLARE $author_id AS Uint64;
DECLARE $name AS Utf8;
INSERT INTO authors (author_id, name)
VALUES ($author_id, $name)
RETURNING author_id, name;`;
const _CREATE_AUTHOR_SQL_EXEC = `-- name: CreateAuthor :one
\x20\x20\x20
\x20\x20\x20
INSERT INTO authors (author_id, name)
VALUES ($author_id, $name)
RETURNING author_id, name;`;

export const CREATE_BOOK_SQL = `-- name: CreateBook :one
DECLARE $book_id AS Uint64;
DECLARE $author_id AS Uint64;
DECLARE $isbn AS Utf8;
DECLARE $book_type AS Utf8;
DECLARE $title AS Utf8;
DECLARE $publication_year AS Int32;
DECLARE $available AS Timestamp;
DECLARE $tags AS Json;
INSERT INTO books (
    book_id,
    author_id,
    isbn,
    book_type,
    title,
    publication_year,
    available,
    tags
) VALUES (
    $book_id,
    $author_id,
    $isbn,
    $book_type,
    $title,
    $publication_year,
    $available,
    $tags
)
RETURNING book_id, author_id, isbn, book_type, title, publication_year, available, tags;`;
const _CREATE_BOOK_SQL_EXEC = `-- name: CreateBook :one
\x20\x20\x20
\x20\x20\x20
\x20\x20\x20
\x20\x20\x20
\x20\x20\x20
\x20\x20\x20
\x20\x20\x20
\x20\x20\x20
INSERT INTO books (
    book_id,
    author_id,
    isbn,
    book_type,
    title,
    publication_year,
    available,
    tags
) VALUES (
    $book_id,
    $author_id,
    $isbn,
    $book_type,
    $title,
    $publication_year,
    $available,
    $tags
)
RETURNING book_id, author_id, isbn, book_type, title, publication_year, available, tags;`;

export const UPDATE_BOOK_SQL = `-- name: UpdateBook :exec
DECLARE $book_id AS Uint64;
DECLARE $title AS Utf8;
DECLARE $tags AS Json;
UPDATE books
SET title = $title, tags = $tags
WHERE book_id = $book_id;`;
const _UPDATE_BOOK_SQL_EXEC = `-- name: UpdateBook :exec
\x20\x20\x20
\x20\x20\x20
\x20\x20\x20
UPDATE books
SET title = $title, tags = $tags
WHERE book_id = $book_id;`;

export const UPDATE_BOOK_ISBN_SQL = `-- name: UpdateBookISBN :exec
DECLARE $book_id AS Uint64;
DECLARE $title AS Utf8;
DECLARE $tags AS Json;
DECLARE $isbn AS Utf8;
UPDATE books
SET title = $title, tags = $tags, isbn = $isbn
WHERE book_id = $book_id;`;
const _UPDATE_BOOK_ISBN_SQL_EXEC = `-- name: UpdateBookISBN :exec
\x20\x20\x20
\x20\x20\x20
\x20\x20\x20
\x20\x20\x20
UPDATE books
SET title = $title, tags = $tags, isbn = $isbn
WHERE book_id = $book_id;`;

export const DELETE_AUTHOR_BEFORE_YEAR_SQL = `-- name: DeleteAuthorBeforeYear :exec
DECLARE $author_id AS Uint64;
DECLARE $publication_year AS Int32;
DELETE FROM books
WHERE publication_year < $publication_year AND author_id = $author_id;`;
const _DELETE_AUTHOR_BEFORE_YEAR_SQL_EXEC = `-- name: DeleteAuthorBeforeYear :exec
\x20\x20\x20
\x20\x20\x20
DELETE FROM books
WHERE publication_year < $publication_year AND author_id = $author_id;`;

export const SAY_HELLO_SQL = `-- name: SayHello :one
DECLARE $name AS Utf8;
SELECT "hello "u || $name AS greeting;`;
const _SAY_HELLO_SQL_EXEC = `-- name: SayHello :one
\x20\x20\x20
SELECT "hello "u || $name AS greeting;`;

function _int32(value, name) { if (!Number.isInteger(value) || value < -2147483648 || value > 2147483647) throw new RangeError(`${name} is outside YQL Int32 range`); return value; }
function _uint64(value, name) { if (typeof value !== "bigint" || value < 0n || value > 18446744073709551615n) throw new RangeError(`${name} is outside YQL Uint64 range`); return value; }
function _string(value, name) { if (typeof value !== "string") throw new TypeError(`${name} must be a string`); return value; }
function _timestamp(value, name) { if (typeof value !== "bigint" || value < 0n || value > 4291747199999999n) throw new RangeError(`${name} is outside YQL Timestamp microsecond range`); return value; }
function _json(value, name) { if (typeof value !== "string") throw new TypeError(`${name} must be JSON text`); try { JSON.parse(value); } catch (error) { throw new TypeError(`${name} must contain valid JSON`, { cause: error }); } return value; }

function _rawValue(value, name, expectedCase) { if (value === null || typeof value !== "object" || value.value?.case !== expectedCase) throw new TypeError(`${name} has an unexpected YDB value shape`); return value.value.value; }
function _rawOptional(value, name, read) { if (value === null || typeof value !== "object") throw new TypeError(`${name} has an unexpected YDB Optional shape`); return value.value?.case === "nullFlagValue" ? null : read(value); }

function _decodeGetAuthorRow(row) {
  if (row === null || typeof row !== "object" || Array.isArray(row)) throw new TypeError("GetAuthor: expected an object row");
  if (!Object.hasOwn(row, "author_id")) throw new TypeError("GetAuthor: result row is missing column author_id");
  if (!Object.hasOwn(row, "name")) throw new TypeError("GetAuthor: result row is missing column name");
  return {
    authorId: row["author_id"],
    name: row["name"],
  };
}

function _decodeGetBookRow(row) {
  if (row === null || typeof row !== "object" || Array.isArray(row)) throw new TypeError("GetBook: expected an object row");
  if (!Object.hasOwn(row, "book_id")) throw new TypeError("GetBook: result row is missing column book_id");
  if (!Object.hasOwn(row, "author_id")) throw new TypeError("GetBook: result row is missing column author_id");
  if (!Object.hasOwn(row, "isbn")) throw new TypeError("GetBook: result row is missing column isbn");
  if (!Object.hasOwn(row, "book_type")) throw new TypeError("GetBook: result row is missing column book_type");
  if (!Object.hasOwn(row, "title")) throw new TypeError("GetBook: result row is missing column title");
  if (!Object.hasOwn(row, "publication_year")) throw new TypeError("GetBook: result row is missing column publication_year");
  if (!Object.hasOwn(row, "available")) throw new TypeError("GetBook: result row is missing column available");
  if (!Object.hasOwn(row, "tags")) throw new TypeError("GetBook: result row is missing column tags");
  return {
    bookId: _rawValue(row["book_id"], "GetBook.book_id", "uint64Value"),
    authorId: _rawValue(row["author_id"], "GetBook.author_id", "uint64Value"),
    isbn: _rawValue(row["isbn"], "GetBook.isbn", "textValue"),
    bookType: _rawValue(row["book_type"], "GetBook.book_type", "textValue"),
    title: _rawValue(row["title"], "GetBook.title", "textValue"),
    publicationYear: _rawValue(row["publication_year"], "GetBook.publication_year", "int32Value"),
    available: _rawValue(row["available"], "GetBook.available", "uint64Value"),
    tags: _rawValue(row["tags"], "GetBook.tags", "textValue"),
  };
}

function _decodeBooksByTitleYearRow(row) {
  if (row === null || typeof row !== "object" || Array.isArray(row)) throw new TypeError("BooksByTitleYear: expected an object row");
  if (!Object.hasOwn(row, "book_id")) throw new TypeError("BooksByTitleYear: result row is missing column book_id");
  if (!Object.hasOwn(row, "author_id")) throw new TypeError("BooksByTitleYear: result row is missing column author_id");
  if (!Object.hasOwn(row, "isbn")) throw new TypeError("BooksByTitleYear: result row is missing column isbn");
  if (!Object.hasOwn(row, "book_type")) throw new TypeError("BooksByTitleYear: result row is missing column book_type");
  if (!Object.hasOwn(row, "title")) throw new TypeError("BooksByTitleYear: result row is missing column title");
  if (!Object.hasOwn(row, "publication_year")) throw new TypeError("BooksByTitleYear: result row is missing column publication_year");
  if (!Object.hasOwn(row, "available")) throw new TypeError("BooksByTitleYear: result row is missing column available");
  if (!Object.hasOwn(row, "tags")) throw new TypeError("BooksByTitleYear: result row is missing column tags");
  return {
    bookId: _rawValue(row["book_id"], "BooksByTitleYear.book_id", "uint64Value"),
    authorId: _rawValue(row["author_id"], "BooksByTitleYear.author_id", "uint64Value"),
    isbn: _rawValue(row["isbn"], "BooksByTitleYear.isbn", "textValue"),
    bookType: _rawValue(row["book_type"], "BooksByTitleYear.book_type", "textValue"),
    title: _rawValue(row["title"], "BooksByTitleYear.title", "textValue"),
    publicationYear: _rawValue(row["publication_year"], "BooksByTitleYear.publication_year", "int32Value"),
    available: _rawValue(row["available"], "BooksByTitleYear.available", "uint64Value"),
    tags: _rawValue(row["tags"], "BooksByTitleYear.tags", "textValue"),
  };
}

function _decodeBooksByTagsRow(row) {
  if (row === null || typeof row !== "object" || Array.isArray(row)) throw new TypeError("BooksByTags: expected an object row");
  if (!Object.hasOwn(row, "b.book_id")) throw new TypeError("BooksByTags: result row is missing column b.book_id");
  if (!Object.hasOwn(row, "b.title")) throw new TypeError("BooksByTags: result row is missing column b.title");
  if (!Object.hasOwn(row, "a.name")) throw new TypeError("BooksByTags: result row is missing column a.name");
  if (!Object.hasOwn(row, "b.isbn")) throw new TypeError("BooksByTags: result row is missing column b.isbn");
  if (!Object.hasOwn(row, "b.tags")) throw new TypeError("BooksByTags: result row is missing column b.tags");
  return {
    bookId: _rawValue(row["b.book_id"], "BooksByTags.b.book_id", "uint64Value"),
    title: _rawValue(row["b.title"], "BooksByTags.b.title", "textValue"),
    name: _rawOptional(row["a.name"], "BooksByTags.a.name", (value) => _rawValue(value, "BooksByTags.a.name", "textValue")),
    isbn: _rawValue(row["b.isbn"], "BooksByTags.b.isbn", "textValue"),
    tags: _rawValue(row["b.tags"], "BooksByTags.b.tags", "textValue"),
  };
}

function _decodeCreateAuthorRow(row) {
  if (row === null || typeof row !== "object" || Array.isArray(row)) throw new TypeError("CreateAuthor: expected an object row");
  if (!Object.hasOwn(row, "author_id")) throw new TypeError("CreateAuthor: result row is missing column author_id");
  if (!Object.hasOwn(row, "name")) throw new TypeError("CreateAuthor: result row is missing column name");
  return {
    authorId: row["author_id"],
    name: row["name"],
  };
}

function _decodeCreateBookRow(row) {
  if (row === null || typeof row !== "object" || Array.isArray(row)) throw new TypeError("CreateBook: expected an object row");
  if (!Object.hasOwn(row, "book_id")) throw new TypeError("CreateBook: result row is missing column book_id");
  if (!Object.hasOwn(row, "author_id")) throw new TypeError("CreateBook: result row is missing column author_id");
  if (!Object.hasOwn(row, "isbn")) throw new TypeError("CreateBook: result row is missing column isbn");
  if (!Object.hasOwn(row, "book_type")) throw new TypeError("CreateBook: result row is missing column book_type");
  if (!Object.hasOwn(row, "title")) throw new TypeError("CreateBook: result row is missing column title");
  if (!Object.hasOwn(row, "publication_year")) throw new TypeError("CreateBook: result row is missing column publication_year");
  if (!Object.hasOwn(row, "available")) throw new TypeError("CreateBook: result row is missing column available");
  if (!Object.hasOwn(row, "tags")) throw new TypeError("CreateBook: result row is missing column tags");
  return {
    bookId: _rawValue(row["book_id"], "CreateBook.book_id", "uint64Value"),
    authorId: _rawValue(row["author_id"], "CreateBook.author_id", "uint64Value"),
    isbn: _rawValue(row["isbn"], "CreateBook.isbn", "textValue"),
    bookType: _rawValue(row["book_type"], "CreateBook.book_type", "textValue"),
    title: _rawValue(row["title"], "CreateBook.title", "textValue"),
    publicationYear: _rawValue(row["publication_year"], "CreateBook.publication_year", "int32Value"),
    available: _rawValue(row["available"], "CreateBook.available", "uint64Value"),
    tags: _rawValue(row["tags"], "CreateBook.tags", "textValue"),
  };
}

function _decodeSayHelloRow(row) {
  if (row === null || typeof row !== "object" || Array.isArray(row)) throw new TypeError("SayHello: expected an object row");
  if (!Object.hasOwn(row, "greeting")) throw new TypeError("SayHello: result row is missing column greeting");
  return {
    greeting: row["greeting"],
  };
}

export class Queries {
  #client;

  /** @param {import("@ydbjs/query").QueryClient} client */
  constructor(client) {
    if (typeof client !== "function") throw new TypeError("Queries requires a YDB QueryClient");
    this.#client = client;
  }

  async getAuthor(authorId) {
    const _pending = this.#client(_GET_AUTHOR_SQL_EXEC)
      .parameter("author_id", new Uint64(_uint64(authorId, "author_id")))
    ;
    const _resultSets = await _pending;
    if (!Array.isArray(_resultSets) || !Array.isArray(_resultSets[0])) throw new TypeError("GetAuthor: expected the first YDB result set to be an array");
    const _rows = _resultSets[0];
    return _rows.length === 0 ? null : _decodeGetAuthorRow(_rows[0]);
  }

  async getBook(bookId) {
    const _pending = this.#client(_GET_BOOK_SQL_EXEC)
      .parameter("book_id", new Uint64(_uint64(bookId, "book_id")))
    ;
    const _resultSets = await _pending.raw();
    if (!Array.isArray(_resultSets) || !Array.isArray(_resultSets[0])) throw new TypeError("GetBook: expected the first YDB result set to be an array");
    const _rows = _resultSets[0];
    return _rows.length === 0 ? null : _decodeGetBookRow(_rows[0]);
  }

  async deleteBook(bookId) {
    const _pending = this.#client(_DELETE_BOOK_SQL_EXEC)
      .parameter("book_id", new Uint64(_uint64(bookId, "book_id")))
    ;
    const _resultSets = await _pending;
    return undefined;
  }

  async booksByTitleYear(args) {
    const _pending = this.#client(_BOOKS_BY_TITLE_YEAR_SQL_EXEC)
      .parameter("title", new Utf8(_string(args.title, "title")))
      .parameter("publication_year", new Int32(_int32(args.publicationYear, "publication_year")))
    ;
    const _resultSets = await _pending.raw();
    if (!Array.isArray(_resultSets) || !Array.isArray(_resultSets[0])) throw new TypeError("BooksByTitleYear: expected the first YDB result set to be an array");
    const _rows = _resultSets[0];
    return _rows.map(_decodeBooksByTitleYearRow);
  }

  async booksByTags(tags) {
    const _pending = this.#client(_BOOKS_BY_TAGS_SQL_EXEC)
      .parameter("tags", new Json(_json(tags, "tags")))
    ;
    const _resultSets = await _pending.raw();
    if (!Array.isArray(_resultSets) || !Array.isArray(_resultSets[0])) throw new TypeError("BooksByTags: expected the first YDB result set to be an array");
    const _rows = _resultSets[0];
    return _rows.map(_decodeBooksByTagsRow);
  }

  async createAuthor(args) {
    const _pending = this.#client(_CREATE_AUTHOR_SQL_EXEC)
      .parameter("author_id", new Uint64(_uint64(args.authorId, "author_id")))
      .parameter("name", new Utf8(_string(args.name, "name")))
    ;
    const _resultSets = await _pending;
    if (!Array.isArray(_resultSets) || !Array.isArray(_resultSets[0])) throw new TypeError("CreateAuthor: expected the first YDB result set to be an array");
    const _rows = _resultSets[0];
    return _rows.length === 0 ? null : _decodeCreateAuthorRow(_rows[0]);
  }

  async createBook(args) {
    const _pending = this.#client(_CREATE_BOOK_SQL_EXEC)
      .parameter("book_id", new Uint64(_uint64(args.bookId, "book_id")))
      .parameter("author_id", new Uint64(_uint64(args.authorId, "author_id")))
      .parameter("isbn", new Utf8(_string(args.isbn, "isbn")))
      .parameter("book_type", new Utf8(_string(args.bookType, "book_type")))
      .parameter("title", new Utf8(_string(args.title, "title")))
      .parameter("publication_year", new Int32(_int32(args.publicationYear, "publication_year")))
      .parameter("available", new Primitive({ value: { case: "uint64Value", value: _timestamp(args.available, "available") } }, new TimestampType()))
      .parameter("tags", new Json(_json(args.tags, "tags")))
    ;
    const _resultSets = await _pending.raw();
    if (!Array.isArray(_resultSets) || !Array.isArray(_resultSets[0])) throw new TypeError("CreateBook: expected the first YDB result set to be an array");
    const _rows = _resultSets[0];
    return _rows.length === 0 ? null : _decodeCreateBookRow(_rows[0]);
  }

  async updateBook(args) {
    const _pending = this.#client(_UPDATE_BOOK_SQL_EXEC)
      .parameter("book_id", new Uint64(_uint64(args.bookId, "book_id")))
      .parameter("title", new Utf8(_string(args.title, "title")))
      .parameter("tags", new Json(_json(args.tags, "tags")))
    ;
    const _resultSets = await _pending;
    return undefined;
  }

  async updateBookISBN(args) {
    const _pending = this.#client(_UPDATE_BOOK_ISBN_SQL_EXEC)
      .parameter("book_id", new Uint64(_uint64(args.bookId, "book_id")))
      .parameter("title", new Utf8(_string(args.title, "title")))
      .parameter("tags", new Json(_json(args.tags, "tags")))
      .parameter("isbn", new Utf8(_string(args.isbn, "isbn")))
    ;
    const _resultSets = await _pending;
    return undefined;
  }

  async deleteAuthorBeforeYear(args) {
    const _pending = this.#client(_DELETE_AUTHOR_BEFORE_YEAR_SQL_EXEC)
      .parameter("author_id", new Uint64(_uint64(args.authorId, "author_id")))
      .parameter("publication_year", new Int32(_int32(args.publicationYear, "publication_year")))
    ;
    const _resultSets = await _pending;
    return undefined;
  }

  async sayHello(name) {
    const _pending = this.#client(_SAY_HELLO_SQL_EXEC)
      .parameter("name", new Utf8(_string(name, "name")))
    ;
    const _resultSets = await _pending;
    if (!Array.isArray(_resultSets) || !Array.isArray(_resultSets[0])) throw new TypeError("SayHello: expected the first YDB result set to be an array");
    const _rows = _resultSets[0];
    return _rows.length === 0 ? null : _decodeSayHelloRow(_rows[0]);
  }
}
