// Code generated by sqlc-ydb. DO NOT EDIT.
import type { QueryClient } from "@ydbjs/query";

export const GET_AUTHOR_SQL: string;
export const GET_BOOK_SQL: string;
export const DELETE_BOOK_SQL: string;
export const BOOKS_BY_TITLE_YEAR_SQL: string;
export const BOOKS_BY_TAGS_SQL: string;
export const CREATE_AUTHOR_SQL: string;
export const CREATE_BOOK_SQL: string;
export const UPDATE_BOOK_SQL: string;
export const UPDATE_BOOK_ISBN_SQL: string;
export const DELETE_AUTHOR_BEFORE_YEAR_SQL: string;
export const SAY_HELLO_SQL: string;

export interface GetAuthorRow {
  readonly authorId: bigint;
  readonly name: string;
}

export interface GetBookRow {
  readonly bookId: bigint;
  readonly authorId: bigint;
  readonly isbn: string;
  readonly bookType: string;
  readonly title: string;
  readonly publicationYear: number;
  readonly available: bigint;
  readonly tags: string;
}

export interface BooksByTitleYearParams {
  readonly title: string;
  readonly publicationYear: number;
}

export interface BooksByTitleYearRow {
  readonly bookId: bigint;
  readonly authorId: bigint;
  readonly isbn: string;
  readonly bookType: string;
  readonly title: string;
  readonly publicationYear: number;
  readonly available: bigint;
  readonly tags: string;
}

export interface BooksByTagsRow {
  readonly bookId: bigint;
  readonly title: string;
  readonly name: string | null;
  readonly isbn: string;
  readonly tags: string;
}

export interface CreateAuthorParams {
  readonly authorId: bigint;
  readonly name: string;
}

export interface CreateAuthorRow {
  readonly authorId: bigint;
  readonly name: string;
}

export interface CreateBookParams {
  readonly bookId: bigint;
  readonly authorId: bigint;
  readonly isbn: string;
  readonly bookType: string;
  readonly title: string;
  readonly publicationYear: number;
  readonly available: bigint;
  readonly tags: string;
}

export interface CreateBookRow {
  readonly bookId: bigint;
  readonly authorId: bigint;
  readonly isbn: string;
  readonly bookType: string;
  readonly title: string;
  readonly publicationYear: number;
  readonly available: bigint;
  readonly tags: string;
}

export interface UpdateBookParams {
  readonly bookId: bigint;
  readonly title: string;
  readonly tags: string;
}

export interface UpdateBookISBNParams {
  readonly bookId: bigint;
  readonly title: string;
  readonly tags: string;
  readonly isbn: string;
}

export interface DeleteAuthorBeforeYearParams {
  readonly authorId: bigint;
  readonly publicationYear: number;
}

export interface SayHelloRow {
  readonly greeting: string;
}

export class Queries {
  constructor(client: QueryClient);
  getAuthor(authorId: bigint): Promise<GetAuthorRow | null>;
  getBook(bookId: bigint): Promise<GetBookRow | null>;
  deleteBook(bookId: bigint): Promise<void>;
  booksByTitleYear(args: BooksByTitleYearParams): Promise<BooksByTitleYearRow[]>;
  booksByTags(tags: string): Promise<BooksByTagsRow[]>;
  createAuthor(args: CreateAuthorParams): Promise<CreateAuthorRow | null>;
  createBook(args: CreateBookParams): Promise<CreateBookRow | null>;
  updateBook(args: UpdateBookParams): Promise<void>;
  updateBookISBN(args: UpdateBookISBNParams): Promise<void>;
  deleteAuthorBeforeYear(args: DeleteAuthorBeforeYearParams): Promise<void>;
  sayHello(name: string): Promise<SayHelloRow | null>;
}
