// Code generated by sqlc-ydb. DO NOT EDIT.
package authors.nativeapi;

import tech.ydb.query.QueryTransaction;
import tech.ydb.query.tools.QueryReader;
import tech.ydb.table.query.Params;
import tech.ydb.table.values.PrimitiveValue;
import tech.ydb.table.values.PrimitiveType;
import tech.ydb.table.values.OptionalType;

// The caller owns the injected client and its lifecycle.
public final class Queries {
    private final QueryTransaction client;

    public Queries(QueryTransaction client) {
        this.client = java.util.Objects.requireNonNull(client);
    }

    // -- name: GetAuthor :one
    public java.util.Optional<GetAuthorRow> getAuthor(long authorId) {
        var _params = Params.create();
        _params.put("$author_id", PrimitiveValue.newUint64(authorId));
        var _query = QueryReader.readFrom(
                client.createQuery("""
                    SELECT id, name, bio FROM authors WHERE id = $author_id;\
                    """, _params)).join().getValue();
        if (_query.getResultSetCount() != 1) throw new IllegalStateException("Expected one result set");
        var _rows = _query.getResultSet(0);
        if (!_rows.next()) return java.util.Optional.empty();
        long _value0 = _rows.getColumn(0).getUint64();
        String _value1 = _rows.getColumn(1).getText();
        String _value2 = _rows.getColumn(2).getText();
        return java.util.Optional.of(new GetAuthorRow(_value0, _value1, _value2));
    }

    // -- name: ListAuthors :many
    public java.util.List<ListAuthorsRow> listAuthors() {
        var _params = Params.create();
        var _query = QueryReader.readFrom(
                client.createQuery("""
                    SELECT id, name, bio FROM authors ORDER BY name;\
                    """, _params)).join().getValue();
        if (_query.getResultSetCount() != 1) throw new IllegalStateException("Expected one result set");
        var _rows = _query.getResultSet(0);
        var _items = new java.util.ArrayList<ListAuthorsRow>();
        while (_rows.next()) {
            long _value0 = _rows.getColumn(0).getUint64();
            String _value1 = _rows.getColumn(1).getText();
            String _value2 = _rows.getColumn(2).getText();
            _items.add(new ListAuthorsRow(_value0, _value1, _value2));
        }
        return _items;
    }

    // -- name: ListAuthorsPage :many
    public java.util.List<ListAuthorsPageRow> listAuthorsPage(int pageSize, long offset) {
        if (offset < 0 || offset > 4294967295L) throw new IllegalArgumentException("parameter $offset is outside Uint32 range");
        var _params = Params.create();
        _params.put("$page_size", PrimitiveValue.newInt32(pageSize));
        _params.put("$offset", PrimitiveValue.newUint32(offset));
        var _query = QueryReader.readFrom(
                client.createQuery("""
                    DECLARE $page_size AS Int;
                    DECLARE $offset AS Uint32;
                    SELECT id, name, bio FROM authors ORDER BY id LIMIT $page_size OFFSET $offset;\
                    """, _params)).join().getValue();
        if (_query.getResultSetCount() != 1) throw new IllegalStateException("Expected one result set");
        var _rows = _query.getResultSet(0);
        var _items = new java.util.ArrayList<ListAuthorsPageRow>();
        while (_rows.next()) {
            long _value0 = _rows.getColumn(0).getUint64();
            String _value1 = _rows.getColumn(1).getText();
            String _value2 = _rows.getColumn(2).getText();
            _items.add(new ListAuthorsPageRow(_value0, _value1, _value2));
        }
        return _items;
    }

    // -- name: GetAuthorName :one
    public java.util.Optional<GetAuthorNameRow> getAuthorName(long authorId) {
        var _params = Params.create();
        _params.put("$author_id", PrimitiveValue.newUint64(authorId));
        var _query = QueryReader.readFrom(
                client.createQuery("""
                    SELECT name FROM authors WHERE id = $author_id;\
                    """, _params)).join().getValue();
        if (_query.getResultSetCount() != 1) throw new IllegalStateException("Expected one result set");
        var _rows = _query.getResultSet(0);
        if (!_rows.next()) return java.util.Optional.empty();
        String _value0 = _rows.getColumn(0).getText();
        return java.util.Optional.of(new GetAuthorNameRow(_value0));
    }

    // -- name: CreateAuthor :one
    public java.util.Optional<CreateAuthorRow> createAuthor(long authorId, String authorName, String biography) {
        var _params = Params.create();
        _params.put("$author_id", PrimitiveValue.newUint64(authorId));
        _params.put("$author_name", PrimitiveValue.newText(authorName));
        _params.put("$biography", biography == null ? OptionalType.of(PrimitiveType.Text).emptyValue() : PrimitiveValue.newText(biography).makeOptional());
        var _query = QueryReader.readFrom(
                client.createQuery("""
                    INSERT INTO `authors` (`id`, `name`, `bio`)
                    VALUES ($author_id, $author_name, $biography)
                    RETURNING `id`, `name`, `bio`;\
                    """, _params)).join().getValue();
        if (_query.getResultSetCount() != 1) throw new IllegalStateException("Expected one result set");
        var _rows = _query.getResultSet(0);
        if (!_rows.next()) return java.util.Optional.empty();
        long _value0 = _rows.getColumn(0).getUint64();
        String _value1 = _rows.getColumn(1).getText();
        String _value2 = _rows.getColumn(2).getText();
        return java.util.Optional.of(new CreateAuthorRow(_value0, _value1, _value2));
    }

    // -- name: UpsertAuthor :exec
    public void upsertAuthor(long authorId, String authorName, String biography) {
        var _params = Params.create();
        _params.put("$author_id", PrimitiveValue.newUint64(authorId));
        _params.put("$author_name", PrimitiveValue.newText(authorName));
        _params.put("$biography", biography == null ? OptionalType.of(PrimitiveType.Text).emptyValue() : PrimitiveValue.newText(biography).makeOptional());
        client.createQuery("""
            UPSERT INTO authors (id, name, bio)
            VALUES ($author_id, $author_name, $biography);\
            """, _params).execute().join().getStatus().expectSuccess();
    }

    // -- name: DeleteAuthor :exec
    public void deleteAuthor(long authorId) {
        var _params = Params.create();
        _params.put("$author_id", PrimitiveValue.newUint64(authorId));
        client.createQuery("""
            DELETE FROM authors WHERE id = $author_id;\
            """, _params).execute().join().getStatus().expectSuccess();
    }

    // -- name: FindAuthorsByName :many
    public java.util.List<FindAuthorsByNameRow> findAuthorsByName(String name) {
        var _params = Params.create();
        _params.put("$name", PrimitiveValue.newText(name));
        var _query = QueryReader.readFrom(
                client.createQuery("""
                    SELECT a.`id` AS `id`, `a`.`name` AS `name`, `a`.`bio` AS `bio` FROM authors VIEW by_name AS a
                    WHERE a.name = $name ORDER BY a.id;\
                    """, _params)).join().getValue();
        if (_query.getResultSetCount() != 1) throw new IllegalStateException("Expected one result set");
        var _rows = _query.getResultSet(0);
        var _items = new java.util.ArrayList<FindAuthorsByNameRow>();
        while (_rows.next()) {
            long _value0 = _rows.getColumn(0).getUint64();
            String _value1 = _rows.getColumn(1).getText();
            String _value2 = _rows.getColumn(2).getText();
            _items.add(new FindAuthorsByNameRow(_value0, _value1, _value2));
        }
        return _items;
    }

    // -- name: FindAuthorsByNameCovering :many
    public java.util.List<FindAuthorsByNameCoveringRow> findAuthorsByNameCovering(String name) {
        var _params = Params.create();
        _params.put("$name", PrimitiveValue.newText(name));
        var _query = QueryReader.readFrom(
                client.createQuery("""
                    DECLARE $name AS Utf8;
                    SELECT `id`, `name`, `bio` FROM authors VIEW by_name_covering WHERE name = $name ORDER BY id;\
                    """, _params)).join().getValue();
        if (_query.getResultSetCount() != 1) throw new IllegalStateException("Expected one result set");
        var _rows = _query.getResultSet(0);
        var _items = new java.util.ArrayList<FindAuthorsByNameCoveringRow>();
        while (_rows.next()) {
            long _value0 = _rows.getColumn(0).getUint64();
            String _value1 = _rows.getColumn(1).getText();
            String _value2 = _rows.getColumn(2).getText();
            _items.add(new FindAuthorsByNameCoveringRow(_value0, _value1, _value2));
        }
        return _items;
    }
}
