<?php
// Code generated by sqlc-ydb. DO NOT EDIT.
declare(strict_types=1);

namespace PhpCodec;

final class BindValuesParams
{
    public function __construct(
        public readonly string $id,
        public readonly float $float,
        public readonly ?float $floatOptional,
        public readonly float $double,
        public readonly ?float $doubleOptional,
        public readonly string $uint64,
        public readonly ?string $uint64Optional,
        public readonly int $timestamp,
        public readonly ?int $timestampOptional,
        public readonly string $json,
        public readonly ?string $jsonOptional
    ) {}
}
