// Code generated by sqlc-ydb. DO NOT EDIT.
#include "queries.hpp"

#include <ydb-cpp-sdk/client/params/params.h>
#include <ydb-cpp-sdk/client/result/result.h>
#include <ydb-cpp-sdk/client/types/status/status.h>

#include <stdexcept>
#include <utility>

namespace jets::native {

// -- name: CountPilots :one
std::optional<CountPilotsRow> Queries::CountPilots() const {
    std::optional<NYdb::TResultSet> sqlc_result_set;
    const auto sqlc_execute = [&](NYdb::NQuery::TSession sqlc_session, const NYdb::NQuery::TTxControl& sqlc_tx) -> NYdb::TStatus {
        auto sqlc_result = sqlc_session.ExecuteQuery(
            R"sql(
                SELECT COUNT(*) AS pilot_count FROM pilots;
            )sql",
            sqlc_tx,
            this->execute_settings_
        ).GetValueSync();
        if (sqlc_result.IsSuccess()) {
            if (sqlc_result.GetResultSets().size() != 1) {
                throw std::runtime_error("expected exactly one result set");
            }
            sqlc_result_set = sqlc_result.GetResultSet(0);
        }
        return sqlc_result;
    };
    const auto sqlc_status = this->transaction_ != nullptr
        ? sqlc_execute(this->transaction_->GetSession(), NYdb::NQuery::TTxControl::Tx(*this->transaction_))
        : this->client_->RetryQuerySync([&](NYdb::NQuery::TSession sqlc_session) -> NYdb::TStatus {
            return sqlc_execute(
                std::move(sqlc_session),
                NYdb::NQuery::TTxControl::BeginTx(this->tx_settings_).CommitTx()
            );
        }, this->retry_settings_);
    NYdb::NStatusHelpers::ThrowOnError(sqlc_status);
    if (!sqlc_result_set) {
        throw std::runtime_error("CountPilots: successful query returned no result set");
    }
    NYdb::TResultSetParser sqlc_parser(*sqlc_result_set);
    if (!sqlc_parser.TryNextRow()) {
        return std::nullopt;
    }
    CountPilotsRow sqlc_row{
        sqlc_parser.ColumnParser("pilot_count").GetUint64(),
    };
    return sqlc_row;
}

// -- name: ListPilots :many
std::vector<ListPilotsRow> Queries::ListPilots() const {
    std::optional<NYdb::TResultSet> sqlc_result_set;
    const auto sqlc_execute = [&](NYdb::NQuery::TSession sqlc_session, const NYdb::NQuery::TTxControl& sqlc_tx) -> NYdb::TStatus {
        auto sqlc_result = sqlc_session.ExecuteQuery(
            R"sql(
                SELECT id, name FROM pilots ORDER BY id LIMIT 5;
            )sql",
            sqlc_tx,
            this->execute_settings_
        ).GetValueSync();
        if (sqlc_result.IsSuccess()) {
            if (sqlc_result.GetResultSets().size() != 1) {
                throw std::runtime_error("expected exactly one result set");
            }
            sqlc_result_set = sqlc_result.GetResultSet(0);
        }
        return sqlc_result;
    };
    const auto sqlc_status = this->transaction_ != nullptr
        ? sqlc_execute(this->transaction_->GetSession(), NYdb::NQuery::TTxControl::Tx(*this->transaction_))
        : this->client_->RetryQuerySync([&](NYdb::NQuery::TSession sqlc_session) -> NYdb::TStatus {
            return sqlc_execute(
                std::move(sqlc_session),
                NYdb::NQuery::TTxControl::BeginTx(this->tx_settings_).CommitTx()
            );
        }, this->retry_settings_);
    NYdb::NStatusHelpers::ThrowOnError(sqlc_status);
    if (!sqlc_result_set) {
        throw std::runtime_error("ListPilots: successful query returned no result set");
    }
    NYdb::TResultSetParser sqlc_parser(*sqlc_result_set);
    std::vector<ListPilotsRow> sqlc_rows;
    sqlc_rows.reserve(sqlc_result_set->RowsCount());
    while (sqlc_parser.TryNextRow()) {
        sqlc_rows.push_back(ListPilotsRow{
            sqlc_parser.ColumnParser("id").GetInt32(),
            sqlc_parser.ColumnParser("name").GetUtf8(),
        });
    }
    return sqlc_rows;
}

// -- name: DeletePilot :exec
void Queries::DeletePilot(std::int32_t pilot_id) const {
    const auto sqlc_execute = [&](NYdb::NQuery::TSession sqlc_session, const NYdb::NQuery::TTxControl& sqlc_tx) -> NYdb::TStatus {
        auto sqlc_params = NYdb::TParamsBuilder()
            .AddParam("$pilot_id").Int32(pilot_id).Build()
            .Build();
        auto sqlc_result = sqlc_session.ExecuteQuery(
            R"sql(
                DELETE FROM pilots WHERE id = $pilot_id;
            )sql",
            sqlc_tx,
            sqlc_params,
            this->execute_settings_
        ).GetValueSync();
        return sqlc_result;
    };
    const auto sqlc_status = this->transaction_ != nullptr
        ? sqlc_execute(this->transaction_->GetSession(), NYdb::NQuery::TTxControl::Tx(*this->transaction_))
        : this->client_->RetryQuerySync([&](NYdb::NQuery::TSession sqlc_session) -> NYdb::TStatus {
            return sqlc_execute(
                std::move(sqlc_session),
                NYdb::NQuery::TTxControl::BeginTx(this->tx_settings_).CommitTx()
            );
        }, this->retry_settings_);
    NYdb::NStatusHelpers::ThrowOnError(sqlc_status);
}

}  // namespace jets::native
