// Code generated by sqlc-ydb. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Reflection;
using System.Threading;
using System.Threading.Tasks;
using Dapper;
using Ydb.Sdk.Ado;
using Ydb.Sdk.Value;

namespace Namespaces.Dapper;

public sealed class Queries
{
    private readonly YdbConnection _connection;
    private readonly YdbTransaction? _transaction;

    public Queries(YdbConnection connection, YdbTransaction? transaction = null)
    {
        _connection = connection ?? throw new ArgumentNullException(nameof(connection));
        if (transaction is not null && !ReferenceEquals(transaction.Connection, connection))
        {
            throw new ArgumentException("Transaction must belong to the supplied connection.", nameof(transaction));
        }
        _transaction = transaction;
    }

    public Queries WithTransaction(YdbTransaction transaction) => new(_connection, transaction ?? throw new ArgumentNullException(nameof(transaction)));

    static Queries()
    {
        SqlMapper.SetTypeMap(typeof(CompareUserNamesRow), new ColumnTypeMap(typeof(CompareUserNamesRow), new Dictionary<string, string>
        {
            ["primary_name"] = nameof(CompareUserNamesRow.PrimaryName),
            ["secondary_name"] = nameof(CompareUserNamesRow.SecondaryName),
        }));
    }

    private sealed class ColumnTypeMap : SqlMapper.ITypeMap
    {
        private readonly DefaultTypeMap _default;
        private readonly IReadOnlyDictionary<string, string> _columns;

        public ColumnTypeMap(Type type, IReadOnlyDictionary<string, string> columns)
        {
            _default = new DefaultTypeMap(type);
            _columns = columns;
        }

        private string MemberName(string column) => _columns.TryGetValue(column, out var member) ? member : column;
        public ConstructorInfo? FindConstructor(string[] names, Type[] types) => _default.FindConstructor(names.Select(MemberName).ToArray(), types);
        public ConstructorInfo? FindExplicitConstructor() => _default.FindExplicitConstructor();
        public SqlMapper.IMemberMap? GetConstructorParameter(ConstructorInfo constructor, string columnName) => _default.GetConstructorParameter(constructor, MemberName(columnName));
        public SqlMapper.IMemberMap? GetMember(string columnName) => _default.GetMember(MemberName(columnName));
    }

    // -- name: UpsertPrimaryUser :exec
    public async Task UpsertPrimaryUserAsync(UpsertPrimaryUserParams args, CancellationToken cancellationToken = default, int? commandTimeout = null)
    {
        var parameters = new YdbParameters(
            new YdbParameter("$id", DbType.UInt64, args.ID),
            new YdbParameter("$name", DbType.String, args.Name)
        );

        var command = new CommandDefinition(
            commandText: """
            PRAGMA TablePathPrefix("/local/sqlc_namespaces/a");
            DECLARE $id AS Uint64;
            DECLARE $name AS Utf8;
            UPSERT INTO users (id, name) VALUES ($id, $name);
            """,
            parameters: parameters,
            transaction: _transaction,
            commandTimeout: commandTimeout,
            cancellationToken: cancellationToken);

        await _connection.ExecuteAsync(command).ConfigureAwait(false);
    }

    // -- name: UpsertSecondaryUser :exec
    public async Task UpsertSecondaryUserAsync(UpsertSecondaryUserParams args, CancellationToken cancellationToken = default, int? commandTimeout = null)
    {
        var parameters = new YdbParameters(
            new YdbParameter("$id", DbType.UInt64, args.ID),
            new YdbParameter("$name", DbType.String, args.Name)
        );

        var command = new CommandDefinition(
            commandText: """
            PRAGMA TablePathPrefix("/local/sqlc_namespaces/b");
            DECLARE $id AS Uint64;
            DECLARE $name AS Utf8;
            UPSERT INTO users (id, name) VALUES ($id, $name);
            """,
            parameters: parameters,
            transaction: _transaction,
            commandTimeout: commandTimeout,
            cancellationToken: cancellationToken);

        await _connection.ExecuteAsync(command).ConfigureAwait(false);
    }

    // -- name: GetPrimaryUser :one
    public async Task<GetPrimaryUserRow> GetPrimaryUserAsync(ulong id, CancellationToken cancellationToken = default, int? commandTimeout = null)
    {
        var parameters = new YdbParameters(
            new YdbParameter("$id", DbType.UInt64, id)
        );

        var command = new CommandDefinition(
            commandText: """
            PRAGMA TablePathPrefix("/local/sqlc_namespaces/a");
            SELECT users.`id` AS `id`, `users`.`name` AS `name` FROM users WHERE id = $id;
            """,
            parameters: parameters,
            transaction: _transaction,
            commandTimeout: commandTimeout,
            cancellationToken: cancellationToken);

        return await _connection.QueryFirstAsync<GetPrimaryUserRow>(command).ConfigureAwait(false);
    }

    // -- name: GetSecondaryUser :one
    public async Task<GetSecondaryUserRow> GetSecondaryUserAsync(ulong id, CancellationToken cancellationToken = default, int? commandTimeout = null)
    {
        var parameters = new YdbParameters(
            new YdbParameter("$id", DbType.UInt64, id)
        );

        var command = new CommandDefinition(
            commandText: """
            PRAGMA TablePathPrefix("/local/sqlc_namespaces/b");
            DECLARE $id AS Uint64;
            SELECT users.`id` AS `id`, `users`.`name` AS `name` FROM users WHERE id = $id;
            """,
            parameters: parameters,
            transaction: _transaction,
            commandTimeout: commandTimeout,
            cancellationToken: cancellationToken);

        return await _connection.QueryFirstAsync<GetSecondaryUserRow>(command).ConfigureAwait(false);
    }

    // -- name: FindPrimaryUsersByName :many
    public async Task<IReadOnlyList<FindPrimaryUsersByNameRow>> FindPrimaryUsersByNameAsync(string name, CancellationToken cancellationToken = default, int? commandTimeout = null)
    {
        var parameters = new YdbParameters(
            new YdbParameter("$name", DbType.String, name)
        );

        var command = new CommandDefinition(
            commandText: """
            PRAGMA TablePathPrefix("/local/sqlc_namespaces/a");
            SELECT u.`id` AS `id`, `u`.`name` AS `name` FROM users VIEW by_name AS u WHERE u.name = $name ORDER BY u.id;
            """,
            parameters: parameters,
            transaction: _transaction,
            commandTimeout: commandTimeout,
            cancellationToken: cancellationToken);

        return (await _connection.QueryAsync<FindPrimaryUsersByNameRow>(command).ConfigureAwait(false)).AsList();
    }

    // -- name: CompareUserNames :many
    public async Task<IReadOnlyList<CompareUserNamesRow>> CompareUserNamesAsync(CancellationToken cancellationToken = default, int? commandTimeout = null)
    {
        var command = new CommandDefinition(
            commandText: """
            PRAGMA TablePathPrefix("/local/sqlc_namespaces/a");
            SELECT a.id AS id, a.name AS primary_name, b.name AS secondary_name
            FROM users AS a
            LEFT JOIN `/local/sqlc_namespaces/b/users` AS b ON a.id = b.id
            ORDER BY a.id;
            """,
            parameters: null,
            transaction: _transaction,
            commandTimeout: commandTimeout,
            cancellationToken: cancellationToken);

        return (await _connection.QueryAsync<CompareUserNamesRow>(command).ConfigureAwait(false)).AsList();
    }

    private sealed class YdbParameters : SqlMapper.IDynamicParameters
    {
        private readonly YdbParameter[] _parameters;

        public YdbParameters(params YdbParameter[] parameters) => _parameters = parameters;

        public void AddParameters(IDbCommand command, SqlMapper.Identity identity)
        {
            foreach (var parameter in _parameters)
            {
                command.Parameters.Add(parameter);
            }
        }
    }
}
