// Code generated by sqlc-ydb. DO NOT EDIT.
#pragma once

#include <cstdint>
#include <optional>
#include <string>
#include <util/datetime/base.h>

namespace ondeck::native {

struct ListCitiesRow final {
    std::string slug;
    std::string name;
};

struct GetCityRow final {
    std::string slug;
    std::string name;
};

struct CreateCityRow final {
    std::string slug;
    std::string name;
};

struct ListVenuesRow final {
    std::uint64_t id;
    std::string slug;
    std::string name;
    std::string city;
    std::string status;
    std::optional<std::string> statuses;
    std::string spotify_playlist;
    std::optional<std::string> songkick_id;
    std::optional<std::string> tags;
    std::optional<TInstant> created_at;
};

struct GetVenueRow final {
    std::uint64_t id;
    std::string slug;
    std::string name;
    std::string city;
    std::string status;
    std::optional<std::string> statuses;
    std::string spotify_playlist;
    std::optional<std::string> songkick_id;
    std::optional<std::string> tags;
    std::optional<TInstant> created_at;
};

struct CreateVenueRow final {
    std::uint64_t id;
};

struct UpdateVenueNameRow final {
    std::uint64_t id;
};

struct VenueCountByCityRow final {
    std::string city;
    std::uint64_t venue_count;
};

}  // namespace ondeck::native
