// Code generated by sqlc-ydb. DO NOT EDIT.
import type { Query, SQL } from "@ydbjs/query";
import { Uint64, Utf8 } from "@ydbjs/value/primitive";

export type ConfigureQuery = (query: Query) => void;

export type UpsertPrimaryUserParams = {
  readonly id: bigint;
  readonly name: string;
};

export type UpsertSecondaryUserParams = {
  readonly id: bigint;
  readonly name: string;
};

export type GetPrimaryUserRow = {
  readonly id: bigint;
  readonly name: string;
};

export type GetSecondaryUserRow = {
  readonly id: bigint;
  readonly name: string;
};

export type FindPrimaryUsersByNameRow = {
  readonly id: bigint;
  readonly name: string;
};

export type CompareUserNamesRow = {
  readonly id: bigint;
  readonly primary_name: string;
  readonly secondary_name: string | null;
};

export class Queries {
  readonly #sql: SQL;

  constructor(sql: SQL) {
    if (typeof sql !== "function") throw new TypeError("Queries requires a YDB SQL function");
    this.#sql = sql;
  }

  // -- name: UpsertPrimaryUser :exec
  async upsertPrimaryUser(args: UpsertPrimaryUserParams, configure?: ConfigureQuery): Promise<void> {
    const stmt = this.#sql(
      "PRAGMA TablePathPrefix(\"/local/sqlc_namespaces/a\");\n" +
      "DECLARE $id AS Uint64;\n" +
      "DECLARE $name AS Utf8;\n" +
      "UPSERT INTO users (id, name) VALUES ($id, $name);"
    );
    // Keep explicit DECLARE statements; the SDK otherwise prepends duplicates.
    Object.defineProperty(stmt, "text", { value: stmt.text, writable: false });
    stmt
      .parameter("id", new Uint64(args.id))
      .parameter("name", new Utf8(args.name));
    configure?.(stmt);
    await stmt;
  }

  // -- name: UpsertSecondaryUser :exec
  async upsertSecondaryUser(args: UpsertSecondaryUserParams, configure?: ConfigureQuery): Promise<void> {
    const stmt = this.#sql(
      "PRAGMA TablePathPrefix(\"/local/sqlc_namespaces/b\");\n" +
      "DECLARE $id AS Uint64;\n" +
      "DECLARE $name AS Utf8;\n" +
      "UPSERT INTO users (id, name) VALUES ($id, $name);"
    );
    // Keep explicit DECLARE statements; the SDK otherwise prepends duplicates.
    Object.defineProperty(stmt, "text", { value: stmt.text, writable: false });
    stmt
      .parameter("id", new Uint64(args.id))
      .parameter("name", new Utf8(args.name));
    configure?.(stmt);
    await stmt;
  }

  // -- name: GetPrimaryUser :one
  async getPrimaryUser(id: bigint, configure?: ConfigureQuery): Promise<GetPrimaryUserRow | null> {
    const stmt = this.#sql<[GetPrimaryUserRow]>(
      "PRAGMA TablePathPrefix(\"/local/sqlc_namespaces/a\");\n" +
      "SELECT users.`id` AS `id`, `users`.`name` AS `name` FROM users WHERE id = $id;"
    )
      .parameter("id", new Uint64(id));
    configure?.(stmt);
    const [rows] = await stmt;

    return rows[0] ?? null;
  }

  // -- name: GetSecondaryUser :one
  async getSecondaryUser(id: bigint, configure?: ConfigureQuery): Promise<GetSecondaryUserRow | null> {
    const stmt = this.#sql<[GetSecondaryUserRow]>(
      "PRAGMA TablePathPrefix(\"/local/sqlc_namespaces/b\");\n" +
      "DECLARE $id AS Uint64;\n" +
      "SELECT users.`id` AS `id`, `users`.`name` AS `name` FROM users WHERE id = $id;"
    );
    // Keep explicit DECLARE statements; the SDK otherwise prepends duplicates.
    Object.defineProperty(stmt, "text", { value: stmt.text, writable: false });
    stmt
      .parameter("id", new Uint64(id));
    configure?.(stmt);
    const [rows] = await stmt;

    return rows[0] ?? null;
  }

  // -- name: FindPrimaryUsersByName :many
  async findPrimaryUsersByName(name: string, configure?: ConfigureQuery): Promise<FindPrimaryUsersByNameRow[]> {
    const stmt = this.#sql<[FindPrimaryUsersByNameRow]>(
      "PRAGMA TablePathPrefix(\"/local/sqlc_namespaces/a\");\n" +
      "SELECT u.`id` AS `id`, `u`.`name` AS `name` FROM users VIEW by_name AS u WHERE u.name = $name ORDER BY u.id;"
    )
      .parameter("name", new Utf8(name));
    configure?.(stmt);
    const [rows] = await stmt;

    return rows;
  }

  // -- name: CompareUserNames :many
  async compareUserNames(configure?: ConfigureQuery): Promise<CompareUserNamesRow[]> {
    const stmt = this.#sql<[CompareUserNamesRow]>(
      "PRAGMA TablePathPrefix(\"/local/sqlc_namespaces/a\");\n" +
      "SELECT a.id AS id, a.name AS primary_name, b.name AS secondary_name\n" +
      "FROM users AS a\n" +
      "LEFT JOIN `/local/sqlc_namespaces/b/users` AS b ON a.id = b.id\n" +
      "ORDER BY a.id;"
    );
    configure?.(stmt);
    const [rows] = await stmt;

    return rows;
  }
}
