package endtoend

// builtinLiveQueries returns one metadata probe for every C++ library function
// and arity supported by internal/yql/builtins. The live harness replaces
// $TABLE with its disposable table name; temporal probes use its required
// Timestamp column so AutoMap nullability does not hide the base result type.
func builtinLiveQueries() []struct{ Name, SQL string } {
	return []struct{ Name, SQL string }{
		{Name: "string_base64_encode", SQL: `SELECT String::Base64Encode("YQL") AS value;`},
		{Name: "string_base64_decode", SQL: `SELECT String::Base64Decode("WVFM") AS value;`},
		{Name: "string_base64_strict_decode", SQL: `SELECT String::Base64StrictDecode("WVFM") AS value;`},
		{Name: "string_escape_c", SQL: `SELECT String::EscapeC("a\nb") AS value;`},
		{Name: "string_unescape_c", SQL: `SELECT String::UnescapeC("a\\nb") AS value;`},
		{Name: "string_hex_encode", SQL: `SELECT String::HexEncode("YQL") AS value;`},
		{Name: "string_hex_decode", SQL: `SELECT String::HexDecode("59514c") AS value;`},
		{Name: "string_encode_html", SQL: `SELECT String::EncodeHtml("<p>") AS value;`},
		{Name: "string_decode_html", SQL: `SELECT String::DecodeHtml("&lt;p&gt;") AS value;`},
		{Name: "string_cgi_escape", SQL: `SELECT String::CgiEscape("a b") AS value;`},
		{Name: "string_cgi_unescape", SQL: `SELECT String::CgiUnescape("a%20b") AS value;`},
		{Name: "string_strip", SQL: `SELECT String::Strip(" text ") AS value;`},
		{Name: "string_collapse", SQL: `SELECT String::Collapse("a   b") AS value;`},
		{Name: "string_find_two", SQL: `SELECT String::Find("abcabc", "bc") AS value;`},
		{Name: "string_find_three", SQL: `SELECT String::Find("abcabc", "bc", 2ul) AS value;`},
		{Name: "string_reverse_find_two", SQL: `SELECT String::ReverseFind("abcabc", "bc") AS value;`},
		{Name: "string_reverse_find_three", SQL: `SELECT String::ReverseFind("abcabc", "bc", 2ul) AS value;`},
		{Name: "string_substring_two", SQL: `SELECT String::Substring("abcdef", 2ul) AS value;`},
		{Name: "string_substring_three", SQL: `SELECT String::Substring("abcdef", 2ul, 3ul) AS value;`},
		{Name: "string_ascii_lower", SQL: `SELECT String::AsciiToLower("ABC") AS value;`},
		{Name: "string_ascii_upper", SQL: `SELECT String::AsciiToUpper("abc") AS value;`},
		{Name: "string_ascii_title", SQL: `SELECT String::AsciiToTitle("abc") AS value;`},
		{Name: "string_replace_all", SQL: `SELECT String::ReplaceAll("abcabc", "a", "x") AS value;`},
		{Name: "string_replace_first", SQL: `SELECT String::ReplaceFirst("abcabc", "a", "x") AS value;`},
		{Name: "string_replace_last", SQL: `SELECT String::ReplaceLast("abcabc", "a", "x") AS value;`},

		{Name: "unicode_is_utf", SQL: `SELECT Unicode::IsUtf("text") AS value;`},
		{Name: "unicode_length", SQL: `SELECT Unicode::GetLength("текст"u) AS value;`},
		{Name: "unicode_find_two", SQL: `SELECT Unicode::Find("абвабв"u, "бв"u) AS value;`},
		{Name: "unicode_find_three", SQL: `SELECT Unicode::Find("абвабв"u, "бв"u, 2ul) AS value;`},
		{Name: "unicode_rfind_two", SQL: `SELECT Unicode::RFind("абвабв"u, "бв"u) AS value;`},
		{Name: "unicode_rfind_three", SQL: `SELECT Unicode::RFind("абвабв"u, "бв"u, 2ul) AS value;`},
		{Name: "unicode_substring_two", SQL: `SELECT Unicode::Substring("абвгд"u, 1ul) AS value;`},
		{Name: "unicode_substring_three", SQL: `SELECT Unicode::Substring("абвгд"u, 1ul, 2ul) AS value;`},
		{Name: "unicode_lower", SQL: `SELECT Unicode::ToLower("ТЕКСТ"u) AS value;`},
		{Name: "unicode_upper", SQL: `SELECT Unicode::ToUpper("текст"u) AS value;`},
		{Name: "unicode_title", SQL: `SELECT Unicode::ToTitle("текст"u) AS value;`},
		{Name: "unicode_normalize", SQL: `SELECT Unicode::Normalize("текст"u) AS value;`},
		{Name: "unicode_normalize_nfc", SQL: `SELECT Unicode::NormalizeNFC("текст"u) AS value;`},
		{Name: "unicode_normalize_nfd", SQL: `SELECT Unicode::NormalizeNFD("текст"u) AS value;`},
		{Name: "unicode_normalize_nfkc", SQL: `SELECT Unicode::NormalizeNFKC("текст"u) AS value;`},
		{Name: "unicode_normalize_nfkd", SQL: `SELECT Unicode::NormalizeNFKD("текст"u) AS value;`},

		{Name: "datetime_get_year", SQL: `SELECT DateTime::GetYear(stamp) AS value FROM $TABLE;`},
		{Name: "datetime_get_day_of_year", SQL: `SELECT DateTime::GetDayOfYear(stamp) AS value FROM $TABLE;`},
		{Name: "datetime_get_month", SQL: `SELECT DateTime::GetMonth(stamp) AS value FROM $TABLE;`},
		{Name: "datetime_get_month_name", SQL: `SELECT DateTime::GetMonthName(stamp) AS value FROM $TABLE;`},
		{Name: "datetime_get_week_of_year", SQL: `SELECT DateTime::GetWeekOfYear(stamp) AS value FROM $TABLE;`},
		{Name: "datetime_get_week_of_year_iso8601", SQL: `SELECT DateTime::GetWeekOfYearIso8601(stamp) AS value FROM $TABLE;`},
		{Name: "datetime_get_day_of_month", SQL: `SELECT DateTime::GetDayOfMonth(stamp) AS value FROM $TABLE;`},
		{Name: "datetime_get_day_of_week", SQL: `SELECT DateTime::GetDayOfWeek(stamp) AS value FROM $TABLE;`},
		{Name: "datetime_get_day_of_week_name", SQL: `SELECT DateTime::GetDayOfWeekName(stamp) AS value FROM $TABLE;`},
		{Name: "datetime_get_hour", SQL: `SELECT DateTime::GetHour(stamp) AS value FROM $TABLE;`},
		{Name: "datetime_get_minute", SQL: `SELECT DateTime::GetMinute(stamp) AS value FROM $TABLE;`},
		{Name: "datetime_get_second", SQL: `SELECT DateTime::GetSecond(stamp) AS value FROM $TABLE;`},
		{Name: "datetime_get_millisecond", SQL: `SELECT DateTime::GetMillisecondOfSecond(stamp) AS value FROM $TABLE;`},
		{Name: "datetime_get_microsecond", SQL: `SELECT DateTime::GetMicrosecondOfSecond(stamp) AS value FROM $TABLE;`},
		{Name: "datetime_get_timezone_id", SQL: `SELECT DateTime::GetTimezoneId(stamp) AS value FROM $TABLE;`},
		{Name: "datetime_get_timezone_name", SQL: `SELECT DateTime::GetTimezoneName(stamp) AS value FROM $TABLE;`},
	}
}
