// Code generated by sqlc-ydb. DO NOT EDIT.
package db

import (
	"github.com/google/uuid"
	"github.com/ydb-platform/ydb-go-sdk/v3/types"
)

type BindNativeTypesRow struct {
	Ids         []uint64
	OptionalIds []*uint64
	Amount      types.Decimal
	ID          uuid.UUID
}

type BindNativeTypesParams struct {
	Ids         []uint64
	OptionalIds []*uint64
	Amount      types.Decimal
	ID          uuid.UUID
}
