// Code generated by sqlc-ydb. DO NOT EDIT.
#include "queries.hpp"

namespace booktest::userver {

// -- name: GetAuthor :one
std::optional<GetAuthorRow> Queries::GetAuthor(std::uint64_t author_id) const {
    const auto sqlc_query = ::userver::ydb::Query{
        "SELECT author_id, name\n"
        "FROM authors\n"
        "WHERE author_id = $author_id;",
        ::userver::ydb::Query::Name{"GetAuthor"},
        ::userver::ydb::Query::LogMode::kNameOnly,
    };
    auto sqlc_response =
        this->transaction_ != nullptr
        ? this->transaction_->Execute(this->execute_settings_, sqlc_query, "$author_id", author_id)
        : this->client_->ExecuteQuery(this->operation_settings_, sqlc_query, "$author_id", author_id);
    auto sqlc_cursor = sqlc_response.GetSingleCursor();
    if (sqlc_cursor.empty()) {
        return std::nullopt;
    }
    auto sqlc_row = sqlc_cursor.GetFirstRow();
    return GetAuthorRow{
        sqlc_row.Get<std::uint64_t>("author_id"),
        sqlc_row.Get<::userver::ydb::Utf8>("name"),
    };
}

// -- name: GetBook :one
std::optional<GetBookRow> Queries::GetBook(std::uint64_t book_id) const {
    const auto sqlc_query = ::userver::ydb::Query{
        "SELECT book_id, author_id, isbn, book_type, title, publication_year, available, tags\n"
        "FROM books\n"
        "WHERE book_id = $book_id;",
        ::userver::ydb::Query::Name{"GetBook"},
        ::userver::ydb::Query::LogMode::kNameOnly,
    };
    auto sqlc_response =
        this->transaction_ != nullptr
        ? this->transaction_->Execute(this->execute_settings_, sqlc_query, "$book_id", book_id)
        : this->client_->ExecuteQuery(this->operation_settings_, sqlc_query, "$book_id", book_id);
    auto sqlc_cursor = sqlc_response.GetSingleCursor();
    if (sqlc_cursor.empty()) {
        return std::nullopt;
    }
    auto sqlc_row = sqlc_cursor.GetFirstRow();
    return GetBookRow{
        sqlc_row.Get<std::uint64_t>("book_id"),
        sqlc_row.Get<std::uint64_t>("author_id"),
        sqlc_row.Get<::userver::ydb::Utf8>("isbn"),
        sqlc_row.Get<::userver::ydb::Utf8>("book_type"),
        sqlc_row.Get<::userver::ydb::Utf8>("title"),
        sqlc_row.Get<std::int32_t>("publication_year"),
        sqlc_row.Get<std::chrono::system_clock::time_point>("available"),
        sqlc_row.Get<::userver::formats::json::Value>("tags"),
    };
}

// -- name: DeleteBook :exec
void Queries::DeleteBook(std::uint64_t book_id) const {
    const auto sqlc_query = ::userver::ydb::Query{
        "DELETE FROM books\n"
        "WHERE book_id = $book_id;",
        ::userver::ydb::Query::Name{"DeleteBook"},
        ::userver::ydb::Query::LogMode::kNameOnly,
    };
    static_cast<void>(
        this->transaction_ != nullptr
        ? this->transaction_->Execute(this->execute_settings_, sqlc_query, "$book_id", book_id)
        : this->client_->ExecuteQuery(this->operation_settings_, sqlc_query, "$book_id", book_id)
    );
}

// -- name: BooksByTitleYear :many
std::vector<BooksByTitleYearRow> Queries::BooksByTitleYear(const ::userver::ydb::Utf8& title, std::int32_t publication_year) const {
    const auto sqlc_query = ::userver::ydb::Query{
        "SELECT book_id, author_id, isbn, book_type, title, publication_year, available, tags\n"
        "FROM books\n"
        "WHERE title = $title AND publication_year = $publication_year;",
        ::userver::ydb::Query::Name{"BooksByTitleYear"},
        ::userver::ydb::Query::LogMode::kNameOnly,
    };
    auto sqlc_response =
        this->transaction_ != nullptr
        ? this->transaction_->Execute(this->execute_settings_, sqlc_query, "$title", title, "$publication_year", publication_year)
        : this->client_->ExecuteQuery(this->operation_settings_, sqlc_query, "$title", title, "$publication_year", publication_year);
    auto sqlc_cursor = sqlc_response.GetSingleCursor();
    std::vector<BooksByTitleYearRow> sqlc_rows;
    sqlc_rows.reserve(sqlc_cursor.size());
    for (auto sqlc_row : sqlc_cursor) {
        sqlc_rows.push_back(BooksByTitleYearRow{
            sqlc_row.Get<std::uint64_t>("book_id"),
            sqlc_row.Get<std::uint64_t>("author_id"),
            sqlc_row.Get<::userver::ydb::Utf8>("isbn"),
            sqlc_row.Get<::userver::ydb::Utf8>("book_type"),
            sqlc_row.Get<::userver::ydb::Utf8>("title"),
            sqlc_row.Get<std::int32_t>("publication_year"),
            sqlc_row.Get<std::chrono::system_clock::time_point>("available"),
            sqlc_row.Get<::userver::formats::json::Value>("tags"),
        });
    }
    return sqlc_rows;
}

// -- name: BooksByTags :many
std::vector<BooksByTagsRow> Queries::BooksByTags(const ::userver::formats::json::Value& tags) const {
    const auto sqlc_query = ::userver::ydb::Query{
        "DECLARE $tags AS Json;\n"
        "SELECT\n"
        "    b.book_id,\n"
        "    b.title,\n"
        "    a.name,\n"
        "    b.isbn,\n"
        "    b.tags\n"
        "FROM books AS b\n"
        "LEFT JOIN authors AS a ON b.author_id = a.author_id\n"
        "WHERE NOT SetIsDisjoint(\n"
        "    ToSet(Yson::ConvertToStringList(b.tags)),\n"
        "    Yson::ConvertToStringList($tags)\n"
        ");",
        ::userver::ydb::Query::Name{"BooksByTags"},
        ::userver::ydb::Query::LogMode::kNameOnly,
    };
    auto sqlc_response =
        this->transaction_ != nullptr
        ? this->transaction_->Execute(this->execute_settings_, sqlc_query, "$tags", tags)
        : this->client_->ExecuteQuery(this->operation_settings_, sqlc_query, "$tags", tags);
    auto sqlc_cursor = sqlc_response.GetSingleCursor();
    std::vector<BooksByTagsRow> sqlc_rows;
    sqlc_rows.reserve(sqlc_cursor.size());
    for (auto sqlc_row : sqlc_cursor) {
        sqlc_rows.push_back(BooksByTagsRow{
            sqlc_row.Get<std::uint64_t>("b.book_id"),
            sqlc_row.Get<::userver::ydb::Utf8>("b.title"),
            sqlc_row.Get<std::optional<::userver::ydb::Utf8>>("a.name"),
            sqlc_row.Get<::userver::ydb::Utf8>("b.isbn"),
            sqlc_row.Get<::userver::formats::json::Value>("b.tags"),
        });
    }
    return sqlc_rows;
}

// -- name: CreateAuthor :one
std::optional<CreateAuthorRow> Queries::CreateAuthor(std::uint64_t author_id, const ::userver::ydb::Utf8& name) const {
    const auto sqlc_query = ::userver::ydb::Query{
        "INSERT INTO authors (author_id, name)\n"
        "VALUES ($author_id, $name)\n"
        "RETURNING author_id, name;",
        ::userver::ydb::Query::Name{"CreateAuthor"},
        ::userver::ydb::Query::LogMode::kNameOnly,
    };
    auto sqlc_response =
        this->transaction_ != nullptr
        ? this->transaction_->Execute(this->execute_settings_, sqlc_query, "$author_id", author_id, "$name", name)
        : this->client_->ExecuteQuery(this->operation_settings_, sqlc_query, "$author_id", author_id, "$name", name);
    auto sqlc_cursor = sqlc_response.GetSingleCursor();
    if (sqlc_cursor.empty()) {
        return std::nullopt;
    }
    auto sqlc_row = sqlc_cursor.GetFirstRow();
    return CreateAuthorRow{
        sqlc_row.Get<std::uint64_t>("author_id"),
        sqlc_row.Get<::userver::ydb::Utf8>("name"),
    };
}

// -- name: CreateBook :one
std::optional<CreateBookRow> Queries::CreateBook(std::uint64_t book_id, std::uint64_t author_id, const ::userver::ydb::Utf8& isbn, const ::userver::ydb::Utf8& book_type, const ::userver::ydb::Utf8& title, std::int32_t publication_year, const std::chrono::system_clock::time_point& available, const ::userver::formats::json::Value& tags) const {
    const auto sqlc_query = ::userver::ydb::Query{
        "INSERT INTO books (\n"
        "    book_id,\n"
        "    author_id,\n"
        "    isbn,\n"
        "    book_type,\n"
        "    title,\n"
        "    publication_year,\n"
        "    available,\n"
        "    tags\n"
        ") VALUES (\n"
        "    $book_id,\n"
        "    $author_id,\n"
        "    $isbn,\n"
        "    $book_type,\n"
        "    $title,\n"
        "    $publication_year,\n"
        "    $available,\n"
        "    $tags\n"
        ")\n"
        "RETURNING book_id, author_id, isbn, book_type, title, publication_year, available, tags;",
        ::userver::ydb::Query::Name{"CreateBook"},
        ::userver::ydb::Query::LogMode::kNameOnly,
    };
    auto sqlc_response =
        this->transaction_ != nullptr
        ? this->transaction_->Execute(this->execute_settings_, sqlc_query, "$book_id", book_id, "$author_id", author_id, "$isbn", isbn, "$book_type", book_type, "$title", title, "$publication_year", publication_year, "$available", available, "$tags", tags)
        : this->client_->ExecuteQuery(this->operation_settings_, sqlc_query, "$book_id", book_id, "$author_id", author_id, "$isbn", isbn, "$book_type", book_type, "$title", title, "$publication_year", publication_year, "$available", available, "$tags", tags);
    auto sqlc_cursor = sqlc_response.GetSingleCursor();
    if (sqlc_cursor.empty()) {
        return std::nullopt;
    }
    auto sqlc_row = sqlc_cursor.GetFirstRow();
    return CreateBookRow{
        sqlc_row.Get<std::uint64_t>("book_id"),
        sqlc_row.Get<std::uint64_t>("author_id"),
        sqlc_row.Get<::userver::ydb::Utf8>("isbn"),
        sqlc_row.Get<::userver::ydb::Utf8>("book_type"),
        sqlc_row.Get<::userver::ydb::Utf8>("title"),
        sqlc_row.Get<std::int32_t>("publication_year"),
        sqlc_row.Get<std::chrono::system_clock::time_point>("available"),
        sqlc_row.Get<::userver::formats::json::Value>("tags"),
    };
}

// -- name: UpdateBook :exec
void Queries::UpdateBook(const ::userver::ydb::Utf8& title, const ::userver::formats::json::Value& tags, std::uint64_t book_id) const {
    const auto sqlc_query = ::userver::ydb::Query{
        "UPDATE books\n"
        "SET title = $title, tags = $tags\n"
        "WHERE book_id = $book_id;",
        ::userver::ydb::Query::Name{"UpdateBook"},
        ::userver::ydb::Query::LogMode::kNameOnly,
    };
    static_cast<void>(
        this->transaction_ != nullptr
        ? this->transaction_->Execute(this->execute_settings_, sqlc_query, "$title", title, "$tags", tags, "$book_id", book_id)
        : this->client_->ExecuteQuery(this->operation_settings_, sqlc_query, "$title", title, "$tags", tags, "$book_id", book_id)
    );
}

// -- name: UpdateBookISBN :exec
void Queries::UpdateBookISBN(const ::userver::ydb::Utf8& title, const ::userver::formats::json::Value& tags, const ::userver::ydb::Utf8& isbn, std::uint64_t book_id) const {
    const auto sqlc_query = ::userver::ydb::Query{
        "UPDATE books\n"
        "SET title = $title, tags = $tags, isbn = $isbn\n"
        "WHERE book_id = $book_id;",
        ::userver::ydb::Query::Name{"UpdateBookISBN"},
        ::userver::ydb::Query::LogMode::kNameOnly,
    };
    static_cast<void>(
        this->transaction_ != nullptr
        ? this->transaction_->Execute(this->execute_settings_, sqlc_query, "$title", title, "$tags", tags, "$isbn", isbn, "$book_id", book_id)
        : this->client_->ExecuteQuery(this->operation_settings_, sqlc_query, "$title", title, "$tags", tags, "$isbn", isbn, "$book_id", book_id)
    );
}

// -- name: DeleteAuthorBeforeYear :exec
void Queries::DeleteAuthorBeforeYear(std::int32_t publication_year, std::uint64_t author_id) const {
    const auto sqlc_query = ::userver::ydb::Query{
        "DELETE FROM books\n"
        "WHERE publication_year < $publication_year AND author_id = $author_id;",
        ::userver::ydb::Query::Name{"DeleteAuthorBeforeYear"},
        ::userver::ydb::Query::LogMode::kNameOnly,
    };
    static_cast<void>(
        this->transaction_ != nullptr
        ? this->transaction_->Execute(this->execute_settings_, sqlc_query, "$publication_year", publication_year, "$author_id", author_id)
        : this->client_->ExecuteQuery(this->operation_settings_, sqlc_query, "$publication_year", publication_year, "$author_id", author_id)
    );
}

// -- name: SayHello :one
std::optional<SayHelloRow> Queries::SayHello(const ::userver::ydb::Utf8& name) const {
    const auto sqlc_query = ::userver::ydb::Query{
        "SELECT \"hello \"u || $name AS greeting;",
        ::userver::ydb::Query::Name{"SayHello"},
        ::userver::ydb::Query::LogMode::kNameOnly,
    };
    auto sqlc_response =
        this->transaction_ != nullptr
        ? this->transaction_->Execute(this->execute_settings_, sqlc_query, "$name", name)
        : this->client_->ExecuteQuery(this->operation_settings_, sqlc_query, "$name", name);
    auto sqlc_cursor = sqlc_response.GetSingleCursor();
    if (sqlc_cursor.empty()) {
        return std::nullopt;
    }
    auto sqlc_row = sqlc_cursor.GetFirstRow();
    return SayHelloRow{
        sqlc_row.Get<::userver::ydb::Utf8>("greeting"),
    };
}

// -- name: ListAuthorsWithRecentBooks :many
std::vector<ListAuthorsWithRecentBooksRow> Queries::ListAuthorsWithRecentBooks(std::int32_t since_year) const {
    const auto sqlc_query = ::userver::ydb::Query{
        "SELECT a.author_id, a.name\n"
        "FROM authors AS a\n"
        "WHERE a.author_id IN (\n"
        "    SELECT b.author_id FROM books AS b WHERE b.publication_year >= $since_year\n"
        ")\n"
        "ORDER BY a.author_id;",
        ::userver::ydb::Query::Name{"ListAuthorsWithRecentBooks"},
        ::userver::ydb::Query::LogMode::kNameOnly,
    };
    auto sqlc_response =
        this->transaction_ != nullptr
        ? this->transaction_->Execute(this->execute_settings_, sqlc_query, "$since_year", since_year)
        : this->client_->ExecuteQuery(this->operation_settings_, sqlc_query, "$since_year", since_year);
    auto sqlc_cursor = sqlc_response.GetSingleCursor();
    std::vector<ListAuthorsWithRecentBooksRow> sqlc_rows;
    sqlc_rows.reserve(sqlc_cursor.size());
    for (auto sqlc_row : sqlc_cursor) {
        sqlc_rows.push_back(ListAuthorsWithRecentBooksRow{
            sqlc_row.Get<std::uint64_t>("author_id"),
            sqlc_row.Get<::userver::ydb::Utf8>("name"),
        });
    }
    return sqlc_rows;
}

// -- name: ListBooksWithRecentEditions :many
std::vector<ListBooksWithRecentEditionsRow> Queries::ListBooksWithRecentEditions(std::int32_t since_year) const {
    const auto sqlc_query = ::userver::ydb::Query{
        "DECLARE $since_year AS Int32;\n"
        "SELECT b.book_id, b.author_id, b.isbn, b.book_type, b.title, b.publication_year, b.available, b.tags\n"
        "FROM books AS b\n"
        "WHERE (b.author_id, b.book_type) IN (\n"
        "    SELECT (recent.author_id, recent.book_type)\n"
        "    FROM books AS recent\n"
        "    WHERE recent.publication_year >= $since_year\n"
        ")\n"
        "ORDER BY b.book_id;",
        ::userver::ydb::Query::Name{"ListBooksWithRecentEditions"},
        ::userver::ydb::Query::LogMode::kNameOnly,
    };
    auto sqlc_response =
        this->transaction_ != nullptr
        ? this->transaction_->Execute(this->execute_settings_, sqlc_query, "$since_year", since_year)
        : this->client_->ExecuteQuery(this->operation_settings_, sqlc_query, "$since_year", since_year);
    auto sqlc_cursor = sqlc_response.GetSingleCursor();
    std::vector<ListBooksWithRecentEditionsRow> sqlc_rows;
    sqlc_rows.reserve(sqlc_cursor.size());
    for (auto sqlc_row : sqlc_cursor) {
        sqlc_rows.push_back(ListBooksWithRecentEditionsRow{
            sqlc_row.Get<std::uint64_t>("book_id"),
            sqlc_row.Get<std::uint64_t>("author_id"),
            sqlc_row.Get<::userver::ydb::Utf8>("isbn"),
            sqlc_row.Get<::userver::ydb::Utf8>("book_type"),
            sqlc_row.Get<::userver::ydb::Utf8>("title"),
            sqlc_row.Get<std::int32_t>("publication_year"),
            sqlc_row.Get<std::chrono::system_clock::time_point>("available"),
            sqlc_row.Get<::userver::formats::json::Value>("tags"),
        });
    }
    return sqlc_rows;
}

// -- name: DeleteBooksByAuthorName :exec
void Queries::DeleteBooksByAuthorName(const ::userver::ydb::Utf8& author_name) const {
    const auto sqlc_query = ::userver::ydb::Query{
        "DELETE FROM books\n"
        "WHERE author_id IN (SELECT author_id FROM authors WHERE name = $author_name);",
        ::userver::ydb::Query::Name{"DeleteBooksByAuthorName"},
        ::userver::ydb::Query::LogMode::kNameOnly,
    };
    static_cast<void>(
        this->transaction_ != nullptr
        ? this->transaction_->Execute(this->execute_settings_, sqlc_query, "$author_name", author_name)
        : this->client_->ExecuteQuery(this->operation_settings_, sqlc_query, "$author_name", author_name)
    );
}

}  // namespace booktest::userver
